$(function() {

    $('time').each(function() {
        var tz_display = $(this).data('content');
        $(this).text(moment(tz_display).format('LT'));
    });

    if ($('.tab-content').length > 0) {
        $('.tab-content').prependTo('form.form');

        $('form fieldset#basic_info').appendTo('#tab-info');

        $('form fieldset#select_source').appendTo('#tab-source');
        $('form fieldset.source_fieldset').appendTo('#tab-source');

        $('form fieldset#select_type').appendTo('#tab-scheduling');
        $('form fieldset.type_fieldset').appendTo('#tab-scheduling');
    }

    showFieldset('type', $('form #field_type input:checked').val());
    showFieldset('source', $('form #field_source input:checked').val());

    $('form #field_type input').on('change', function() {
        showFieldset('type', $(this).val());
    });

    $('form #field_source input').on('change', function() {
        showFieldset('source', $(this).val());
    });
});

function showFieldset(fieldset_prefix, fieldset_id)
{
    $('form fieldset.'+fieldset_prefix+'_fieldset').slideUp('fast');
    $('form fieldset#'+fieldset_prefix+'_'+fieldset_id).slideDown('fast');
}
