<?php
$props = [
    'listUrl' => $router->fromHere('api:stations:playlists:list'),
    'calendarUrl' => $router->fromHere('api:stations:playlists:calendar'),
    'locale' => substr($customization->getLocale(), 0, 2),
    'filesUrl' => $router->fromHere('stations:files:index'),
    'stationTimeZone' => $station_tz,
]
?>
var station_playlists;

$(function () {
  station_playlists = new Vue({
    el: '#station-playlist',
    render: function (createElement) {
      return createElement(StationMedia.default, {
        props: <?=json_encode($props) ?>
      });
    }
  });
});