<?php

$this->layout(
    'main',
    [
        'title' => __('Playlists'),
        'manual' => true,
    ]
);

/** @var App\Http\RouterInterface $router */
$props = [
    'listUrl' => (string)$router->fromHere('api:stations:playlists'),
    'scheduleUrl' => (string)$router->fromHere('api:stations:playlists:schedule'),
    'locale' => substr($customization->getLocale()->getLocale(), 0, 2),
    'filesUrl' => (string)$router->fromHere('stations:files:index'),
    'stationTimeZone' => $station_tz,
    'enableAdvancedFeatures' => $enableAdvancedFeatures,
];

/** @var \App\Assets $assets */
$assets->addVueRender('Vue_StationsPlaylists', '#station-playlist', $props);
?>

<div id="station-playlist"></div>
