<?php
use App\Entity\StationPlaylist;

$this->layout('main', ['title' => __('Playlists'), 'manual' => true]);

/** @var \Azura\Assets $assets */
$assets->load('fullcalendar')
    ->addInlineJs($this->fetch('stations/playlists/index.js', [
        'schedule_now' => $schedule_now,
        'schedule_url' => $schedule_url,
    ]));
?>

<div class="card">
    <div class="card-header bg-primary-dark">
        <h2 class="card-title"><?=__('Playlists') ?></h2>
    </div>
    <div class="card-header">
        <ul class="nav nav-pills card-header-pills">
            <li class="nav-item">
                <a class="nav-link active" role="tab" data-toggle="tab" aria-expanded="true" aria-controls="all-playlists" href="#all-playlists"><?=__('All Playlists') ?></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" role="tab" data-toggle="tab" aria-controls="schedule-view" href="#schedule-view"><?=__('Schedule View') ?></a>
            </li>
        </ul>
    </div>
    <div role="tabpanel">
        <div class="tab-content">
            <div class="tab-pane active" id="all-playlists" role="tabpanel">
                <div class="card-actions">
                    <a class="btn btn-outline-primary" role="button" href="<?=$router->fromHere('stations:playlists:add') ?>">
                        <i class="material-icons" aria-hidden="true">add</i>
                        <?=__('Add %s', __('Playlist')) ?>
                    </a>
                </div>
                <table class="table table-striped">
                    <colgroup>
                        <col width="30%">
                        <col width="30%">
                        <col width="25%">
                        <col width="15%">
                    </colgroup>
                    <thead>
                    <tr>
                        <th><?=__('Actions') ?></th>
                        <th><?=__('Playlist') ?></th>
                        <th><?=__('Scheduling') ?></th>
                        <th><?=__('# Songs') ?></th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php foreach($playlists as $row): ?>
                        <tr class="align-middle">
                            <td>
                                <div class="btn-group btn-group-sm">
                                    <a class="btn btn-primary" href="<?=$router->fromHere('stations:playlists:edit', ['id' => $row['id']]) ?>"><?=__('Edit') ?></a>
                                    <a class="btn btn-sm btn-danger" data-confirm-title="<?=$this->e(__('Delete playlist "%s"?', $row['name'])) ?>" href="<?=$router->fromHere('stations:playlists:delete', ['id' => $row['id'], 'csrf' => $csrf]) ?>"><?=__('Delete') ?></a>

                                    <div class="btn-group btn-group-sm">
                                        <button type="button" class="btn btn-dark dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                            <?=__('More') ?> <span class="caret"></span>
                                        </button>
                                        <ul class="dropdown-menu">
                                                <li><a class="dropdown-item" href="<?=$router->fromHere('stations:playlists:toggle', ['id' => $row['id']]) ?>"><?=($row['is_enabled'] ? __('Disable') : __('Enable')) ?></a></li>
                                            <?php if ($row['source'] === StationPlaylist::SOURCE_SONGS && $row['order'] === StationPlaylist::ORDER_SEQUENTIAL): ?>
                                                <li><a class="dropdown-item" href="<?=$router->fromHere('stations:playlists:reorder', ['id' => $row['id']]) ?>"><?=__('Reorder') ?></a></li>
                                            <?php endif; ?>
                                            <?php foreach(['pls', 'm3u'] as $format): ?>
                                                <li><a class="dropdown-item" href="<?=$router->fromHere('stations:playlists:export', ['id' => $row['id'], 'format' => $format]) ?>"><?=__('Export %s', strtoupper($format)) ?></a></li>
                                            <?php endforeach; ?>
                                        </ul>
                                    </div>
                                </div>
                            </td>
                            <td>
                                <h5 class="m-0"><?=$this->e($row['name']) ?></h5>
                                <div>
                                    <span class="badge badge-dark"><?=(($row['source'] === StationPlaylist::SOURCE_SONGS) ? __('Song-based') : __('Remote URL')) ?></span>
                                <?php if ($row['is_jingle']): ?>
                                    <span class="badge badge-primary"><?=__('Jingle Mode') ?></span>
                                <?php endif; ?>
                                <?php if ($row['source'] === StationPlaylist::SOURCE_SONGS && $row['order'] === StationPlaylist::ORDER_SEQUENTIAL): ?>
                                    <span class="badge badge-info"><?=__('Sequential') ?></span>
                                <?php endif; ?>
                                <?php if ($row['include_in_automation']): ?>
                                    <span class="badge badge-success"><?=__('Auto-Assigned') ?></span>
                                <?php endif; ?>
                                </div>
                            </td>
                            <td>
                                <?php if (!$row['is_enabled']): ?>
                                    <?=__('Disabled') ?>
                                <?php elseif ($row['type'] === StationPlaylist::TYPE_DEFAULT): ?>
                                    <?=__('General Rotation') ?><br>
                                    <?=__('Weight') ?>: <?=(int)$row['weight'] ?> (<?=$row['probability'] ?>)
                                <?php elseif ($row['type'] === StationPlaylist::TYPE_SCHEDULED): ?>
                                    <?=__('Scheduled') ?><br>
                                    <?=__('Plays between %s and %s', '<time data-content="'.$row['schedule_start'].'"></time>', '<time data-content="'.$row['schedule_end'].'"></time>') ?>
                                <?php elseif ($row['type'] === StationPlaylist::TYPE_ONCE_PER_X_SONGS): ?>
                                    <?=__('Once per %d Songs', $row['play_per_songs']) ?>
                                <?php elseif ($row['type'] === StationPlaylist::TYPE_ONCE_PER_X_MINUTES): ?>
                                    <?=__('Once per %d Minutes', $row['play_per_minutes']) ?>
                                <?php elseif ($row['type'] === StationPlaylist::TYPE_ONCE_PER_HOUR): ?>
                                    <?=__('Once per Hour (at :%02d)', $row['play_per_hour_minute']) ?>
                                <?php elseif ($row['type'] === StationPlaylist::TYPE_ADVANCED): ?>
                                    <?=__('Custom') ?>
                                <?php endif; ?>
                            </td>
                            <td>
                                <a href="<?=$router->fromHere('stations:files:index').'#playlist:'.urlencode($row['name']) ?>"><?=$row['num_songs'] ?></a>
                                (<?=$row['total_length'] ?>)
                            </td>
                        </tr>
                    <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
            <div class="tab-pane card-padding" id="schedule-view" role="tabpanel">
                <div id="playlist-calendar"></div>
            </div>
        </div>
    </div>
</div>
