<?php
$props = [
    'listUrl' => $router->fromHere('api:stations:playlists'),
    'scheduleUrl' => $router->fromHere('api:stations:playlists:schedule'),
    'locale' => substr($customization->getLocale(), 0, 2),
    'filesUrl' => $router->fromHere('stations:files:index'),
    'stationTimeZone' => $station_tz,
    'enableAdvancedFeatures' => $settings->enableAdvancedFeatures(),
]
?>
var station_playlists;

$(function () {
    station_playlists = new Vue({
        el: '#station-playlist',
        render: function (createElement) {
            return createElement(StationPlaylists.default, {
                props: <?=json_encode($props) ?>
            });
        }
    });
});