<?php
$this->layout('main', [
    'title' => __('Reorder Playlist'),
    'manual' => true
]);

/** @var \App\Assets $assets */
$assets->load('sortable')
    ->addInlineJs($this->fetch('stations/playlists/reorder.js', [
        'csrf' => $csrf,
    ]));
?>

<div class="card">
    <div class="card-header bg-primary-dark ch-alt">
        <h2 class="card-title"><?=__('Reorder Playlist: %s', $this->e($playlist->getName())) ?></h2>
    </div>
    <table class="table table-responsive-md table-striped sortable mb-0">
        <colgroup>
            <col width="40%">
            <col width="30%">
            <col width="30%">
        </colgroup>
        <thead>
        <tr>
            <th><?=__('Title') ?></th>
            <th><?=__('Artist') ?></th>
            <th><?=__('Album') ?></th>
            <th><?=__('Actions') ?></th>
        </tr>
        </thead>
        <tbody id="reorder">
        <?php foreach($media_items as $row): ?>
            <tr class="align-middle" data-id="<?=$row['id'] ?>">
                <td><big><?=$this->e($row['media']['title']) ?></big></td>
                <td><?=$this->e($row['media']['artist']) ?></td>
                <td><?=$this->e($row['media']['album']) ?></td>
                <td>
                    <div class="btn-group btn-group-sm">
                        <button class="btn btn-sm btn-primary js-order-down" title="<?=__('Down') ?>">
                            <i class="material-icons">arrow_downward</i>
                        </button>
                        <button class="btn btn-sm btn-primary js-order-up" title="<?=__('Up') ?>">
                            <i class="material-icons">arrow_upward</i>
                        </button>
                    </div>
                </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>
