<div class="dropdown ml-3" id="radio-player-controls">
    <button aria-expanded="false" aria-haspopup="true" class="navbar-toggler" data-toggle="dropdown" type="button">
        <i class="material-icons">radio</i>
    </button>
    <ul class="dropdown-menu dropdown-menu-right">
        <li>
            <a href="javascript:;" class="dropdown-item jp-pause">
                <i class="material-icons">pause</i>
                <?=__('Pause') ?>
            </a>
        </li>
        <li>
            <span class="dropdown-item dropdown-item-text">
                <i class="material-icons">volume_up</i>
                <input type="range" title="<?=__('Volume') ?>" class="custom-range jp-volume-range" id="jp-volume-range" min="0" max="100" step="1">
            </span>
        </li>
    </ul>
</div>
