<?php
$this->layout('main', [
    'title' => $title,
    'header' => $header,
    'manual' => true,
]);

/** @var \Azura\Assets $assets */
$assets
    ->load('chosen')
    ->addInlineJs($this->fetch('partials/station_form.js'), 99)
    ->addInlineJs($this->fetch('system/form_edit.js'));
?>

<section class="card mb-3" role="region">
    <div class="card-header">
        <ul class="nav nav-justified nav-tabs card-header-tabs" role="tablist">
            <li class="nav-item">
                <a aria-controls="home" aria-selected="true" class="nav-link active" data-toggle="tab" href="#tab-profile" id="tab-profile-link" role="tab"><?=__('Station Profile') ?></a>
            </li>
            <li class="nav-item">
                <a aria-controls="profile" aria-selected="false" class="nav-link" data-toggle="tab" href="#tab-frontend" id="tab-frontend-link" role="tab"><?=__('Broadcasting') ?></a>
            </li>
            <li class="nav-item">
                <a aria-controls="contact" aria-selected="false" class="nav-link" data-toggle="tab" href="#tab-backend" id="tab-backend-link" role="tab"><?=__('AutoDJ') ?></a>
            </li>
        </ul>
    </div>
    <div class="card-body">
        <div class="tab-content">
            <div aria-labelledby="tab-profile-link" class="tab-pane fade show active" id="tab-profile" role="tabpanel"></div>
            <div aria-labelledby="tab-frontend-link" class="tab-pane fade" id="tab-frontend" role="tabpanel"></div>
            <div aria-labelledby="tab-backend-link" class="tab-pane fade" id="tab-backend" role="tabpanel"></div>
        </div>

        <?=$form->render() ?>
    </div>
</section>
