<?
$title = 'Administration';
$manual = true;

// Admin sidebar.
$panels = array(
    'System Maintenance' => array(
        'System Settings' => array(
            'url'       => 'admin/settings',
            'icon'      => 'fa fa-cog',
            'permission' => $this->acl->isAllowed('administer all'),
        ),
        'User Accounts' => array(
            'url'       => 'admin/users',
            'icon'      => 'fa fa-user',
            'permission' => $this->acl->isAllowed('administer all'),
        ),
        'Roles and Permissions' => array(
            'url'       => 'admin/permissions',
            'icon'      => 'fa fa-key',
            'permission' => $this->acl->isAllowed('administer all'),
        ),
        'API Keys' => array(
            'url'      => 'admin/api',
            'icon'     => 'fa fa-share-alt',
            'permission' => $this->acl->isAllowed('administer api keys'),
        ),
    ),
    'Stations' => array(
        'Manage Stations' => array(
            'url'       => 'admin/stations',
            'icon'      => 'fa fa-cog',
            'permission' => $this->acl->isAllowed('administer stations'),
        ),
    ),
);

// Process and purge based on permissions.
foreach($panels as $sidebar_category => &$sidebar_items)
{
    foreach($sidebar_items as $item_name => $item_params)
    {
        if (!$item_params['permission'])
            unset($sidebar_items[$item_name]);
    }

    if (empty($sidebar_items))
        unset($panels[$sidebar_category]);
}
?>

<div class="block-header">
    <h2>Administration</h2>
</div>

<div class="row">
    <? foreach($panels as $category_name => $category_items): ?>
    <div class="col-sm-4">
        <div class="card">
            <div class="card-header ch-alt">
                <h2><?=$category_name ?></h2>
            </div>
            <div class="card-body card-padding-sm">
                <ul class="nav nav-list" <? if (count($category_items) >= 15): ?>style="height: 300px; overflow-y: scroll;"<? endif; ?>>
                    <? foreach($category_items as $item_name => $item_params): ?>
                        <li>
                            <a href="<?=(is_array($item_params['url']) ? $this->viewHelper->route($item_params['url']) : $this->url->get($item_params['url'])) ?>" title="<?=$item_params['title'] ?>">
                                <i class="<?=$item_params['icon'] ?>"></i> <?=$item_name ?>
                            </a>
                        </li>
                    <? endforeach; ?>
                </ul>
            </div>
        </div>
    </div>
    <? endforeach; ?>
</div>

<div class="block-header">
    <h2>Synchronization Tasks</h2>
</div>

<div class="row">
    <? foreach($sync_times as $sync_key => $sync_info): ?>
    <div class="col-sm-3">
        <div class="card">
            <div class="card-header bgm-bluegray">
                <h2>
                    <?=$sync_info['name'] ?>
                    <small><?=implode(', ', $sync_info['contents']) ?></small>
                </h2>
                <a class="btn bgm-blue btn-float" href="<?=$this->url->routeFromHere(array('action' => 'sync', 'type' => $sync_key)) ?>" title="Run Manually"><i class="zmdi zmdi-mail-send"></i></a>
            </div>
            <div class="card-body card-padding">
                <p><?=date('F j, Y g:ia', $sync_info['latest']) ?><br><small><?=$sync_info['diff_text'] ?> ago</small></p>
            </div>
        </div>
    </div>
    <? endforeach; ?>
</div>