<?php
$this->headTitle('Import Songs');
?>

<h2>Import Results</h2>

<h3>Successful Imports</h3>
<ul>
<?
foreach((array)$this->output['successes'] as $file_name => $message)
    echo '<li><b>'.$file_name.'</b>: '.$message.'</li>';
?>
</ul>

<h3>Unsuccessful Imports</h3>
<ul>
<?
foreach((array)$this->output['failures'] as $file_name => $message)
    echo '<li><b>'.$file_name.'</b>: '.$message.'</li>';
?>  
</ul>