<?php
$props = [
    'listUrl' => $router->fromHere('api:stations:files:list'),
    'batchUrl' => $router->fromHere('api:stations:files:batch'),
    'uploadUrl' => $router->fromHere('api:stations:files:upload'),
    'listDirectoriesUrl' => $router->fromHere('api:stations:files:directories'),
    'mkdirUrl' => $router->fromHere('api:stations:files:mkdir'),
    'renameUrl' => $router->fromHere('api:stations:files:rename'),
    'initialPlaylists' => $playlists,
    'customFields' => $custom_fields,
    'validMimeTypes' => $mime_types,
]
?>
var station_media_manager;

$(function () {
    station_media_manager = new Vue({
        el: '#media-manager',
        render: function (createElement) {
            return createElement(StationMedia.default, {
                props: <?=json_encode($props) ?>
            });
        }
    });
});
