<?php $this->layout('main', ['title' => _('API Keys'), 'manual' => true]); ?>

<div class="block-header">
    <h2><?=_('Administration') ?></h2>
</div>

<div class="card">
    <div class="card-header ch-alt">
        <h2><?=_('API Keys') ?></h2>
    </div>
    <div class="table-responsive">
        <table class="table table-striped">
            <colgroup>
                <col width="20%">
                <col width="25%">
                <col width="30%">
                <col width="25%">
            </colgroup>
            <thead>
            <tr>
                <th>&nbsp;</th>
                <th><?=_('API Key') ?></th>
                <th><?=_('Comments') ?></th>
                <th><?=_('Owner') ?></th>
            </tr>
            </thead>
            <tbody>
            <?php foreach($records as $record): ?>
                <tr class="input">
                    <td class="center">
                        <a class="btn btn-sm btn-primary" href="<?=$url->named('admin:api:edit', ['id' => $record['id']]) ?>"><?=_('Edit') ?></a>
                        <a class="btn btn-sm btn-danger" href="<?=$url->named('admin:api:delete', ['id' => $record['id']]) ?>"><?=_('Revoke') ?></a>
                    </td>
                    <td><code><?=$record['id'] ?></code></td>
                    <td><?=$this->e($record['comment']) ?></td>
                    <td><?=$this->e($record['user']['email']) ?></td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>