<?php $this->layout('embed', ['title' => $this->e($station->name)]) ?>

<?php $this->start('custom_js') ?>
<script type="text/javascript" src="<?=$url->content('vendors/bower_components/store-js/store.min.js') ?>"></script>
<script type="text/javascript" src="<?=$assets->getPath('js/radio.js') ?>"></script>
<?php $this->stop('custom_js') ?>

<ul class="actions pull-right">
    <?=$this->fetch('partials/radio_controls') ?>
</ul>
<div class="stations nowplaying">
    <div class="media media-left" id="station_<?=$station->id ?>">
        <div class="pull-left">
            <a class="btn-audio" href="#" data-url="<?=$stream_url ?>">
                <i class="zmdi zmdi-play"></i>
            </a>
        </div>
        <div class="media-body">
            <h4 class="media-heading nowplaying-title"><?=_('Song Title') ?></h4>
            <div class="nowplaying-artist"><?=_('Song Artist') ?></div>
        </div>
    </div>
</div>

<script type="text/javascript">
function nowPlaying() {
    $.getJSON('<?=$url->route([
        'module' => 'api',
        'controller' => 'nowplaying',
        'station' => $station->id
    ]) ?>', {}, function (row) {
        var station_row = $('#station_'+row.station.id);

        if ('mediaSession' in navigator) {
            navigator.mediaSession.metadata = new MediaMetadata({
                title: row.now_playing.song.title,
                artist: row.now_playing.song.artist
            });
        }

        station_row.find('.nowplaying-title').text(row.now_playing.song.title);
        station_row.find('.nowplaying-artist').text(row.now_playing.song.artist);
        station_row.find('.nowplaying-listeners').text(row.listeners.total);

        setTimeout('nowPlaying()', 30*1000);
    });
}

$(function() {
    nowPlaying();
});
</script>