<?php /** @var \Entity\Station $station */ ?>

<?php $this->layout('embed', ['title' => $this->e($station->getName())]) ?>

<?php $this->start('custom_js') ?>
<script type="text/javascript" src="<?=$url->content('vendors/bower_components/store-js/store.min.js') ?>"></script>
<script type="text/javascript" src="<?=$assets->getPath('js/radio.js') ?>"></script>
<script type="text/javascript" src="<?=$assets->getPath('js/nchan.js') ?>"></script>
<?php $this->stop('custom_js') ?>

<ul class="actions pull-right">
    <?=$this->fetch('partials/radio_controls') ?>
</ul>
<div class="stations nowplaying">
    <div class="media media-left" id="station_<?=$station->getId() ?>">
        <div class="pull-left">
            <a class="btn-audio" href="#" data-url="<?=$this->e($stream_url) ?>">
                <i class="zmdi zmdi-play"></i>
            </a>
        </div>
        <div class="media-body">
            <h4 class="media-heading nowplaying-title"><?=_('Song Title') ?></h4>
            <div class="nowplaying-artist"><?=_('Song Artist') ?></div>
        </div>
    </div>
</div>

<script type="text/javascript">
$(function() {
    var sub = new NchanSubscriber('/api/live/nowplaying/<?=$station->getId() ?>');

    sub.on("message", function(message, message_metadata) {
        var row = JSON.parse(message);

        var station_row = $('#station_'+row.station.id);

        if ('mediaSession' in navigator) {
            navigator.mediaSession.metadata = new MediaMetadata({
                title: row.now_playing.song.title,
                artist: row.now_playing.song.artist
            });
        }

        station_row.find('.nowplaying-title').text(row.now_playing.song.title);
        station_row.find('.nowplaying-artist').text(row.now_playing.song.artist);
        station_row.find('.nowplaying-listeners').text(row.listeners.total);
    });
});
</script>