<?php /** @var \Entity\Station $station */ ?>

<?php $this->layout('minimal', ['page_class' => 'embed', 'title' => $this->e($station->getName())]) ?>

<?php
/** @var \AzuraCast\Assets $assets */
$assets->load('bootgrid');
?>

<table class="data-table table table-striped" id="requests-table">
    <thead>
    <tr>
        <th data-column-id="song_id" data-identifier="true" data-visible="false">ID</th>
        <th data-column-id="song_title"><?=_('Title') ?></th>
        <th data-column-id="song_artist"><?=_('Artist') ?></th>
        <th data-column-id="commands" data-formatter="commands" data-sortable="false"><?=_('Actions') ?></th>
    </tr>
    </thead>
    <tbody></tbody>
</table>

<script type="text/javascript">
$(function() {
    var grid = $("#requests-table").bootgrid({
        ajax: true,
        rowSelect: false,
        caseSensitive: false,
        columnSelection: false,
        css: {
            icon: 'zmdi icon',
            iconColumns: 'zmdi-view-module',
            iconDown: 'zmdi-sort-amount-desc',
            iconRefresh: 'zmdi-refresh',
            iconUp: 'zmdi-sort-amount-asc'
        },
        url: "<?=$url->route(['module' => 'api', 'controller' => 'requests', 'action' => 'list', 'station' => $station->getId()]) ?>",
        formatters: {
            "commands": function(column, row) {
                return '<a class="btn btn-request btn-sm btn-primary" data-url="'+row.request_url+'"><?=_('Request') ?></a>';
            }
        }
    }).on("loaded.rs.jquery.bootgrid", function()
    {
        /* Executes after data is loaded and rendered */
        grid.find(".btn-request").on("click", function(e)
        {
            e.preventDefault();

            $.ajax({
                dataType: "json",
                url: $(this).data('url')
            }).done(function(data) {
                notify(data, 'success');
            }).fail(function(jqXhr) {
                notify('Error: ' + jqXhr.responseJSON, 'danger');
            });

            return false;
        });
    });
});
</script>