<?php $this->layout('minimal', ['title' => $this->e($station->name), 'page_class' => 'public-page-content']) ?>

<?php $this->start('custom_js') ?>
<script type="text/javascript" src="<?=$url->content('vendors/bootgrid/jquery.bootgrid.updated.js') ?>"></script>

<script type="text/javascript" src="<?=$url->content('vendors/bower_components/store-js/store.min.js') ?>"></script>
<script type="text/javascript" src="<?=$url->content('js/radio.js') ?>"></script>
<?php $this->stop('custom_js') ?>

<?php $this->start('custom_css') ?>
<link rel="stylesheet" type="text/css" href="<?=$url->content('vendors/bootgrid/jquery.bootgrid.min.css') ?>">
<?php $this->stop('custom_css') ?>

<div class="public-page">
    <div class="public-block">

        <ul class="actions pull-right">
            <?=$this->fetch('partials/radio_controls') ?>
        </ul>
        <h3 class="text-left"><?=$this->e($station->name) ?></h3>

        <div class="stations nowplaying">
            <div class="media media-left" id="station_<?=$station->id ?>">
                <div class="pull-left">
                    <a class="btn-audio" href="#" data-url="<?=$station->getFrontendAdapter($di)->getStreamUrl() ?>">
                        <i class="zmdi zmdi-play"></i>
                    </a>
                </div>
                <div class="media-body">
                    <h4 class="media-heading nowplaying-title">
                        <?= _('Song Title') ?>
                    </h4>
                    <div class="nowplaying-artist">
                        <?= _('Song Artist') ?>
                    </div>
                    <div class="nowplaying-progress" style="display: none;">

                    </div>
                </div>
            </div>
        </div>

        <div class="buttons">
            <a class="btn btn-default btn-icon-text" data-toggle="modal" data-target="#modal-history">
                <i class="zmdi zmdi-time-restore"></i> <?=_('Song History') ?>
            </a>
        <?php if ($station->enable_requests): ?>
            <a class="btn btn-default btn-icon-text" data-toggle="modal" data-target="#modal-request">
                <i class="zmdi zmdi-help-outline"></i> <?=_('Request Song') ?>
            </a>
        <?php endif; ?>
            <div class="btn-group">
                <button type="button" class="btn btn-default btn-icon-text dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="zmdi zmdi-download"></i> <?=_('Playlist') ?> <span class="caret"></span>
                </button>
                <ul class="dropdown-menu">
                    <?php foreach(['pls', 'm3u'] as $format): ?>
                        <li><a href="<?=$url->named('public:playlist', ['station' => $station->getShortName(), 'format' => $format]) ?>"><?=sprintf(_('Download %s'), strtoupper($format)) ?></a></li>
                    <?php endforeach; ?>
                </ul>
            </div>
        </div>

    </div>
</div>

<div class="modal fade" id="modal-history" tabindex="-1" role="dialog" aria-labelledby="modal-history-label">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="modal-history-label"><?=_('Song History') ?></h4>
            </div>
            <div class="modal-body">
                <ol type="1" id="song-history">

                </ol>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="modal-request" tabindex="-1" role="dialog" aria-labelledby="modal-request-label">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="modal-request-label"><?=_('Request a Song') ?></h4>
            </div>
            <div class="modal-body">

                <table class="data-table table table-striped" id="requests-table">
                    <thead>
                    <tr>
                        <th data-column-id="song_id" data-identifier="true" data-visible="false">ID</th>
                        <th data-column-id="song_title"><?=_('Title') ?></th>
                        <th data-column-id="song_artist"><?=_('Artist') ?></th>
                        <th data-column-id="commands" data-formatter="commands" data-sortable="false"><?=_('Actions') ?></th>
                    </tr>
                    </thead>
                    <tbody></tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
function nowPlaying() {
    $.getJSON('<?=$url->route([
        'module' => 'api',
        'controller' => 'nowplaying',
        'station' => $station->id
    ]) ?>', {}, function (row) {
        var station_row = $('#station_'+row.station.id);

        var np_title = row.now_playing.song.title;
        if (row.now_playing.is_request) {
            np_title += '<span class="label label-default">Listener Request</span>';
        }
        station_row.find('.nowplaying-title').html(np_title);
        station_row.find('.nowplaying-artist').text(row.now_playing.song.artist);
        station_row.find('.nowplaying-listeners').text(row.listeners.total);

        if (row.now_playing.duration) {
            var time_played = Math.floor(Date.now() / 1000) - row.now_playing.played_at;
            var time_total = row.now_playing.duration;

            if (time_played > time_total) {
                time_played = time_total;
            }

            var time_display = formatTime(time_played) + ' / ' + formatTime(time_total);

            station_row.find('.nowplaying-progress')
                .data('time-played', time_played)
                .data('time-total', time_total)
                .text(time_display)
                .show();
        } else {
            station_row.find('.nowplaying-progress').hide();
        }

        $('#song-history').empty();
        $.each(row.song_history, function(i, history_row) {
            var li = $('<li>').append('<b>'+history_row.song.title+'</b><br>'+history_row.song.artist);
            $('#song-history').append(li);
        });

        setTimeout('nowPlaying()', 10 * 1000);
    });
}

function iterateTimer() {
    $('.nowplaying-progress:visible').each(function () {
        var time_played = $(this).data('time-played') + 1;
        var time_total = $(this).data('time-total');

        if (time_played > time_total) {
            time_played = time_total;
        }

        var time_display = formatTime(time_played) + ' / ' + formatTime(time_total);

        $(this).data('time-played', time_played)
            .text(time_display)
    });
}

function formatTime(time) {
    var sec_num = parseInt(time, 10);

    var hours = Math.floor(sec_num / 3600);
    var minutes = Math.floor((sec_num - (hours * 3600)) / 60);
    var seconds = sec_num - (hours * 3600) - (minutes * 60);

    if (hours < 10) {
        hours = "0" + hours;
    }
    if (minutes < 10) {
        minutes = "0" + minutes;
    }
    if (seconds < 10) {
        seconds = "0" + seconds;
    }
    return (hours !== "00" ? hours + ':' : "") + minutes + ':' + seconds;
}

$(function() {
    nowPlaying();

    setInterval(iterateTimer, 1000);
});

var request_dialog = $('#modal-request');

request_dialog.on('show.bs.modal', function (event) {

    if (!request_dialog.data('request_loaded'))
    {
        var grid = $("#requests-table").bootgrid({
            ajax: true,
            rowSelect: false,
            caseSensitive: false,
            columnSelection: false,
            css: {
                icon: 'zmdi icon',
                iconColumns: 'zmdi-view-module',
                iconDown: 'zmdi-sort-amount-desc',
                iconRefresh: 'zmdi-refresh',
                iconUp: 'zmdi-sort-amount-asc'
            },
            url: "<?=$url->route(['module' => 'api', 'controller' => 'requests', 'action' => 'list', 'station' => $station->id]) ?>",
            formatters: {
                "commands": function(column, row) {
                    return '<a class="btn btn-request btn-sm btn-primary" data-url="'+row.request_url+'"><?=_('Request') ?></a>';
                }
            }
        }).on("loaded.rs.jquery.bootgrid", function()
        {
            /* Executes after data is loaded and rendered */
            grid.find(".btn-request").on("click", function(e)
            {
                e.preventDefault();
                request_dialog.modal('hide');

                $.ajax({
                    dataType: "json",
                    url: $(this).data('url')
                }).done(function(data) {
                    notify(data, 'success');
                }).fail(function(jqXhr) {
                    notify('Error: ' + jqXhr.responseJSON, 'danger');
                });

                return false;
            });
        });

        request_dialog.data('request_loaded', true);
    }

});
</script>