<?
$affiliates = array(
	
	array(
		'name'		=> 'Ponyhoof',
		'url'		=> 'http://ponyhoof.little.my',
		'description' => 'Ponify Facebook and make it 20% cooler!',
		'image'		=> \DF\Url::content('affiliates/ponyhoof.png'),
	),

	array(
		'name'		=> 'Journey of the Spark',
		'url'		=> 'http://fimsparkmovie.tumblr.com/',
		'description' => 'A Full Length Fan-Created Movie',
		'image'		=> \DF\Url::content('affiliates/jots.png'),
	),

	array(
		'name'		=> 'PonyMC',
		'description' => 'A Ponyville Live! Minecraft Partner',
		'url'		=> 'http://ponymc.com/',
		'image'		=> '//ponymc.com/img/logos/random_logo.php?width=150&height=150', // \DF\Url::content('affiliates/ponymc.png'),
	),

	array(
		'name'		=> 'Legends of Equestria',
		'url'		=> 'http://legendsofequestria.com/',
		'description' => 'A Pony-Themed MMORPG',
		'image'		=> \DF\Url::content('affiliates/loe.png'),
	),

	array(
		'name'		=> 'PonySquare/BronySquare',
		'url'		=> 'http://www.ponysquare.com/',
		'custom'	=> '<a href="http://www.ponysquare.com/" target="_blank">PonySquare</a> &amp; <a href="http://www.bronysquare.com/" target="_blank">BronySquare</a>',
		'description' => 'Pony-Driven Social Networks',
		'image'		=> \DF\Url::content('affiliates/squared.png'),
	),

	array(
		'name'		=> 'Brony Aerospace',
		'url'		=> 'http://bronyaerospace.net/',
		'description' => 'Launching Rockets Pony-Style!',
		'image'		=> \DF\Url::content('affiliates/aerospace.png'),
	),

	array(
		'name'		=> 'Brony@Home',
		'url'		=> 'http://bronyathome.org/',
		'description' => 'Distributed Computing for the Greater Good',
		'image'		=> \DF\Url::content('affiliates/bronyathome.png'),
	),

	array(
		'name'		=> 'Derpy Hooves News',
		'url'		=> 'http://www.derpyhoovesnews.com/',
		'description' => 'Aderpable Pony News Site',
		'image'		=> \DF\Url::content('affiliates/dhn.png'),
	),

	array(
		'name'		=> 'Bronies For Good',
		'url'		=> 'http://broniesforgood.org/',
		'description' => 'Promoting Brony Kindness and Philanthropy',
		'image'		=> \DF\Url::content('affiliates/bfg.png'),
	),

	array(
		'name'		=> 'Brony Musician Directory',
		'url'		=> 'http://bronymusic.com/',
		'description' => 'Profiles and Biographies of Pony Musicians',
		'image'		=> \DF\Url::content('affiliates/bmd.png'),
	),

	/*
	array(
		'name'		=> 'MTMS Gaming',
		'url'		=> 'http://steamcommunity.com/groups/MaximumServers',
		'description' => 'Home of TF2 Servers and L4D Servers',
		'image'		=> \DF\Url::content('affiliates/mtms.png'),
	),
	*/

	array(
		'name'		=> 'Las Pegasus Gaming',
		'url'		=> 'http://laspegasus.net/',
		'description' => 'A Community Brony Gaming Site',
		'image'		=> \DF\Url::content('affiliates/lpp.png'),
	),

);

shuffle($affiliates);

$num_affiliates = count($affiliates);
$col1_length = ceil($num_affiliates / 2);
$col1 = array_splice($affiliates, 0, $col1_length);
$cols = array($col1, $affiliates);
?>

<div class="footer-inner">
	<div class="row-fluid">
		<div class="span8">
			<div class="headline"><h3>Friends &amp; Affiliates</h3></div>

			<div class="row-fluid">
			<? foreach($cols as $column): ?>
				<div class="span6">
					<ul class="media-list">
					<? foreach($column as $affiliate): ?>
						<li class="media">
							<div class="media-object pull-left">
								<a href="<?=$affiliate['url'] ?>" target="_blank">
									<img src="<?=$affiliate['image'] ?>" style="width: 40px;">
								</a>
							</div>
							<div class="media-body">
								<h4>
								<? if ($affiliate['custom']): ?>
									<?=$affiliate['custom'] ?><br>
								<? else: ?>
									<a href="<?=$affiliate['url'] ?>" target="_blank"><?=$affiliate['name'] ?></a><br>
								<? endif; ?>
									<small><?=$affiliate['description'] ?></small>
								</h4>
							</div>
						</li>
					<? endforeach; ?>
					</ul>
				</div>
			<? endforeach; ?>
			</div>
		</div>

		<div class="span4">
			<div class="headline"><h3>Support PVL</h3></div>
			<form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top">
				<input type="hidden" name="cmd" value="_s-xclick">
				<input type="hidden" name="hosted_button_id" value="ATKJ53AWWRQP4">
				<input type="image" src="https://www.paypalobjects.com/en_US/i/btn/btn_donateCC_LG.gif" border="0" name="submit" alt="PayPal - The safer, easier way to pay online!">
				<img alt="" border="0" src="https://www.paypalobjects.com/en_US/i/scr/pixel.gif" width="1" height="1">
			</form>
			<br>
			<ul class="unstyled">
				<li><a href="http://www.zazzle.com/ponyvillelive" target="_blank"><i class="icon-money"></i> Swag Store</a></li>
			</ul>

	        <div class="headline"><h3>Contact Us</h3></div>	
	        <ul class="unstyled">
	        	<li>Public Relations:<br><?=$this->mailto('pr@ponyvillelive.com') ?></li>
	        	<li>Director:<br><?=$this->mailto('silvereagle@ponyvillelive.com') ?></li>
	        	<li>Associate Director:<br><?=$this->mailto('weareborg@ponyvillelive.com') ?></li>
	        </ul>

	        <div class="headline"><h3>Stay Connected</h3></div>

	        <ul class="unstyled">
				<li><a href="http://news.ponyvillelive.com/" target="_blank"><img src="<?=\DF\Url::content('social/tumblr_16.png') ?>" alt="Tumblr"> Tumblr</a></li>
				<li><a href="http://steamcommunity.com/groups/ponyvillelive" target="_blank"><img src="<?=\DF\Url::content('social/steam_16.png') ?>" alt="Steam"> Steam</a></li>
				<li><a href="https://www.facebook.com/pages/Ponyville-LIVE/517435684948331" target="_blank"><img src="<?=\DF\Url::content('social/facebook_16.png') ?>" alt="Facebook"> Facebook</a></li>
				<li><a href="https://twitter.com/PonyvilleLive" target="_blank"><img src="<?=\DF\Url::content('social/twitter_16.png') ?>" alt="Twitter"> Twitter</a></li>
			</ul>
		</div>
	</div>
</div>