<div class="well">
	<!-- Player Interface -->
	<div id="jquery_jplayer" style="width: 0; height: 0;"></div>
	<div id="jp_container" class="jp-audio" style="display: none;">
		<div id="sidebar-shortcuts">
			<div id="sidebar-shortcuts-large">
				<div class="jp-type-single">
					<div id="jp_interface_1" class="jp-interface">
						<ul class="jp-controls">
							<li><a href="#" class="jp-play" tabindex="1">play</a></li>
							<li><a href="#" class="jp-pause" tabindex="1">pause</a></li>
							<li><a href="#" class="jp-mute" tabindex="1">mute</a></li>
							<li><a href="#" class="jp-unmute" tabindex="1">unmute</a></li>
						</ul>
						<div class="jp-progress-container">
							<div class="jp-progress">
								<div class="jp-seek-bar">
									<div class="jp-play-bar"></div>
								</div>
							</div>
						</div>
						<div class="jp-volume-bar-container">
							<div class="jp-volume-bar">
								<div class="jp-volume-bar-value"></div>
							</div>
						</div>
					</div>
				</div>
				<div id="nowplaying">
					<b><span id="nowplaying-title">Now Playing...</span></b><br>
					<span id="nowplaying-artist">Loading...</span>
				</div>
			</div>
		</div>
	</div>

	<ul class="nav nav-list">
	    <li><a href="<?=$this->route(array('module' => 'mlpma')) ?>" class="ajax"><i class="icon-home"></i> Home</a></li>

	    <li class="nav-header">Search the Archive</li>
	    <li>

	    </li>

	    <li class="nav-header">Browse the Archive</li>
		<?
		$genres = \Entity\ArchiveGenre::getTop();
		foreach($genres as $genre_id => $genre): ?>
			<li><a href="<?=$this->route(array('module' => 'mlpma', 'controller' => 'search', 'genre' => $genre['name'])) ?>" class="ajax"><i class="icon-double-angle-right"></i> <?=$genre['name'] ?></a></li>
		<? endforeach; ?>

		<li class="nav-header">Other Actions</li>
		<li><a href="<?=$this->route(array('module' => 'mlpma', 'controller' => 'index', 'action' => 'download')) ?>" class="ajax"><i class="icon-download"></i> Download the Archive</a></li>
		<li><a href="<?=$this->route(array('module' => 'mlpma', 'controller' => 'submit')) ?>"><i class="icon-plus-sign"></i> Submit a Song </a></li>

	<? if ($this->acl->isAllowed('administer mlpma songs')): ?>
		<li class="nav-header">Administration</li>

		<li><a href="<?=$this->route(array('module' => 'mlpma', 'controller' => 'manage', 'action' => 'import')) ?>"><i class="icon-inbox"></i><span>Import New Music</span></a></li>

	<? endif; ?>

	</ul>
</div>