<ul class="media-list">
<? foreach($this->podcasts as $podcast_info): ?>
    <?
    $podcast = $podcast_info['record'];
    $episodes = $podcast_info['episodes'];
    $ep = $episodes[0];
    ?>
    <li class="media podcast">
        <div class="media-object pull-left">
            <a href="<?=$this->routeFromHere(array('controller' => 'show', 'action' => 'view', 'id' => $podcast->id)) ?>">
                <img class="station-image" src="<?=\DF\Url::content($podcast->image_url) ?>" alt="<?=$podcast->name ?> Logo">
            </a>
        </div>
        <div class="media-body">
            <div class="station-info">
                <h4>
                <? if (!empty($podcast['country'])): ?>
                    <span class="f16"><span class="flag <?=strtolower($podcast['country']) ?>" title="<?=\PVL\Internationalization::getCountryName($podcast['country']) ?>"></span></span>
                <? endif; ?>
                    <?=$podcast->name ?><br>
                    <span class="block genre-info">
                        <?=$podcast->description ?>
                    </span>
                <?
                if (count($podcast->stations) > 0)
                {
                    $station_links = array();
                    foreach($podcast->stations as $station)
                    {
                        $station_link = '<a href="#" class="btn-play-station" data-station="station_'.$station->short_name.'">'.$station->name.'</a>';
                        $station_links[] = $station_link;
                    }

                    echo '<span class="block airson-info"><i class="icon-star"></i> Airs on '.implode(', ', $station_links).'</span>';
                }
                ?>
                </h4>

                <?
                $time_diff = \DF\Utilities::timeDifferenceText(time(), $ep['timestamp']);
                ?>
                <small><?=$time_diff?> ago:</small><br>
                <a href="<?=$ep['web_url'] ?>" target="_blank"><b><?=$ep['title'] ?></b></a>
            </div>
        </div>
    </li>
<? endforeach; ?>
</ul>