---
- name: Install Beanstalkd
  apt:
    name: beanstalkd

- name: Extend default message size.
  template:
    src: etc_default_beanstalkd.j2
    dest: /etc/default/beanstalkd
    force: true
    mode: 0644
