project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
base_url: 'https://crowdin.com'
preserve_hierarchy: 1
files:
  - source: /translations/default.pot
    translation: /translations/%locale_with_underscore%.UTF-8/LC_MESSAGES/default.po
