services:
  web:
    environment:
      VIRTUAL_HOST: ${LETSENCRYPT_HOST:-azuracast.local}
      HTTPS_METHOD: noredirect

  nginx_proxy:
    container_name: nginx_proxy
    image: "ghcr.io/azuracast/nginx_proxy:${AZURACAST_VERSION:-latest}"
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - letsencrypt:/etc/nginx/certs
      - nginx_proxy_vhosts:/etc/nginx/vhost.d
      - letsencrypt_html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    environment:
      NGINX_TIMEOUT: ${NGINX_TIMEOUT:-1800}
      DEFAULT_HOST: ${LETSENCRYPT_HOST:-azuracast.local}
    networks:
      - frontend
    depends_on:
      - web
    restart: unless-stopped

  nginx_proxy_letsencrypt:
    container_name: nginx_proxy_letsencrypt
    image: "ghcr.io/azuracast/nginx_proxy_letsencrypt:${AZURACAST_VERSION:-latest}"
    volumes_from:
      - nginx_proxy
    volumes:
      - letsencrypt_acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: always

volumes:
  letsencrypt_html: { }
  letsencrypt_acme: { }
  nginx_proxy_vhosts: { }
