services:
  web:
    build:
      context: .
    ports:
      - '10022:2022'
      - "127.0.0.1:3306:3306"
      - "127.0.0.1:6379:6379"
    volumes:
      - ${LOCAL_WORKSPACE_FOLDER:-.}/vendor:/var/azuracast/www/vendor
      - ${LOCAL_WORKSPACE_FOLDER:-.}:/var/azuracast/www
