#!/usr/bin/env bash

if [ `whoami` != 'azuracast' ]; then
    echo 'This script must be run as the "azuracast" user. Rerunning...'
    setuser azuracast azuracast_cli "$@"
    exit $?
fi

cd /var/azuracast/www
php bin/console "$@"
