#!/usr/bin/env bash

minimal_init /bin/true || exit 1

azuracast_install || exit 1

chmod 777 tests/_output/
chmod 777 tests/_support/_generated

cd /var/azuracast/www
composer codeception-no-coverage
