#!/usr/bin/env bash

bool() {
    case "$1" in
    Y* | y* | true | TRUE | 1) return 0 ;;
    esac
    return 1
}

if [ $(whoami) != 'azuracast' ]; then
    echo 'This script must be run as the "azuracast" user. Rerunning...'
    sudo -E -u azuracast azuracast_install "$@"
    exit 1
fi

echo "AzuraCast Setup"

APPLICATION_ENV="${APPLICATION_ENV:-production}"
echo "(Environment: $APPLICATION_ENV)"

if [ "$APPLICATION_ENV" = "production" ]; then
    if bool "$COMPOSER_PLUGIN_MODE"; then
        composer update --lock --no-dev --optimize-autoloader
    fi
else
    composer install
fi

azuracast_cli azuracast:restore "$@"
