#!/usr/bin/env bash

cd /var/azuracast/www

while test $# -gt 0; do
    case "$1" in
        --dev)
            APP_ENV="development"
            shift
            ;;

        *)
            break
            ;;
    esac
done

APP_ENV="${APP_ENV:-production}"

echo "Updating AzuraCast (Environment: $APP_ENV)"

ansible-playbook util/ansible/docker_install.yml --inventory=util/ansible/hosts --extra-vars "app_env=$APP_ENV"