#!/usr/bin/env bash

if [ $(whoami) != 'azuracast' ]; then
    echo 'This script must be run as the "azuracast" user. Rerunning...'
    exec gosu azuracast azuracast_ci "$@"
fi

azuracast_install || exit 1

cd /var/azuracast/www
composer codeception-no-coverage
