#!/bin/bash

# Wait for services to spin up.
gosu azuracast php /var/azuracast/www/bin/uptime_wait || exit 1

# Initialize before running FPM
gosu azuracast azuracast_cli azuracast:setup --init || exit 1

# Run initial Acme check
gosu azuracast azuracast_cli azuracast:acme:get-certificate || true

# Run PHP-FPM
exec php-fpm -F --fpm-config /usr/local/etc/php-fpm.conf
