#!/bin/bash

source /etc/php/.version

# Set up PHP config
dockerize -template "/etc/php/${PHP_VERSION}/fpm/05-azuracast.ini.tmpl:/etc/php/${PHP_VERSION}/fpm/conf.d/05-azuracast.ini" \
  -template "/etc/php/${PHP_VERSION}/fpm/www.conf.tmpl:/etc/php/${PHP_VERSION}/fpm/pool.d/www.conf" \
  cp /etc/php/${PHP_VERSION}/fpm/conf.d/05-azuracast.ini /etc/php/${PHP_VERSION}/cli/conf.d/05-azuracast.ini

# Wait for services to spin up.
gosu azuracast php /var/azuracast/www/bin/uptime_wait || exit 1

# Initialize before running FPM
gosu azuracast azuracast_cli azuracast:setup --init || exit 1

# Run initial Acme check
gosu azuracast azuracast_cli azuracast:acme:get-certificate || true

# Run PHP-FPM
exec /usr/sbin/php-fpm${PHP_VERSION} -F --fpm-config /etc/php/${PHP_VERSION}/fpm/php-fpm.conf -c /etc/php/${PHP_VERSION}/fpm/
