#!/usr/bin/env bash

exec tmpreaper 12h --verbose \
    --protect '.tmpreaper' \
    --protect 'proxies' \
    --protect 'service_*.log' \
    /tmp/app_nginx_client \
    /tmp/app_fastcgi_temp \
    /var/azuracast/stations/*/temp \
    /var/azuracast/www_tmp
