<?php
$this->headTitle('Charity Double Dash');
$this->layout()->manual = true;
?>

<div class="row-fluid">
    <div class="span6">
        <div class="well">
            <iframe width="100%" height="400" src="http://cdn.livestream.com/embed/ponyvillelive?layout=4&color=0x8cb6e5&autoPlay=true&mute=false&iconColorOver=0x5484ba&iconColor=0x386496&allowchat=true&height=340&width=560" style="border:0;outline:0" frameborder="0" scrolling="no"></iframe>
        </div>
    </div>
    <div class="span6">
        <div class="well" style="padding: 3px; background-color: #faf8ec">
            <iframe src="http://events.yoursiblings.org/iframe.html" height="150" width="100%" allowtransparent="true" frameborder="0" scrolling="no"></iframe>
        </div>
        <div class="well">
            <div style="width: 100%; height: 220px; overflow-x: hidden; overflow-y: scroll;">
                <p>BfG: Charity Double Premiere: Dash of Christmas and A Princess Carol</p>
                <p>The double premiere of the year is here: All throughout 2013 and longer, Bronystate and Brony Radio have each collaborated with many talented artists, singers, and voice actors on their respective projects, the radio plays Dash of Christmas and A Princess Carol!</p>
                <p>Both will premiere in parallel on Sunday, December 22, at 12:30 p.m. EST on the Your Siblings events page, Ponyville Live, and Celestia Radio!</p>
                <p><b>Dash of Christmas</b></p>
                <p>This Sunday, we bring you a touching tale of a mare working her way around work and weather to make a young filly’s Christmas the best one ever. After three months of brutal work comes Dash of Christmas, featuring the voices of PKEmi, Anne Chloe, Mary Medley, Missy Angel and DJ Calcos! Written by Bronystate members Reikm and Sylandest, Art by Reikm and Tesuai, and created by Scoot-Scootaloo!</p>
                <p><b>A Princess Carol</b></p>
                <p>This Sunday, we bring you a pony take on an old Christmas classic with multiple carols, penned by the talented John Perry, inspired by Charles Dickens’ A Princess Carol, and featuring the voices of Hannah as Luna, Memj0123 as Celestia and Spike, Meredith Sims as Twilight, ProjectSNT as Pinkie Pie, Adrienne as Fluttershy, Rev as Coltroy, Deftfunk as the town crier, Mochi as Mayor Mayor and Zecora, and Sleepypony as narrator. Join us as we travel on a journey with Princess Luna: Will she see the true meaning of Hearth’s Warming before it’s too late?</p>
                <p>On the charity side, every viewer and listener is held to donate as much as they see fit in view of these wonderful plays to the Seeds of Kindness 3 fundraiser, which will also be linked on the viewer pages. You will thereby contribute to the extension of the Green Village project in Burundi, which provides not only a home for street children but through practical education also a stepping stone for them into a new self-determined future.</p>
            </div>
        </div>
    </div>
</div>
<div class="row-fluid">
    <div class="span12">
        <div class="well">
            <h2><i class="icon-comments"></i> Join the Chat</h2>
            <iframe src="http://webchat.ponychat.net/?autojoin=%23SeedsOfKindness&amp;showNickSelection=true&amp;showIdentifySelection=true&amp;showMenuButton=true" allowtransparent="true" frameborder="0" scrolling="no" height="500" width="100%">iframe support is required to use the web chat</iframe>
        </div>
    </div>
</div>