<?php
$this->headTitle('Ponyville Live! Presents: Live Event Coverage');
$this->layout()->manual = true;
?>

<div class="row">
	<div class="span4">
		<div class="floating">
			<?
			echo $this->renderHere('player', true);
			?>
		</div>
	</div>
	<div class="span5">
		<div class="floating">
			<div id="lightIRC"></div>
			<script type="text/javascript">
			var rand_num = Math.floor((Math.random()*1000)+1);

			var params = {
	            host: 'irc.canternet.org',
	            port: '6667',
	            policyPort: '843',
	            language: 'en',
	            styleURL: 'css/black.css',
	            nick: 'Pony_'+rand_num,
	            autojoin: '#PonyvilleLive',
	            showNickSelection: 'false',
	            navigationPosition: 'top',
	            realname: 'Ponyville Live! Visitor',
	            quitMessage: 'Watch and listen live at http://www.ponyvillelive.com'
	          };

	          swfobject.embedSWF("<?=\DF\Url::content('lightIRC/lightIRC.swf') ?>", "lightIRC", "100%", "550", "10.0.0", "<?=\DF\Url::content('lightIRC/expressInstall.swf') ?>", params);
			</script>
		</div>
	</div>
	<div class="span3">
		<a class="twitter-timeline" href="https://twitter.com/PonyvilleLive" data-widget-id="304830659438972928">Tweets by @PonyvilleLive</a>
		<script>
		!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");
		</script>
	</div>
</div>

<script type="text/javascript">
var new_header = "<?=\DF\Url::content('layout/header_dark_pvlp.png') ?>";

$(function() {
	$('#logo-title-site img').prop('src', new_header);
	$('h1.title').hide();
});
</script>