<?php
$this->headTitle('Team Fortress 2 Tournament');
$this->layout()->manual = true;
?>

<img src="<?=\DF\Url::content('images/tf2_header.png') ?>">
<div class="row">
	<div class="span12">
		<div class="floating">
			<iframe frameborder="0" transparent="1" style="width: 100%; height: 600px; border: 0;" src="<?=$this->station['stream_url'] ?>"></iframe>
		</div>
	</div>
</div>

<script type="text/javascript">
$(function() {
	$('h1.title').hide();
	$('html').css('background-image', "url('<?=\DF\Url::content('images/tf2_bg.jpg') ?>')");
});
</script>