<?php
/** @var \App\Customization $customization */
?>

var inline_player;

var pause_text = <?=$this->escapeJs(__('Pause')) ?>;
var play_text = <?=$this->escapeJs(__('Play')) ?>;

$(function () {
    inline_player = new Vue({
        el: '#radio-player-controls',
        render: function (createElement) {
            return createElement(InlinePlayer.default);
        }
    });

    $('.btn-audio').each(function () {
        $(this).removeClass('playing')
            .attr('role', 'button')
            .attr('title', play_text)
            .attr('aria-label', play_text);

        $(this).find('i').attr('aria-hidden', true);
    });

    $('.btn-audio').on('click', function (e) {
        e.preventDefault();
        inline_player.$eventHub.$emit('player_toggle', $(this).data('url'));
        return false;
    });

    inline_player.$eventHub.$on('player_stopped', function () {
        $('.btn-audio').each(function () {
            $(this).removeClass('playing')
                .attr('title', play_text)
                .attr('aria-label', play_text);

            var play_icon = $(this).find('i');
            if (play_icon.hasClass('material-icons')) {
                play_icon.text('play_circle_filled');
            }
        });
    });

    inline_player.$eventHub.$on('player_playing', function (audio_source) {

        var urlWithoutQuery = audio_source.split(/[?#]/)[0];

        $('.btn-audio').each(function () {
            var play_icon;
            if ($(this).is('[data-url^="' + urlWithoutQuery + '"]')) {
                $(this).addClass('playing')
                    .attr('title', pause_text)
                    .attr('aria-label', pause_text);

                play_icon = $(this).find('i');
                if (play_icon.hasClass('material-icons')) {
                    play_icon.text('pause_circle_filled');
                }
            } else {
                $(this).removeClass('playing')
                    .attr('title', play_text)
                    .attr('aria-label', play_text);

                play_icon = $(this).find('i');
                if (play_icon.hasClass('material-icons')) {
                    play_icon.text('play_circle_filled');
                }
            }
        });
    });
});
