<?
$title = 'Manage Video Streams';
?>

<div class="buttons">
    <?=$this->viewHelper->button(array(
        'type'      => 'link',
        'class'     => 'large success',
        'href'      => $this->viewHelper->routeFromHere(array('action' => 'edit')),
        'icon'      => 'icon-plus-sign',
        'text'      => 'Add New Stream',
    )) ?>
</div>

<h2>Current Active Stations</h2>

<table class="table table-striped table-bordered table-condensed">
    <colgroup>
        <col width="20%">
        <col width="10%">
        <col width="30%">
        <col width="40%">
    </colgroup>
    <thead>
    <tr>
        <th>Actions</th>
        <th>Image</th>
        <th>Station</th>
        <th>Playing URL</th>
    </tr>
    </thead>
    <tbody>
    <? foreach((array)$stations as $record): ?>
        <tr class="input">
            <td class="center">
                <div class="btn-group">
                    <?=$this->viewHelper->button(array(
                        'type'      => 'small',
                        'href'      => $this->viewHelper->routeFromHere(array('action' => 'edit', 'id' => $record['id'])),
                        'text'      => 'Edit',
                    )) ?>
                    <?=$this->viewHelper->button(array(
                        'type'      => 'small',
                        'class'     => 'danger confirm-delete',
                        'href'      => $this->viewHelper->routeFromHere(array('action' => 'delete', 'id' => $record['id'])),
                        'text'      => 'Delete',
                    )) ?>
                </div>
            </td>
            <td class="center"><img src="<?=\DF\Url::content($record['image_url']) ?>" style="max-width: 70px;"></td>
            <td>
                <div><big><?=$record['name'] ?></big></div>
            </td>
            <td>
                <div><b>Stream:</b> <?=$this->viewHelper->link($record['stream_url']) ?></div>
                <div><b>Data:</b> <?=$this->viewHelper->link($record['nowplaying_url']) ?></div>
            </td>
        </tr>
    <? endforeach; ?>
    </tbody>
</table>