<?php

$this->layout('main', ['title' => __('Upcoming Song Queue'), 'manual' => true]);

/** @var App\Http\RouterInterface $router */
$props = [
    'listUrl' => (string)$router->fromHere('api:stations:queue'),
    'locale' => substr($customization->getLocale(), 0, 2),
    'stationTimeZone' => $stationTz,
];

/** @var \App\Assets $assets */
$assets->addVueRender('Vue_StationsQueue', '#station-queue', $props);
?>

<div id="station-queue"></div>
