<?php
$props = [
    'listUrl' => $router->fromHere('api:stations:queue'),
    'locale' => substr($customization->getLocale(), 0, 2),
    'stationTimeZone' => $stationTz,
]
?>

var stationQueue;
$(function () {
    stationQueue = new Vue({
        el: '#station-queue',
        render: function (createElement) {
            return createElement(StationQueue.default, {
                props: <?=json_encode($props) ?>
            });
        }
    });
});
