<?
$title = 'Station Schedules';

$this->assets->collection('custom_js')
    ->addJs('//cdnjs.cloudflare.com/ajax/libs/fullcalendar/2.2.6/fullcalendar.min.js', false);

$this->assets->collection('custom_css')
    ->addCss('//cdnjs.cloudflare.com/ajax/libs/fullcalendar/2.2.6/fullcalendar.min.css', false);
?>

<ul class="nav nav-pills autoselect" rel="<?=$station ?>">
    <li rel="all"><a href="<?=$this->viewHelper->routeFromHere(array('station' => 'all')) ?>">All Schedules</a></li>
    <? foreach($all_stations as $station): ?>
        <li rel="<?=$station['short_name'] ?>"><a href="<?=$this->viewHelper->routeFromHere(array('station' => $station['short_name'])) ?>"><?=$station['name'] ?></a></li>
    <? endforeach; ?>
</ul>
<br>

<div id="calendar"></div>

<script type="text/javascript">
$(function() {
    $('#calendar').fullCalendar({
        header: {
            left: 'prev,next today',
            center: 'title',
            right: 'month,agendaWeek,agendaDay'
        },
        defaultView: 'agendaWeek',
        editable: false,
        events: '<?=$this->viewHelper->routeFromHere(array('action' => 'fetch')) ?>'
    });
});
</script>