<?php
$this->headTitle('Download the Archive');
?>

<h2>Latest Version</h2>
<p>You can download the newest MLP Music Archive using the link below.</p>

<div class="buttons">
    <?=$this->button(array(
        'type'      => 'link',
        'class'     => 'btn-large btn-primary',
        'icon'      => 'icon-download',
        'text'      => 'Download MLPMA Version 15, Fall 2013 (.torrent)',
        'href'      => '//ponyvillelive.com/resources/mlpma_v15.torrent',
    )) ?>
</div>

<h2>Older Versions</h2>
<p>Old versions of the MLP Music Archive are available for download below.</p>

<ul class="nav nav-list">
    <li><a href="//ponyvillelive.com/resources/mlpma_v14.torrent"><i class="icon-download"></i> MLPMA Version 14, Fall 2012 (.torrent)</a></li>
</ul>

<br>
<h2>About .torrent Files</h2>
<p>A .torrent file lets you download files from the BitTorrent peer-to-peer file sharing network. Since the MLPMA is so large, this is the best way to make sure everyone can download it at the fastest possible speeds, without overloading servers in the process.</p>

<p>In order to download .torrent files, you will need a BitTorrent downloader tool. There are many options available, but a simple lightweight option is the <a href="http://deluge-torrent.org/">Deluge</a> client.</p>