<?php
$this->headTitle('Download the Archive');
?>

<h2>Your Favorite Pony Songs, All In One Place.</h2>

<p>You can download the existing MLP Music Archive using the link below.<br>This version of the archive was created on November 27, 2012.</p>

<div class="buttons">
	<a href="https://docs.google.com/open?id=0B5LW1ZIpaxUIZkIwdUtsQnFKUVU" class="btn btn-xlarge btn-primary">Download v14 (Torrent)</a>
</div>