<?
$this->headTitle('Welcome to the MLP Music Archive');
$this->layout()->manual = true;
$this->layout()->hide_title = true;
?>

<h1 class="title">Welcome to the <b>MLP Music Archive</b>!</h1>
<p>The MLP Music Archive project is now a proud member of the <a href="http://www.ponyvillelive.com/" target="_blank">Ponyville Live!</a> family. We are working hard to bring you a brand spankin' new and improved version of the archive, with the latest and greatest in pony hits included, plus tons of new features.</p>

<div class="row-fluid">
    <div class="span8">
        <h2>Newly Added Songs</h2>
        <?
        $this->songs = $this->newest_songs;
        $this->compact_view = true;
        echo $this->renderHere('songs', TRUE);
        ?>
    </div>
    <div class="span4">
        <h2>Explore By Genre</h2>
        <div class="well">
            <ul class="nav nav-list">
            <? foreach($this->genres as $genre_id => $genre): ?>
                <li><a href="<?=$this->route(array('module' => 'mlpma', 'controller' => 'search', 'genre' => $genre['name'])) ?>" class="ajax"><i class="icon-folder-close"></i> <?=$genre['name'] ?> <span class="label pull-right"><?=$genre['total'] ?></span></a></li>
            <? endforeach; ?>
            </ul>
        </div>
    </div>
</div>