<?
$this->headTitle('Welcome to the MLP Music Archive');
$this->layout()->manual = true;
?>

<h1 class="title">Welcome to the <b>MLP Music Archive</b>!</h1>
<p>The MLP Music Archive project is now a proud member of the <a href="http://www.ponyvillelive.com/" target="_blank">Ponyville Live!</a> family. We are working hard to bring you a brand spankin' new and improved version of the archive, with the latest and greatest in pony hits included, plus tons of new features.</p>

<div class="row-fluid">

	<div class="span8">
		<div class="widget-box transparent">
			<div class="widget-header widget-header-flat">
				<h4 class="lighter">Newly Added Songs</h4>
				<div class="widget-toolbar"><a href="#" data-action="collapse"><i class="icon-chevron-up"></i></a></div>
			</div>
			<div class="widget-body">
				<div class="widget-body-inner">
					<div class="widget-main padding-5">
						<?
						$this->songs = $this->newest_songs;
						$this->compact_view = true;
						echo $this->renderHere('songs', TRUE);
						?>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="span4">
		<div class="widget-box transparent">
			<div class="widget-header widget-header-flat">
				<h4 class="lighter">Explore By Genre</h4>
				<div class="widget-toolbar"><a href="#" data-action="collapse"><i class="icon-chevron-up"></i></a></div>
			</div>
			<div class="widget-body">
				<div class="widget-body-inner">
					<div class="widget-main padding-5">
						<ul class="item-list">
						<? foreach($this->genres as $genre_id => $genre): ?>
							<li class="item"><a href="<?=$this->route(array('module' => 'mlpma', 'controller' => 'search', 'genre' => $genre['name'])) ?>" class="ajax"><?=$genre['name'] ?> <span class="label"><?=$genre['total'] ?></span></li>
						<? endforeach; ?>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>