<?
$title = 'Set Up';
$page_class = 'login-content';
?>

<!-- Login -->
<div class="lc-block toggled" id="l-login">
    <h3 class="text-left">Welcome to <?=$this->config->application->name ?>!</h3>
    <P class="text-left">Begin setup by creating a Super Administrator account.</p>

    <div class="input-group m-b-20">
        <span class="input-group-addon"><i class="zmdi zmdi-account"></i></span>
        <div class="fg-line">
            <input type="text" name="username" class="form-control" placeholder="E-mail Address">
        </div>
    </div>

    <div class="input-group m-b-20">
        <span class="input-group-addon"><i class="zmdi zmdi-male"></i></span>
        <div class="fg-line">
            <input type="password" name="password" class="form-control" placeholder="Password">
        </div>
    </div>

    <div class="clearfix"></div>

    <a href="" class="btn btn-login btn-danger btn-float"><i class="zmdi zmdi-arrow-forward"></i></a>
</div>