<?php $this->layout('main', ['title' => _('Create Station')]); ?>

<p><?=_('To continue the setup process, enter the basic details of your first station below. Some technical details will automatically be retrieved from the system after you complete this step.') ?></p>

<?=$this->fetch('partials/form') ?>

<div class="alert alert-info m-b-0 m-t-25">
    <?=_('Note: If you are not starting with an empty station directory, it may take a while to process any existing MP3 files or playlists that are in this station\'s directory.') ?>
</div>