<?php
$this->headTitle('Events');
$this->layout()->manual = true;

if ($this->show_map)
{
	$this->headScript()->appendFile('//maps.googleapis.com/maps/api/js?sensor=false');
	$this->headScript()->appendFile(\DF\Url::content('map.js'));
}
?>

<? if ($this->show_map): ?>
	<div class="row-fluid">
		<div class="span12">
			<div class="floating">
				<div id="map_canvas" style="width: 100%; height: 300px;"></div>
			</div>
		</div>
	</div>
<? endif; ?>

<div class="row-fluid">
	<div class="span3">
		<div class="floating">
			<h2>List of Events</h2>

			<dl>
			<? foreach($this->all_events as $event): ?>
				<dt class="event" data-city="<?=$event['city'] ?>"><a href="<?=$event['web_url'] ?>"><?=$event['title_full'] ?></a></dt>
				<dd>
					<div><?=date('F j', $event['start_timestamp']) ?> to <?=date('F j, Y', $event['end_timestamp']) ?></div>
					<div><?=$event['city'] ?></div>
				</dd>
			<? endforeach; ?>
			</dl>
		</div>
	</div>
	<div class="span9">
		<div class="floating">
			<h2>Calendar of Events</h2>

			<? if ($this->calendar['prev_page_datecode']): ?>
				<?=$this->button(array(
					'type'		=> 'small',
					'icon'		=> 'icon-arrow-left',
					'class'		=> 'btn-inverse',
					'text'		=> $this->calendar['prev_page_text'],
					'style'		=> 'float: left',
					'href'		=> $this->routeFromHere(array('month' => $this->calendar['prev_page_datecode'])),
				)) ?>
			<? endif; ?>
			<? if ($this->calendar['next_page_datecode']): ?>
				<?=$this->button(array(
					'type'		=> 'small',
					'icon'		=> 'icon-arrow-right',
					'class'		=> 'btn-inverse',
					'text'		=> $this->calendar['next_page_text'],
					'style'		=> 'float: right',
					'href'		=> $this->routeFromHere(array('month' => $this->calendar['next_page_datecode'])),
				)) ?>
			<? endif; ?>
			<h3 style="text-align: center"><?=$this->calendar['current_page_text'] ?></h3>

			<table class="table table-striped" width="100%">
				<thead>
				    <tr>
				        <th width="15%" align="center">Sunday</th>
				        <th width="14%" align="center">Monday</th>
				        <th width="14%" align="center">Tuesday</th>
				        <th width="14%" align="center">Wednesday</th>
				        <th width="14%" align="center">Thursday</th>
				        <th width="14%" align="center">Friday</th>
				        <th width="15%" align="center">Saturday</th>
				    </tr>
				</thead>
				<tbody>
			    <? foreach($this->calendar['days'] as $calendar_row): ?>
				    <tr class="nopad">
						<? foreach($calendar_row as $calendar_day): ?>
				        <td style="vertical-align: top; height: 100px;" <? if ($calendar_day['disabled']): ?>class="disabled"<? endif; ?>>
				            <big><?=$calendar_day['day'] ?></big><br />
				            <? foreach($calendar_day['records'] as $event): ?>
				                <div style="padding: 1px 0px 3px 0px; border-top: 1px dashed #DDD;">
				                	<a href="<?=$event['web_url'] ?>"><?=$event['title_full'] ?><br><small><?=$event['city'] ?></small></a>
				                </div>
				            <? endforeach; ?>
				        </td>
				        <? endforeach; ?>
				    </tr>
			    <? endforeach; ?>
			   	</tbody>
			</table>
		</div>
		<div class="floating">
			<?=\Entity\Block::render('events') ?>
		</div>
	</div>
</div>
