---
php_version: "8.1"
php_sys_packages:
  - "php{{ php_version }}-fpm"
  - "php{{ php_version }}-cli"
  - "php{{ php_version }}-gd"
  - "php{{ php_version }}-curl"
  - "php{{ php_version }}-xml"         # IceCast XML config
  - "php{{ php_version }}-zip"         # Composer installs
  - "php{{ php_version }}-mysqlnd"     # MySQL Native Driver (Doctrine)
  - "php{{ php_version }}-mbstring"    # Codeception Tests
  - "php{{ php_version }}-intl"        # Localization
  - "php{{ php_version }}-redis"       # Cache
  - "php{{ php_version }}-bcmath"      # BigInteger
  - "php{{ php_version }}-gmp"         # BigInteger and PHP-IP
  - "php{{ php_version }}-maxminddb"   # Maxmind (GeoIP) DB native ext


