<?php
$this->layout('minimal', [
    'title' => '404: Page Not Found',
    'page_class' => 'four-zero-content'
]); ?>

<div class="public-page">
    <div class="card">
        <div class="card-body">
            <h2 class="display-1 mt-2">404</h2>
            <p><?=__('The page you requested was not found.') ?></p>

            <a role="button" title="<?=__('Dashboard') ?>" class="btn btn-login btn-primary btn-float" href="<?=$router->named('home') ?>">
                <i class="material-icons">home</i>
            </a>
        </div>
    </div>
</div>
