<?php
$this->layout('minimal', [
    'title' => 'Error',
    'page_class' => 'error-content'
]);
?>

<div class="public-page">
    <div class="card">
        <div class="card-body">
            <h2 class="display-1 mt-2">500</h2>
            <p>
                <?=$exception->getMessage() ?><br>
                <?=basename($exception->getFile()) ?> : <?=$exception->getLine() ?>
            </p>

            <a role="button" title="<?=__('Dashboard') ?>" class="btn btn-login btn-primary btn-float" href="<?=$router->named('home') ?>">
                <i class="material-icons" aria-hidden="true">home</i>
            </a>
        </div>
    </div>
</div>
