$(function() {
    $('form.form').each(function() {
        var $form = $(this);

        $form.addClass('fa-form-engine fa-form');

        $form.find('.form-group > label').addClass('control-label');

        $form.find('input:not(input[type=button],input[type=submit],input[type=reset],input[type=radio],input[type=checkbox]),textarea,select').addClass('form-control');

        $form.find('select').wrap('<div class="select" />').chosen({
            width: "100%",
            placeholder_text_single: <?=$this->escapeJs(__('Select...')) ?>,
            placeholder_text_multiple: <?=$this->escapeJs(__('Select...')) ?>,
            no_results_text: <?=$this->escapeJs(__('No results found!')) ?>
        });

        autosize($form.find('textarea'));

        $form.find('input[type=radio]').each(function() {
            $(this).closest('.form-field').addClass('radio-group');
            $(this).next('label').addBack().wrapAll('<div class="radio m-b-15" />');
        });
        $form.find('input[type=checkbox]').each(function() {
            $(this).closest('.form-field').addClass('checkbox-group');
            $(this).next('label').addBack().wrapAll('<div class="checkbox m-b-15" />');
        });

        $form.find('input[type=checkbox],input[type=radio]').after('<i class="input-helper"></i>');

        $form.find('input[type=checkbox].inline').removeClass('inline').closest('div.checkbox').addClass('checkbox-inline');
        $form.find('input[type=radio].inline').removeClass('inline').closest('div.radio').addClass('radio-inline');

        $form.find('div.checkbox:not(.checkbox-inline)').addClass('m-b-15');
        $form.find('div.radio:not(.radio-inline)').addClass('m-b-15');

        $form.find('.help-block.form-error').parent().addClass('has-error');
        $form.find('.help-block.form-success').parent().addClass('has-success');
        $form.find('.help-block.form-warning').parent().addClass('has-warning');

        // noinspection JSAnnotator
        $form.find('.control-label.advanced,fieldset.advanced legend')
            .prepend('<span class="label label-default">'+<?=$this->escapeJs(__('Advanced')) ?>+'</span> ');

        $form.find('input[type=button],input[type=submit],input[type=reset]').addClass('btn m-t-10');

        // Scroll to errors.
        var error_fields = $form.find('.has-error:visible');
        if (error_fields.length > 0) {
            $([document.documentElement, document.body]).animate({
                scrollTop: error_fields.first().offset().top - $('#header').outerHeight() - 15
            }, 1000);
        }
    });


});
