<?php $this->layout('main', ['title' => _('Stations'), 'manual' => true]); ?>

<div class="block-header">
    <h2><?=_('Administration') ?></h2>
</div>

<div class="card">
    <div class="card-header ch-alt">
        <h2><?=_('Manage Stations') ?></h2>

        <a class="btn bgm-blue btn-float" role="button" title="<?=_('Add new item') ?>" href="<?=$url->routeFromHere(['action' => 'edit']) ?>"><i class="zmdi zmdi-plus"></i></a>
    </div>
    <div class="table-responsive">
        <table class="table table-striped">
            <colgroup>
                <col width="30%">
                <col width="70%">
            </colgroup>
            <thead>
            <tr>
                <th><?=_('Actions') ?></th>
                <th><?=_('Station') ?></th>
            </tr>
            </thead>
            <tbody>
            <?php foreach((array)$stations as $record): ?>
                <tr class="input">
                    <td class="center">
                        <a class="btn btn-sm btn-primary" href="<?=$url->route(array('module' => 'stations', 'station' => $record['id'])) ?>" target="_blank"><?=_('Manage') ?></a>
                        <a class="btn btn-sm btn-default" href="<?=$url->routeFromHere(array('action' => 'edit', 'id' => $record['id'])) ?>"><?=_('Edit') ?></a>
                        <a class="btn btn-sm btn-default" href="<?=$url->routeFromHere(array('action' => 'clone', 'id' => $record['id'])) ?>"><?=_('Clone') ?></a>
                        <a class="btn btn-sm btn-danger" href="<?=$url->routeFromHere(array('action' => 'delete', 'id' => $record['id'])) ?>"><?=_('Delete') ?></a>
                    </td>
                    <td>
                        <big><?=$this->e($record['name']) ?></big>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>