<?php
$title = 'Apps &amp; Players';
$manual = true;
?>

<div class="media clearfix">
    <div class="media-object pull-left">
        <a href="http://he4rtofcourage.deviantart.com/art/Chrome-poni-305866510" title="Chrome Pony by he4rtofcourage" target="_blank"><img src="<?=\DF\Url::content('images/platform_chrome.png') ?>" alt="Chrome Pony"></a>
    </div>
    <div class="media-body">
        <h2>Chrome Browser</h2>

        <div class="well">
            <img src="<?=\DF\Url::content('images/app_hoofsounds_1.jpg') ?>" class="pull-right" style="width: 200px; padding-left: 5px;" alt="">
            <h3>HoofSounds for Chrome</h3>
            <p>Ponyville Live! has partnered with the developer behind popular plugin <a href="http://ponyhoof.little.my/" target="_blank">PonyHoof</a> to build a Chrome plugin that lets you listen to all of our pony music right from your Chrome toolbar. Visit the link below to learn more and install it!</p>

            <div class="buttons">
                <?=$this->viewHelper->button(array(
                    'type'      => 'link',
                    'class'     => 'btn-primary',
                    'icon'      => 'icon-globe',
                    'href'      => 'http://hoofsounds.little.my/',
                    'target'    => '_blank',
                    'text'      => 'HoofSounds Homepage',
                )) ?>
            </div>
        </div>
        <div class="well">
            <h3>PVL Chrome Desktop App</h3>
            <p>If you're looking for the convenience of pony music but without having to keep your browser open, we also offer a dedicated Chrome app that works on all platforms, including Chromebooks. Check it out!</p>

            <div class="buttons">
                <?=$this->viewHelper->button(array(
                    'type'      => 'link',
                    'class'     => 'btn-primary',
                    'icon'      => 'icon-globe',
                    'href'      => 'https://chrome.google.com/webstore/detail/ponyville-live-desktop-ap/hladljgddjaoinnigfcokaglahhcpilm?hl=en',
                    'target'    => '_blank',
                    'text'      => 'Install PVL Chrome App from Google Web Store',
                )) ?>
            </div>
        </div>
    </div>
</div>

<div class="media clearfix">
    <div class="media-object pull-left">
        <a href="http://paulirish.deviantart.com/art/My-Little-Browser-Firefox-260640031" title="Firefox Pony by NoReasonToHope" target="_blank"><img src="<?=\DF\Url::content('images/platform_firefox.png') ?>" alt="Firefox Pony"></a>
    </div>
    <div class="media-body">
        <h2>Firefox Browser</h2>

        <div class="well">
            <h3>HoofSounds for Firefox</h3>
            <p>The same HoofSounds plugin you know and love for Chrome has also been released as a Firefox plugin. Now you can enjoy pony music on either browser with the same experience!</p>

            <div class="buttons">
                <?=$this->viewHelper->button(array(
                    'type'      => 'link',
                    'class'     => 'btn-primary',
                    'icon'      => 'icon-globe',
                    'href'      => 'http://hoofsounds.little.my/',
                    'target'    => '_blank',
                    'text'      => 'HoofSounds Homepage',
                )) ?>
            </div>
        </div>
    </div>
</div>

<div class="media clearfix">
    <div class="media-object pull-left">
        <img src="<?=\DF\Url::content('images/platform_android.png') ?>" alt="Android Platform">
    </div>
    <div class="media-body">
        <h2>Android</h2>

        <div class="well">
            <img src="<?=\DF\Url::content('images/mobile1.png') ?>" style="width: 150px;" class="pull-right" alt="">
            <img src="<?=\DF\Url::content('images/mobile2.png') ?>" style="width: 150px; margin-right: 5px;" class="pull-right" alt="">
            <img src="<?=\DF\Url::content('images/mobile3.png') ?>" style="width: 150px; margin-right: 5px;" class="pull-right" alt="">

            <h3>PVL Mobile for Android</h3>
            <p>The new PVL! Mobile web application lets you enjoy awesome pony radio, video stations, podcasts and more, anywhere you go. The Android app includes all the features of our web application, plus notifications and persistent playback.</p>

            <a href="https://play.google.com/store/apps/details?id=com.ponyvillelive.pvlmobile">
                <img alt="Get it on Google Play"
                     src="https://developer.android.com/images/brand/en_generic_rgb_wo_60.png" />
            </a>
        </div>

        <div class="well">
            <h3>All Pony Radio</h3>

            <p>Our friends at Black Apple Research Facility have worked hard on their own Android app that plays all of Ponyville Live!'s music streams.</p>

            <div class="buttons btn-group">
                <?=$this->viewHelper->button(array(
                    'type'      => 'link',
                    'class'     => 'btn-primary',
                    'icon'      => 'icon-download',
                    'href'      => 'http://bit.ly/AllPonyRadioApp',
                    'target'    => '_blank',
                    'text'      => 'Install All Pony Radio',
                )) ?>
                <?=$this->viewHelper->button(array(
                    'type'      => 'link',
                    'icon'      => 'icon-globe',
                    'href'      => 'http://www.allponyradio.com/',
                    'target'    => '_blank',
                    'text'      => 'All Pony Radio Homepage',
                )) ?>
            </div>

        </div>
    </div>
</div>


<div class="media clearfix">
    <div class="media-object pull-left">
        <img src="<?=\DF\Url::content('images/platform_ios.png') ?>" alt="iOS Platform">
    </div>
    <div class="media-body">
        <h2>iOS</h2>

        <div class="well">
            <h3>Pony Unite for iOS</h3>

            <p>This awesome app was built completely by fans of the Ponyville Live! network, and features a modern interface, along with all of PVL's radio stations, podcasts and upcoming events. It's our favorite way to take pony with us on our iPhones!</p>

            <div class="buttons">
                <?=$this->viewHelper->button(array(
                    'type'      => 'link',
                    'class'     => 'primary',
                    'target'    => '_blank',
                    'icon'      => 'icon-globe',
                    'href'      => 'https://itunes.apple.com/us/app/pony-unite/id929695987?mt=8',
                    'text'      => 'Pony Unite on the App Store',
                )) ?>
            </div>
        </div>

        <div class="well">
            <h3>PVL Mobile for Web Browsers</h3>

            <p>Our mobile web site, featuring all the same radio stations, podcasts and convention coverage as our homepage, is available for all major mobile browsers, and can be pinned to your homepage for even easier access! Check it out below.</p>

            <div class="buttons">
                <?=$this->viewHelper->button(array(
                    'type'      => 'link',
                    'class'     => 'primary btn-tune-in',
                    'target'    => '_blank',
                    'icon'      => 'icon-globe',
                    'href'      => 'http://m.pvlive.me',
                    'text'      => 'PVL! Mobile',
                )) ?>
            </div>
        </div>
    </div>
</div>

<div class="media clearfix">
    <div class="media-object pull-left">
        <img src="<?=\DF\Url::content('images/platform_ipony.png') ?>" alt="iPonyRadio">
    </div>
    <div class="media-body">
        <h2>iPonyRadio</h2>

        <div class="well">
            <h3>iPonyRadio for iOS, Android, and Desktops</h3>

            <p>Originally launched for iOS, the third-party iPonyRadio app has been updated to include Android and desktop platforms. You can listen to every Ponyville Live! station through iPonyRadio, along with Everfree Radio from Canterlot Hill.</p>

            <div class="buttons btn-group">
                <?=$this->viewHelper->button(array(
                    'type'      => 'link',
                    'class'     => 'btn-primary',
                    'icon'      => 'icon-download',
                    'href'      => 'https://itunes.apple.com/us/app/iponyadio/id680943103?ls=1&mt=8',
                    'target'    => '_blank',
                    'text'      => 'iPonyRadio for iOS',
                )) ?>
                <?=$this->viewHelper->button(array(
                    'type'      => 'link',
                    'class'     => 'btn-primary',
                    'icon'      => 'icon-download',
                    'href'      => 'https://play.google.com/store/apps/details?id=com.iponyradio.android',
                    'target'    => '_blank',
                    'text'      => 'iPonyRadio for Android',
                )) ?>
                <?=$this->viewHelper->button(array(
                    'type'      => 'link',
                    'icon'      => 'icon-globe',
                    'href'      => 'http://iponyradio.com/',
                    'target'    => '_blank',
                    'text'      => 'iPonyRadio Homepage',
                )) ?>
            </div>

        </div>
    </div>
</div>

<div class="media clearfix">
    <div class="media-object pull-left">
        <img src="<?=\DF\Url::content('images/platform_generic.png') ?>" alt="Other Platforms">
    </div>
    <div class="media-body">
        <h2>Other Platforms</h2>

        <div class="well">
            <h3>Winamp, iTunes, VLC, etc.</h3>

            <p>Download playlist files containing all of the Ponyville Live! radio stations in one single file. This file can then be used in many major media players.</p>

            <div class="buttons">
                <?=$this->viewHelper->button(array(
                    'type'      => 'link',
                    'class'     => 'btn-primary',
                    'icon'      => 'icon-download',
                    'href'      => $this->viewHelper->routeFromHere(array('controller' => 'station', 'action' => 'playlist', 'format' => 'pls')),
                    'target'    => '_blank',
                    'text'      => 'Download PLS File (VLC, Winamp)',
                )) ?>
                <?=$this->viewHelper->button(array(
                    'type'      => 'link',
                    'class'     => 'btn-primary',
                    'icon'      => 'icon-download',
                    'href'      => $this->viewHelper->routeFromHere(array('controller' => 'station', 'action' => 'playlist', 'format' => 'm3u')),
                    'target'    => '_blank',
                    'text'      => 'Download M3U File (iTunes)',
                )) ?>
            </div>
        </div>

        <div class="well">
            <h3>Embedded On Your Web Site</h3>
            <p>Embed the PVL radio player, including all of its stations, directly into your web site for all of your users to enjoy! With the embedded widget, you can play music and tune into streams directly from your own web site.</p>

            <div class="buttons">
                <?=$this->viewHelper->button(array(
                    'type'      => 'link',
                    'class'     => 'btn-primary',
                    'icon'      => 'icon-globe',
                    'href'      => $this->viewHelper->route(array('controller' => 'widget')),
                    'text'      => 'Web Site Embed Instructions',
                )) ?>
            </div>
        </div>
    </div>
</div>