<?
$title = ('Support the Ponyville Live! Network');
?>

<p>
    The Ponyville Live! network is a not-for-profit operation, and makes no revenue from its convention coverage, radio, video or podcast syndication services.<br>
    We depend on the support of our community to help us bring you the best in pony media.
</p>

<h2>Why Donate?</h2>

<p>
    Ponyville Live! is more than just a web site. We build and maintain a huge network to bring you the best of pony media all day, every day.<br>
    In addition to our own homepage, we also maintain the following services:
</p>

<br>
<div class="row-fluid">
    <div class="span4 text-center">
        <div><i class="large-icon icon-globe"></i></div>
        <h3>Web Hosting</h3>

        <p>PVL provides free-of-charge hosting for a number of our radio stations and video streams. We also host the databases powering not only our own homepage, but also third-party apps like HoofSounds.</p>
    </div>
    <div class="span4 text-center">
        <div><i class="large-icon icon-music"></i></div>
        <h3>Radio Station Hosting</h3>

        <p>Eight of PVL's radio stations are hosted on the Ponyville Live! radio server. Just like web hosting, we provide a fully-licensed CentovaCast station completely free of charge to the stations who use it.</p>
    </div>
    <div class="span4 text-center">
        <div><i class="large-icon icon-group"></i></div>
        <h3>Convention Coverage</h3>

        <p>The PVL press teams cover conventions from across the globe, and we never charge conventions for our recording or streaming services. Sending our cameras and staff to conventions is by far our largest expense.</p>
    </div>
</div>

<br><br>
<p>100% of your donations to the Ponyville Live! network go directly toward supporting the services listed above.</p>

<div class="row-fluid">
    <div class="span6">
        <h2>Donate via PayPal</h2>
        <p>Click the button below to donate directly to the Ponyville Live! network operation fund. The PayPal account is listed as Bravely Blue Media LLC, the parent company to Ponyville Live.</p>

        <center>
            <form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top">
                <input type="hidden" name="cmd" value="_s-xclick">
                <input type="hidden" name="hosted_button_id" value="ATKJ53AWWRQP4">
                <input type="image" src="https://www.paypalobjects.com/en_US/i/btn/btn_donateCC_LG.gif" border="0" name="submit" alt="PayPal - The safer, easier way to pay online!">
                <img alt="" border="0" src="https://www.paypalobjects.com/en_US/i/scr/pixel.gif" width="1" height="1">
            </form>
        </center>
    </div>
    <div class="span6">
        <h2>Donate via Patreon</h2>

        <p>Click the button below to visit our Patreon page, where you can pledge to support our core operations every month. You can update or remove your pledge at any time!</p>

        <iframe
            src="https://ptrn.me/patreon-btn.html?creator=ponyvillelive&amp;size=large&amp;unit=month"
            allowtransparency="true"
            frameborder="0"
            scrolling="0"
            width="300"
            height="30">
        </iframe>
    </div>
</div>