<?
$schedule = array_slice($events_by_day, 0, 2, TRUE);
$col_span = (12 / (count($schedule)+1));
?>
<div class="row-fluid">
    <? foreach($schedule as $day_date => $day_info): ?>
        <div class="span<?=$col_span ?>">
            <div class="well">
                <h3><?=$day_info['day_name'] ?><br><small><?=date('F j, Y', $day_info['timestamp']) ?></small></h3>
                <ul class="unstyled nopadding">
                <? foreach($day_info['events'] as $event): ?>
                    <li class="clearfix" itemscope itemtype="http://data-vocabulary.org/Event">
                        <a itemprop="url" href="<?=$this->viewHelper->routeFromHere() ?>" target="_blank"><img itemprop="photo" class="pull-left" src="<?=$event['image_url'] ?>" alt="<?=$event['station']['name'] ?>" style="width: 32px; margin-right: 5px; margin-top: 5px;"></a>
                        <h5 itemprop="summary"><?=\Entity\Schedule::formatName($event['title']) ?><br><small>
                                <time itemprop="startDate" datetime="<?=date('c', $event['start_time']) ?>">
                                    <? if ($event['status'] == "now"): ?>
                                        <b>Right now</b>
                                    <? else: ?>
                                        <?=date('g:ia', $event['start_time']) ?>
                                    <? endif; ?>
                                </time>
                                on <span itemprop="location"><?=$event['station']['name'] ?></span>
                            </small></h5>
                    </li>
                <? endforeach; ?>
                </ul>
            </div>
        </div>
    <? endforeach; ?>

    <div class="span<?=$col_span ?>">
        <div class="well">
            <h3><i class="icon-twitter"></i> Follow Us for Show Updates</h3>
            <p>Ponyville Live!'s main Twitter account announces shows as they're coming up, so you can keep up to date with what's going on right from your Twitter homepage!</p>

            <div class="buttons">
                <?=$this->viewHelper->button(array(
                    'type'      => 'link',
                    'target'    => '_blank',
                    'class'     => 'btn-primary',
                    'icon'      => 'icon-twitter',
                    'text'      => '@PonyvilleLive on Twitter',
                    'href'      => 'https://twitter.com/intent/user?screen_name=PonyvilleLive',
                )) ?>
            </div>

            <?
            $ical_url = $this->url->get('api/schedule/index/format/ical/nocache/'.time());
            $ical_url = str_replace('http://', 'webcal://', $ical_url);
            $gcal_url = 'http://www.google.com/calendar/render?cid='.urlencode($ical_url);
            ?>

            <h3><i class="icon-calendar-empty"></i> Subscribe for Updates</h3>
            <p>You can subscribe to the list of upcoming Ponyville Live! events using your favorite calendar software (iCal, etc.) or add the feed directly to your Google Calendar feed.</p>

            <div class="buttons btn-group">
                <?=$this->viewHelper->button(array(
                    'type'      => 'link',
                    'target'    => '_blank',
                    'class'     => 'btn-primary',
                    'icon'      => 'icon-download',
                    'text'      => 'Download ICS',
                    'href'      => $ical_url,
                )) ?>
                <?=$this->viewHelper->button(array(
                    'type'      => 'link',
                    'class'     => 'btn-primary',
                    'target'    => '_blank',
                    'icon'      => 'icon-plus-sign',
                    'text'      => 'Add to Google Calendar',
                    'href'      => $gcal_url,
                )) ?>
            </div>
        </div>
    </div>

</div>