<?php
/** @var $station App\Entity\Station */
/** @var $frontend App\Radio\Frontend\FrontendAbstract */
/** @var $backend App\Radio\Backend\BackendAbstract */
/** @var $router \App\Http\Router */
/** @var $assets \App\Assets */

$assets->addInlineJs($this->fetch('stations/sidebar.js'));

$user = $request->getUser();
?>
<div class="navdrawer-header">
    <a class="navbar-brand px-0" href="<?=$router->fromHere('stations:profile:index') ?>">
        <?=$this->e($station->getName()) ?>
    </a>
</div>

<ul class="navdrawer-nav">
<?php if ($acl->userAllowed($user, 'manage station broadcasting', $station->getId())): ?>
    <?php if (!$station->getHasStarted()): ?>
    <li class="nav-item">
        <a class="nav-link api-call text-success" href="<?=$router->fromHere('api:stations:restart') ?>">
            <i class="navdrawer-nav-icon material-icons">refresh</i>
            <?=__('Click to Start Station') ?>
        </a>
    </li>
    <?php elseif ($station->getNeedsRestart()): ?>
    <li class="nav-item">
        <a class="nav-link api-call text-warning" href="<?=$router->fromHere('api:stations:restart') ?>">
            <i class="navdrawer-nav-icon material-icons">refresh</i>
            <?=__('Click to Restart Station') ?>
        </a>
    </li>
    <?php endif; ?>

<?php endif; ?>

    <li class="nav-item">
        <a class="nav-link <?php if ($active_tab === 'profile'): ?>active<?php endif; ?>" href="<?=$router->fromHere('stations:profile:index') ?>">
            <i class="navdrawer-nav-icon material-icons">image</i>
            <?=__('Profile') ?>
        </a>
    </li>

<?php if ($station->getEnablePublicPage()): ?>
    <li class="nav-item">
        <a class="nav-link" href="<?=$router->named('public:index', ['station' => $station->getShortName()]) ?>" target="_blank">
            <i class="navdrawer-nav-icon material-icons">public</i>
            <?=__('Public Page') ?> <i class="material-icons sm">open_in_new</i>
        </a>
    </li>
<?php endif; ?>

<?php if ($acl->userAllowed($user, 'manage station media', $station->getId()) && $backend::supportsMedia()): ?>
    <li class="nav-item">
        <a class="nav-link <?php if ($active_tab === 'files'): ?>active<?php endif; ?>" href="<?=$router->fromHere('stations:files:index') ?>">
            <i class="navdrawer-nav-icon material-icons">library_music</i>
            <?=__('Music Files') ?>
        </a>
    </li>
    <li class="nav-item">
        <a class="nav-link <?php if ($active_tab === 'playlists'): ?>active<?php endif; ?>" href="<?=$router->fromHere('stations:playlists:index') ?>">
            <i class="navdrawer-nav-icon material-icons">queue_music</i>
            <?=__('Playlists') ?>
        </a>
    </li>
<?php endif; ?>

<?php if ($acl->userAllowed($user, 'manage station streamers', $station->getId()) && $backend::supportsStreamers()): ?>
    <li class="nav-item">
        <a class="nav-link <?php if ($active_tab === 'streamers'): ?>active<?php endif; ?>" href="<?=$router->fromHere('stations:streamers:index') ?>">
            <i class="navdrawer-nav-icon material-icons">mic</i>
            <?=__('Streamer/DJ Accounts') ?>
        </a>
    </li>
<?php endif; ?>
<?php if ($station->getEnablePublicPage() && $station->getEnableStreamers()): ?>
    <li class="nav-item">
        <a class="nav-link" href="<?=$router->named('public:dj', ['station' => $station->getShortName()]) ?>" target="_blank">
            <i class="navdrawer-nav-icon material-icons">surround_sound</i>
            <?=__('Web DJ') ?> <i class="material-icons sm">open_in_new</i>
        </a>
    </li>
<?php endif; ?>

<?php if ($acl->userAllowed($user, 'manage station mounts', $station->getId()) && $frontend::supportsMounts()): ?>
    <li class="nav-item">
        <a class="nav-link <?php if ($active_tab === 'mounts'): ?>active<?php endif; ?>" href="<?=$router->fromHere('stations:mounts:index') ?>">
            <i class="navdrawer-nav-icon material-icons">wifi_tethering</i>
            <?=__('Mount Points') ?>
        </a>
    </li>
<?php endif; ?>

<?php if ($acl->userAllowed($user, 'manage station remotes', $station->getId())): ?>
    <li class="nav-item">
        <a class="nav-link <?php if ($active_tab === 'remotes'): ?>active<?php endif; ?>" href="<?=$router->fromHere('stations:remotes:index') ?>">
            <i class="navdrawer-nav-icon material-icons">router</i>
            <?=__('Remote Relays') ?>
        </a>
    </li>
<?php endif; ?>

<?php if ($acl->userAllowed($user, 'manage station web hooks', $station->getId())): ?>
    <li class="nav-item">
        <a class="nav-link <?php if ($active_tab === 'webhooks'): ?>active<?php endif; ?>" href="<?=$router->fromHere('stations:webhooks:index') ?>">
            <i class="navdrawer-nav-icon material-icons">code</i>
            <?=__('Web Hooks') ?>
        </a>
    </li>
<?php endif; ?>

<?php if ($acl->userAllowed($user, 'view station reports', $station->getId())): ?>
    <li class="nav-item">
        <a class="nav-item nav-link" data-toggle="collapse" href="#sidebar-submenu-reports">
            <i class="navdrawer-nav-icon material-icons">assignment</i>
            <?=__('Reports') ?>
        </a>
        <div class="collapse pb-2" id="sidebar-submenu-reports">
            <ul class="navdrawer-nav">
                <li class="nav-item">
                    <a class="nav-link pl-4 py-2 text-muted" href="<?=$router->fromHere('stations:reports:overview') ?>">
                        <?=__('Statistics Overview') ?>
                    </a>
                </li>
            <?php if ($frontend::supportsListenerDetail()): ?>
                <li class="nav-item">
                    <a class="nav-link pl-4 py-2 text-muted" href="<?=$router->fromHere('stations:reports:listeners') ?>">
                        <?=__('Listeners') ?>
                    </a>
                </li>
            <?php endif; ?>
            <?php if ($station->getEnableRequests()): ?>
                <li class="nav-item">
                    <a class="nav-link pl-4 py-2 text-muted" href="<?=$router->fromHere('stations:reports:requests') ?>">
                        <?=__('Song Requests') ?>
                    </a>
                </li>
            <?php endif; ?>
                <li class="nav-item">
                    <a class="nav-link pl-4 py-2 text-muted" href="<?=$router->fromHere('stations:reports:timeline') ?>">
                        <?=__('Song Playback Timeline') ?>
                    </a>
                </li>
            <?php if ($backend::supportsMedia()): ?>
                <li class="nav-item">
                    <a class="nav-link pl-4 py-2 text-muted" href="<?=$router->fromHere('stations:reports:performance') ?>">
                        <?=__('Song Listener Impact') ?>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link pl-4 py-2 text-muted" href="<?=$router->fromHere('stations:reports:duplicates') ?>">
                        <?=__('Duplicate Songs') ?>
                    </a>
                </li>
            <?php endif; ?>
            <?php if ($frontend::supportsListenerDetail()): ?>
                <li class="nav-item">
                    <a class="nav-link pl-4 py-2 text-muted" href="<?=$router->fromHere('stations:reports:soundexchange') ?>">
                        <?=__('SoundExchange Royalties') ?>
                    </a>
                </li>
            <?php endif; ?>
            </ul>
        </div>
    </li>
<?php endif; ?>

    <li class="sub-menu">
        <a class="nav-item nav-link" data-toggle="collapse" href="#sidebar-submenu-utilities">
            <i class="navdrawer-nav-icon material-icons">settings</i>
            <?=__('Utilities') ?>
        </a>
        <div class="collapse pb-2" id="sidebar-submenu-utilities">
            <ul class="navdrawer-nav">
            <?php if ($acl->userAllowed($user, 'manage station automation', $station->getId()) && $backend::supportsMedia()): ?>
                <li class="nav-item">
                    <a class="nav-link pl-4 py-2 text-muted" href="<?=$router->fromHere('stations:automation:index') ?>">
                        <?=__('Automated Assignment') ?>
                    </a>
                </li>
            <?php endif; ?>
            <?php if ($acl->userAllowed($user, 'view station logs', $station->getId())): ?>
                <li class="nav-item">
                    <a class="nav-link pl-4 py-2 text-muted" href="<?=$router->fromHere('stations:logs:index') ?>">
                        <?=__('Log Viewer') ?>
                    </a>
                </li>
            <?php endif; ?>
            <?php if ($acl->userAllowed($user, 'manage station broadcasting', $station->getId())): ?>
                <li>
                    <a class="api-call nav-link pl-4 py-2 text-muted" data-restart="false" href="<?=$router->fromHere('api:stations:restart') ?>">
                        <?=__('Restart Broadcasting') ?>
                    </a>
                </li>
            <?php endif; ?>
            </ul>
        </div>
    </li>
</ul>
