<?
if ($this->auth->isLoggedIn())
{
    $user = $this->auth->getLoggedInUser();
    $chat_username = $user->name;
}
else
{
    $chat_username = 'PVL_'.mt_rand(0, 10000);
}

$skin = \PVL\Customization::get('theme');
if ($skin == 'dark')
    $chat_skin = 'css/black.css';
else
    $chat_skin = 'css/pvl_light.css';
?>

<script type="text/javascript">
    var PVL_ChatUser = '<?=$chat_username ?>';
    var PVL_ChatSkin = '<?=$skin ?>';
</script>

<?
echo $this->view->special_chat_embed;
?>