<?
$this->assets->collection('custom_js')
    ->addJs('//cdn.socket.io/socket.io-1.3.5.js', false)
    ->addJs('//cdnjs.cloudflare.com/ajax/libs/jplayer/2.9.2/jplayer/jquery.jplayer.min.js', false)
    ->addJs('js/radio.js');

$this->assets->collection('custom_css')
    ->addCss('vendor/world-flags-sprite/stylesheets/flags16.css');
?>
<script type="text/javascript">
    var pvlnode_remote_url = '<?=$this->config->apis->pvlnode_remote_url ?>';
    var pvlnode_remote_path = '<?=$this->config->apis->pvlnode_remote_path ?>';
</script>

<? if ($station_id && $autoplay): ?>
<script type="text/javascript">
var pvl_autoplay_station = <?=$station_id ?>;
</script>
<? endif; ?>

<? if ($volume !== NULL): ?>
<script type="text/javascript">
var pvl_autoplay_volume = <?=(int)$volume ?>;
</script>
<? endif; ?>

<div id="pvl-jplayer-controls-image" style="display: none;">
    <div class="jp-type-single">
        <div class="jp-gui jp-interface clearfix">
            <a href="javascript:;" aria-label="Pause" class="jp-pause" role="button" tabindex="1" title="pause"><i class="icon-pause"></i></a>
            <a href="javascript:;" aria-label="Play" class="jp-play" role="button" tabindex="1" title="play"><i class="icon-play"></i></a>

            <a href="javascript:;" aria-label="Mute" class="jp-mute" role="button" tabindex="1" title="mute"><i class="icon-volume-off"></i></a>
            <a href="javascript:;" aria-label="Unmute" class="jp-unmute" role="button" tabindex="1" title="unmute"><i class="icon-volume-down"></i></a>

            <div class="jp-volume-bar progress">
                <div class="jp-volume-bar-value bar"></div>
            </div>

            <a href="javascript:;" aria-label="Volume Max" class="jp-volume-max" role="button" tabindex="1" title="max volume"><i class="icon-volume-up"></i></a>
        </div>
    </div>
</div>