<?php $this->layout('main', ['title' => __('Music Files'), 'manual' => true, 'page_class' => 'page-file-manager']) ?>

<?php
/** @var \App\Assets $assets */
$assets
    ->load('vue')
    ->load('radio')
    ->load('bootgrid')
    ->load('moment')
    ->load('flowjs')
    ->addInlineJs($this->fetch('stations/files/index.js', [
        'csrf' => $csrf,
        'max_upload_size' => $max_upload_size,
        'playlists' => $playlists,
    ]));
?>

<div class="row">
    <div class="col-sm-12">
        <div class="card">
            <div class="card-body">
                <div class="row mb-3">
                    <div class="col-md-7">
                        <h2 class="card-title"><?=__('Music Files') ?></h2>
                        <h3 class="card-subtitle" id="breadcrumb" class="">&nbsp;</h3>
                    </div>
                    <div class="col-md-5 text-right">
                        <div class="row">
                            <div class="col-md-12">
                                <div class="progress">
                                    <div class="progress-bar" role="progressbar" aria-valuenow="<?=$space_percent ?>" aria-valuemin="0" aria-valuemax="100" style="width: <?=$space_percent ?>%;">
                                        <span class="sr-only"><?=$space_percent ?>%</span>
                                    </div>
                                </div>
                                <?=sprintf(__('%s of %s Used (%s Free)'), $space_used, $space_total, $space_free) ?>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-12">
                                <?=sprintf(__('%s Files', $files_count)) ?>
                            </div>
                        </div>
                    </div>
                </div>

                <?php if (APP_INSIDE_DOCKER): ?>
                    <p><i class="material-icons sm">info</i> <?=sprintf(__('You can also upload files in bulk via SFTP by <a href="%s" target="_blank">following these instructions</a>. Newly uploaded files will automatically be processed within a few minutes.'), 'https://github.com/AzuraCast/AzuraCast/blob/master/SUPPORT.md#access-files-via-sftp-docker-installations') ?></p>
                <?php endif; ?>

                <div id="upload_progress"></div>
                <div id="file_drop_target">
                    <?=__('Drag files here to upload to this folder or ') ?>
                    <input id="file_browse_target" type="file" accept=".mp3,.ogg,.wav,.aac,.mp4,.m4a,audio/*" multiple />
                </div>

                <div class="row pt-4" id="app-toolbar">
                    <div class="col-sm-8">
                        <?=__('With selected:') ?>&nbsp;
                        <div class="btn-group">
                            <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                                <i class="material-icons">add</i> <?=__('Add to Playlist') ?>
                                <span class="caret"></span>
                            </button>
                            <ul class="dropdown-menu" role="menu">
                                <li v-for="playlist in playlists">
                                    <a href="#" class="dropdown-item btn-batch" v-on:click="doBatch" v-bind:data-action="'playlist_' + playlist.id">{{ playlist.name }}</a>
                                </li>
                                <li><a href="#" class="dropdown-item btn-new-playlist" data-toggle="modal" data-target="#mdl-create-playlist"><?=__('Create new...') ?></a></li>
                            </ul>
                        </div>
                        <button type="button" class="btn btn-warning" v-on:click="doBatch" data-action="clear"><i class="material-icons">clear_all</i> <?=__('Clear Playlists') ?></button>
                        <button type="button" class="btn btn-danger" v-on:click="doBatch" data-action="delete"><i class="material-icons">delete</i> <?=__('Delete') ?></button>
                    </div>
                    <div class="col-sm-4 text-right">
                        <a class="btn btn-default" href="#" data-toggle="modal" data-target="#mdl-create-directory"><i class="material-icons">folder</i> <?=__('New Folder') ?></a>
                    </div>
                </div>
            </div>
            <div class="table-responsive">
                <table class="data-table table table-striped" id="file-table">
                    <thead>
                        <tr>
                            <th data-column-id="name" data-formatter="playable" data-identifier="true"><?=__('Name') ?></th>
                            <th data-column-id="media_title" data-visible="false"><?=__('Title') ?></th>
                            <th data-column-id="media_artist" data-visible="false"><?=__('Artist') ?></th>
                            <th data-column-id="media_album" data-visible="false"><?=__('Album') ?></th>
                            <th data-column-id="media_length" data-formatter="file_length"><?=__('Length') ?></th>
                        <?php foreach($custom_fields as $field_key => $field_label): ?>
                            <th data-column-id="<?=$field_key ?>" data-visible="false"><?=$this->e($field_label) ?></th>
                        <?php endforeach; ?>
                            <th data-column-id="size" data-formatter="file_size"><?=__('Size') ?></th>
                            <th data-column-id="mtime" data-formatter="file_mtime"><?=__('Modified') ?></th>
                            <th data-column-id="media_playlists" data-formatter="playlists"><?=__('Playlists') ?></th>
                            <th data-column-id="commands" data-formatter="commands" data-sortable="false"><?=__('Actions') ?></th>
                        </tr>
                    </thead>
                    <tbody></tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="mdl-create-playlist" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <form id="frm-create-playlist">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="exampleModalLabel"><?=__('Create Playlist') ?></h4>
                </div>
                <div class="modal-body">
                    <div class="form-group">
                        <label for="name" class="control-label"><?=__('Playlist Name') ?>:</label>
                        <input type="text" class="form-control" id="fld-playlist-name" name="name">
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <button type="submit" id="btn-create-new-playlist" class="btn btn-primary"><?=__('Create Playlist') ?></button>
                </div>
            </div>
        </form>
    </div>
</div>

<div class="modal fade" id="mdl-create-directory" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <form id="frm-create-directory">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="exampleModalLabel"><?=__('New Directory') ?></h4>
                </div>
                <div class="modal-body">
                    <div class="form-group">
                        <label for="name" class="control-label"><?=__('Directory Name') ?>:</label>
                        <input type="text" class="form-control" id="fld-directory-name" name="name">
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <button type="submit" id="btn-create-new-playlist" class="btn btn-primary"><?=__('Create Directory') ?></button>
                </div>
            </div>
        </form>
    </div>
</div>

<script type="text/javascript" nonce="<?=$assets->getCspNonce() ?>">

</script>
