<?
$affiliates = \Entity\Affiliate::fetch(true);
$columns = \DF\Utilities::columns($affiliates, 3);
?>
<div class="footer-inner">
    <div class="row-fluid">
    <? foreach($columns as $column): ?>
        <div class="span4">
            <ul class="media-list">
            <? foreach($column as $affiliate): ?>
                <li class="media">
                    <div class="media-object pull-left">
                        <a href="<?=$affiliate['web_url'] ?>" target="_blank">
                            <img src="<?=\DF\Url::content($affiliate['image_url']) ?>" alt="<?=$affiliate['name'] ?> Logo" style="width: 40px;">
                        </a>
                    </div>
                    <div class="media-body">
                        <h4>
                        <? if (isset($affiliate['custom'])): ?>
                            <?=$affiliate['custom'] ?><br>
                        <? else: ?>
                            <a href="<?=$affiliate['web_url'] ?>" target="_blank"><?=$affiliate['name'] ?></a><br>
                        <? endif; ?>
                            <small><?=$affiliate['description'] ?></small>
                        </h4>
                    </div>
                </li>
            <? endforeach; ?>
            </ul>
        </div>
    <? endforeach; ?>
    </div>
</div>