<?
$categories = \Entity\Station::getStationsInCategories();
$podcasts = \Entity\Podcast::fetchArray('name');
?>

<ul class="nav primary_menu">

    <!-- About PVL -->
    <li class="dropdown">
        <a href="<?=$this->url->get('about') ?>"><i class="icon-info-sign"></i> About</a>
        <ul class="dropdown-menu">
            <li><a href="<?=$this->url->get('about') ?>"><i class="icon-info-sign"></i> About Us</a></li>
            <li><a href="<?=$this->url->get('contact') ?>"><i class="icon-envelope"></i> Contact Us</a></li>
            <li><a href="<?=$this->url->get('donate') ?>"><i class="icon-money"></i> Support Us</a></li>
            <li class="divider"></li>
            <li><a href="http://m.pvlive.me/"><i class="icon-mobile-phone"></i> PVL! Mobile</a></li>
            <li><a href="<?=$this->url->get('apps') ?>"><i class="icon-cloud-download"></i> Apps &amp; Players</a></li>
            <li><a href="http://docs.ponyvillelive.apiary.io/" target="_blank"><i class="icon-cog"></i> PVL! Data API</a></li>
            <li class="divider"></li>
            <li><a href="<?=$this->url->get('schedule') ?>"><i class="icon-calendar"></i> Station Schedules</a></li>
            <li><a href="<?=$this->url->get('conventions') ?>"><i class="icon-building"></i> Pony Conventions</a></li>
            <li><a href="<?=$this->url->get('artists') ?>"><i class="icon-group"></i> Artists Directory</a></li>
        </ul>
    </li>
    
    <!-- Stations -->
    <li class="dropdown">
        <a href="#" data-toggle="dropdown"><i class="icon-music"></i> Radio</a>
        <ul class="dropdown-menu">
        <? foreach($categories['audio']['stations'] as $station): ?>
            <li><a href="<?=$station['web_url'] ?>" title="<?=$station['genre'] ?>" target="_blank"><?=$station['name'] ?></a></li>
        <? endforeach; ?>
        </ul>
    </li>
    <li class="dropdown">
        <a href="#" data-toggle="dropdown"><i class="icon-facetime-video"></i> Video</a>
        <ul class="dropdown-menu">
        <? foreach($categories['video']['stations'] as $station): ?>
            <li><a href="<?=$station['web_url'] ?>" title="<?=$station['genre'] ?>" target="_blank"><?=$station['name'] ?></a></li>
        <? endforeach; ?>
        </ul>
    </li>
    <li class="dropdown">
        <a href="#" data-toggle="dropdown"><i class="icon-rss"></i> Shows</a>
        <ul class="dropdown-menu">
            <li><a href="<?=$this->url->get('shows') ?>">Show Directory</a></li>
            <li class="divider"></li>
        <? foreach($podcasts as $podcast): ?>
            <li><a href="<?=$podcast['web_url'] ?>" title="<?=$podcast['description'] ?>" target="_blank"><?=$podcast['name'] ?></a></li>
        <? endforeach; ?>
        </ul>
    </li>
    <li class="dropdown">
        <a href="#" data-toggle="dropdown"><i class="icon-user"></i> Community</a>
        <ul class="dropdown-menu">
            <li><a href="http://pvlive.me/forums" target="_blank">PVL Forums</a></li>
            <li><a href="<?=$this->url->get('index/chat') ?>">Chat + Player</a></li>
        </ul>
    </li>

    <li></li>
</ul>