<?
if (!$columns)
    $columns = 3;

$span = 12 / $columns;
?>
<div class="media-list row-fluid row-multiple">
<? foreach($podcasts as $podcast): ?>
    <div class="media podcast span<?=$span ?>">
        <div class="media-object pull-left">
            <a href="<?=$this->url->get('show/view/id/'.$podcast['id']) ?>">
                <img class="station-image" src="<?=\DF\Url::content($podcast['image_url']) ?>" alt="<?=$podcast['name'] ?> Logo">
            </a>
        </div>
        <div class="media-body">
            <div class="station-info">
                <h4>
                <? if (!empty($podcast['country'])): ?>
                    <span class="f16"><span class="flag <?=strtolower($podcast['country']) ?>" title="<?=\PVL\Internationalization::getCountryName($podcast['country']) ?>"></span></span>
                <? endif; ?>
                    <a href="<?=$this->url->get('show/view/id/'.$podcast['id']) ?>"><?=$podcast['name'] ?></a><br>
                    <span class="block genre-info">
                        <?=$podcast['description'] ?>
                    </span>
                <?
                if (count($podcast['stations']) > 0)
                {
                    $station_links = array();
                    foreach($podcast['stations'] as $station)
                    {
                        $station_link = '<a href="'.$station['web_url'].'" target="_blank">'.$station['name'].'</a>';
                        $station_links[] = $station_link;
                    }

                    echo '<span class="block airson-info"><i class="icon-star"></i> Airs on '.implode(', ', $station_links).'</span>';
                }
                ?>
                </h4>

            <? foreach($podcast['episodes'] as $ep): ?>
                <div class="podcast-episode">
                    <?
                    $time_diff = \DF\Utilities::timeDifferenceText(time(), $ep['timestamp'], 0);
                    ?>
                    <small><span title="<?=date('l, F j, Y g:ia', $ep['timestamp']) ?>"><?=$time_diff?> ago</span>:</small><br>
                    <a href="<?=$ep['web_url'] ?>" target="_blank"><b><?=$ep['title'] ?></b></a>
                </div>
            <? endforeach; ?>
            </div>
        </div>
    </div>
<? endforeach; ?>
</div>