<?
$this->assets->collection('custom_js')
    ->addJs('js/videos.js');
?>

<div class="video-channels clearfix row-fluid">
<? foreach((array)$video_channels as $station): ?>
    <a class="video-channel clearfix span3" id="channel_<?=$station['short_name'] ?>" data-id="<?=$station['id'] ?>" data-name="<?=$station['name'] ?>" href="<?=$station['stream_url'] ?>" target="_blank">
        <img class="video-thumbnail" src="<?=\DF\Url::content('images/video_thumbnail.png') ?>" alt="Video Thumbnail" width="426" height="240">

        <div class="station-info">
            <img class="station-image" src="<?=\DF\Url::content($station['image_url']) ?>" alt="<?=$station['name'] ?> Logo">

            <div class="station-name">
                <h4>
                    <? if (!empty($station['country'])): ?>
                        <span class="f16"><span class="flag <?=strtolower($station['country']) ?>" title="<?=\PVL\Internationalization::getCountryName($station['country']) ?>"></span></span>
                    <? endif; ?>
                    <?=$station['name'] ?>
                    <span class="nowplaying-listeners"><i class="icon-user"></i> 0</span>
                    <? if ($station['genre']): ?>
                        <span class="block genre-info"><?=$station['genre'] ?></span>
                    <? endif; ?>
                </h4>

                <? if ($station['now']): ?>
                    <div class="nowplaying-onair underline-when-playing">
                        <i class="icon-star"></i> On Air: <?=$station['now']['title'] ?>
                    </div>
                <? else: ?>
                    <div class="nowplaying-onair underline-when-playing" style="display: none;"></div>
                <? endif; ?>
            </div>
        </div>
    </a>
<? endforeach; ?>
</div>