<div class="media-list" style="padding-bottom: 0; margin-bottom: 0;">
<? foreach((array)$stations as $station): ?>
    <div class="media station video clearfix rendermode-<?=$render_mode ?>" id="station_<?=$station['short_name'] ?>"
        data-id="<?=$station['id'] ?>"
        data-name="<?=$station['name'] ?>"
        data-inactive="<? if ($station['hide_if_inactive']): ?>hide<? else: ?>show<? endif; ?>"
        data-defaultstream="<?=$station['default_stream_id'] ?>"
        data-streamid="<?=$station['current_stream_id'] ?>">

        <div class="media-object pull-left center">
            <div><img class="station-image" src="<?=\DF\Url::content($station['image_url']) ?>" alt="<?=$station['name'] ?> Logo"></div>
        </div>

        <div class="media-body">
            <div class="station-info">
                <!-- Station Header -->
                <h4>
                    <? if (!empty($station['country'])): ?>
                        <span class="f16"><span class="flag <?=strtolower($station['country']) ?>" title="<?=\PVL\Internationalization::getCountryName($station['country']) ?>"></span></span>
                    <? endif; ?>
                    <?=$station['name'] ?>
                    <span class="nowplaying-listeners"><i class="icon-user"></i> 0</span>
                    <? if ($station['genre']): ?>
                        <span class="block genre-info"><?=$station['genre'] ?></span>
                    <? endif; ?>
                </h4>

                <? if ($station['now']): ?>
                    <div class="nowplaying-onair underline-when-playing">
                        <i class="icon-star"></i> On Air: <?=$station['now']['title'] ?>
                    </div>
                <? else: ?>
                    <div class="nowplaying-onair underline-when-playing" style="display: none;"></div>
                <? endif; ?>

                <div class="show-when-playing">
                    <div class="station-player-container"></div>
                </div>

                <!-- Now Playing Information -->
                <div class="song-info underline-when-playing" title="Click for Song Information">
                    <div><big><span class="nowplaying-artist">Loading...</span></big></div>
                    <div><span class="nowplaying-title">Loading...</span></div>
                </div>

                <div class="video-stream-player" style="display: none;">
                    <a href="#" class="btn btn-block btn-inverse btn-launch-video"><i class="icon-facetime-video"></i> Launch Stream</a>
                </div>
            </div>
        </div>
    </div>
<? endforeach; ?>
</div>