<?php

$this->layout(
    'minimal',
    [
        'title' => __('Forgot Password'),
        'page_class' => 'login-content',
    ]
);
?>

<div class="public-page">
    <div class="card">
        <div class="card-body">
            <h2 class="card-title mb-4 text-center"><?=__('Forgot Password')?></h2>

            <form id="login-form" action="" method="post">
                <div class="form-group">
                    <label for="email" class="mb-2 d-flex align-items-center gap-2">
                        <?= $this->fetch('icons/mail') ?>
                        <strong><?= __('E-mail Address') ?></strong>
                    </label>
                    <input type="email" id="email" name="email" class="form-control" placeholder="<?= __(
                        'name@example.com'
                    ) ?>" aria-label="<?= __('E-mail Address') ?>" required autofocus>
                </div>

                <div class="block-buttons mt-2 mb-3">
                    <button type="submit" role="button" title="<?= __(
                        'Sign in'
                    ) ?>" class="btn btn-login btn-primary">
                        <?= __('Send Recovery E-mail') ?>
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>
