<?php
/**
 * @var App\Customization $customization
 * @var App\Environment $environment
 * @var App\Http\RouterInterface $router
 */

$this->layout(
    'minimal',
    [
        'title' => __('Log In'),
        'page_class' => 'login-content',
    ]
);
?>

<div class="public-page">
    <div class="card">
        <div class="card-body">
            <div class="row mb-4">
                <div class="col-sm">
                    <h2 class="card-title text-center">
                        <?php
                        if ($customization->hideProductName()): ?>
                            <?= __('Welcome!') ?>
                        <?php
                        else: ?>
                            <?= sprintf(__('Welcome to %s!'), $environment->getAppName()) ?>
                        <?php
                        endif; ?>
                    </h2>
                    <?php
                    if (!empty($customization->getInstanceName())): ?>
                        <h3 class="card-subtitle text-center text-muted">
                            <?= $this->e($customization->getInstanceName()) ?>
                        </h3>
                    <?php
                    endif; ?>
                </div>
            </div>

            <form id="login-form" action="" method="post">
                <div class="form-group">
                    <label for="username" class="mb-2">
                        <i class="material-icons me-1 align-middle" aria-hidden="true">email</i>
                        <strong><?= __('E-mail Address') ?></strong>
                    </label>
                    <input type="email" id="username" name="username" class="form-control" placeholder="<?= __(
                        'name@example.com'
                    ) ?>" aria-label="<?= __('E-mail Address') ?>" required autofocus>
                </div>
                <div class="form-group mt-3">
                    <label for="password" class="mb-2">
                        <i class="material-icons me-1 align-middle" aria-hidden="true">vpn_key</i>
                        <strong><?= __('Password') ?></strong>
                    </label>
                    <input type="password" id="password" name="password" class="form-control" placeholder="<?= __(
                        'Enter your password'
                    ) ?>" aria-label="<?= __('Password') ?>" required>
                </div>
                <div class="form-group mt-4">
                    <div class="custom-control custom-checkbox">
                        <input type="checkbox" name="remember" id="frm_remember_me" value="1"
                               class="toggle-switch custom-control-input">
                        <label for="frm_remember_me" class="custom-control-label">
                            <?= __('Remember me') ?>
                        </label>
                    </div>
                </div>
                <div class="block-buttons mt-3 mb-3">
                    <button type="submit" role="button" title="<?= __(
                        'Sign in'
                    ) ?>" class="btn btn-login btn-primary">
                        <?= __('Sign in') ?>
                    </button>
                </div>
            </form>

            <p class="text-center m-0"><?= __('Please log in to continue.') ?> <?= sprintf(
                    '<a href="%s">%s</a>',
                    $router->named('account:forgot'),
                    __('Forgot your password?')
                ) ?></p>
        </div>
    </div>
</div>
