<?php
$this->layout('minimal', [
    'title' => __('Log In'),
    'page_class' => 'login-content'
]);
?>

<div class="public-page">
    <div class="card">
        <div class="card-body">
            <h2 class="card-title"><?=__('Enter Two-Factor Code') ?></h2>
            <p class="text-left"><?=__('Your account uses a two-factor security code. Enter the code your device is currently showing below.') ?>

            <form id="login-form" class="pr-5" action="" method="post">
                <div class="input-group">
                    <div class="floating-label">
                        <label for="otp"><?=__('Security Code') ?></label>
                        <input type="number" name="otp" class="form-control form-control-lg" placeholder="" aria-label="<?=__('Security Code') ?>" required>
                    </div>
                    <span class="input-group-icon">
                        <i class="material-icons" aria-hidden="true">lock</i>
                    </span>
                </div>

                <button type="submit" role="button" title="<?=__('Log In') ?>" class="btn btn-login btn-primary btn-float">
                    <i class="material-icons" aria-hidden="true">arrow_forward_ios</i>
                </button>
            </form>
        </div>
    </div>
</div>
