<?php $this->layout('main', ['title' => _('Station Center'), 'manual' => true]) ?>

<?php $this->start('custom_js') ?>
<script type="text/javascript" src="//code.highcharts.com/highcharts.js"></script>
<script type="text/javascript" src="//code.highcharts.com/highcharts-more.js"></script>
<script type="text/javascript" src="//code.highcharts.com/modules/exporting.js"></script>

<?php if ($customization->getTheme() == 'dark'): ?>
<script type="text/javascript" src="<?=$url->content('js/highcharts/dark-blue.js') ?>"></script>
<?php endif; ?>
<?php $this->stop('custom_js') ?>

<script type="text/javascript">
$(function () {
    Highcharts.setOptions({
        global: {
            timezoneOffset: <?=\App\Timezone::getOffsetMinutes() ?>,
            useUTC: false
        }
    });
});
</script>

<div class="row">
    <div class="col-sm-12">
        <div class="card">
            <div class="card-header ch-alt">
                <h2><?=_('Station Statistics') ?></h2>
            </div>
            <div class="card-body card-padding" role="tabpanel">
                <ul class="tab-nav" role="tablist">
                    <li class="active"><a role="tab" data-toggle="tab" aria-expanded="true" aria-controls="listeners-by-day" href="#listeners-by-day"><?=_('Listeners by Day') ?></a></li>
                    <li><a role="tab" data-toggle="tab" aria-controls="listeners-by-hour" href="#listeners-by-hour"><?=_('Listeners by Hour') ?></a></li>
                    <li><a role="tab" data-toggle="tab" aria-controls="listeners-by-day-of-week" href="#listeners-by-day-of-week"><?=_('Listeners by Day of Week') ?></a></li>
                </ul>

                <div class="tab-content">
                    <div class="tab-pane active" id="listeners-by-day" role="tabpanel">
                        <?=$this->fetch('controller::index-dailystats') ?>
                    </div>
                    <div class="tab-pane" id="listeners-by-hour" role="tabpanel">
                        <?=$this->fetch('controller::index-hourlystats') ?>
                    </div>
                    <div class="tab-pane" id="listeners-by-day-of-week" role="tabpanel">
                        <?=$this->fetch('controller::index-dayofweek') ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-sm-6">
        <div class="card">
            <div class="card-header ch-alt">
                <h2><i class="zmdi zmdi-thumb-up"></i> <?=_('Best Performing Songs') ?> <small><?=_('in the last 48 hours') ?></small></h2>
            </div>
            <div class="table-responsive">
                <table class="table table-striped table-condensed table-nopadding">
                    <colgroup>
                        <col width="20%">
                        <col width="80%">
                    </colgroup>
                    <thead>
                        <tr>
                            <th><?=_('Change') ?></th>
                            <th><?=_('Song') ?></th>
                        </tr>
                    </thead>
                    <tbody>
                    <?php foreach($best_performing_songs as $song_row): ?>
                        <tr>
                            <td class="text-center text-success">
                                <i class="zmdi zmdi-thumb-up"></i> <?=abs($song_row['stat_delta']) ?><br>
                                <small><?=$song_row['stat_start'] ?> to <?=$song_row['stat_end'] ?>
                            </td>
                            <td>
                                <?php if ($song_row['song']['title']): ?>
                                    <b><?=$song_row['song']['title'] ?></b><br>
                                    <?=$song_row['song']['artist'] ?>
                                <?php else: ?>
                                    <?=$song_row['song']['text'] ?>
                                <?php endif; ?>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <div class="col-sm-6">
        <div class="card">
            <div class="card-header ch-alt">
                <h2><i class="zmdi zmdi-thumb-down"></i> <?=_('Worst Performing Songs') ?> <small><?=_('in the last 48 hours') ?></small></h2>
            </div>
            <div class="table-responsive">
                <table class="table table-striped table-condensed table-nopadding">
                    <colgroup>
                        <col width="20%">
                        <col width="80%">
                    </colgroup>
                    <thead>
                        <tr>
                            <th><?=_('Change') ?></th>
                            <th><?=_('Song') ?></th>
                        </tr>
                    </thead>
                    <tbody>
                    <?php foreach($worst_performing_songs as $song_row): ?>
                        <tr>
                            <td class="text-center text-danger">
                                <i class="zmdi zmdi-thumb-down"></i> <?=abs($song_row['stat_delta']) ?><br>
                                <small><?=$song_row['stat_start'] ?> to <?=$song_row['stat_end'] ?>
                            </td>
                            <td>
                                <?php if ($song_row['song']['title']): ?>
                                    <b><?=$song_row['song']['title'] ?></b><br>
                                    <?=$song_row['song']['artist'] ?>
                                <?php else: ?>
                                    <?=$song_row['song']['text'] ?>
                                <?php endif; ?>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-sm-12">
        <div class="card">
            <div class="card-header ch-alt">
                <h2><?=_('Most Played Songs') ?> <small><?=_('in the last month') ?></small></h2>
            </div>
            <div class="table-responsive">
                <table class="table table-striped table-condensed table-nopadding">
                    <colgroup>
                        <col width="10%">
                        <col width="90%">
                    </colgroup>
                    <thead>
                        <tr>
                            <th><?=_('Plays') ?></th>
                            <th><?=_('Song') ?></th>
                        </tr>
                    </thead>
                    <tbody>
                    <?php foreach($song_totals['played'] as $song_row): ?>
                        <tr>
                            <td class="text-center"><?=$song_row['records'] ?></td>
                            <td>
                            <?php if ($song_row['song']['title']): ?>
                                <b><?=$song_row['song']['title'] ?></b><br>
                                <?=$song_row['song']['artist'] ?>
                            <?php else: ?>
                                <?=$song_row['song']['text'] ?>
                            <?php endif; ?>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>