<?php $this->layout('main', ['title' => 'Recent Playback Timeline', 'manual' => true]) ?>

<div class="block-header">
    <h2><?=$this->e($station->name) ?></h2>
</div>

<div class="card">
    <div class="card-header ch-alt">
        <h2><?=_('Station Playback Timeline') ?></h2>

        <ul class="actions">
            <li>
                <a href="<?=$url->routeFromHere(['format' => 'csv']) ?>" title="Download Excel CSV">
                    <i class="zmdi zmdi-download"></i>
                </a>
            </li>
        </ul>
    </div>
    <div class="table-responsive">
        <table class="data-table table table-striped">
            <colgroup>
                <col width="15%">
                <col width="10%">
                <col width="10%">
                <col width="45%">
                <col width="20%">
            </colgroup>
            <thead>
                <tr>
                    <th data-column-id="date_time"><?=_('Date/Time') ?></th>
                    <th data-column-id="listeners"><?=_('Listeners') ?></th>
                    <th data-column-id="delta"><?=_('Change') ?></th>
                    <th data-column-id="song"><?=_('Song Title') ?></th>
                    <th data-column-id="playlists"><?=_('Playlist(s)') ?></th>
                </tr>
            </thead>
            <tbody>
            <?php foreach($songs as $song_row): ?>
                <tr class="input" id="song_<?=$song_row['timestamp'] ?>">
                    <td class="text-center"><?=date('D g:ia', $song_row['timestamp_start']) ?></td>
                    <td class="text-center"><big><?=$song_row['stat_start'] ?></big></td>
                    <td class="text-center">
                        <big>
                    <?php if ($song_row['stat_delta'] > 0): ?>
                        <span class="text-success"><i class="icon-caret-up"></i> <?=$song_row['stat_delta'] ?></span>
                    <?php elseif ($song_row['stat_delta'] < 0): ?>
                        <span class="text-danger"><i class="icon-caret-down"></i> <?=abs($song_row['stat_delta']) ?></span>
                    <?php else: ?>
                        0
                    <?php endif; ?>
                        </big>
                    </td>
                    <td>
                        <?php if ($song_row['song']['title']): ?>
                            <b><?=$song_row['song']['title'] ?></b><br>
                            <?=$song_row['song']['artist'] ?>
                        <?php else: ?>
                            <?=$song_row['song']['text'] ?>
                        <?php endif; ?>
                        <?php if ($song_row['requested']): ?>
                            <br>
                            <span class="label label-default">Requested on <?=date('D g:ia', $song_row['requested']) ?></span>
                        <?php endif; ?>
                        <!-- <a href="#" class="btn-show-song-info" data-id="<?=$song_row['song']['id'] ?>" title="Click for Song Information"></a> -->
                    </td>
                    <td><?=implode('<br>', $song_row['playlists']) ?></td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>

<script type="text/javascript">
    $(function() {
        $(".data-table").bootgrid({
            caseSensitive: false,
            sorting: false,
            css: {
                icon: 'zmdi icon',
                iconColumns: 'zmdi-view-module',
                iconDown: 'zmdi-sort-amount-desc',
                iconRefresh: 'zmdi-refresh',
                iconUp: 'zmdi-sort-amount-asc'
            }
        });
    });
</script>