<?php $this->layout('main', ['title' => __('Restart Broadcasting'), 'manual' => true]) ?>

<div class="card">
    <div class="card-header ch-alt">
        <h2><?=__('Restart Broadcasting') ?></h2>
    </div>
    <div class="card-body card-padding">
        <p><?=__('Your station\'s configuration has been rewritten and broadcasting has been restarted. Status messages related to this process are listed below.') ?></p>

        <?php if ($flash->hasMessages()): ?>
            <?php foreach($flash->getMessages() as $message): ?>
                <div class="alert alert-<?=$message['color'] ?>">
                    <?=nl2br($message['text']) ?>
                </div>
            <?php endforeach; ?>
        <?php endif; ?>

        <script type="text/javascript" nonce="<?=$assets->getCspNonce() ?>">
            $(function() {
                $('ul.main-menu').find('li.menu-alert,li.menu-info').hide();
            });
        </script>
    </div>
</div>