---
- name: Add nodejs repository key
  apt_key:
    url: "{{ azuracast_build_node_keyring_url }}"
    keyring: "{{ azuracast_build_node_keyring_path }}"

- name: Add nodejs repositories
  apt_repository:
    repo: "{{ _current_repo }}"
  loop: "{{ azuracast_build_node_repositories }}"
  loop_control:
    loop_var: _current_repo

- name: Install system dependencies
  apt:
    name: "{{ azuracast_build_system_packages }}"
    update_cache: true

- name: Set permissions for folders
  file:
    path: "{{ _current_directory }}"
    state: directory
    owner: "{{ azuracast_user }}"
    group: "{{ azuracast_www_group }}"
    mode: 0755
  loop: "{{ azuracast_www_directories }}"
  loop_control:
    loop_var: _current_directory

- name: Install node dependencies
  block:
    - name: Pull Node Dependencies
      become: true
      become_user: "{{ azuracast_user }}"
      command: >-
        npm ci
      args:
        chdir: "{{ azuracast_src_dir }}/frontend"

    - name: Build AzuraCast Frontend Scripts
      become: true
      become_user: "{{ azuracast_user }}"
      command: >-
        npm run build
      args:
        chdir: "{{ azuracast_src_dir }}/frontend"

    - name: Set permissions of generated frontend content
      command: >-
        {{ _current_perm_command }}
      loop:
        - "chown -R azuracast:www-data {{ azuracast_src_dir }}"
        - "find {{ azuracast_src_dir }} -type d -exec chmod 755 {} \\;"
        - "find {{ azuracast_src_dir }} -type f -exec chmod 644 {} \\;"
      loop_control:
        loop_var: _current_perm_command

    - name: Mark nodejs setup done
      copy:
        dest: /etc/ansible/facts.d/azuracast_nodejs_done.fact
        content: "True"
        mode: 0644
  when: >-
    not (ansible_local.azuracast_nodejs_done | default(false))
    or (force_update | default(false))
