<?
$title = 'Manage API Keys';
$manual = true;
?>
<div class="block-header">
    <h2>Administration</h2>
</div>

<div class="card">
    <div class="card-header ch-alt">
        <h2>API Keys</h2>
        <a class="btn bgm-blue btn-float" href="<?=$url->routeFromHere(array('action' => 'edit')) ?>"><i class="zmdi zmdi-plus"></i></a>
    </div>
    <div class="table-responsive">
        <table class="table table-striped">
            <colgroup>
                <col width="20%">
                <col width="35%">
                <col width="10%">
                <col width="35%">
            </colgroup>
            <thead>
            <tr>
                <th>&nbsp;</th>
                <th>API Key</th>
                <th>Calls</th>
                <th>Owner</th>
            </tr>
            </thead>
            <tbody>
            <? foreach($records as $record): ?>
                <tr class="input">
                    <td class="center">
                        <a class="btn btn-sm btn-primary" href="<?=$url->routeFromHere(array('action' => 'edit', 'id' => $record['id'])) ?>">Edit</a>
                        <a class="btn btn-sm btn-danger" href="<?=$url->routeFromHere(array('action' => 'delete', 'id' => $record['id'])) ?>">Revoke</a>
                    </td>
                    <td><code><?=$record['id'] ?></code></td>
                    <td><?=$record['calls_made'] ?></td>
                    <td><?=$record['owner'] ?></td>
                </tr>
            <? endforeach; ?>
            </tbody>
        </table>
    </div>
</div>