<?php /** @var \Entity\Station $station */ ?>

<?php $this->layout('minimal', ['page_class' => 'embed', 'title' => $this->e($station->getName())]) ?>

<?php
/** @var \AzuraCast\Assets $assets */
$assets
    ->load('vue')
    ->load('radio');
?>

<ul class="actions pull-right">
    <?=$this->fetch('partials/radio_controls') ?>
</ul>
<div class="stations nowplaying">
    <?=$this->fetch('frontend/public/player_component') ?>
</div>

<script type="text/javascript" nonce="<?=$assets->getCspNonce() ?>">
$(function() {
    function loadNowPlaying() {
        $.getJSON('<?=$url->named('api:nowplaying:index', ['station' => $station->getId()]) ?>', function(row) {
            nowPlaying.np = row;

            if ('mediaSession' in navigator) {
                navigator.mediaSession.metadata = new MediaMetadata({
                    title: row.now_playing.song.title,
                    artist: row.now_playing.song.artist
                });
            }

            setTimeout(loadNowPlaying, 15000);
        });
    }

    loadNowPlaying();
});
</script>