<?php /** @var \Entity\Station $station */ ?>

<?php $this->layout('minimal', ['title' => $this->e($station->getName()), 'page_class' => 'public-page-content']) ?>

<?php
/** @var \AzuraCast\Assets $assets */
$assets
    ->load('vue')
    ->load('radio')
    ->load('bootgrid');
?>

<div class="public-page">
    <div class="public-block">

        <ul class="actions pull-right" id="radio-player-controls">
            <li><a href="javascript:;" class="jp-mute" title="<?=_('Mute') ?>"><i class="zmdi zmdi-volume-up"></i></a></li>
            <li><a href="javascript:;" class="jp-unmute" title="<?=_('Unmute') ?>"><i class="zmdi zmdi-volume-off"></i></a></li>
            <li>
                <div class="progress jp-volume-bar" style="width: 100px; height: 15px;">
                    <div class="jp-volume-bar-value progress-bar" role="progressbar"></div>
                </div>
            </li>
        </ul>
        <h3 class="text-left"><?=$this->e($station->getName()) ?></h3>

        <div class="stations nowplaying">
            <div class="media media-left" id="station-nowplaying">
                <div class="pull-left p-r-10 p-t-5">
                    <a class="btn-audio" href="#" data-url="<?=$this->e($stream_url) ?>">
                        <i class="zmdi zmdi-play"></i>
                    </a>
                </div>
                <div class="pull-left p-r-10" v-if="np.now_playing.song.art">
                    <a v-bind:href="np.now_playing.song.art" target="_blank"><img v-bind:src="np.now_playing.song.art" style="width: 50px; height: auto; border-radius: 5px;"></a>
                </div>
                <div class="media-body">
                    <h4 class="media-heading">
                        {{ np.now_playing.song.title }}
                    </h4>
                    <div>
                        {{ np.now_playing.song.artist }}
                    </div>
                    <div class="nowplaying-progress" v-if="time_display">
                        {{ time_display }}
                    </div>
                </div>
            </div>
        </div>

        <div class="buttons">
            <a class="btn btn-default btn-icon-text" data-toggle="modal" data-target="#modal-history">
                <i class="zmdi zmdi-time-restore"></i> <?=_('Song History') ?>
            </a>
        <?php if ($station->getEnableRequests()): ?>
            <a class="btn btn-default btn-icon-text" data-toggle="modal" data-target="#modal-request">
                <i class="zmdi zmdi-help-outline"></i> <?=_('Request Song') ?>
            </a>
        <?php endif; ?>
            <div class="btn-group">
                <button type="button" class="btn btn-default btn-icon-text dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="zmdi zmdi-download"></i> <?=_('Playlist') ?> <span class="caret"></span>
                </button>
                <ul class="dropdown-menu">
                    <?php foreach(['pls', 'm3u'] as $format): ?>
                        <li><a href="<?=$url->named('public:playlist', ['station' => $station->getShortName(), 'format' => $format]) ?>"><?=sprintf(_('Download %s'), strtoupper($format)) ?></a></li>
                    <?php endforeach; ?>
                </ul>
            </div>
        </div>

    </div>
</div>

<div class="modal fade" id="modal-history" tabindex="-1" role="dialog" aria-labelledby="modal-history-label">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="modal-history-label"><?=_('Song History') ?></h4>
            </div>
            <div class="modal-body">
                <ol type="1" id="station-history">
                    <li v-for="row in history">
                        <b>{{ row.song.title }}</b><br>
                        {{ row.song.artist }}
                    </li>
                </ol>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="modal-request" tabindex="-1" role="dialog" aria-labelledby="modal-request-label">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="modal-request-label"><?=_('Request a Song') ?></h4>
            </div>
            <div class="modal-body">

                <table class="data-table table table-striped" id="requests-table">
                    <thead>
                    <tr>
                        <th data-column-id="song_id" data-identifier="true" data-visible="false" data-visible-in-selection="false">ID</th>
                        <th data-column-id="song_title"><?=_('Title') ?></th>
                        <th data-column-id="song_artist"><?=_('Artist') ?></th>
                        <th data-column-id="song_album" data-visible="false"><?=_('Album') ?></th>
                        <th data-column-id="commands" data-formatter="commands" data-sortable="false"><?=_('Actions') ?></th>
                    </tr>
                    </thead>
                    <tbody></tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript" nonce="<?=$assets->getCspNonce() ?>">
var nowPlaying;

function iterateTimer() {
    var np_elapsed = nowPlaying.np.now_playing.elapsed;
    var np_total = nowPlaying.np.now_playing.duration;

    if (np_elapsed < np_total) {
        nowPlaying.np.now_playing.elapsed = np_elapsed + 1;
    }
}

function formatTime(time) {
    var sec_num = parseInt(time, 10);

    var hours = Math.floor(sec_num / 3600);
    var minutes = Math.floor((sec_num - (hours * 3600)) / 60);
    var seconds = sec_num - (hours * 3600) - (minutes * 60);

    if (hours < 10) {
        hours = "0" + hours;
    }
    if (minutes < 10) {
        minutes = "0" + minutes;
    }
    if (seconds < 10) {
        seconds = "0" + seconds;
    }
    return (hours !== "00" ? hours + ':' : "") + minutes + ':' + seconds;
}

$(function() {
    nowPlaying = new Vue({
        el: '#station-nowplaying',
        data: {
            np: {
                now_playing: {
                    song: {
                        title: '<?= _('Song Title') ?>',
                        artist: '<?= _('Song Artist') ?>',
                        art: '<?= $url->content('img/generic_song.jpg') ?>'
                    },
                    is_request: false,
                    elapsed: 0,
                    duration: 0
                }
            }
        },
        computed: {
            "time_display": function() {
                var time_played = this.np.now_playing.elapsed;
                var time_total = this.np.now_playing.duration;

                if (!time_total) {
                    return null;
                }

                if (time_played > time_total) {
                    time_played = time_total;
                }

                return formatTime(time_played) + ' / ' + formatTime(time_total);
            }
        }
    });

    songHistory = new Vue({
        el: '#station-history',
        data: {
            history: [
                {
                    song: {
                        title: '<?= _('Song Title') ?>',
                        artist: '<?= _('Song Artist') ?>'
                    }
                }
            ]
        }
    });

    function loadNowPlaying() {
        $.getJSON('<?=$url->named('api:nowplaying:index', ['station' => $station->getId()]) ?>', function(row) {
            nowPlaying.np = row;
            songHistory.history = row.song_history;

            if ('mediaSession' in navigator) {
                navigator.mediaSession.metadata = new MediaMetadata({
                    title: row.now_playing.song.title,
                    artist: row.now_playing.song.artist
                });
            }

            setTimeout(loadNowPlaying, 15000);
        });
    }

    loadNowPlaying();

    setInterval(iterateTimer, 1000);
});

var request_dialog = $('#modal-request');

request_dialog.on('show.bs.modal', function (event) {

    if (!request_dialog.data('request_loaded'))
    {
        var grid = $("#requests-table").bootgrid({
            ajax: true,
            rowSelect: false,
            caseSensitive: false,
            css: {
                icon: 'zmdi icon',
                iconColumns: 'zmdi-view-module',
                iconDown: 'zmdi-sort-amount-desc',
                iconRefresh: 'zmdi-refresh',
                iconUp: 'zmdi-sort-amount-asc'
            },
            url: "<?=$url->named('api:requests:list', ['station' => $station->getId()]) ?>",
            formatters: {
                "commands": function(column, row) {
                    return '<a class="btn btn-request btn-sm btn-primary" data-url="'+row.request_url+'"><?=_('Request') ?></a>';
                }
            }
        }).on("loaded.rs.jquery.bootgrid", function()
        {
            /* Executes after data is loaded and rendered */
            grid.find(".btn-request").on("click", function(e)
            {
                e.preventDefault();
                request_dialog.modal('hide');

                $.ajax({
                    dataType: "json",
                    url: $(this).data('url')
                }).done(function(data) {
                    notify(data, 'success');
                }).fail(function(jqXhr) {
                    notify('Error: ' + jqXhr.responseJSON, 'danger');
                });

                return false;
            });
        });

        request_dialog.data('request_loaded', true);
    }

});
</script>