<?php $this->layout('main', ['title' => 'Song Duplicates', 'manual' => true]) ?>

<div class="block-header">
    <h2><?=$station->name ?></h2>
</div>

<div class="card">
    <div class="card-header ch-alt">
        <h2>Possible Song Duplicates</h2>
    </div>
<?php if (empty($dupes)): ?>
    <div class="card-body card-padding">
        No duplicates were found. Nice work!
    </div>
<?php else: ?>
    <?php foreach($dupes as $dupe_row): ?>
        <div class="table-responsive">
            <table class="table table-striped">
                <colgroup>
                    <col width="15%">
                    <col width="55%">
                    <col width="15%">
                    <col width="15%">
                </colgroup>
                <thead>
                    <tr>
                        <th>Actions</th>
                        <th>Title / File Path</th>
                        <th class="text-right">Playlists</th>
                        <th class="text-right">Length</th>
                    </tr>
                </thead>
                <tbody>
                <?php foreach($dupe_row as $media_row): ?>
                    <tr class="input">
                        <td>
                            <a class="btn btn-sm btn-danger" href="<?=$url->routeFromHere(['action' => 'deletedupe', 'media_id' => $media_row['id']]) ?>">Delete</a>
                        </td>
                        <td>
                            <big><?=$media_row['song']['artist'] ?> - <?=$media_row['song']['title'] ?></big><br>
                            <?=$media_row['path'] ?>
                        </td>
                        <td class="text-right">
                        <?php if (count($media_row['playlists']) == 0): ?>
                            0
                        <?php else: ?>
                            <abbr title="<?=implode(', ', \App\Utilities::ipull($media_row['playlists'], 'name')) ?>"><?=count($media_row['playlists']) ?></abbr>
                        <?php endif; ?>
                        </td>
                        <td class="text-right"><?=$media_row['length_text'] ?></td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    <?php endforeach; ?>
<?php endif; ?>
</div>