<?php
$title = 'Syndication Sources';
echo $this->viewHelper->renderHere('header', true, array('title' => $title));
?>

<p>The <?=$this->config->application->name ?> system automatically syndicates episodes from each of the sources below. You can show or hide individual episodes from the main Podcast Center.</p>

<div class="buttons">
    <?=$this->viewHelper->button(array(
        'type'      => 'link',
        'class'     => 'btn-large success',
        'href'      => $this->viewHelper->routeFromHere(array('action' => 'edit')),
        'icon'      => 'icon-plus-sign',
        'text'      => 'Add New Source',
    )) ?>
</div>

<table class="table table-striped table-bordered table-condensed">
    <colgroup>
        <col width="20%">
        <col width="20%">
        <col width="20%">
        <col width="40%">
    </colgroup>
    <thead>
    <tr>
        <th>Actions</th>
        <th>Source Type</th>
        <th>Episodes</th>
        <th>URL</th>
    </tr>
    </thead>
    <tbody>
    <? foreach($sources as $record): ?>
        <tr class="input <? if ($record['is_default']) { ?>blue<? } elseif (!$record['is_active']) { ?>disabled<? } ?>">
            <td class="center">
                <div class="btn-group">
                    <?=$this->viewHelper->button(array(
                        'type'      => 'link',
                        'class'     => 'btn-small',
                        'href'      => $this->viewHelper->routeFromHere(array('action' => 'edit', 'id' => $record['id'])),
                        'icon'      => 'icon-pencil',
                        'text'      => 'Edit',
                    )) ?>
                    <?=$this->viewHelper->button(array(
                        'type'      => 'link',
                        'class'     => 'btn-small btn-danger confirm-action',
                        'href'      => $this->viewHelper->routeFromHere(array('action' => 'delete', 'id' => $record['id'])),
                        'icon'      => 'icon-trash',
                        'text'      => 'Delete',
                    )) ?>
                </div>
            </td>
            <td class="center">
                <?=$record->type ?>
            </td>
            <td class="center">
                <?=count($record->episodes) ?>
            </td>
            <td><?=$this->viewHelper->link($record->url) ?></td>
        </tr>
    <? endforeach; ?>
    </tbody>
</table>