<?php $this->layout('main', ['title' => _('Station Profile'), 'manual' => true]) ?>

<?php $this->start('custom_js') ?>
<script type="text/javascript" src="<?=$url->content('vendors/bower_components/store-js/store.min.js') ?>"></script>
<script type="text/javascript" src="<?=$url->content('js/radio.js') ?>"></script>
<?php $this->stop('custom_js') ?>

<div class="row">
    <div class="col-sm-6">

        <div class="card">
            <div class="card-header ch-alt">
                <h2><?=_('On the Air') ?></h2>
            </div>
            <div class="card-body card-padding nowplaying" id="station_<?=$station->id ?>">
                <div class="row">

                    <div class="col-sm-4">
                        <div class="m-l-25" style="position: relative;">
                            <div style="position: absolute; top: 0; left: -22px;"><i class="zmdi-hc-lg zmdi zmdi-collection-music"></i></div>

                            <h6><?=_('Now Playing') ?>:</h6>

                            <h4 class="media-heading nowplaying-title">
                                <?= _('Song Title') ?>
                            </h4>
                            <div class="nowplaying-artist">
                                <?= _('Song Artist') ?>
                            </div>
                            <div class="nowplaying-progress" style="display: none;"></div>
                        </div>
                    </div>

                    <div class="col-sm-4">
                        <div class="m-l-25" style="position: relative;">
                            <div style="position: absolute; top: 0; left: -22px;"><i class="zmdi-hc-lg zmdi zmdi-skip-next"></i></div>

                            <h6><?=_('Playing Next') ?>:</h6>

                            <h4 class="media-heading nowplaying-next-title">
                                <?= _('Song Title') ?>
                            </h4>
                            <div class="nowplaying-next-artist">
                                <?= _('Song Artist') ?>
                            </div>
                        </div>
                    </div>

                    <div class="col-sm-3">
                        <div class="m-l-25" style="position: relative;">
                            <div style="position: absolute; top: 0; left: -22px;"><i class="zmdi-hc-lg zmdi zmdi-headset"></i></div>

                            <h6><?=_('Listeners') ?>:</h6>

                            <h4><span class="nowplaying-listeners">0</span> <?=_('Total') ?></h4>
                            <div>
                                <span class="nowplaying-listeners-unique">0</span> <?=_('Unique') ?>
                            </div>
                        </div>
                    </div>

                </div>

            </div>
        </div>



        <div class="card">
            <div class="card-header ch-alt">
                <h2><?=_('Station Profile') ?></h2>

                <?php if ($acl->isAllowed('manage station profile', $station->id)): ?>
                <a class="btn bgm-blue btn-float" title="Edit Profile" href="<?=$url->routeFromHere(array('action' => 'edit')) ?>"><i class="zmdi zmdi-edit"></i></a>
                <?php endif; ?>
            </div>
            <table class="table table-striped table-responsive">
                <colgroup>
                    <col width="30%">
                    <col width="70%">
                </colgroup>
                <tbody>
                    <tr>
                        <td><?=_('Name') ?></td>
                        <td><?=$this->e($station->name) ?></td>
                    </tr>
                    <tr>
                        <td><?=_('Description') ?></td>
                        <td><?=$this->e($station->description) ?></td>
                    </tr>
                    <?php if ($backend->supportsRequests()): ?>
                    <tr>
                        <td><?=_('Song Requests') ?></td>
                        <td>
                        <?php if ($station->enable_requests): ?>
                            <span class="text-success"><?=_('Enabled') ?></span>

                            <div class="form-field">
                                <textarea class="full-width form-control text-preformatted" style="height: 50px;"><iframe src="<?=$url->named('public:embedrequests', ['station' => $station->getShortName()], true) ?>" frameborder="0" allowtransparency="true" style="width: 100%; min-height: 850px; border: 0;"></iframe></textarea>
                            </div>
                        <?php else: ?>
                            <span class="text-danger"><?=_('Disabled') ?></span><br><small><?=_('Edit station profile to enable.') ?></small>
                        <?php endif; ?>
                        </td>
                    </tr>
                    <? endif; ?>
                    <?php if ($backend->supportsStreamers()): ?>
                    <tr>
                        <td><?=_('Streamers/DJs') ?></td>
                        <td>
                        <?php if ($station->enable_streamers): ?>
                            <span class="text-success"><?=_('Enabled') ?></span><br>
                            <a href="<?=$url->routeFromHere(['controller' => 'streamers']) ?>"><?=_('Manage streamer accounts') ?></a>
                        <?php else: ?>
                            <span class="text-danger"><?=_('Disabled') ?></span><br><small><?=_('Edit station profile to enable.') ?></small>
                        <?php endif; ?>
                        </td>
                    </tr>
                    <? endif; ?>
                    <tr>
                        <td><?=_('Base Directory') ?></td>
                        <td class="text-preformatted"><?=$station->getRadioBaseDir() ?></td>
                    </tr>
                    <tr>
                        <td><?=_('Media Directory') ?></td>
                        <td class="text-preformatted"><?=$station->getRadioMediaDir() ?></td>
                    </tr>
                    <tr>
                        <td><?=_('Player Embed Code') ?></td>
                        <td class="form-field">
                            <textarea class="full-width form-control text-preformatted" style="height: 50px;"><iframe src="<?=$url->named('public:embed', ['station' => $station->getShortName()], true) ?>" frameborder="0" allowtransparency="true" style="width: 100%; min-height: 150px; border: 0;"></iframe></textarea>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
    <div class="col-sm-6">
        <?php if ($frontend_type == 'remote'): ?>
        <div class="card">
            <div class="card-header bgm-bluegray ch-alt">
                <h2>
                    <?=_('External Radio Server') ?>
                </h2>
            </div>
            <div class="card-body card-padding">
                <dl>
                    <dt><?=_('Stream Public URL') ?>:</dt>
                    <dd>
                        <?php foreach($stream_urls as $stream_url): ?>
                            <div><a href="<?=$stream_url ?>"><?=$stream_url ?></a></div>
                        <?php endforeach; ?>
                    </dd>
                </dl>
            </div>
        </div>
        <?php else: ?>
        <div class="card">
            <div class="card-header <?php if ($frontend_is_running): ?>bgm-green<?php else: ?>bgm-red<?php endif; ?> ch-alt">
                <h2>
                    <?php if ($frontend_type == 'icecast'): ?>
                        <?=_('IceCast (Broadcasting Service)') ?>
                    <?php elseif ($frontend_type == 'shoutcast2'): ?>
                        <?=_('ShoutCast (Broadcasting Service)') ?>
                    <?php endif; ?>
                    <br><small><?php if ($frontend_is_running): ?><?=_('Running') ?><?php else: ?><?=_('Not Running') ?><?php endif; ?></small>
                </h2>

                <?php if ($acl->isAllowed('manage station broadcasting', $station->id)): ?>
                <ul class="actions">
                    <li class="dropdown">
                        <a href="" data-toggle="dropdown" aria-expanded="false">
                            <i class="zmdi zmdi-more-vert"></i>
                        </a>
                        <ul class="dropdown-menu dropdown-menu-right">
                            <li><a href="<?=$url->routeFromHere(['action' => 'frontend', 'do' => 'restart']) ?>"><?=_('Restart Service') ?></a></li>
                            <li><a href="<?=$url->routeFromHere(['action' => 'frontend', 'do' => 'start']) ?>"><?=_('Start Service') ?></a></li>
                            <li><a href="<?=$url->routeFromHere(['action' => 'frontend', 'do' => 'stop']) ?>"><?=_('Stop Service') ?></a></li>
                        </ul>
                    </li>
                </ul>
                <?php endif; ?>
            </div>

            <table class="table table-condensed table-striped">
                <colgroup>
                    <col width="10%">
                    <col width="90%">
                </colgroup>
                <thead>
                    <tr>
                        <th>&nbsp;</th>
                        <th><?=_('Public URL') ?></th>
                    </tr>
                </thead>
                <tbody>
                <?php foreach($stream_urls as $stream_url): ?>
                <tr class="input">
                    <td>
                        <a class="btn-audio" href="#" data-url="<?=$stream_url ?>">
                            <i class="zmdi zmdi-play"></i>
                        </a>
                    </td>
                    <td>
                        <a href="<?=$stream_url ?>"><?=$stream_url ?></a>
                    </td>
                </tr>
                <?php endforeach; ?>
                </tbody>
            </table>

            <div class="card-body card-padding">
                <dl>
                    <dt><?=_('Stream Playlists') ?>:</dt>
                    <dd>
                        <a class="btn btn-xs btn-primary" href="<?=$url->named('public:playlist', ['station' => $station->getShortName(), 'format' => 'pls']) ?>">PLS</a>
                        <a class="btn btn-xs btn-primary" href="<?=$url->named('public:playlist', ['station' => $station->getShortName(), 'format' => 'm3u']) ?>">M3U</a>
                    </dd>
                </dl>

                <dl>
                    <dt><?=_('Administration URL') ?>:</dt>
                    <dd><a href="<?=$frontend->getAdminUrl() ?>"><?=$frontend->getAdminUrl() ?></a></dd>

                    <dt><?=_('Administrator Password') ?>:</dt>
                    <dd><?=$frontend_config['admin_pw'] ?></dd>

                    <dt><?=_('Source Password') ?>:</dt>
                    <dd><?=$frontend_config['source_pw'] ?></dd>
                </dl>
            </div>
        </div>
        <?php endif; ?>

        <?php if ($backend_type == 'none'): ?>
        <div class="card">
            <div class="card-header bgm-bluegray ch-alt">
                <h2><?=_('AutoDJ Disabled') ?></h2>
            </div>
            <div class="card-body card-padding">
                <p><?=_('AutoDJ has been disabled for this station. No music will automatically be played when a source is not live.') ?></p>
            </div>
        </div>
        <?php else: ?>
        <div class="card">
            <div class="card-header <?php if ($backend_is_running): ?>bgm-green<?php else: ?>bgm-red<?php endif; ?> ch-alt">
                <h2>
                <?php if ($backend_type == 'liquidsoap'): ?>
                    <?=_('LiquidSoap (AutoDJ Service)') ?><br>
                <?php endif; ?>
                    <small><?php if ($backend_is_running): ?><?=_('Running') ?><?php else: ?><?=_('Not Running') ?><?php endif; ?></small>
                </h2>

                <?php if ($acl->isAllowed('manage station broadcasting', $station->id)): ?>
                <ul class="actions">
                    <li class="dropdown">
                        <a href="" data-toggle="dropdown" aria-expanded="false">
                            <i class="zmdi zmdi-more-vert"></i>
                        </a>
                        <ul class="dropdown-menu dropdown-menu-right">
                            <li><a href="<?=$url->routeFromHere(['action' => 'backend', 'do' => 'skip']) ?>"><?=_('Skip Song') ?></a></li>
                            <li class="divider">&nbsp;</li>
                            <li><a href="<?=$url->routeFromHere(['action' => 'backend', 'do' => 'restart']) ?>"><?=_('Restart Service') ?></a></li>
                            <li><a href="<?=$url->routeFromHere(['action' => 'backend', 'do' => 'start']) ?>"><?=_('Start Service') ?></a></li>
                            <li><a href="<?=$url->routeFromHere(['action' => 'backend', 'do' => 'stop']) ?>"><?=_('Stop Service') ?></a></li>
                        </ul>
                    </li>
                </ul>
                <?php endif; ?>
            </div>
            <div class="card-body card-padding">
                <p><?=sprintf(_('LiquidSoap is currently shuffling from <b>%d uploaded songs</b> in <b>%d playlists</b>.'), $num_songs, $num_playlists) ?></p>

                <?php if ($acl->isAllowed('manage station media', $station->id)): ?>
                    <div class="buttons">
                        <a class="btn btn-primary" href="<?=$url->named('stations:files:index', ['station' => $station->id]) ?>"><?=_('Music Files') ?></a>
                        <a class="btn btn-primary" href="<?=$url->named('stations:playlists:index', ['station' => $station->id]) ?>"><?=_('Playlists') ?></a>
                    </div>
                <?php endif; ?>
            </div>
        </div>
        <?php endif; ?>
    </div>
</div>

<script type="text/javascript">
function nowPlaying() {
    $.getJSON('<?=$url->route([
        'module' => 'api',
        'controller' => 'nowplaying',
        'station' => $station->id
    ]) ?>', {}, function (row) {
        var station_row = $('#station_'+row.station.id);

        var np_title = row.now_playing.song.title;
        if (row.now_playing.is_request) {
            np_title += '<span class="label label-default">Listener Request</span>';
        }
        station_row.find('.nowplaying-title').html(np_title);
        station_row.find('.nowplaying-artist').text(row.now_playing.song.artist);

        station_row.find('.nowplaying-listeners').text(row.listeners.total);
        station_row.find('.nowplaying-listeners-unique').text(row.listeners.unique);

        var np_next_title = row.playing_next.song.title;
        if (row.playing_next.is_request) {
            np_next_title += '<span class="label label-default">Listener Request</span>';
        }
        station_row.find('.nowplaying-next-title').html(np_next_title);
        station_row.find('.nowplaying-next-artist').text(row.playing_next.song.artist);

        if (row.now_playing.duration) {
            var time_played = row.now_playing.elapsed;
            var time_total = row.now_playing.duration;

            if (time_played > time_total) {
                time_played = time_total;
            }

            var time_display = formatTime(time_played) + ' / ' + formatTime(time_total);

            station_row.find('.nowplaying-progress')
                .data('time-played', time_played)
                .data('time-total', time_total)
                .text(time_display)
                .show();
        } else {
            station_row.find('.nowplaying-progress').hide();
        }

        $('#song-history').empty();
        $.each(row.song_history, function(i, history_row) {
            var li = $('<li>').append('<b>'+history_row.song.title+'</b><br>'+history_row.song.artist);
            $('#song-history').append(li);
        });

        setTimeout('nowPlaying()', 10 * 1000);
    });
}

function iterateTimer() {
    $('.nowplaying-progress:visible').each(function () {
        var time_played = $(this).data('time-played') + 1;
        var time_total = $(this).data('time-total');

        if (time_played > time_total) {
            time_played = time_total;
        }

        var time_display = formatTime(time_played) + ' / ' + formatTime(time_total);

        $(this).data('time-played', time_played)
            .text(time_display)
    });
}

function formatTime(time) {
    var sec_num = parseInt(time, 10);

    var hours = Math.floor(sec_num / 3600);
    var minutes = Math.floor((sec_num - (hours * 3600)) / 60);
    var seconds = sec_num - (hours * 3600) - (minutes * 60);

    if (hours < 10) {
        hours = "0" + hours;
    }
    if (minutes < 10) {
        minutes = "0" + minutes;
    }
    if (seconds < 10) {
        seconds = "0" + seconds;
    }
    return (hours !== "00" ? hours + ':' : "") + minutes + ':' + seconds;
}

$(function() {
    nowPlaying();

    setInterval(iterateTimer, 1000);
});
</script>