<?php $this->layout('main', ['title' => _('Station Profile'), 'manual' => true]) ?>

<div class="block-header">
    <h2><?=$this->e($station->name) ?></h2>
</div>

<div class="row">
    <div class="col-sm-6">
        <div class="card">
            <div class="card-header ch-alt">
                <h2><?=_('Basic Profile') ?></h2>

                <?php if ($acl->isAllowed('manage station profile', $station->id)): ?>
                <a class="btn bgm-blue btn-float" title="Edit Profile" href="<?=$url->routeFromHere(array('action' => 'edit')) ?>"><i class="zmdi zmdi-edit"></i></a>
                <?php endif; ?>
            </div>
            <div class="card-body card-padding">
                <dl>
                    <dt><?=_('Station Name') ?>:</dt>
                    <dd><?=$this->e($station->name) ?></dd>

                    <dt><?=_('Station Description') ?>:</dt>
                    <dd><?=$this->e($station->description) ?></dd>

                    <dt><?=_('Player Embed Code') ?>:</dt>
                    <dd class="form-field">
                        <textarea class="full-width form-control text-preformatted" style="height: 50px;"><iframe src="<?=$url->named('public:embed', ['station' => $station->id], true) ?>" frameborder="0" allowtransparency="true" style="width: 100%; min-height: 150px; border: 0;"></iframe></textarea>
                    </dd>
                </dl>
            </div>
        </div>

        <?php if ($backend->supportsRequests()): ?>
        <div class="card">
            <div class="card-header <?php if ($station->enable_requests): ?>bgm-green<?php else: ?>bgm-red<?php endif; ?>">
                <h2><?=_('Song Requests') ?></h2>
            </div>
            <div class="card-body card-padding">
            <?php if ($station->enable_requests): ?>
                <dl>
                    <dd><?=_('Song requests are currently <b>enabled</b> for this station.') ?></dd>

                    <dt><?=_('Request Delay') ?>:</dt>
                <?php if ($station->request_delay == 0): ?>
                    <dd><?=_('Requests are queued for playback immediately after the currently playing song.') ?></dd>
                <?php else: ?>
                    <dd><?=sprintf(_('Requests are queued for playback on the station within <b>%d to %d minutes</b> of being submitted.'), $station->request_delay, $station->request_delay*2) ?></dd>
                <?php endif; ?>

                    <dt><?=_('Request Embed Code') ?></dt>
                    <dd class="form-field">
                        <textarea class="full-width form-control text-preformatted" style="height: 50px;"><iframe src="<?=$url->named('public:embedrequests', ['station' => $station->id], true) ?>" frameborder="0" allowtransparency="true" style="width: 100%; min-height: 850px; border: 0;"></iframe></textarea>
                    </dd>
                </dl>

                <p></p>

            <?php else: ?>
                <p><?=_('Song requests are currently <b>disabled</b> for this station. Edit your profile above to enable them.') ?></p>
            <?php endif; ?>
            </div>
        </div>
        <?php else: ?>
        <div class="card">
            <div class="card-header bgm-bluegray">
                <h2><?=_('Song Requests') ?></h2>
            </div>
            <div class="card-body card-padding">
                <p><?=_('This feature is not currently supported on this station.') ?></p>
            </div>
        </div>
        <?php endif; ?>

        <?php if ($frontend->supportsStreamers()): ?>
        <div class="card">
            <div class="card-header <?php if ($station->enable_streamers): ?>bgm-green<?php else: ?>bgm-red<?php endif; ?>">
                <h2><?=_('Streamers/DJs') ?></h2>
            </div>
            <div class="card-body card-padding">

                <?php if ($station->enable_streamers): ?>
                    <p><?=_('Support for live streamers / DJs is currently <b>enabled</b> for this station. Edit your profile above to enable it.') ?></p>
                    <p><?=sprintf(_('Manage streamer accounts <a href="%s">on the Streamers / DJ Accounts page</a>.'), $url->routeFromHere(['controller' => 'streamers'])) ?></p>
                <?php else: ?>
                    <p><?=_('Support for live streamers / DJs is currently <b>disabled</b> for this station.') ?></p>
                    <p><?=_('Only the AutoDJ (based on your uploaded media and playlists) will be able to play on the air.') ?></p>
                <?php endif; ?>
            </div>
        </div>
        <?php else: ?>
        <div class="card">
            <div class="card-header bgm-bluegray">
                <h2><?=_('Streamers/DJs') ?></h2>
            </div>
            <div class="card-body card-padding">
                <p><?=_('This feature is not currently supported on this station.') ?></p>
            </div>
        </div>
        <?php endif; ?>
    </div>
    <div class="col-sm-6">
        <?php if ($frontend_type == 'remote'): ?>
        <div class="card">
            <div class="card-header bgm-bluegray ch-alt">
                <h2>
                    <?=_('External Radio Server') ?>
                </h2>
            </div>
            <div class="card-body card-padding">
                <dl>
                    <dt><?=_('Stream Public URL') ?>:</dt>
                    <dd>
                        <?php foreach($stream_urls as $stream_url): ?>
                            <div><a href="<?=$stream_url ?>"><?=$stream_url ?></a></div>
                        <?php endforeach; ?>
                    </dd>
                </dl>
            </div>
        </div>
        <?php else: ?>
        <div class="card">
            <div class="card-header <?php if ($frontend_is_running): ?>bgm-green<?php else: ?>bgm-red<?php endif; ?> ch-alt">
                <h2>
                    <?php if ($frontend_type == 'icecast'): ?>
                        <?=_('IceCast (Broadcasting Service)') ?>
                    <?php elseif ($frontend_type == 'shoutcast2'): ?>
                        <?=_('ShoutCast (Broadcasting Service)') ?>
                    <?php endif; ?>
                    <br><small><?php if ($frontend_is_running): ?><?=_('Running') ?><?php else: ?><?=_('Not Running') ?><?php endif; ?></small>
                </h2>

                <?php if ($acl->isAllowed('manage station broadcasting', $station->id)): ?>
                <ul class="actions">
                    <li class="dropdown">
                        <a href="" data-toggle="dropdown" aria-expanded="false">
                            <i class="zmdi zmdi-more-vert"></i>
                        </a>
                        <ul class="dropdown-menu dropdown-menu-right">
                            <li><a href="<?=$url->routeFromHere(['action' => 'frontend', 'do' => 'restart']) ?>"><?=_('Restart Service') ?></a></li>
                            <li><a href="<?=$url->routeFromHere(['action' => 'frontend', 'do' => 'start']) ?>"><?=_('Start Service') ?></a></li>
                            <li><a href="<?=$url->routeFromHere(['action' => 'frontend', 'do' => 'stop']) ?>"><?=_('Stop Service') ?></a></li>
                        </ul>
                    </li>
                </ul>
                <?php endif; ?>
            </div>
            <div class="card-body card-padding">
                <dl>
                    <dt><?=_('Stream Public URL') ?>:</dt>
                    <dd>
                    <?php foreach($stream_urls as $stream_url): ?>
                        <div><a href="<?=$stream_url ?>"><?=$stream_url ?></a></div>
                    <?php endforeach; ?>
                    </dd>
                </dl>

                <dl>
                    <dt><?=_('Administration URL') ?>:</dt>
                    <dd><a href="<?=$frontend->getAdminUrl() ?>"><?=$frontend->getAdminUrl() ?></a></dd>

                    <dt><?=_('Administrator Password') ?>:</dt>
                    <dd><?=$frontend_config['admin_pw'] ?></dd>

                    <dt><?=_('Source Password') ?>:</dt>
                    <dd><?=$frontend_config['source_pw'] ?></dd>
                </dl>
            </div>
        </div>
        <?php endif; ?>

        <?php if ($backend_type == 'none'): ?>
        <div class="card">
            <div class="card-header bgm-bluegray ch-alt">
                <h2><?=_('AutoDJ Disabled') ?></h2>
            </div>
            <div class="card-body card-padding">
                <p><?=_('AutoDJ has been disabled for this station. No music will automatically be played when a source is not live.') ?></p>
            </div>
        </div>
        <?php else: ?>
        <div class="card">
            <div class="card-header <?php if ($backend_is_running): ?>bgm-green<?php else: ?>bgm-red<?php endif; ?> ch-alt">
                <h2>
                <?php if ($backend_type == 'liquidsoap'): ?>
                    <?=_('LiquidSoap (AutoDJ Service)') ?><br>
                <?php endif; ?>
                    <small><?php if ($backend_is_running): ?><?=_('Running') ?><?php else: ?><?=_('Not Running') ?><?php endif; ?></small>
                </h2>

                <?php if ($acl->isAllowed('manage station broadcasting', $station->id)): ?>
                <ul class="actions">
                    <li class="dropdown">
                        <a href="" data-toggle="dropdown" aria-expanded="false">
                            <i class="zmdi zmdi-more-vert"></i>
                        </a>
                        <ul class="dropdown-menu dropdown-menu-right">
                            <li><a href="<?=$url->routeFromHere(['action' => 'backend', 'do' => 'skip']) ?>"><?=_('Skip Song') ?></a></li>
                            <li class="divider">&nbsp;</li>
                            <li><a href="<?=$url->routeFromHere(['action' => 'backend', 'do' => 'restart']) ?>"><?=_('Restart Service') ?></a></li>
                            <li><a href="<?=$url->routeFromHere(['action' => 'backend', 'do' => 'start']) ?>"><?=_('Start Service') ?></a></li>
                            <li><a href="<?=$url->routeFromHere(['action' => 'backend', 'do' => 'stop']) ?>"><?=_('Stop Service') ?></a></li>
                        </ul>
                    </li>
                </ul>
                <?php endif; ?>
            </div>
            <div class="card-body card-padding">
                <p><?=sprintf(_('LiquidSoap is currently shuffling from <b>%d uploaded songs</b> in <b>%d playlists</b>.'), $num_songs, $num_playlists) ?></p>
            </div>
        </div>
        <?php endif; ?>
    </div>
</div>