<?php
$this->headTitle('Show: '.$this->podcast->name);
?>

<div class="clearfix">
    <img class="pull-left" src="<?=\DF\Url::content($this->podcast->image_url) ?>" style="width: 150px; margin-right: 10px;">

    <blockquote>
        <p><?=nl2br($this->podcast->description) ?></p>
    </blockquote>

    <div class="buttons">
        <?=$this->button(array(
            'type'      => 'link',
            'icon'      => 'icon-rss',
            'href'      => $this->routeFromHere(array('action' => 'feed', 'type' => 'single')),
            'text'      => 'Episode RSS Feed',
            'target'    => '_blank',
        )) ?>
    </div>
</div>

<dl>
    <dt>URL:</dt>
    <dd><a href="<?=$this->podcast->web_url ?>"><?=$this->podcast->web_url ?></a></dd>

<? if (count($this->podcast->stations) > 0): ?>
    <dt>Also airs on:</dt>
    <dd>
    <? foreach($this->podcast->stations as $station): ?>
        <div><?=$station->name ?></div>
    <? endforeach; ?>
    </dd>
<? endif; ?>
</dl>

<br>
<h2>Recent Episodes</h2>

<? foreach($this->episodes as $ep): ?>
    <h4>
        <small><?=date('l, F j, Y g:ia', $ep['timestamp']) ?></small><br>
        <a href="<?=$ep['web_url'] ?>" target="_blank"><?=$ep['title'] ?></a>
    </h4>
<? if ($ep['description']): ?>
    <p><?=\DF\Utilities::truncateText($ep['description'], 500) ?></p>
<? endif; ?>
<? endforeach; ?>