<?php
/** @var \Slim\Exception\HttpException $exception */

$this->layout('minimal', [
    'title' => $exception->getTitle(),
    'page_class' => 'error-content',
]);
?>

<div class="public-page">
    <div class="card p-3">
        <div class="card-body">
            <h2 class="display-1"><?= $this->e($exception->getCode()) ?></h2>
            <h4><?= $this->e($exception->getMessage()) ?></h4>
            <p class="text-muted card-text">
                <?= $this->e($exception->getDescription()) ?>
            </p>

            <div class="block-buttons">
                <a role="button" title="<?= __('Dashboard') ?>" class="btn btn-login btn-primary" href="/">
                    Home
                </a>
            </div>
        </div>
    </div>
</div>
