<?php
/** @var \Slim\Exception\HttpException $exception */

$this->layout('minimal', [
    'title' => $exception->getTitle(),
    'page_class' => 'error-content',
]);
?>

<div class="public-page">
    <div class="card">
        <div class="card-body">
            <h2 class="display-1"><?= $this->e($exception->getCode()) ?></h2>
            <h4><?= $this->e($exception->getMessage()) ?></h4>
            <p class="text-muted card-text mb-0">
                <?= $this->e($exception->getDescription()) ?>
            </p>

            <a role="button" title="<?= __('Dashboard') ?>" class="btn btn-login btn-primary btn-float"
               href="/">
                <i class="material-icons" aria-hidden="true">home</i>
            </a>
        </div>
    </div>
</div>
