<?php
$this->layout('main', ['title' => $title, 'manual' => true]);
?>

<div class="card" id="log-view">
    <?php foreach ($log_records as $id => $row): ?>
        <div class="card-header" id="log-row-<?=$id?>">
            <?php if ($row['level'] === \Monolog\Logger::DEBUG): ?>
                <h5 class="text-info">Debug</h5>
            <?php elseif ($row['level'] === \Monolog\Logger::INFO): ?>
                <h5 class="text-info">Info</h5>
            <?php elseif ($row['level'] === \Monolog\Logger::NOTICE): ?>
                <h5 class="text-info">Notice</h5>
            <?php elseif ($row['level'] === \Monolog\Logger::WARNING): ?>
                <h5 class="text-warning">Warning</h5>
            <?php elseif ($row['level'] === \Monolog\Logger::ERROR): ?>
                <h5 class="text-danger">Error</h5>
            <?php elseif ($row['level'] === \Monolog\Logger::CRITICAL): ?>
                <h5 class="text-danger">Critical</h5>
            <?php elseif ($row['level'] === \Monolog\Logger::ALERT): ?>
                <h5 class="text-danger">Alert</h5>
            <?php elseif ($row['level'] === \Monolog\Logger::EMERGENCY): ?>
                <h5 class="text-danger">Emergency</h5>
            <?php endif; ?>

            <h3><?=$this->e($row['message'])?></h3>

            <?php if (!empty($row['context'])): ?>
                <button class="btn btn-sm btn-outline-inverse" type="button" data-toggle="collapse" data-target="#detail-row-<?=$id?>" aria-controls="detail-row-<?=$id?>">
                    <?=__('Details')?>
                </button>
            <?php endif; ?>
        </div>

        <?php if (!empty($row['context'])): ?>
            <div id="detail-row-<?=$id?>" class="collapse" aria-labelledby="log-row-<?=$id?>" data-parent="#log-view">
                <div class="card-body">
                    <?php foreach ($row['context'] as $context_header => $context_value): ?>
                        <h4 class="card-subtitle"><?=$context_header?></h4>
                        <?=$this->dump($context_value)?>
                    <?php endforeach; ?>
                    <?php foreach ($row['extra'] as $context_header => $context_value): ?>
                        <h4 class="card-subtitle"><?=$context_header?></h4>
                        <?=$this->dump($context_value)?>
                    <?php endforeach; ?>
                </div>
            </div>
        <?php endif; ?>
    <?php endforeach; ?>
</div>