<?php

declare(strict_types=1);

namespace App\Nginx;

use App\Entity\Station;
use App\Environment;
use App\Event\Nginx\WriteNginxConfiguration;
use Psr\EventDispatcher\EventDispatcherInterface;
use Supervisor\SupervisorInterface;
use Symfony\Component\Filesystem\Filesystem;

final class Nginx
{
    private const string PROCESS_NAME = 'nginx';

    public function __construct(
        private readonly SupervisorInterface $supervisor,
        private readonly EventDispatcherInterface $eventDispatcher
    ) {
    }

    public function writeConfiguration(
        Station $station,
        bool $reloadIfChanged = true,
    ): void {
        $configPath = $this->getConfigPath($station);

        $currentConfig = (is_file($configPath))
            ? file_get_contents($configPath)
            : null;

        $newConfig = $this->getConfiguration($station, true);

        $fs = new Filesystem();
        $changed = false;

        if ($currentConfig !== $newConfig) {
            $fs->dumpFile($configPath, $newConfig);
            $changed = true;
        }

        if ($this->writeCustomDomainConfiguration($station)) {
            $changed = true;
        }

        if ($changed && $reloadIfChanged) {
            $this->testConfiguration();
            $this->reload();
        }
    }

    /**
     * Write (or remove) a dedicated nginx server block for a station's custom public-page domain.
     * Files go to /etc/nginx/sites-enabled/ which is included at the HTTP-block level,
     * allowing full server{} entries. Returns true if the file changed.
     */
    public function writeCustomDomainConfiguration(Station $station): bool
    {
        $customDomainConfigPath = $this->getCustomDomainConfigPath($station);
        $fs = new Filesystem();

        if (empty($station->custom_domain)) {
            if (is_file($customDomainConfigPath)) {
                $fs->remove($customDomainConfigPath);
                return true;
            }
            return false;
        }

        $domain = $station->custom_domain;
        $stationSlug = $station->short_name;

        if (!preg_match('/^(?=.{1,253}$)([a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?\.)+[a-z]{2,63}$/i', $domain)) {
            throw new \InvalidArgumentException('Invalid custom domain: ' . $domain);
        }
        if (!preg_match('/^[a-z0-9_-]+$/', $stationSlug)) {
            throw new \InvalidArgumentException('Invalid station slug: ' . $stationSlug);
        }
        $stationName = str_replace(["\n", "\r", '#'], ' ', $station->name);

        $acmeDir = Environment::getInstance()->getParentDirectory() . '/storage/acme';

        // Port the streaming server (Icecast, RSAS, etc.) listens on.
        $streamingPort = $station->frontend_config->port ?? 8000;

        // proxy_params already includes proxy_buffering off and long timeouts —
        // do not set them again or nginx will reject the config as duplicate.
        $newConfig = <<<NGINX
        # Custom public-page domain for station: {$stationName}
        # Generated by AzuraCast — do not edit manually.
        server {
            listen 80;
            listen 443 ssl;
            http2 on;

            ssl_certificate        {$acmeDir}/ssl.crt;
            ssl_certificate_key    {$acmeDir}/ssl.key;
            ssl_protocols TLSv1.3 TLSv1.2;
            ssl_prefer_server_ciphers on;
            ssl_ciphers EECDH+AESGCM:EECDH+AES256;

            server_name {$domain};

            # Static assets, docs, system paths — ^~ passes straight through.
            location ^~ /static {
                include /etc/nginx/proxy_params;
                proxy_pass http://127.0.0.1:6010;
            }
            location ^~ /docs {
                include /etc/nginx/proxy_params;
                proxy_pass http://127.0.0.1:6010;
            }
            location = /favicon.ico {
                include /etc/nginx/proxy_params;
                proxy_pass http://127.0.0.1:6010;
            }
            location = /public/sw.js {
                include /etc/nginx/proxy_params;
                proxy_pass http://127.0.0.1:6010;
            }

            # Centrifugo live Now Playing stream — must precede /api so the longer
            # ^~ /api/live/ prefix wins in nginx location matching.
            location ^~ /api/live/ {
                rewrite ^/api/live/nowplaying/(.*)\$ /connection/uni_\$1 break;
                proxy_http_version 1.1;
                proxy_set_header Upgrade \$http_upgrade;
                proxy_set_header Connection "";
                proxy_buffering off;
                proxy_pass http://127.0.0.1:6020;
            }
            location ^~ /api {
                include /etc/nginx/proxy_params;
                proxy_pass http://127.0.0.1:6010;
            }

            # Stream mounts: /listen/[mount] → streaming server directly.
            # ^~ strips the /listen/ prefix; the streaming server handles /[mount].
            location ^~ /listen/ {
                include /etc/nginx/proxy_params;
                proxy_intercept_errors on;
                proxy_pass http://127.0.0.1:{$streamingPort}/;
            }

            # Once rewritten, station paths pass through without further rewriting.
            # ^~ prevents regex locations from interfering.
            location ^~ /public/{$stationSlug} {
                include /etc/nginx/proxy_params;
                proxy_pass http://127.0.0.1:6010;
            }

            # Root → station public page (transparent proxy, no URL change in browser).
            location = / {
                rewrite ^ /public/{$stationSlug} last;
            }

            # Sub-paths (/embed, /history, etc.) → prepend station path, re-evaluate.
            # 'last' flag ensures re-evaluation hits the ^~ /public/{$stationSlug} block above.
            location / {
                rewrite ^/(.+)\$ /public/{$stationSlug}/\$1 last;
            }
        }
        NGINX;

        $currentConfig = is_file($customDomainConfigPath)
            ? file_get_contents($customDomainConfigPath)
            : null;

        if ($currentConfig === $newConfig) {
            return false;
        }

        $fs->dumpFile($customDomainConfigPath, $newConfig);
        return true;
    }

    public function getConfiguration(
        Station $station,
        bool $writeToDisk = false
    ): string {
        $event = new WriteNginxConfiguration(
            $station,
            $writeToDisk
        );

        $this->eventDispatcher->dispatch($event);

        return $event->buildConfiguration();
    }

    public function testConfiguration(): void
    {
        exec('nginx -t 2>&1', $output, $exitCode);
        if ($exitCode !== 0) {
            throw new \RuntimeException('nginx config test failed: ' . implode("\n", $output));
        }
    }

    public function reload(): void
    {
        $this->supervisor->signalProcess(self::PROCESS_NAME, 'HUP');
    }

    public function reopenLogs(): void
    {
        $this->supervisor->signalProcess(self::PROCESS_NAME, 'USR1');
    }

    private function getConfigPath(Station $station): string
    {
        return $station->getRadioConfigDir() . '/nginx.conf';
    }

    private function getCustomDomainConfigPath(Station $station): string
    {
        return $station->getRadioConfigDir() . '/custom_domain.conf';
    }
}
