<?php
$title = '404: Page Not Found';
$manual = true;
?>

<div class="row-fluid">
    <div class="span8">
        <h2>You Broke It!</h2>
        <center><img src="<?=\DF\Url::content('images/404.png') ?>" alt="Broken Link" /></center>
    </div>
    <div class="span4">
        <h2>Where Am I?</h2>
        <p>You're on the web site of <b><?=$this->config->application->name ?></b>, a network of fandom radio stations, video streams, podcasts, conventions and more.</p>

        <p>Visit our homepage and explore our network by clicking the link below!</p>

        <div class="buttons">
            <?=$this->viewHelper->button(array(
                'href'      => \DF\Url::route(),
                'text'      => 'Bravely Blue Homepage',
                'class'     => 'btn-large btn-primary',
                'icon'      => 'icon-home',
            )) ?>
        </div>
    </div>
</div>