---
- name: restart cron
  service:
    name: cron
    enabled: true
    state: restarted

- name: send user notification
  debug:
    msg: >-
      A user account named 'azuracast' has been created. The password value is
      in the file: {{ azuracast_user_password_file }}

- name: send mysql notification
  debug:
    msg: >-
      The MySQL 'azuracast'@'localhost' account has been created. The password value is
      in the file: {{ azuracast_mysql_password_file }}
