<?
$title = 'Station Center';
$manual = true;

$this->assets->collection('custom_js')
    ->addJs('//code.highcharts.com/highcharts.js', false)
    ->addJs('//code.highcharts.com/highcharts-more.js', false)
    ->addJs('//code.highcharts.com/modules/exporting.js', false);
?>

<script type="text/javascript">
$(function () {
    Highcharts.setOptions({
        global: {
            timezoneOffset: <?=\App\Timezone::getOffsetMinutes() ?>,
            useUTC: false
        }
    });
});
</script>

<div class="block-header">
    <h2>Station Center</h2>
</div>

<div class="row">
    <div class="col-sm-12">
        <div class="card">
            <div class="card-header ch-alt">
                <h2>Listeners By Day</h2>
            </div>
            <div class="card-body card-padding-sm">
                <?=$viewHelper->renderHere('index-dailystats') ?>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-sm-6">
        <div class="card">
            <div class="card-header ch-alt">
                <h2>Listeners by Hour of Day</h2>
            </div>
            <div class="card-body card-padding-sm">
                <?=$viewHelper->renderHere('index-hourlystats') ?>
            </div>
        </div>
    </div>
    <div class="col-sm-6">
        <div class="card">
            <div class="card-header ch-alt">
                <h2>Listeners by Day of Week</h2>
            </div>
            <div class="card-body card-padding-sm">
                <?=$viewHelper->renderHere('index-dayofweek') ?>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-sm-6">
        <div class="card">
            <div class="card-header ch-alt">
                <h2><i class="zmdi zmdi-thumb-up"></i> Best Performing Songs<br><small>in the last 48 hours</small></h2>
            </div>
            <div class="table-responsive">
                <table class="table table-striped table-condensed table-nopadding">
                    <colgroup>
                        <col width="20%">
                        <col width="80%">
                    </colgroup>
                    <thead>
                        <tr>
                            <th>Change</th>
                            <th>Song</th>
                        </tr>
                    </thead>
                    <tbody>
                    <? foreach($best_performing_songs as $song_row): ?>
                        <tr>
                            <td class="text-center text-success">
                                <i class="zmdi zmdi-thumb-up"></i> <?=abs($song_row['stat_delta']) ?><br>
                                <small><?=$song_row['stat_start'] ?> to <?=$song_row['stat_end'] ?>
                            </td>
                            <td>
                                <? if ($song_row['song']['title']): ?>
                                    <b><?=$song_row['song']['title'] ?></b><br>
                                    <?=$song_row['song']['artist'] ?>
                                <? else: ?>
                                    <?=$song_row['song']['text'] ?>
                                <? endif; ?>
                                <!-- <a href="<?=$url->routeFromHere(array('action' => 'timeline', '#target' => 'song_'.$song_row['timestamp'])) ?>"> </a> -->
                            </td>
                        </tr>
                    <? endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <div class="col-sm-6">
        <div class="card">
            <div class="card-header ch-alt">
                <h2><i class="zmdi zmdi-thumb-down"></i> Worst Performing Songs<br><small>in the last 48 hours</small></h2>
            </div>
            <div class="table-responsive">
                <table class="table table-striped table-condensed table-nopadding">
                    <colgroup>
                        <col width="20%">
                        <col width="80%">
                    </colgroup>
                    <thead>
                        <tr>
                            <th>Change</th>
                            <th>Song</th>
                        </tr>
                    </thead>
                    <tbody>
                    <? foreach($worst_performing_songs as $song_row): ?>
                        <tr>
                            <td class="text-center text-danger">
                                <i class="zmdi zmdi-thumb-down"></i> <?=abs($song_row['stat_delta']) ?><br>
                                <small><?=$song_row['stat_start'] ?> to <?=$song_row['stat_end'] ?>
                            </td>
                            <td>
                                <? if ($song_row['song']['title']): ?>
                                    <b><?=$song_row['song']['title'] ?></b><br>
                                    <?=$song_row['song']['artist'] ?>
                                <? else: ?>
                                    <?=$song_row['song']['text'] ?>
                                <? endif; ?>
                                <!--  <a href="<?=$url->routeFromHere(array('action' => 'timeline', '#target' => 'song_'.$song_row['timestamp'])) ?>"> </a> -->
                            </td>
                        </tr>
                    <? endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-sm-12">
        <div class="card">
            <div class="card-header ch-alt">
                <h2>Most Played Songs<br><small>in the last month</small></h2>
            </div>
            <div class="table-responsive">
                <table class="table table-striped table-condensed table-nopadding">
                    <colgroup>
                        <col width="10%">
                        <col width="90%">
                    </colgroup>
                    <thead>
                        <tr>
                            <th>Plays</th>
                            <th>Song</th>
                        </tr>
                    </thead>
                    <tbody>
                    <? foreach($song_totals['played'] as $song_row): ?>
                        <tr>
                            <td class="text-center"><?=$song_row['records'] ?></td>
                            <td>
                            <? if ($song_row['song']['title']): ?>
                                <b><?=$song_row['song']['title'] ?></b><br>
                                <?=$song_row['song']['artist'] ?>
                            <? else: ?>
                                <?=$song_row['song']['text'] ?>
                            <? endif; ?>
                            </td>
                        </tr>
                    <? endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>