<?
$title = 'Recent Playback Timeline';
$manual = true;
?>

<div class="block-header">
    <h2><?=$station->name ?></h2>
</div>

<div class="card">
    <div class="card-header ch-alt">
        <h2>Station Playback Timeline</h2>

        <ul class="actions">
            <li>
                <a href="<?=$url->routeFromHere(['format' => 'csv']) ?>" title="Download Excel CSV">
                    <i class="zmdi zmdi-download"></i>
                </a>
            </li>
        </ul>
    </div>
    <div id="data-table-basic-header" class="bootgrid-header container-fluid">
        <?=$viewHelper->paginate($pager) ?>
    </div>
    <div class="table-responsive">
        <table class="table table-striped">
            <colgroup>
                <col width="15%">
                <col width="10%">
                <col width="10%">
                <col width="45%">
                <col width="20%">
            </colgroup>
            <thead>
                <tr>
                    <th>Date/Time</th>
                    <th>Listeners</th>
                    <th>Change</th>
                    <th>Song Title</th>
                    <th>Playlist(s)</th>
                </tr>
            </thead>
            <tbody>
            <? foreach($pager as $song_row): ?>
                <tr class="input" id="song_<?=$song_row['timestamp'] ?>">
                    <td class="text-center"><?=date('D g:ia', $song_row['timestamp_start']) ?></td>
                    <td class="text-center"><big><?=$song_row['stat_start'] ?></big></td>
                    <td class="text-center">
                        <big>
                    <? if ($song_row['stat_delta'] > 0): ?>
                        <span class="text-success"><i class="icon-caret-up"></i> <?=$song_row['stat_delta'] ?></span>
                    <? elseif ($song_row['stat_delta'] < 0): ?>
                        <span class="text-error"><i class="icon-caret-down"></i> <?=abs($song_row['stat_delta']) ?></span>
                    <? else: ?>
                        0
                    <? endif; ?>
                        </big>
                    </td>
                    <td>
                        <? if ($song_row['song']['title']): ?>
                            <b><?=$song_row['song']['title'] ?></b><br>
                            <?=$song_row['song']['artist'] ?>
                        <? else: ?>
                            <?=$song_row['song']['text'] ?>
                        <? endif; ?>
                        <!-- <a href="#" class="btn-show-song-info" data-id="<?=$song_row['song']['id'] ?>" title="Click for Song Information"></a> -->
                    </td>
                    <td><?=implode('<br>', $song_row['playlists']) ?></td>
                </tr>
            <? endforeach; ?>
            </tbody>
        </table>
    </div>
</div>