<?
$title = 'Recent Playback Timeline';
?>

<div class="buttons">
    <?=$this->viewHelper->button(array(
        'type'      => 'link',
        'icon'      => 'icon-download',
        'text'      => 'Download Excel/CSV',
        'href'      => $this->viewHelper->routeFromHere(array('format' => 'csv')),
    )) ?>
</div>

<?=$this->viewHelper->paginate($pager) ?>

<table class="datatable table-striped table-condensed table-nopadding">
    <colgroup>
        <col width="15%">
        <col width="7%">
        <col width="7%">
        <col width="7%">
        <col width="39%">
        <col width="25%">
    </colgroup>
    <thead>
        <tr>
            <th>Date/Time</th>
            <th>Listeners</th>
            <th>Change</th>
            <th><i class="icon-thumbs-up"></i> / <i class="icon-thumbs-down"></i></th>
            <th>Song Title</th>
            <th>Event</th>
        </tr>
    </thead>
    <tbody>
    <? foreach($pager as $song_row): ?>
        <tr class="input" id="song_<?=$song_row['timestamp'] ?>">
            <td class="center"><?=date('D g:ia', $song_row['timestamp']) ?></td>
            <td class="center"><big><?=$song_row['stat_start'] ?></big></td>
            <td class="center">
                <big>
            <? if ($song_row['stat_delta'] > 0): ?>
                <span class="text-success"><i class="icon-caret-up"></i> <?=$song_row['stat_delta'] ?></span>
            <? elseif ($song_row['stat_delta'] < 0): ?>
                <span class="text-error"><i class="icon-caret-down"></i> <?=abs($song_row['stat_delta']) ?></span>
            <? else: ?>
                0
            <? endif; ?>
                </big>
            </td>
            <td class="center">
            <? if ($song_row['score_dislikes'] > 0): ?>
                <span class="text-error"><i class="icon-thumbs-down"></i> <?=abs($song_row['score_dislikes']) ?></span>
            <? endif; ?>
            <? if ($song_row['score_likes'] > 0): ?>
                <span class="text-success"><i class="icon-thumbs-up"></i> <?=abs($song_row['score_likes']) ?></span>
            <? endif; ?>
            </td>
            <td>
                <a href="#" class="btn-show-song-info" data-id="<?=$song_row['song']['id'] ?>" title="Click for Song Information">
                <? if ($song_row['song']['title']): ?>
                    <b><?=$song_row['song']['title'] ?></b><br>
                    <?=$song_row['song']['artist'] ?>
                <? else: ?>
                    <?=$song_row['song']['text'] ?>
                <? endif; ?>
                </a>
            </td>
            <td>
            <? if ($song_row['event']): ?>
                <i class="icon-star"></i> <?=$song_row['event']['title'] ?>
            <? else: ?>
                &nbsp;
            <? endif; ?>
            </td>
        </tr>
    <? endforeach; ?>
    </tbody>
</table>

<?=$this->viewHelper->paginate($pager) ?>