<?php
/**
 * @var \App\Assets $assets
 * @var \App\Customization $customization
 * @var \App\Entity\Station $station
 * @var \App\Http\Router $router
 * @var string $base_uri
 */

$libUrls = [];
$lib = $assets->getLibrary('Webcaster');

$scripts = array_slice($lib['files']['js'], 0, -1);

foreach ($scripts as $script) {
    $libUrls[] = $router->getBaseUrl() . $assets->getUrl($script['src']);
}

$props = [
    'stationName' => $station->getName(),
    'libUrls' => $libUrls,
    'baseUri' => $base_uri,
];
?>

$(function () {
    const web_dj = new Vue({
        el: '#web_dj',
        render: function (createElement) {
            return createElement(Webcaster.default, {
                props: <?=json_encode($props) ?>
            });
        }
    });
});
