<?php
/** @var App\Entity\Station $station */

$this->layout(
    'minimal',
    [
        'page_class' => 'embed station-' . $station->getShortName(),
        'title' => $this->e($station->getName()),
        'hide_footer' => true,
    ]
);

$props = [
    'customFields' => $customFields,
    'requestListUri' => (string)$router->named('api:requests:list', ['station_id' => $station->getId()]),
];

/** @var \App\Assets $assets */
$assets->addVueRender('Vue_PublicRequests', '#song-requests', $props);
?>

<div id="song-requests"></div>
