$(function() {
    var grid = $("#requests-table").bootgrid({
        ajax: true,
        ajaxSettings: {
            method: "GET",
            cache: false
        },
        rowSelect: false,
        caseSensitive: false,
        url: "<?=$router->named('api:requests:list', ['station' => $station->getId()]) ?>",
        formatters: {
            "commands": function(column, row) {
                return '<a class="btn btn-request btn-sm btn-primary" data-url="'+row.request_url+'" tabindex="0"><?=__('Request') ?></a>';
            }
        }
    }).on("loaded.rs.jquery.bootgrid", function()
    {
        /* Executes after data is loaded and rendered */
        grid.find(".btn-request").on("click", function(e)
        {
            e.preventDefault();

            $.ajax({
                dataType: "json",
                url: $(this).data('url')
            }).done(function(data) {
                notify(data, 'success');
            }).fail(function(jqXhr) {
                notify('Error: ' + jqXhr.responseJSON, 'danger');
            });

            return false;
        });
    });
});
