<?php
/** @var App\Entity\Station $station */

$this->layout('minimal', [
    'page_class' => 'embed station-'.$station->getShortName(),
    'title' => $this->e($station->getName()),
    'hide_footer' => true
]);

/** @var \Azura\Assets $assets */
$assets
    ->load('vue')
    ->load('radio')
    ->addInlineJs($this->fetch('frontend/public/embed.js', ['station' => $station]));
?>

<div class="stations nowplaying">
    <?=$this->fetch('frontend/public/player_component', [
        'stream_url' => $stream_url,
        'autoplay' => $autoplay
    ]) ?>
</div>
