<?php
/** @var App\Entity\Station $station */

$this->layout('minimal', [
    'page_class' => 'embed station-' . $station->getShortName(),
    'title' => $this->e($station->getName()),
    'hide_footer' => true,
]);

/** @var \App\Assets $assets */
$assets
    ->load('SongRequest')
    ->addInlineJs($this->fetch('frontend/public/embedrequests.js', ['station' => $station]));
?>

<div id="song-requests"></div>
