$(function () {
  // Song history Vue component
  var songHistory = new Vue({
    el: '#station-history',
    data: {
      history: [
        {
          song: {
            title: '<?=__('Song Title') ?>',
            artist: '<?=__('Song Artist') ?>',
            album: '<?=__('Album') ?>',
            played_at: '<?=__('Date Played') ?>'
          }
        }
      ]
    },
    mounted: function () {
      radio_player.$eventHub.$on('np_updated', function (np_new) {
        songHistory.history = np_new.song_history;
      });
    },
    computed: {
      langNoRecords () {
        return this.$gettext('No records to display.');
      }
    },
    methods: {
      unixTimestampToDate(timestamp) {
        if (!timestamp) {
          return '';
        }
        const date = moment.unix(timestamp);
        if (moment().diff(date, 'days', true) > 0.5) {
          return date.calendar();
        }
        return date.fromNow();
      },
      albumAndArtist(song) {
        return [song.album, song.artist].filter(str => !!str).join(', ');
      }
    }
  });

  $('[data-fancybox]').fancybox({
    buttons: ['close']
  });

  // Song request modal dialog component
  var request_dialog = $('#modal-request');

  request_dialog.on('show.bs.modal', function (event) {

    if (!request_dialog.data('request_loaded')) {
      var grid = $("#requests-table").bootgrid({
        ajax: true,
        ajaxSettings: {
          method: "GET",
          cache: false
        },
        rowSelect: false,
        caseSensitive: false,
        url: "<?=$router->named('api:requests:list', ['station_id' => $station->getId()]) ?>",
        formatters: {
          "commands": function (column, row) {
            return '<a class="btn btn-request btn-sm btn-primary" data-url="' + row.request_url + '" tabindex="0"><?=__('Request') ?></a>';
          }
        }
      }).on("loaded.rs.jquery.bootgrid", function () {
        /* Executes after data is loaded and rendered */
        grid.find(".btn-request").on("click", function (e) {
          e.preventDefault();
          request_dialog.modal('hide');

          $.ajax({
            dataType: "json",
            url: $(this).data('url')
          }).done(function (data) {
            notify(data.message, 'success');
          }).fail(function (jqXhr) {
            var response = jqXhr.responseJSON;
            notify('Error: ' + response.message, 'danger');
          });

          return false;
        });
      });

      request_dialog.data('request_loaded', true);
    }

  });
});
