<?php
/**
 * @var \App\Customization $customization
 * @var \App\Entity\Station $station
 * @var array $nowplaying
 * @var \App\Http\Router $router
 */

$props = [
    'stationName' => $station->getName(),
    'enableRequests' => $station->getEnableRequests(),
    'downloadPlaylistUri' => (string)$router->named('public:playlist',
        ['station_id' => $station->getShortName(), 'format' => 'pls']),
    'requestListUri' => (string)$router->named('api:requests:list', ['station_id' => $station->getId()]),
    'initialNowPlaying' => $nowplaying,
    'showAlbumArt' => !$customization->hideAlbumArt(),
];

if ($customization->useWebSocketsForNowPlaying()) {
    $props['useNchan'] = true;
    $props['nowPlayingUri'] = '/api/live/nowplaying/' . urlencode($station->getShortName());
} else {
    $props['useNchan'] = false;
    $props['nowPlayingUri'] = (string)$router->named('api:nowplaying:index', ['station_id' => $station->getId()]);
}
?>

$(function () {
    let publicRadioPlayer = new Vue({
        el: '#public-radio-player',
        render: function (createElement) {
            return createElement(PublicRadioPlayer.default, {
                props: <?=json_encode($props) ?>
            });
        }
    });

    $('[data-fancybox]').fancybox({
        buttons: ['close']
    });
});
