<?php
$this->layout('minimal', [
    'page_class' => 'ondemand station-' . $station->getShortName(),
    'title' => 'On-Demand Media - ' . $this->e($station->getName()),
    'hide_footer' => true,
]);

/** @var \App\Assets $assets */
$assets
    ->load('vue')
    ->load('fancybox')
    ->load('station_on_demand')
    ->addInlineJs($this->fetch('frontend/public/ondemand.js', [
        'station' => $station,
        'custom_fields' => $custom_fields,
    ]));
?>
<section id="content" role="main" style="height: 100vh;">
    <div class="container pt-5 pb-5">
        <div id="station_on_demand"></div>
    </div>
</section>
