<?php
/**
 * @var \App\Customization $customization
 * @var \App\Entity\Station $station
 * @var array $nowplaying
 * @var \App\Http\Router $router
 */

$props = [
    'initial_now_playing' => $nowplaying,
    'show_album_art' => !$customization->hideAlbumArt(),
];

if ($customization->useWebSocketsForNowPlaying()) {
    $props['use_nchan'] = true;
    $props['now_playing_uri'] = '/api/live/nowplaying/' . urlencode($station->getShortName());
} else {
    $props['use_nchan'] = false;
    $props['now_playing_uri'] = (string)$router->named('api:nowplaying:index', ['station_id' => $station->getId()]);
}
?>

var radio_player;

$(function () {
  radio_player = RadioPlayer.default({
    el: '#station-nowplaying',
    lang: <?=$customization->getVueLocale() ?>,
    props: <?=json_encode($props) ?>
  });
});
