<?php
/**
 * @var \App\Customization $customization
 * @var \App\Entity\Station $station
 * @var \App\Http\Router $router
 */

$locale_short = substr($customization->getLocale(), 0, 2);

$locale_info = [
    'locale' => $locale_short,
    'messages' => [
        $locale_short => [
            'play_btn'          => __('Play'),
            'pause_btn'         => __('Pause'),
            'mute_btn'          => __('Mute'),
            'volume_slider'     => __('Volume'),
            'full_volume_btn'   => __('Full Volume'),
            'album_art_alt'     => __('Album Art'),
        ],
    ],
];

$props = [
    'show_album_art' => !$customization->hideAlbumArt(),
];

if (\App\Service\NChan::isSupported()) {
    $props['use_nchan'] = true;
    $props['now_playing_uri'] = '/api/live/nowplaying/'.urlencode($station->getShortName());
} else {
    $props['use_nchan'] = false;
    $props['now_playing_uri'] = (string)$router->named('api:nowplaying:index', ['station' => $station->getId()]);
}
?>

var i18n, radio_player;

$(function() {
    i18n = new VueI18n(<?=json_encode($locale_info) ?>)
    radio_player = new Vue({
        i18n,
        el: '#station-nowplaying',
        render: function(createElement) {
            return createElement(RadioPlayer.default, {
                props: <?=json_encode($props) ?>
            });
        }
    });
});
