<?php
/**
 * @var App\View\GlobalSections $sections
 * @var App\Entity\Station $station
 * @var string $wss_url
 */

$this->layout(
    'minimal',
    [
        'page_class' => 'dj station-' . $station->getShortName(),
        'hide_footer' => true,
        'title' => __('Web DJ') . ' - ' . $station->getName(),
        'manual' => true,
    ]
);

echo $this->fetch(
    'partials/vue_body',
    [
        'component' => 'Vue_PublicWebDJ',
        'id' => 'web_dj',
        'props' => [
            'stationName' => $station->getName(),
            'baseUri' => $wss_url,
        ],
    ]
);
