<?php $this->layout('main', ['title' => 'Station Profile', 'manual' => true]) ?>

<div class="block-header">
    <h2><?=$this->e($station->name) ?></h2>
</div>

<div class="row">
    <div class="col-sm-6">
        <div class="card">
            <div class="card-header ch-alt">
                <h2><?=_('Basic Profile') ?></h2>
                <a class="btn bgm-blue btn-float" title="Edit Profile" href="<?=$url->routeFromHere(array('action' => 'edit')) ?>"><i class="zmdi zmdi-edit"></i></a>
            </div>
            <div class="card-body card-padding">
                <dl>
                    <dt><?=_('Station Name') ?>:</dt>
                    <dd><?=$this->e($station->name) ?></dd>

                    <dt><?=_('Station Description') ?>:</dt>
                    <dd><?=$this->e($station->description) ?></dd>
                </dl>
            </div>
        </div>

        <div class="card">
            <div class="card-header <?php if ($station->enable_requests): ?>bgm-green<?php else: ?>bgm-red<?php endif; ?>">
                <h2><?=_('Song Requests') ?></h2>
            </div>
            <div class="card-body card-padding">
            <?php if ($station->enable_requests): ?>
                <p><?=_('Song requests are currently <b>enabled</b> for this station.') ?></p>
                <?php if ($station->request_delay == 0): ?>
                    <p><?=_('Requests are queued for playback immediately after the currently playing song.') ?></p>
                <?php else: ?>
                    <p><?=sprintf(_('Requests are queued for playback on the station within <b>%d to %d minutes</b> of being submitted.'), $station->request_delay, $station->request_delay*2) ?></p>
                <?php endif; ?>
            <?php else: ?>
                <p><?=_('Song requests are currently <b>disabled</b> for this station. Edit your profile above to enable them.') ?></p>
            <?php endif; ?>
            </div>
        </div>

        <div class="card">
            <div class="card-header <?php if ($station->enable_streamers): ?>bgm-green<?php else: ?>bgm-red<?php endif; ?>">
                <h2><?=_('Streamers/DJs') ?></h2>
            </div>
            <div class="card-body card-padding">
                <?php if ($station->enable_streamers): ?>
                    <p><?=_('Support for live streamers / DJs is currently <b>enabled</b> for this station. Edit your profile above to enable it.') ?></p>
                    <p><?=sprintf(_('Manage streamer accounts <a href="%s">on the Streamers / DJ Accounts page</a>.'), $url->routeFromHere(['controller' => 'streamers'])) ?></p>
                <?php else: ?>
                    <p><?=_('Support for live streamers / DJs is currently <b>disabled</b> for this station.') ?></p>
                    <p><?=_('Only the AutoDJ (based on your uploaded media and playlists) will be able to play on the air.') ?></p>
                <?php endif; ?>
            </div>
        </div>
    </div>
    <div class="col-sm-6">
        <?php if ($frontend_type == 'icecast'): ?>
        <div class="card">
            <div class="card-header <?php if ($frontend_is_running): ?>bgm-green<?php else: ?>bgm-red<?php endif; ?> ch-alt">
                <h2>
                    <?=_('IceCast (Broadcasting Service)') ?><br>
                    <small><?php if ($frontend_is_running): ?><?=_('Running') ?><?php else: ?><?=_('Not Running') ?><?php endif; ?></small>
                </h2>

                <ul class="actions">
                    <li class="dropdown">
                        <a href="" data-toggle="dropdown" aria-expanded="false">
                            <i class="zmdi zmdi-more-vert"></i>
                        </a>
                        <ul class="dropdown-menu dropdown-menu-right">
                            <li><a href="<?=$url->routeFromHere(['action' => 'frontend', 'do' => 'restart']) ?>"><?=_('Restart Service') ?></a></li>
                            <li><a href="<?=$url->routeFromHere(['action' => 'frontend', 'do' => 'start']) ?>"><?=_('Start Service') ?></a></li>
                            <li><a href="<?=$url->routeFromHere(['action' => 'frontend', 'do' => 'stop']) ?>"><?=_('Stop Service') ?></a></li>
                        </ul>
                    </li>
                </ul>
            </div>
            <div class="card-body card-padding">
                <dl>
                    <dt><?=_('Stream Public URL') ?>:</dt>
                    <dd><a href="<?=$frontend_adapter->getStreamUrl() ?>"><?=$frontend_adapter->getStreamUrl() ?></a></dd>
                </dl>

                <dl>
                    <dt><?=_('Administration URL') ?>:</dt>
                    <dd><a href="<?=$frontend_adapter->getAdminUrl() ?>"><?=$frontend_adapter->getAdminUrl() ?></a></dd>

                    <dt><?=_('Administrator Password') ?>:</dt>
                    <dd><?=$frontend_config['admin_pw'] ?></dd>

                    <dt><?=_('Source Password') ?>:</dt>
                    <dd><?=$frontend_config['source_pw'] ?></dd>
                </dl>
            </div>
        </div>
        <?php endif; ?>

        <?php if ($backend_type == 'liquidsoap'): ?>
        <div class="card">
            <div class="card-header <?php if ($backend_is_running): ?>bgm-green<?php else: ?>bgm-red<?php endif; ?> ch-alt">
                <h2>
                    <?=_('LiquidSoap (AutoDJ Service)') ?><br>
                    <small><?php if ($backend_is_running): ?><?=_('Running') ?><?php else: ?><?=_('Not Running') ?><?php endif; ?></small>
                </h2>

                <ul class="actions">
                    <li class="dropdown">
                        <a href="" data-toggle="dropdown" aria-expanded="false">
                            <i class="zmdi zmdi-more-vert"></i>
                        </a>
                        <ul class="dropdown-menu dropdown-menu-right">
                            <li><a href="<?=$url->routeFromHere(['action' => 'backend', 'do' => 'skip']) ?>"><?=_('Skip Song') ?></a></li>
                            <li class="divider">&nbsp;</li>
                            <li><a href="<?=$url->routeFromHere(['action' => 'backend', 'do' => 'restart']) ?>"><?=_('Restart Service') ?></a></li>
                            <li><a href="<?=$url->routeFromHere(['action' => 'backend', 'do' => 'start']) ?>"><?=_('Start Service') ?></a></li>
                            <li><a href="<?=$url->routeFromHere(['action' => 'backend', 'do' => 'stop']) ?>"><?=_('Stop Service') ?></a></li>
                        </ul>
                    </li>
                </ul>
            </div>
            <div class="card-body card-padding">
                <p><?=sprintf(_('LiquidSoap is currently shuffling from <b>%d uploaded songs</b> in <b>%d playlists</b>.'), $num_songs, $num_playlists) ?></p>
            </div>
        </div>
        <?php endif; ?>
    </div>
</div>