<?php
$title = 'Station Profile';

echo $this->viewHelper->renderHere('stationname', true);
echo $this->viewHelper->renderHere('homelink', true);
?>

<div class="buttons">
    <?=$this->viewHelper->button(array(
        'type'      => 'link',
        'class'     => 'large',
        'href'      => $this->viewHelper->routeFromHere(array('action' => 'edit')),
        'icon'      => 'icon-pencil',
        'text'      => 'Edit Profile',
    )) ?>
</div>

<?=$form->renderView() ?>