<?php
/**
 * @var \Azura\Assets $assets
 * @var array $admin_panels
 */

$this->layout('main', ['title' => 'Administration', 'manual' => true]);

$assets
    ->load('moment')
    ->addInlineJs($this->fetch('admin/index/index.js'), 99);
?>

<h2 class="outside-card-header"><?=__('Administration') ?></h2>

<div class="card-columns">
<?php foreach($admin_panels as $category_id => $category): ?>
    <section class="card" role="region">
        <div class="card-header bg-primary-dark">
            <h2 class="card-title"><?=$category['label'] ?></h2>
        </div>
        <div class="list-group list-group-flush">
        <?php foreach($category['items'] as $item): ?>
            <a class="list-group-item list-group-item-action" href="<?=$item['url'] ?>" title="<?=$item['title'] ?>">
                <?=$item['label'] ?>
            </a>
        <?php endforeach; ?>
        </div>
    </section>
<?php endforeach; ?>
</div>

<h2 class="outside-card-header"><?=__('Synchronization Tasks') ?></h2>

<div class="card-deck">
<?php foreach($sync_times as $sync_key => $sync_info): ?>
    <section class="card" role="region">
        <div class="card-header bg-primary-dark">
            <h2 class="card-title"><?=$sync_info['name'] ?></h2>
            <h3 class="card-subtitle"><?=implode(', ', $sync_info['contents']) ?></h3>
        </div>
        <div class="card-body">
            <p class="card-text"><?=__('Last run: %s', '<time data-duration="'.$sync_info['diff'].'"></time>') ?></p>
        </div>
        <div class="card-actions">
            <a class="btn btn-outline-primary" role="button" href="<?=$router->named('admin:index:sync', ['type' => $sync_key]) ?>">
                <i class="material-icons" aria-hidden="true">send</i>
                <?=__('Run Task') ?>
            </a>
        </div>
    </section>
<?php endforeach; ?>
</div>
