<?php

$this->layout(
    'main',
    [
        'title' => __('Remote Relays'),
        'manual' => true,
    ]
);

/** @var App\Http\RouterInterface $router */
$props = [
    'listUrl' => (string)$router->fromHere('api:stations:remotes'),
    'enableAdvancedFeatures' => $enableAdvancedFeatures,
];

/** @var \App\Assets $assets */
$assets->addVueRender('Vue_StationsRemotes', '#station-remotes', $props);
?>

<div id="station-remotes"></div>
