<?php $this->layout('minimal', ['title' => 'Set Up', 'page_class' => 'login-content']) ?>

<?php $this->start('custom_js') ?>
<script type="text/javascript" src="<?=$url->content('vendors/bower_components/zxcvbn/dist/zxcvbn.js') ?>"></script>
<?php $this->stop('custom_js') ?>

<!-- Login -->
<div class="lc-block toggled" id="l-login">
    <div class="lcb-form">
        <h3 class="text-left"><?=sprintf(_('Welcome to %s!'), $app_settings['name']) ?>!</h3>
        <P class="text-left"><?=_('Begin setup by creating a Super Administrator account.') ?></p>

        <form id="login-form" action="" method="post">
            <div class="input-group m-b-20">
                <span class="input-group-addon"><i class="zmdi zmdi-account"></i></span>
                <div class="fg-line">
                    <input type="email" name="username" class="form-control" placeholder="<?=_('E-mail Address') ?>">
                </div>
            </div>

            <div class="input-group m-b-20">
                <span class="input-group-addon"><i class="zmdi zmdi-lock"></i></span>
                <div class="fg-line">
                    <input type="password" name="password" class="form-control" placeholder="<?=_('Password') ?>">
                </div>
            </div>

            <div class="clearfix"></div>

            <button type="submit" class="btn btn-login btn-primary btn-float"><i class="zmdi zmdi-arrow-forward"></i></button>
        </form>
    </div>
</div>