<?php $this->layout('main', ['title' => _('Mount Points'), 'manual' => true]) ?>

<div class="card">
    <div class="card-header ch-alt">
        <h2><?=_('Mount Points') ?></h2>

        <a class="btn bgm-blue btn-float" href="<?=$url->routeFromHere(array('action' => 'edit')) ?>"><i class="zmdi zmdi-plus"></i></a>
    </div>
<?php if ($frontend_type == 'remote' && count($mounts) == 0): ?>
    <div class="card-body card-padding">
        <p><?=_('Ready to get started using mount points on your remote station? Click the button below to automatically create your first mount based on your existing settings.') ?></p>

        <div class="buttons">
            <a href="<?=$url->routeFromHere(['action' => 'migrate']) ?>" class="btn btn-primary"><?=_('Migrate Settings') ?></a>
        </div>
    </div>
<?php endif; ?>
    <div class="table-responsive">
        <table class="table table-striped">
            <colgroup>
                <col width="25%">
                <col width="45%">
                <col width="30%">
            </colgroup>
            <thead>
            <tr>
                <th><?=_('Actions') ?></th>
                <th><?=_('Mount Point') ?></th>
                <th><?=_('AutoDJ') ?></th>
            </tr>
            </thead>
            <tbody>
            <?php foreach($mounts as $row): ?>
                <?php /** @var \Entity\StationMount $row */ ?>
                <tr class="vertical-align-middle">
                    <td>
                        <a class="btn btn-sm btn-primary" href="<?=$url->routeFromHere(array('action' => 'edit', 'id' => $row->getId())) ?>"><?=_('Edit') ?></a>
                        <a class="btn btn-sm btn-danger" href="<?=$url->routeFromHere(array('action' => 'delete', 'id' => $row->getId())) ?>"><?=_('Delete') ?></a>
                    </td>
                    <td>
                    <?php if ($frontend_type == 'remote'): ?>
                        <big><a href="<?=$this->e($row->getRemoteUrl()) ?>" target="_blank"><?=$this->e($row->getRemoteUrl()) ?></a> # <?=$row->getRemoteMount() ?></big>
                    <?php else: ?>
                        <big><a href="<?=$this->e($frontend->getUrlForMount($row->getName())) ?>" target="_blank"><?=$this->e($row->getName()) ?></a></big>
                    <?php endif; ?>
                    <?php if ($row->getIsDefault()): ?>
                        <br><span class="label label-success"><?=_('Default Mount') ?></span>
                    <?php endif; ?>
                    </td>
                    <td>
                    <?php if ($row->getEnableAutodj()): ?>
                        <?=_('Enabled') ?> - <?=(int)$row->getAutodjBitrate() ?>kbps <?=strtoupper($this->e($row->getAutodjFormat())) ?>
                    <?php else: ?>
                        <?=_('Disabled') ?>
                    <?php endif; ?>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>