<?php $this->layout('main', ['title' => _('Mount Points'), 'manual' => true]) ?>

<div class="card">
    <div class="card-header ch-alt">
        <h2><?=_('Mount Points') ?></h2>

        <a class="btn bgm-blue btn-float" href="<?=$url->routeFromHere(array('action' => 'edit')) ?>"><i class="zmdi zmdi-plus"></i></a>
    </div>
    <div class="table-responsive">
        <table class="table table-striped">
            <colgroup>
                <col width="25%">
                <col width="35%">
                <col width="20%">
                <col width="20%">
            </colgroup>
            <thead>
            <tr>
                <th><?=_('Actions') ?></th>
                <th><?=_('Mount Point') ?></th>
                <th><?=_('Streamers') ?></th>
                <th><?=_('AutoDJ') ?></th>
            </tr>
            </thead>
            <tbody>
            <?php foreach($mounts as $row): ?>
                <tr class="vertical-align-middle">
                    <td>
                        <a class="btn btn-sm btn-primary" href="<?=$url->routeFromHere(array('action' => 'edit', 'id' => $row['id'])) ?>"><?=_('Edit') ?></a>
                        <a class="btn btn-sm btn-danger" href="<?=$url->routeFromHere(array('action' => 'delete', 'id' => $row['id'])) ?>"><?=_('Delete') ?></a>
                    </td>
                    <td>
                        <big><a href="<?=$frontend->getUrlForMount($row['name']) ?>" target="_blank"><?=$row['name'] ?></a></big>
                        <?php if ($row['is_default']): ?>
                            <br><span class="label label-success"><?=_('Default Mount') ?></span>
                        <?php endif; ?>
                    </td>
                    <td>
                    <?php if ($row['enable_streamers']): ?>
                        <?=_('Enabled') ?>
                    <?php else: ?>
                        <?=_('Disabled') ?>
                    <?php endif; ?>
                    </td>
                    <td>
                    <?php if ($row['enable_autodj']): ?>
                        <?=_('Enabled') ?> - <?=$row['autodj_bitrate'] ?>kbps <?=strtoupper($row['autodj_format']) ?>
                    <?php else: ?>
                        <?=_('Disabled') ?>
                    <?php endif; ?>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>