<?php
/**
 * @var \App\Entity\Station $station
 * @var \App\Acl $acl
 * @var \App\Http\Router $router
 * @var \App\Http\Request $request
 * @var \App\Entity\User $user
 * @var string $backend_type
 * @var string $frontend_type
 */
?>

<div class="card mb-4">
    <div class="card-header bg-primary-dark d-flex align-items-center">
        <div class="flex-fill">
            <h2 class="card-title"><?=$this->e($station->getName()) ?></h2>
            <h3 class="card-subtitle">
                <?=$this->e($station->getDescription()) ?>
            </h3>
        </div>
        <?php if ($acl->userAllowed($user, \App\Acl::STATION_PROFILE, $station->getId())): ?>
            <div class="flex-shrink-0">
                <a class="btn btn-light" role="button" href="<?=$router->fromHere('stations:profile:edit') ?>">
                    <i class="material-icons" aria-hidden="true">edit</i>
                    <?=__('Edit Profile') ?>
                </a>
            </div>
        <?php endif; ?>
    </div>
</div>
