<?php
/**
 * @var \App\Entity\Station $station
 * @var \App\Acl $acl
 * @var \App\Http\Router $router
 * @var \App\Http\Request $request
 * @var \App\Entity\User $user
 * @var string $backend_type
 * @var string $frontend_type
 * @var array $stream_urls
 */
?>

<section class="card mb-4" role="region">
    <div class="card-header bg-primary-dark">
        <h3 class="card-title"><?=__('Streams') ?></h3>
    </div>
    <table class="table table-sm table-striped table-responsive mb-0">
        <colgroup>
            <col style="width: 2%;">
            <col style="width: 78%;">
            <col style="width: 20%;">
        </colgroup>
        <?php if (count($stream_urls['local']) > 0): ?>
            <thead>
            <tr>
                <th colspan="2"><?=__('Local Streams') ?></th>
                <th><?=__('Listeners') ?></th>
            </tr>
            </thead>
            <tbody>
            <?php foreach($stream_urls['local'] as [$stream_id, $stream_name, $stream_url]): ?>
                <tr class="align-middle" id="mount_<?=$stream_id ?>">
                    <td class="pr-1">
                        <a class="btn-audio" href="#" data-url="<?=$this->e((string)$stream_url) ?>">
                            <i class="material-icons" aria-hidden="true">play_circle_filled</i>
                        </a>
                    </td>
                    <td class="pl-1">
                        <h6 class="mb-0"><?=$this->e($stream_name) ?></h6>
                        <?=$this->link($stream_url) ?>
                    </td>
                    <td class="pl-1 text-right">
                        <i class="material-icons sm align-middle" aria-hidden="true">headset</i> <span class="listeners-total">0</span><br>
                        <small>
                            <span class="listeners-unique">0</span> <?=__('Unique') ?>
                        </small>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        <?php endif; ?>
        <?php if (count($stream_urls['remote']) > 0): ?>
            <thead>
            <tr>
                <th colspan="2"><?=__('Remote Relays') ?></th>
                <th><?=__('Listeners') ?></th>
            </tr>
            </thead>
            <tbody>
            <?php foreach($stream_urls['remote'] as [$stream_id, $stream_name, $stream_url]): ?>
                <tr class="align-middle" id="remote_<?=$stream_id ?>">
                    <td class="pr-1">
                        <a class="btn-audio" href="#" data-url="<?=$this->e((string)$stream_url) ?>">
                            <i class="material-icons" aria-hidden="true">play_circle_filled</i>
                        </a>
                    </td>
                    <td class="pl-1">
                        <h6 class="mb-0"><?=$this->e($stream_name) ?></h6>
                        <?=$this->link($stream_url) ?>
                    </td>
                    <td class="pl-1 text-right">
                        <i class="material-icons sm align-middle" aria-hidden="true">headset</i> <span class="listeners-total">0</span><br>
                        <small>
                            <span class="listeners-unique">0</span> <?=__('Unique') ?>
                        </small>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        <?php endif; ?>
    </table>
    <div class="card-actions">
        <a class="btn btn-outline-primary" href="<?=$router->fromHere('public:playlist', ['format' => 'pls']) ?>">
            <i class="material-icons" aria-hidden="true">file_download</i>
            <?=__('Download %s', 'PLS') ?>
        </a>
        <a class="btn btn-outline-primary" href="<?=$router->fromHere('public:playlist', ['format' => 'm3u']) ?>">
            <i class="material-icons" aria-hidden="true">file_download</i>
            <?=__('Download %s', 'M3U') ?>
        </a>
    </div>
</section>
