<?php
/**
 * @var \App\Entity\Station $station
 * @var \App\Acl $acl
 * @var \App\Http\Router $router
 * @var \App\Http\Request $request
 * @var \App\Entity\User $user
 * @var string $backend_type
 * @var string $frontend_type
 */
?>

<div id="profile-scheduled">
    <section class="card mb-4 scheduled" role="region" v-if="schedule_items.length > 0">
        <div class="card-header bg-primary-dark">
            <h3 class="card-title"><?=__('Scheduled')?></h3>
        </div>
        <table class="table table-striped mb-0">
            <tbody>
            <tr v-for="row in schedule_items">
                <td>
                    <div class="d-flex w-100 justify-content-between align-items-center">
                        <h5 class="m-0">
                            <small>
                                <template v-if="row.type == 'playlist'"><?=__('Playlist')?></template>
                                <template v-else><?=__('Streamer/DJ')?></template>
                            </small><br>
                            {{ row.name }}
                        </h5>
                        <p class="text-right m-0">
                            <small>{{ row.start_formatted }} - {{ row.end_formatted }}</small>
                            <br>
                            <strong>
                                <template v-if="row.is_now"><?=__('Now')?></template>
                                <template v-else>{{ row.time_until }}</template>
                            </strong>
                        </p>
                    </div>
                </td>
            </tr>
            </tbody>
        </table>
    </section>
</div>