<?php
/**
 * @var \App\Entity\Station $station
 * @var \App\Acl $acl
 * @var \App\Http\Router $router
 * @var \App\Http\Request $request
 * @var \App\Entity\User $user
 * @var string $backend_type
 * @var string $frontend_type
 */
?>

<section class="card mb-4 nowplaying" role="region" id="profile-nowplaying">
    <div class="card-header bg-primary-dark">
        <div class="d-flex align-items-center">
            <h3 class="flex-shrink card-title my-0"><?=__('On the Air')?></h3>
            <h6 class="card-subtitle text-right flex-fill my-0" style="line-height: 1;">
                <i class="material-icons sm align-middle" aria-hidden="true">headset</i>
                <span>{{ np.listeners.total }}</span>
                <span v-if="np.listeners.total == 1"><?=__('Listener')?></span><span v-else><?=__('Listeners')?></span><br>
                <small>
                    <span>{{ np.listeners.unique }}</span> <?=__('Unique')?>
                </small>
            </h6>
        </div>
    </div>
    <div class="card-body">
        <div class="row">
            <div class="col-md-6">
                <div class="clearfix">
                    <h6 style="margin-left: 32px;">
                        <i class="material-icons" aria-hidden="true">music_note</i>
                        <?=__('Now Playing')?>
                    </h6>
                    <div class="media">
                        <a class="mr-2" v-bind:href="np.now_playing.song.art" data-fancybox target="_blank">
                            <img class="rounded" v-bind:src="np.now_playing.song.art" alt="<?=__('Album Art')?>" style="width: 50px;">
                        </a>
                        <div class="media-body">
                            <div v-if="np.now_playing.song.title != ''">
                                <h5 class="media-heading m-0" style="line-height: 1;">
                                    {{ np.now_playing.song.title }}<br>
                                    <small>{{ np.now_playing.song.artist }}</small>
                                </h5>
                            </div>
                            <div v-else>
                                <h5 class="media-heading m-0" style="line-height: 1;">{{ np.now_playing.song.text }}</h5>
                            </div>
                            <div v-if="np.now_playing.playlist">
                                <small class="text-muted"><?=__('Playlist')?>: {{ np.now_playing.playlist }}</small>
                            </div>
                            <div class="nowplaying-progress" v-if="time_display">
                                <small>{{ time_display }}</small>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="clearfix" v-if="!np.live.is_live && np.playing_next">
                    <h6 style="margin-left: 22px;">
                        <i class="material-icons" aria-hidden="true">skip_next</i>
                        <?=__('Playing Next')?>
                    </h6>

                    <div class="media">
                        <a class="mr-2" v-bind:href="np.playing_next.song.art" data-fancybox target="_blank">
                            <img v-bind:src="np.playing_next.song.art" class="rounded" alt="<?=__('Album Art')?>" style="width: 40px;">
                        </a>
                        <div class="media-body">
                            <div v-if="np.playing_next.song.title != ''">
                                <h5 class="media-heading m-0" style="line-height: 1;">
                                    {{ np.playing_next.song.title }}<br>
                                    <small>{{ np.playing_next.song.artist }}</small>
                                </h5>
                            </div>
                            <div v-else>
                                <h5 class="media-heading m-0" style="line-height: 1;">{{ np.playing_next.song.text }}</h5>
                            </div>

                            <div v-if="np.playing_next.playlist">
                                <small class="text-muted"><?=__('Playlist')?>: {{ np.playing_next.playlist }}</small>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="clearfix" v-else-if="np.live.is_live">
                    <h6 style="margin-left: 22px;">
                        <i class="material-icons" aria-hidden="true">mic</i>
                        <?=__('Live')?>
                    </h6>

                    <h4 class="media-heading" style="margin-left: 22px;">
                        {{ np.live.streamer_name }}
                    </h4>
                </div>
            </div>
        </div>
    </div>

    <?php if ($backend_type === \App\Radio\Adapters::BACKEND_LIQUIDSOAP && $acl->userAllowed($user,
            \App\Acl::STATION_BROADCASTING, $station->getId())): ?>
        <div class="card-actions flex-shrink">
            <a id="btn_skip_song" class="btn btn-outline-primary api-call no-reload" role="button" href="<?=$router->fromHere('api:stations:backend',
                ['do' => 'skip'])?>" v-if="!np.live.is_live">
                <i class="material-icons" aria-hidden="true">skip_next</i>
                <?=__('Skip Song')?>
            </a>
            <a id="btn_disconnect_streamer" class="btn btn-outline-primary api-call no-reload" role="button" href="<?=$router->fromHere('api:stations:backend',
                ['do' => 'disconnect'])?>" v-if="np.live.is_live">
                <i class="material-icons" aria-hidden="true">volume_off</i>
                <?=__('Disconnect Streamer')?>
            </a>
        </div>
    <?php endif; ?>
</section>
