<?php
/**
 * @var \App\Entity\Station $station
 * @var \App\Acl $acl
 * @var \App\Http\Router $router
 * @var \App\Http\Request $request
 * @var \App\Entity\User $user
 * @var string $backend_type
 * @var string $frontend_type
 */
?>

<section class="card mb-4 nowplaying" role="region" id="profile-nowplaying">
    <div class="card-header bg-primary-dark">
        <div class="d-flex">
            <h3 class="flex-shrink card-title mt-1 mb-0"><?=__('On the Air') ?></h3>
            <h6 class="card-subtitle text-right flex-fill mt-1 mb-0" style="line-height: 1;">
                <i class="material-icons sm align-middle" aria-hidden="true">headset</i> <span>{{ np.listeners.total }}</span> <span v-if="np.listeners.total == 1"><?=__('Listener') ?></span><span v-else><?=__('Listeners') ?></span><br>
                <small>
                    <span>{{ np.listeners.unique }}</span> <?=__('Unique') ?>
                </small>
            </h6>
        </div>
    </div>
    <div class="card-body">
        <radio-player></radio-player>
    </div>
    <?php if ($backend_type === \App\Radio\Adapters::BACKEND_LIQUIDSOAP && $acl->userAllowed($user, \App\Acl::STATION_BROADCASTING, $station->getId())): ?>
        <div class="card-actions">
            <a id="btn_skip_song" class="btn btn-outline-primary api-call no-reload" role="button" href="<?=$router->fromHere('api:stations:backend', ['do' => 'skip']) ?>" v-if="!np.live.is_live">
                <i class="material-icons" aria-hidden="true">skip_next</i>
                <?=__('Skip Song') ?>
            </a>
            <a id="btn_disconnect_streamer" class="btn btn-outline-primary api-call no-reload" role="button" href="<?=$router->fromHere('api:stations:backend', ['do' => 'disconnect']) ?>" v-if="np.live.is_live">
                <i class="material-icons" aria-hidden="true">volume_off</i>
                <?=__('Disconnect Streamer') ?>
            </a>
        </div>
    <?php endif; ?>
</section>
