<?php

$this->layout('main', ['title' => __('Listeners'), 'manual' => true]);

/**
 * @var App\Http\RouterInterface $router
 * @var \App\Entity\Station $station
 */
$props = [
    'apiUrl' => (string)$router->fromHere('api:listeners:index'),
    'stationTz' => $station->getTimezone(),
];

/** @var \App\Assets $assets */
$assets->addVueRender('Vue_StationsReportsListeners', '#station-report-listeners', $props);
?>

<div id="station-report-listeners"></div>
