$(function () {
    Chart.platform.disableCSSInjection = true;
    moment.tz.setDefault("UTC");

    var daily_chart = new Chart(document.getElementById('listeners_by_day').getContext('2d'), {
        type: 'bar',
        data: <?=$charts['daily'] ?>,
        options: {
            aspectRatio: 4,
            plugins: {
                colorschemes: {
                    scheme: 'tableau.Tableau20'
                }
            },
            scales: {
                xAxes: [{
                    type: 'time',
                    distribution: 'linear',
                    time: {
                        unit: 'day'
                    },
                    ticks: {
                        source: 'data',
                        autoSkip: true
                    }
                }],
                yAxes: [{
                    scaleLabel: {
                        display: true,
                        labelString: <?=$this->escapeJs(__('Listeners')) ?>
                    },
                    ticks: {
                        min: 0
                    }
                }]
            },
            tooltips: {
                intersect: false,
                mode: 'index',
                callbacks: {
                    label: function(tooltipItem, myData) {
                        var label = myData.datasets[tooltipItem.datasetIndex].label || '';
                        if (label) {
                            label += ': ';
                        }
                        label += parseFloat(tooltipItem.value).toFixed(2);
                        return label;
                    }
                }
            }
        }
    });

    var hourly_chart = new Chart(document.getElementById('listeners_by_hour').getContext('2d'), {
        type: 'bar',
        data: <?=$charts['hourly'] ?>,
        options: {
            aspectRatio: 4,
            plugins: {
                colorschemes: {
                    scheme: 'tableau.Tableau20'
                }
            },
            scales: {
                xAxes: [{
                    scaleLabel: {
                        display: true,
                        labelString: <?=$this->escapeJs(__('Hour')) ?>
                    }
                }],
                yAxes: [{
                    scaleLabel: {
                        display: true,
                        labelString: <?=$this->escapeJs(__('Listeners')) ?>
                    },
                    ticks: {
                        min: 0
                    }
                }]
            }
        }
    });

    var day_of_week_chart = new Chart(document.getElementById('listeners_by_day_of_week').getContext('2d'), {
        type: 'pie',
        data: <?=$charts['day_of_week'] ?>,
        options: {
            aspectRatio: 4,
            plugins: {
                colorschemes: {
                    scheme: 'tableau.Tableau20'
                }
            }
        }
    });

    $('canvas time').each(function() {
        $(this).text(moment.utc($(this).data('original')).format('ll'));
    });

});
