<?php

$this->layout('main', ['title' => __('Song Listener Impact'), 'manual' => true]);

/** @var App\Http\RouterInterface $router */
$props = [
    'apiUrl' => (string)$router->fromHere('api:stations:reports:performance'),
];

/** @var \App\Assets $assets */
$assets->addVueRender('Vue_StationsReportsPerformance', '#station-report-performance', $props);
?>

<div id="station-report-performance"></div>
