<?php $this->layout('main', ['title' => __('Song Requests'), 'manual' => true]) ?>

<?php
/** @var \Azura\Assets $assets */
$assets
    ->load('bootgrid');
?>

<div class="card">
    <div class="card-header bg-primary-dark">
        <h2 class="card-title"><?=__('Song Requests') ?></h2>
    </div>
    <div class="table-responsive">
        <table class="data-table table table-striped">
            <thead>
                <tr>
                    <th style="width: 20%;" data-column-id="timestamp"><?=__('Date Requested') ?></th>
                    <th style="width: 20%;" data-column-id="played_at"><?=__('Date Played') ?></th>
                    <th style="width: 30%;" data-column-id="song"><?=__('Song Title') ?></th>
                    <th style="width: 15%;" data-column-id="ip"><?=__('Requester IP') ?></th>
                    <th style="width: 15%;" data-column-id="actions"><?=__('Actions') ?></th>
                </tr>
            </thead>
            <tbody>
            <?php foreach($requests as $request_row): ?>
                <tr class="align-middle" id="request_<?=$request_row['id'] ?>">
                    <td class="text-center"><?=date('F j, Y g:ia', $request_row['timestamp']) ?></td>
                    <td class="text-center">
                    <?php if ($request_row['played_at'] > 0): ?>
                        <?=date('F j, Y g:ia', $request_row['played_at']) ?>
                    <?php else: ?>
                        <?=__('Not Played') ?>
                    <?php endif; ?>
                    </td>
                    <td>
                        <?php if ($request_row['track']['title']): ?>
                            <b><?=$this->e($request_row['track']['title']) ?></b><br>
                            <?=$this->e($request_row['track']['artist']) ?>
                        <?php else: ?>
                            <?=$this->e($request_row['track']['text']) ?>
                        <?php endif; ?>
                    </td>
                    <td><?=$this->e($request_row['ip']) ?></td>
                    <td>
                    <?php if ($request_row['played_at'] == 0): ?>
                        <a class="btn btn-sm btn-danger" href="<?=$router->fromHere('stations:reports:requests:delete', ['request_id' => $request_row['id'], 'csrf' => $csrf]) ?>"><?=__('Delete') ?></a>
                    <?php else: ?>

                    <?php endif; ?>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>

<script type="text/javascript">
    $(function() {
        $(".data-table").bootgrid({
            caseSensitive: false,
            sorting: false
        });
    });
</script>
