<?php

$this->layout('main', ['title' => __('Song Requests'), 'manual' => true]);

/** @var App\Http\RouterInterface $router */
$props = [
    'listUrl' => (string)$router->fromHere('api:stations:reports:requests'),
    'clearUrl' => (string)$router->fromHere('api:stations:reports:requests:clear'),
    'stationTimeZone' => $stationTz,
];

/** @var \App\Assets $assets */
$assets->addVueRender('Vue_StationsReportsRequests', '#station-report-requests', $props);
?>

<div id="station-report-requests"></div>
