<?php $this->layout('main', ['title' => __('Report Not Available'), 'manual' => true]) ?>

<div class="card">
    <div class="card-header">
        <h2 class="card-title"><?=__('Report Not Available') ?></h2>
    </div>
    <div class="card-body">
        <p><?=__('This report is not available for this station, because the system administrator has chosen not to collect detailed IP-based listener information.') ?></p>
    </div>
</div>
