<?php

$this->layout('main', ['title' => __('Song Playback Timeline'), 'manual' => true]);

/**
 * @var App\Http\RouterInterface $router
 * @var \App\Entity\Station $station
 */
$props = [
    'baseApiUrl' => (string)$router->fromHere('api:stations:history'),
    'stationTimeZone' => $station->getTimezone(),
];

/** @var \App\Assets $assets */
$assets->addVueRender('Vue_StationsReportsTimeline', '#station-report-timeline', $props);
?>

<div id="station-report-timeline"></div>
