<?php $this->layout('minimal', ['title' => 'Log In', 'page_class' => 'login-content']) ?>

<!-- Login -->
<div class="lc-block toggled" id="l-login">
    <div class="lcb-form">
        <h3 class="text-left">
            <?php if ($customization->hideProductName()): ?>
                <?=__('Welcome!') ?>
            <?php else: ?>
                <?=sprintf(__('Welcome to %s!'), $app_settings['name']) ?>
            <?php endif; ?>
            <?php if (!empty($customization->getInstanceName())): ?><small><?=$this->e($customization->getInstanceName()) ?></small><?php endif; ?>
        </h3>
        <p class="text-left"><?=__('Please log in to continue.') ?> <?=sprintf(__('<a href="%s" target="_blank">Forgot your password?</a>'), 'https://github.com/AzuraCast/AzuraCast/blob/master/SUPPORT.md#reset-an-account-password') ?></p>

        <form id="login-form" action="" method="post">
            <div class="input-group m-b-20">
                <span class="input-group-addon"><i class="zmdi zmdi-account"></i></span>
                <div class="fg-line">
                    <input type="email" name="username" class="form-control" placeholder="<?=__('E-mail Address') ?>">
                </div>
            </div>

            <div class="input-group m-b-20">
                <span class="input-group-addon"><i class="zmdi zmdi-lock"></i></span>
                <div class="fg-line">
                    <input type="password" name="password" class="form-control" placeholder="<?=__('Password') ?>">
                </div>
            </div>

            <div class="clearfix"></div>

            <button type="submit" role="button" title="<?=__('Log In') ?>" class="btn btn-login btn-primary btn-float"><i class="zmdi zmdi-arrow-forward"></i></button>
        </form>
    </div>

</div>