<?php
$this->layout('minimal', [
    'title' => 'Log In',
    'page_class' => 'login-content'
]);
?>

<div class="public-page">
    <div class="card">
        <div class="card-body">
            <h2 class="card-title mb-0">
            <?php if ($customization->hideProductName()): ?>
                <?=__('Welcome!') ?>
            <?php else: ?>
                <?=sprintf(__('Welcome to %s!'), $settings['name']) ?>
            <?php endif; ?>
            <?php if (!empty($customization->getInstanceName())): ?>
                <small class="text-muted"><?=$this->e($customization->getInstanceName()) ?></small>
            <?php endif; ?>
            </h2>

            <p class="text-left"><?=__('Please log in to continue.') ?> <?=sprintf(__('<a href="%s" target="_blank">Forgot your password?</a>'), 'https://github.com/AzuraCast/AzuraCast/blob/master/SUPPORT.md#reset-an-account-password') ?></p>

            <form id="login-form" class="pr-5" action="" method="post">
                <div class="input-group">
                    <div class="floating-label">
                        <label for="username"><?=__('E-mail Address') ?></label>
                        <input type="email" name="username" class="form-control" placeholder="" required>
                    </div>
                    <span class="input-group-icon">
                        <i class="material-icons">email</i>
                    </span>
                </div>

                <div class="input-group mt-2">
                    <div class="floating-label">
                        <label for="password"><?=__('Password') ?></label>
                        <input type="password" name="password" class="form-control" placeholder="" required>
                    </div>

                    <span class="input-group-icon">
                        <i class="material-icons">vpn_key</i>
                    </span>
                </div>

                <button type="submit" role="button" title="<?=__('Log In') ?>" class="btn btn-login btn-primary btn-float">
                    <i class="material-icons">arrow_forward_ios</i>
                </button>
            </form>
        </div>
    </div>
</div>
