<?
$station = $this->station;
$this->headTitle($station->name);
?>

<div class="station" id="station_<?=$station->short_name ?>" 
	data-autoplay="true" 
	data-id="<?=$station['id'] ?>" 
	data-name="<?=$station['name'] ?>" 
	data-type="<?=$station['type'] ?>" 
	data-stream="<?=$station['stream_url'] ?>" 
	data-inactive="<? if ($station['hide_if_inactive']): ?>hide<? else: ?>show<? endif; ?>">
	<img src="<?=\DF\Url::content($station['image_url']) ?>">

	<h4>
		<?=$station['name'] ?>
		<span class="nowplaying-info">
			<span class="nowplaying-listeners"></span>
		</span>
	<? if ($station['genre']): ?>
		<span class="genre-info"><?=$station['genre'] ?></span>
	<? endif; ?>
	</h4>
	<span class="nowplaying-onair" style="display: none;"></span>
	<span class="nowplaying-artist">Loading...</span>
	<span class="nowplaying-title">Loading...</span>
</div>