<?
$title = 'Song Directory';
?>

<form class="form-search" action="<?=$this->url->routeFromHere(array('page' => NULL)) ?>" method="get">
    <div class="input-append">
        <input type="text" name="q" title="Search terms" placeholder="Search..." class="input-large search-query" value="<?=$e->escapeHtml($q) ?>">
        <button type="submit" class="btn">Search</button>
    </div>
</form>

<?
if ($pager)
{
    echo $this->viewHelper->paginate($pager);
    echo $this->viewHelper->renderHere('list', false, array('songs' => $pager, 'display_mode' => 'index'));
    echo $this->viewHelper->paginate($pager);
}
?>