<?
$title = 'Song Directory';

/*
$this->assets->collection('custom_js')
    ->addJs('//cdnjs.cloudflare.com/ajax/libs/typeahead.js/0.10.4/dist/bloodhound.min.js', false)
    ->addJs('//cdnjs.cloudflare.com/ajax/libs/typeahead.js/0.10.4/dist/typeahead.jquery.min.js', false);
*/
?>

<form class="form-search" action="<?=$this->viewHelper->routeFromHere(array('page' => NULL)) ?>" method="get">
    <div class="input-append">
        <input type="text" name="q" title="Search terms" placeholder="Search..." class="input-large search-query" value="<?=$e->escapeHtml($q) ?>">
        <button type="submit" class="btn">Search</button>
    </div>
</form>

<? if ($pager): ?>
    <?=$this->viewHelper->paginate($pager) ?>

    <table class="table datatable table-striped table-nopadding">
        <colgroup>
            <col width="20%" />
            <col width="7%" />
            <col width="33%" />
            <col width="7%" />
            <col width="7%" />
            <col width="7%" />
            <col width="19%" />
        </colgroup>
        <thead>
        <tr>
            <th>Actions</th>
            <th>Art</th>
            <th>Song</th>
            <th>Pony.fm</th>
            <th>EQBeats</th>
            <th>BTunes</th>
            <th>Info</th>
        </tr>
        </thead>
        <tbody>
        <? foreach($pager as $record): ?>
            <tr class="input">
                <td class="center">
                    <div class="btn-group">
                        <?=$this->viewHelper->button(array(
                            'type'      => 'small',
                            'href'      => '#',
                            'class'     => 'btn-primary',
                            'onclick'   => "showSongInfo('".$record['id']."'); return false;",
                            'text'      => 'Info',
                        )) ?>
                        <?=$this->viewHelper->button(array(
                            'type'      => 'small',
                            'href'      => $this->viewHelper->routeFromHere(array('action' => 'edit', 'id' => $record['id'])),
                            'text'      => 'Edit',
                        )) ?>
                        <?=$this->viewHelper->button(array(
                            'type'      => 'small',
                            'class'     => 'danger confirm-delete',
                            'href'      => $this->viewHelper->routeFromHere(array('action' => 'delete', 'id' => $record['id'])),
                            'text'      => 'Delete',
                        )) ?>
                    </div>
                </td>
                <td class="center">
                <? if ($record['image_url']): ?>
                    <img src="<?=$record['image_url'] ?>" style="width: 64px;">
                <? endif; ?>
                </td>
                <td>
                    <b><?=$record->title ?></b><br>
                    <?=$record->artist ?>
                </td>
                <td class="center">
                    <? if ($record->external_ponyfm_id): ?>
                        <span class="large-icon" title="Approved"><i class="icon-ok-sign"></i></span>
                    <? else: ?>&nbsp;<? endif; ?>
                </td>
                <td class="center">
                    <? if ($record->external_eqbeats_id): ?>
                        <span class="large-icon" title="Approved"><i class="icon-ok-sign"></i></span>
                    <? else: ?>&nbsp;<? endif; ?>
                </td>
                <td class="center">
                    <? if ($record->external_bronytunes_id): ?>
                        <span class="large-icon" title="Approved"><i class="icon-ok-sign"></i></span>
                    <? else: ?>&nbsp;<? endif; ?>
                </td>
                <td>
                    &nbsp;
                </td>
            </tr>
        <? endforeach; ?>
        </tbody>
    </table>

    <?=$this->viewHelper->paginate($pager) ?>
<? endif; ?>