<?
$title = 'Song Directory';
?>

<h2>Merge This Song...</h2>

<div class="media-list">
    <div class="media">
        <div class="media-object pull-left">
            <img src="<?=$song_to_merge->image_url ?>" style="width: 40px;">
        </div>
        <div class="media-body">
            <h4>
                <?=$song_to_merge->title ?><br>
                <small><?=$song_to_merge->artist ?></small>
            </h4>
        </div>
    </div>
</div>

<br>

<h2>...Into This Song:</h2>

<form class="form-search" action="<?=$this->url->routeFromHere(array('merge_q' => NULL, 'page' => NULL)) ?>" method="get">
    <div class="input-append">
        <input type="text" name="merge_q" title="Search terms" placeholder="Search..." class="input-large search-query" value="<?=$e->escapeHtml($q) ?>">
        <button type="submit" class="btn">Search</button>
    </div>
</form>

<?
if ($results)
{
    echo $this->viewHelper->renderHere('list', false, array('songs' => $results, 'display_mode' => 'merge'));
}
?>