<?php
$this->layout('minimal', [
    'title' => 'Set Up',
    'page_class' => 'login-content'
]);

/** @var \App\Assets $assets */
$assets->load('zxcvbn');
?>

<div class="public-page">
    <div class="card">
        <div class="card-body">
            <h2 class="card-title mb-0">
                <?=sprintf(__('Welcome to %s!'), $app_settings['name']) ?>
            </h2>

            <p class="text-left"><?=__('Begin setup by creating a Super Administrator account.') ?></p>

            <form id="login-form" class="pr-5" action="" method="post">
                <div class="floating-label">
                    <label for="username"><?=__('E-mail Address') ?></label>
                    <input type="email" name="username" class="form-control" placeholder="">
                </div>

                <div class="floating-label">
                    <label for="password"><?=__('Password') ?></label>
                    <input type="password" name="password" class="form-control" placeholder="">
                </div>

                <button type="submit" role="button" title="<?=__('Create Account') ?>" class="btn btn-login btn-primary btn-float">
                    <i class="material-icons">arrow_forward_ios</i>
                </button>
            </form>
        </div>
    </div>
</div>
