<?php $this->layout('main', ['title' => __('AzuraCast Setup'), 'manual' => true]); ?>

<div class="block-header">
    <h2><?=__('AzuraCast Setup') ?></h2>
</div>

<div class="card">
    <div class="card-header ch-alt">
        <h2><?=__('Step 2: Create a New Station') ?></h2>
        <div><?=__('Continue the setup process by creating your first radio station below. You can edit any of these details later.') ?></div>
    </div>
    <div class="card-body card-padding">
        <?=$this->fetch('partials/station_form', ['form' => $form]) ?>
    </div>
</div>