<?php
$this->layout('main', [
    'title' => __('AzuraCast Setup'),
    'manual' => true
]);

/** @var \App\Assets $assets */
$assets
    ->addInlineJs($this->fetch('partials/station_form.js'), 99);
?>

<div class="block-header">
    <h2><?=__('AzuraCast Setup') ?></h2>
</div>

<div class="card">
    <div class="card-header ch-alt">
        <h2><?=__('Step 2: Create a New Station') ?></h2>
        <div><?=__('Continue the setup process by creating your first radio station below. You can edit any of these details later.') ?></div>
    </div>
    <div class="card-body card-padding">
        <?=$this->fetch('system/form_edit', ['form' => $form]) ?>
    </div>
</div>
