<?php
/**
 * @var App\Entity\Station $station
 * @var App\Http\RouterInterface $router
 */

$this->layout('main', [
    'title' =>
        __('Station Broadcasting Disabled'),
]);
?>

<p>
    <?= sprintf(
        __(
            'Your station is currently not enabled for broadcasting. You can still manage media, playlists, and other station settings. To re-enable broadcasting, <a href="%s">edit your station profile</a>.'
        ),
        $router->fromHere('stations:profile:edit')
    ) ?></p>
