$(function() {
    $('.api-call').on('click', function(e) {
        e.stopPropagation();
        var btn = $(this);

        var btn_original_text = btn.html();
        var trigger_reload = !btn.hasClass('no-reload');

        btn.text(<?=$this->escapeJs(__('Please wait...')) ?>);
        btn.addClass('disabled');

        $.ajax({
            type: "POST",
            url: btn.attr('href'),
            success: function(data) {
                if (trigger_reload) {
                    // Only restart if the user isn't on a form page
                    if ($('form').length === 0) {
                        setTimeout('location.reload()', 2000);
                    }
                } else {
                    btn.removeClass('disabled').html(btn_original_text);
                }

                var notify_type = (data.success) ? 'success' : 'warning';
                notify(data.message, notify_type);
            },
            error: function(response) {
                data = jQuery.parseJSON(response.responseText);
                notify(data.message, 'danger');

                btn.removeClass('disabled').html(btn_original_text);
            },
            dataType: "json"
        });

        return false;
    });
});
