<?
$this->headTitle('Manage Artists');
?>

<div class="buttons">
	<?=$this->button(array(
		'type'		=> 'link',
		'class'		=> 'large success',
		'href'		=> $this->routeFromHere(array('action' => 'edit')),
		'icon'		=> 'icon-plus-sign',
		'text'		=> 'Add New Artist',
	)) ?>
</div>

<form class="form-search" action="<?=$this->routeFromHere(array('page' => NULL)) ?>" method="get">
	<input type="text" name="q" title="Search terms" placeholder="Search..." class="input-medium span3 search-query" value="<?=$this->q ?>">
	<?=$this->button(array(
	    'type'		=> 'submit',
	    'class'		=> 'primary btn-small',
	    'text'		=> 'Search',
	)) ?>
</form>

<?=$this->paginate($this->pager) ?>

<table class="table table-striped table-nopadding">
	<colgroup>
		<col width="20%" />
		<col width="10%" />
		<col width="5%" />
		<col width="10%" />
		<col width="20%" />
		<col width="20%" />
		<col width="25%" />
	</colgroup>
	<thead>
		<tr>
			<th>Actions</th>
			<th>Avatar</th>
			<th>Status</th>
			<th>Type(s)</th>
			<th>Artist Name</th>
			<th>License</th>
			<th>Interviews</th>
		</tr>
	</thead>
	<tbody>
	<? foreach($this->pager as $record): ?>
		<tr class="input">
			<td class="center">
				<div class="btn-group">
					<?=$this->button(array(
						'type'		=> 'small',
						'icon'		=> 'pencil',
						'href'		=> $this->routeFromHere(array('action' => 'edit', 'id' => $record['id'])),
						'text'		=> 'Edit',
					)) ?>
					<?=$this->button(array(
						'type'		=> 'small',
						'icon'		=> 'delete',
						'class'		=> 'danger confirm-delete',
						'href'		=> $this->routeFromHere(array('action' => 'delete', 'id' => $record['id'])),
						'text'		=> 'Delete',
					)) ?>
				</div>
			</td>
			<td class="center"><img src="<?=\DF\Url::content($record['image_url']) ?>" style="width: 64px;"></td>
			<td class="center">
			<? if ($record->is_approved): ?>
				<span class="large-icon" title="Approved"><i class="icon-ok-sign"></i></span>
			<? else: ?>
				<span class="large-icon" title="Needs Review"><i class="icon-warning-sign"></i></span>
			<? endif; ?>
			</td>
			<td class="center">
			<? foreach($record->types as $type): ?>
				<span class="large-icon" title="<?=$type->name ?>"><i class="<?=$type->icon ?>"></i></span>
			<? endforeach; ?>
			</td>
			<td><big><?=$record['name'] ?></big></td>
			<td>
				<div><b><?=ucfirst($record['license']) ?></b></div>
				<div><small><?=$record['license_specifics'] ?></small></div>
			</td>
			<td>
				<div><b><? if ($record['interviews']): ?>Yes<? else: ?>No<? endif; ?></b></div>
				<div><?=$record['contact_skype'] ?></div>
			</td>
		</tr>
	<? endforeach; ?>
	</tbody>
</table>

<?=$this->paginate($this->pager) ?>