<?
$title = 'Artist Biography';
?>

<img src="<?=\App\Url::upload($artist['image_url']) ?>" style="float: right; padding: 5px;">

<h2>
    <?=$artist['name'] ?><br>
    <small><i class="<?=$artist['type_icon'] ?>"></i> <?=$artist['type_name'] ?></small>
</h2>

<p><?=nl2br($artist['description']) ?></p>

<dl>
    <dt>Homepage:</dt>
    <dd><?=$this->link($artist['web_url']) ?></dd>
</dl>

<div class="clear">&nbsp;</div>