#!/usr/bin/env bash

MYSQL_USER="${MYSQL_USER:-azuracast}"
MYSQL_PASSWORD="${MYSQL_PASSWORD:-azur4c457}"
MYSQL_DATABASE="${MYSQL_DATABASE:-azuracast}"

exec gosu mysql mysql -u${MYSQL_USER} -p${MYSQL_PASSWORD} -D ${MYSQL_DATABASE}