<!DOCTYPE html>
<?php
/**
 * @var \League\Plates\Template\Template $this
 * @var \App\Auth $auth
 * @var \App\Acl $acl
 * @var \App\Http\Router $router
 * @var \App\Session\Flash $flash
 * @var \App\Customization $customization
 * @var \App\Assets $assets
 * @var array $app_settings
 */
?>
<html>
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">

<?php
if ($title)
    $page_title = $title.' - '.$app_settings['name'];
else
    $page_title = $app_settings['name'];

if (!APP_IN_PRODUCTION)
    $page_title = '('.ucfirst(APP_APPLICATION_ENV).') '.$page_title;
?>
<title><?=$page_title ?></title>

<?=$this->fetch('partials/icons') ?>

<?php
$assets
    ->load('main')
    ->load('theme_'.$customization->getTheme())
    ->addInlineCss($customization->getCustomInternalCss());

echo $assets->css();
echo $assets->js();
?>
</head>
<body class="<?=$page_class ?>">
<?=$assets->inlineJs($request) ?>

<a class="sr-only sr-only-focusable" href="#content"><?=__('Skip to main content') ?></a>

<header class="navbar bg-primary-dark fixed-top">
<?php if (!empty($sidebar)): ?>
    <button aria-controls="sidebar" aria-expanded="false" aria-label="<?=__('Toggle Sidebar') ?>" class="navbar-toggler mr-3" data-breakpoint="lg" data-target="#doc-sidebar" data-toggle="navdrawer" data-type="permanent">
        <span class="navbar-toggler-icon"></span>
    </button>
<?php endif; ?>

    <a class="navbar-brand mr-auto" href="<?=$router->named('dashboard') ?>">
        azura<strong>cast</strong> <?php if (!empty($customization->getInstanceName())): ?><small><?=$this->e($customization->getInstanceName()) ?></small><?php endif; ?>
    </a>

    <div class="ml-3">
        <?=$this->fetch('partials/radio_controls') ?>

        <div class="dropdown">
            <button aria-expanded="false" aria-haspopup="true" class="navbar-toggler" data-toggle="dropdown" id="doc-dropdown-follow" type="button"><i class="zmdi zmdi-more-vert"></i></button>
            <div aria-labelledby="doc-dropdown-follow" class="dropdown-menu dropdown-menu-right">
                <ul class="dropdown-menu dm-icon pull-right">
                    <li><a href="<?=$router->named('dashboard') ?>"><i class="zmdi zmdi-home"></i> <?=__('Dashboard') ?></a></li>
                    <?php if ($acl->userAllowed($user, 'view administration')): ?>
                        <li><a href="<?=$router->named('admin:index:index') ?>"><i class="zmdi zmdi-settings"></i> <?=__('System Administration') ?></a></li>
                    <?php endif; ?>
                    <li><a href="<?=$router->named('profile:index') ?>"><i class="zmdi zmdi-account"></i> <?=__('My Account') ?></a></li>
                    <li><a href="<?=$router->named('api_keys:index') ?>"><i class="zmdi zmdi-key"></i> <?=__('My API Keys') ?></a></li>
                    <li class="divider">&nbsp;</li>
                    <?php if ($auth->isMasqueraded()): ?>
                        <li><a href="<?=$router->named('account:endmasquerade') ?>"><i class="zmdi zmdi-power"></i> <?=__('End Session') ?></a></li>
                    <?php else: ?>
                        <li><a href="<?=$router->named('account:logout') ?>"><i class="zmdi zmdi-power"></i> <?=__('Sign Out') ?></a></li>
                    <?php endif; ?>
                </ul>
            </div>
        </div>
    </div>
</header>

<?php if (!empty($sidebar)): ?>
    <div aria-hidden="true" class="navdrawer navdrawer-permanent-clipped" id="sidebar" tabindex="-1">
        <div class="navdrawer-content">
            <?=$sidebar ?>
        </div>
    </div>
<?php endif; ?>

<section id="main">

    <section id="content" <?php if (empty($sidebar)): ?>class="content-alt"<?php endif; ?> role="main">
        <div class="container">
        <?php if ($manual): ?>
            <?=$this->section('content') ?>
        <?php else: ?>
            <?php if ($header): ?>
                <div class="block-header">
                    <h2><?=$header ?></h2>
                </div>
            <?php endif; ?>
            <div class="card">
                <div class="card-header ch-alt">
                    <h3><?=$title ?></h3>
                </div>
                <div class="card-body card-padding">
                    <?=$this->section('content') ?>
                </div>
            </div>
        <?php endif; ?>
        </div>
    </section>
</section>

<footer id="footer" <?php if (empty($sidebar)): ?>class="footer-alt"<?php endif; ?> role="contentinfo">
    <?=__('Powered by %s', '<a href="https://www.azuracast.com/" target="_blank">'.$app_settings['name'].'</a> &bull; '.\App\Version::getVersionText().' &bull; '.(APP_INSIDE_DOCKER ? 'Docker' : 'Traditional').' &bull; PHP '.\PHP_MAJOR_VERSION.'.'.\PHP_MINOR_VERSION) ?><br>
    <?=__('Like our software? <a href="%s" target="_blank">Donate to support AzuraCast!</a>', 'https://www.azuracast.com/donate.html') ?>
</footer>

<div id="radio-player"></div>

<?php if ($flash->hasMessages()): ?>
    <script type="text/javascript" nonce="<?=$assets->getCspNonce() ?>">
        $(function() {
            <?php foreach($flash->getMessages() as $message): ?>
            notify("<?=str_replace(array('"', "\n"), array('\'', '<br>'), $message['text']) ?>", '<?=$message['color'] ?>', false);
            <?php endforeach; ?>
        });
    </script>
<?php endif; ?>
</body>
</html>
