$(function () {
    Chart.platform.disableCSSInjection = true;
    moment.tz.setDefault('UTC');

    const chartOptions = {
        aspectRatio: 4,
        plugins: {
            colorschemes: {
                scheme: 'tableau.Tableau20'
            }
        },
        scales: {
            xAxes: [{
                type: 'time',
                distribution: 'linear',
                time: {
                    unit: 'day'
                },
                ticks: {
                    source: 'data',
                    autoSkip: true
                }
            }],
            yAxes: [{
                scaleLabel: {
                    display: true,
                    labelString: <?=$this->escapeJs(__('Listeners')) ?>
                },
                ticks: {
                    min: 0
                }
            }]
        },
        tooltips: {
            intersect: false,
            mode: 'index',
            callbacks: {
                label: function (tooltipItem, myData) {
                    var label = myData.datasets[tooltipItem.datasetIndex].label || '';
                    if (label) {
                        label += ': ';
                    }
                    label += parseFloat(tooltipItem.value).toFixed(2);
                    return label;
                }
            }
        }
    };

    let averageChart = new Chart(document.getElementById('chart_average').getContext('2d'), {
        type: 'bar',
        data: {
            datasets: <?=json_encode($metrics['average']['metrics'], \JSON_THROW_ON_ERROR) ?>
        },
        options: chartOptions
    });

    let uniqueChart = new Chart(document.getElementById('chart_unique').getContext('2d'), {
        type: 'bar',
        data: {
            datasets: <?=json_encode($metrics['unique']['metrics'], \JSON_THROW_ON_ERROR) ?>
        },
        options: chartOptions
    });

    $('canvas time').each(function () {
        $(this).text(moment.utc($(this).data('original')).format('ll'));
    });
});
