<?php
/**
 * @var \App\Entity\User $user
 * @var \App\Http\Router $router
 */

$props = [
    'userName' => $user->getName() ?? __('AzuraCast User'),
    'userEmail' => $user->getEmail(),
    'userAvatar' => $user->getAvatar(64),
    'profileUrl' => (string)$router->named('profile:index'),
    'adminUrl' => (string)$router->named('admin:index:index'),
    'showAdmin' => $showAdmin,
    'notificationsUrl' => (string)$router->named('api:frontend:dashboard:notifications'),
    'showCharts' => $showCharts,
    'chartsUrl' => (string)$router->named('api:frontend:dashboard:charts'),
    'addStationUrl' => (string)$router->named('admin:stations:add'),
    'stationsUrl' => (string)$router->named('api:frontend:dashboard:stations'),
];
?>

$(function () {
    let dashboard = new Vue({
        el: '#dashboard',
        render: function (createElement) {
            return createElement(Dashboard.default, {
                props: <?=json_encode($props) ?>
            });
        }
    });
});
