<?php
$station_ids = [];
foreach($stations['stations'] as $station) {
    $station_ids[] = $station['station']['id'];
}
?>

var station_dashboard;

$(function() {
    station_dashboard = new Vue({
        el: '#station_dashboard',
        data: <?=json_encode($stations) ?>,
        methods: {
            toggle: function (url) {
                this.$eventHub.$emit('player_toggle', url);
            }
        }
    });
});

<?php
if (\App\Service\NChan::isSupported()):
?>
    $(function() {
        var sub = new NchanSubscriber('/api/live/nowplaying/<?=implode(',', $station_ids) ?>');

        sub.on("message", function(message, message_metadata) {
            var row = JSON.parse(message);

            var station_id = row.station.id;
            station_dashboard['stations'][station_id]['np'] = row;
        });
        sub.start();
    });
<?php
else:
?>
    $(function() {
        setTimeout(loadNowPlaying, 15000);
    });

    function loadNowPlaying() {
        $.getJSON('<?=$router->named('api:nowplaying:index') ?>', function(data) {
            $.each(data, function(k, row) {
                var station_id = row.station.id;
                station_dashboard['stations'][station_id]['np'] = row;
            });

            setTimeout(loadNowPlaying, 15000);
        }).fail(function() {
            setTimeout(loadNowPlaying, 30000);
        });
    }
<?php
endif;
?>
