<?php
$title = 'Artist Licensing Documentation';
echo $this->viewHelper->renderHere('header', true, array('title' => $title));
?>

<h3>Fully Licensed Artists</h3>

<ul class="media-list">
<? foreach($artists as $artist): ?>
    <li class="media">
        <img class="media-object pull-left" src="<?=\App\Url::upload($artist['image_url']) ?>" style="width: 40px;">
        <div class="media-body">
            <h4>
                <?=$artist['name'] ?><br>
                <small>
                    <div>
                    <? foreach((array)$artist['types'] as $type): ?>
                        <i class="<?=$type['icon'] ?>"></i> <?=$type['name'] ?> 
                    <? endforeach; ?>
                    </div>
                </small>
            </h4>
            <div><?=ucfirst($artist['license']) ?> License</div>
            <div>Initialed: <?=$artist['initials'] ?></div>
        <? if ($artist['initial_timestamp']): ?>
            <div>Signed and Authenticated <?=$artist['initial_timestamp']->format('m/d/Y g:ia')  ?></div>
        <? endif; ?>
        </div>
    </li>
<? endforeach; ?>
</ul>
