<?php $this->layout('main', ['title' => __('Streamer/DJ Accounts'), 'manual' => true]) ?>

<div class="card">
    <div class="card-header ch-alt">
        <h2><?=__('Streamer/DJ Accounts') ?></h2>
    </div>
    <div class="card-body card-padding">
        <p><?=__('Streamer accounts are currently disabled for this station. To enable streamer accounts, click the button below.') ?></p>

        <a class="btn btn-lg btn-success" role="button" href="<?=$router->fromHere(null, [], ['enable' => true]) ?>"><?=__('Enable Streaming') ?></a>
    </div>
</div>
