<?php
$this->layout('main', [
    'title' => __('Log Viewer'),
    'manual' => true
]);
?>

<div class="row">
    <div class="col-md-8">
        <div class="card">
            <div class="card-header bg-primary-dark">
                <h2 class="card-title"><?=__('Available Logs') ?></h2>
            </div>
            <div class="list-group list-group-flush">
            <?php foreach($logs as $log_key => $log_info): ?>
                <a class="list-group-item list-group-item-action log-item" href="<?=$router->fromHere('stations:logs:view', ['log' => $log_key]) ?>">
                    <span class="log-name"><?=$log_info['name'] ?></span><br>
                    <small class="text-secondary"><?=$log_info['path'] ?></small>
                </a>
            <?php endforeach; ?>
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <?=$this->fetch('partials/log_help_card') ?>
    </div>
</div>

<?=$this->fetch('partials/log_viewer') ?>
