<?php
$title = $type_name;
$manual = true;
?>

<div class="row-fluid">
    <div class="span3">
        <?=$this->viewHelper->renderHere('sidebar') ?>
    </div>
    <div class="span9">
        <div class="floating">
            <?=$this->viewHelper->paginate($pager) ?>
            <ul class="media-list">
            <? foreach($pager as $artist): ?>
                <li class="media">
                    <div class="media-object pull-left">
                        <a href="<?=$this->viewHelper->route(array('controller' => 'artists', 'action' => 'view', 'id' => $artist['id'])) ?>"><img class="thumbnail" src="<?=\App\Url::upload($artist['image_url']) ?>" style="width: 64px;"></a>
                    </div>
                    <div class="media-body">
                        <h4>
                            <a href="<?=$this->viewHelper->route(array('controller' => 'artists', 'action' => 'view', 'id' => $artist['id'])) ?>"><?=$artist['name'] ?></a><br>
                            <small>
                                <div>
                                <? foreach($artist->types as $type): ?>
                                    <i class="<?=$type['icon'] ?>"></i> <?=$type['name'] ?> 
                                <? endforeach; ?>
                                </div>
                            </small>
                        </h4>
                        <div><?=\App\Utilities::truncateText($artist['description'], 150) ?></div>
                    </div>
                </li>
            <? endforeach; ?>
            </ul>
            <?=$this->viewHelper->paginate($pager) ?>
        </div>
    </div>
</div>

