<?php $this->layout('main', ['title' => $title]) ?>

<?=$this->insert('partials/form', ['form' => $form]) ?>

<script type="text/javascript" nonce="<?=$assets->getCspNonce() ?>">
$(function() {

    showFieldset($('form #field_type input:checked').val());

    $('form #field_type input').on('change', function() {
        showFieldset($(this).val());
    });

});

function showFieldset(fieldset_id)
{
    $('form fieldset.type_fieldset').hide();
    $('form fieldset#type_'+fieldset_id).show();
}
</script>