<?php
$this->layout('main', ['title' => __('Playlists'), 'manual' => true]);

/** @var \AzuraCast\Assets $assets */
$assets->load('fullcalendar');
?>

<div class="card">
    <div class="card-header ch-alt">
        <h2><?=__('Playlists') ?></h2>

        <a class="btn bgm-blue btn-float" role="button" title="<?=sprintf(__('Add %s'), __('Playlist')) ?>" href="<?=$url->named('stations:playlists:add', ['station' => $station->getId()]) ?>"><i class="zmdi zmdi-plus"></i></a>
    </div>

    <div role="tabpanel">
        <ul class="tab-nav" role="tablist">
            <li class="p-l-10 active"><a role="tab" data-toggle="tab" aria-expanded="true" aria-controls="all-playlists" href="#all-playlists"><?=__('All Playlists') ?></a></li>
            <li><a role="tab" data-toggle="tab" aria-controls="schedule-view" href="#schedule-view"><?=__('Schedule View') ?></a></li>
        </ul>

        <div class="tab-content p-t-0 p-b-0">
            <div class="tab-pane active" id="all-playlists" role="tabpanel">

                <table class="table table-striped">
                    <colgroup>
                        <col width="25%">
                        <col width="30%">
                        <col width="30%">
                        <col width="15%">
                    </colgroup>
                    <thead>
                    <tr>
                        <th><?=__('Actions') ?></th>
                        <th><?=__('Playlist') ?></th>
                        <th><?=__('Type') ?></th>
                        <th><?=__('# Songs') ?></th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php foreach($playlists as $row): ?>
                        <tr class="vertical-align-middle">
                            <td>
                                <a class="btn btn-sm btn-primary" href="<?=$url->named('stations:playlists:edit', ['station' => $station->getId(), 'id' => $row['id']]) ?>"><?=__('Edit') ?></a>

                                <div class="btn-group">
                                    <button type="button" class="btn btn-sm btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        <?=__('Export') ?> <span class="caret"></span>
                                    </button>
                                    <ul class="dropdown-menu">
                                        <?php foreach(['pls', 'm3u'] as $format): ?>
                                            <li><a href="<?=$url->named('stations:playlists:export', ['station' => $station->getId(), 'id' => $row['id'], 'format' => $format]) ?>"><?=sprintf(__('Download %s'), strtoupper($format)) ?></a></li>                                        <?php endforeach; ?>
                                    </ul>
                                </div>

                                <a class="btn btn-sm btn-danger" href="<?=$url->named('stations:playlists:delete', ['station' => $station->getId(), 'id' => $row['id'], 'csrf' => $csrf]) ?>"><?=__('Delete') ?></a>
                            </td>
                            <td>
                                <big>
                                    <a href="<?=$url->named('stations:files:index', ['station' => $station->getId()]).'#playlist:'.urlencode($row['name']) ?>"><?=$this->e($row['name']) ?></a>
                                </big>
                                <?php if ($row['include_in_automation']): ?>
                                    <br><span class="label label-success"><?=__('Auto-Assigned') ?></span>
                                <?php endif; ?>
                            </td>
                            <td>
                                <?php if (!$row['is_enabled']): ?>
                                    <?=__('Disabled') ?>
                                <?php elseif ($row['type'] === 'default'): ?>
                                    <?=__('Standard Playlist') ?><br>
                                    <?=__('Weight') ?>: <?=(int)$row['weight'] ?> (<?=$row['probability'] ?>)
                                <?php elseif ($row['type'] === 'scheduled'): ?>
                                    <?=__('Scheduled Playlist') ?><br>
                                    <?=sprintf(__('Plays between %s and %s'), $customization->formatTime(\Entity\StationPlaylist::getTimestamp($row['schedule_start_time'])), $customization->formatTime(\Entity\StationPlaylist::getTimestamp($row['schedule_end_time']))) ?>
                                <?php elseif ($row['type'] === 'once_per_x_songs'): ?>
                                    <?=sprintf(__('Once per %d Songs'), $row['play_per_songs']) ?>
                                <?php elseif ($row['type'] === 'once_per_x_minutes'): ?>
                                    <?=sprintf(__('Once per %d Minutes'), $row['play_per_minutes']) ?>
                                <?php elseif ($row['type'] === 'once_per_day'): ?>
                                    <?=__('Once per Day') ?><br>
                                    <?=sprintf(__('Plays at %s'), $customization->formatTime(\Entity\StationPlaylist::getTimestamp($row['play_once_time']))) ?>
                                <?php elseif ($row['type'] === 'custom'): ?>
                                    <?=__('Custom') ?>
                                <?php endif; ?>
                            </td>
                            <td><?=$row['num_songs'] ?></td>
                        </tr>
                    <?php endforeach; ?>
                    </tbody>
                </table>

            </div>
            <div class="tab-pane card-padding" id="schedule-view" role="tabpanel">
                <div id="playlist-calendar"></div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript" nonce="<?=$assets->getCspNonce() ?>">
$(function() {
    $('a[data-toggle="tab"]').on('shown.bs.tab', function (e) {
        var target = $(e.target).attr("href");

        if (target == '#schedule-view') {

            $('#playlist-calendar').fullCalendar({
                themeSystem: 'bootstrap3',
                nowIndicator: true,
                defaultView: 'agendaWeek',
                locale: '<?=substr(strtolower($customization->getLocale()), 0, 2) ?>',
                header: false,
                footer: false,
                events: '<?=$schedule_url ?>'
            });

        } else {

            $('#playlist-calendar').fullCalendar('destroy').removeClass().empty();

        }
    });
});
</script>