<?
$title = ('Convention Center');
$manual = true;
?>

<div class="row-fluid">
    <div class="span3">
        <h2>PVL! Convention Coverage</h2>
        <p>The <b>Ponyville Live!</b> network is proud to offer free-of-charge convention streaming and recording services, when available, to any convention within the My Little Pony fan community. This is a service we are able to provide thanks to our international team of videographers.</p>

        <p>Below is a list of conventions our network will be attending soon. If you're hosting a MLP convention and would like to inquire about the PVL network covering your event, please contact us at <?=$this->viewHelper->mailto('pr@ponyvillelive.com') ?>.</p>

        <h3>Upcoming Conventions</h3>

        <dl>
        <? foreach($conventions_upcoming as $record): ?>
            <? if ($record['coverage_level'] != "none"): ?>
            <dt><a href="<?=$record['web_url'] ?>" target="_blank"><?=$record['name'] ?></a></dt>
            <dd>
                <?=$record['range'] ?><br>
                <?=$record['location'] ?><br>
                <i class="<?=$record['coverage']['icon'] ?>"></i> <?=$record['coverage']['text'] ?>
            </dd>
            <? endif; ?>
        <? endforeach; ?>
        </dl>
    </div>
    <div class="span9">
        <h2>Convention Video Archives</h2>

        <div class="conventions row-fluid row-multiple clearfix">
            <? foreach($conventions_archived as $record): ?>
            <div class="span4">
                <a class="convention coverage_<?=$record['coverage_level'] ?>" href="<?=$this->viewHelper->routeFromHere(array('action' => 'archive', 'id' => $record['id'])) ?>">
                    <img src="<?=\DF\Url::content($record['image']) ?>" alt="Convention Image">
                    <div class="coverage" title="<?=$record['coverage']['text'] ?>">
                        <i class="large-icon <?=$record['coverage']['icon'] ?>"></i>
                    </div>
                    <div class="name">
                        <h4><?=$record['name'] ?></h4>
                        <?=$record['location'] ?> &bull; <?=$record['range'] ?>
                    </div>
                </a>
            </div>
            <? endforeach; ?>
        </div>
    </div>
</div>