<h2><?=$subject ?></h2>

<p>Your account has been granted access to the following section of the <?=$this->config->application->name ?> administration center:</p>

<ul>
<? foreach($areas as $area): ?>
    <li><?=$area ?></li>
<? endforeach; ?>
</ul>

<p>
    Click the link below to access the main PVL administration page:<br>
    <a href="<?=$this->viewHelper->route(array('module' => 'admin')) ?>" target="_blank"><strong>PVL Administration Center</strong></a>
</p>

<p><b>Note:</b> If you didn't already have an account on the Bravely Blue web site before receiving this e-mail, one was automatically created for you. Use the "Forgot My Password" tool the first time you log in to generate a one-time login code.</p>