<h2><?=$subject ?></h2>

<p>You are receiving this e-mail because you are listed as the administrator of an active <?=$this->config->application->name ?> station.</p>

<p>A new station has been submitted for possible inclusion into the <?=$this->config->application->name ?> homepage. Please take a moment to review this station and indicate your recommendation using the link below.</p>

<p>
    To access the station center and submit your vote, visit this page:<br>
    <?=$this->viewHelper->link($this->viewHelper->route(array('module' => 'stations'))) ?>
</p>

<p>Station details are listed below:</p>

<?=$form->renderView() ?>