<h2><?=$subject ?></h2>

<p>A musician has submitted a song through the <?=$this->config->application->name ?> web site, and has selected your station as a potential recipient.</p>

<p>Song details are included below for your reference. By submitting this song through this system, the uploader has indicated that they are the legitimate copyright holder for the tracks below, and that they are granting your station full permission to add the song to your regular rotation.</p>

<? foreach($songs as $song): ?>
    <h3><?=$song['Artist'] ?> - <?=$song['Title'] ?></h3>

    <? foreach($song as $meta_key => $meta_val): ?>
    <div><b><?=$meta_key ?>:</b> <?=$meta_val ?></div>
    <? endforeach; ?>
<? endforeach; ?>