<?php $this->layout('main', ['title' => __('Custom Fields'), 'manual' => true]); ?>

<div class="card">
    <div class="card-header ch-alt">
        <h2><?=__('Custom Fields') ?></h2>

        <a class="btn bgm-blue btn-float" role="button" title="<?=sprintf(__('Add %s'), __('Custom Field')) ?>" href="<?=$url->named('admin:custom_fields:add') ?>"><i class="zmdi zmdi-plus"></i></a>
    </div>
    <div class="table-responsive">
        <table class="table table-striped">
            <colgroup>
                <col width="30%">
                <col width="70%">
            </colgroup>
            <thead>
            <tr>
                <th><?=__('Actions') ?></th>
                <th><?=__('Name') ?></th>
            </tr>
            </thead>
            <tbody>
            <?php foreach($records as $row): ?>
                <tr class="input">
                    <td>
                        <a class="btn btn-sm btn-default" href="<?=$url->named('admin:custom_fields:edit', ['id' => $row['id']]) ?>"><?=__('Edit') ?></a>
                        <a class="btn btn-sm btn-danger" href="<?=$url->named('admin:custom_fields:delete', ['id' => $row['id'], 'csrf' => $csrf]) ?>"><?=__('Delete') ?></a>
                    </td>
                    <td>
                        <?=$this->e($row['name']) ?>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>