<?
$this->headTitle('The MLP Music Archive');
?>

<!-- A tab to launch the Classic Widget -->
<script>
UserVoice = window.UserVoice || [];
UserVoice.push(['showTab', 'classic_widget', {
  mode: 'feedback',
  primary_color: '#3f51c4',
  link_color: '#59baeb',
  forum_id: 203269,
  tab_label: 'Feedback & Support',
  tab_color: '#006fe6',
  tab_position: 'middle-right',
  tab_inverted: false
}]);
</script>

<h2>Your Favorite Pony Songs, All In One Place.</h2>
<p>The MLP Music Archive project is now a proud member of the <a href="http://www.ponyvillelive.com/" target="_blank">Ponyville Live!</a> family. We are working hard to bring you a brand spankin' new and improved version of the archive, with the latest and greatest in pony hits included, plus tons of new features.</p>

<p>You can download the existing MLP Music Archive using the link below.<br>This version of the archive was created on November 27, 2012.</p>

<div class="buttons">
    <a href="https://docs.google.com/open?id=0B5LW1ZIpaxUIZkIwdUtsQnFKUVU" class="btn btn-xlarge btn-primary">Download v14 (Torrent)</a>
    <a href="https://docs.google.com/folder/d/0B60Mv4AgTPp8WjY4NnpuT05ZT0E/edit" class="btn btn-xlarge btn-inverse">View on Google Drive</a>
</div>