<?php
$props = [
    'listUrl' => $router->fromHere('api:stations:streamers'),
    'scheduleUrl' => $router->fromHere('api:stations:streamers:schedule'),
    'locale' => substr($customization->getLocale(), 0, 2),
    'stationTimeZone' => $station_tz,
]
?>
var station_streamers;

$(function () {
    station_streamers = new Vue({
        el: '#station-streamers',
        render: function (createElement) {
            return createElement(StationStreamers.default, {
                props: <?=json_encode($props) ?>
            });
        }
    });
});