<?php
$this->layout('main', [
    'title' => __('Podcasts'),
    'manual' => true,
]);

$props = [
    'listUrl' => $router->fromHere('api:stations:podcasts'),
    'newArtUrl' => $router->fromHere('api:stations:podcasts:new-art'),
    'stationUrl' => $router->fromHere('stations:index:index', [$stationId]),
    'locale' => substr($customization->getLocale(), 0, 2),
    'stationTimeZone' => $stationTz,
    'languageOptions' => $languageOptions,
    'categoriesOptions' => $categoriesOptions,
];

/** @var \App\Assets $assets */
$assets->addVueRender('Vue_StationsPodcasts', '#station-podcasts', $props);
?>

<div id="station-podcasts"></div>
