---
- name: Sanity checks
  import_tasks: _checks.yml

- name: Common tasks
  import_tasks: _common.yml

- name: Load distro-specific vars
  include_vars: "{{ _current_distribution_vars }}"
  with_first_found:
    - skip: true
      files:
        - "{{ ansible_distribution | lower }}_{{ ansible_distribution_major_version }}_{{ ansible_architecture | lower }}.yml"
        - "{{ ansible_distribution | lower }}_{{ ansible_architecture | lower }}.yml"
        - "{{ ansible_distribution | lower }}_{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_distribution | lower }}.yml"
        - "{{ ansible_os_family | lower }}.yml"
  loop_control:
    loop_var: _current_distribution_vars

- name: Execute distro-specific tasks
  include_tasks: "{{ _current_detected_env }}"
  with_first_found:
    - skip: true
      files:
        - "{{ ansible_distribution | lower }}_{{ ansible_distribution_major_version }}_{{ ansible_architecture | lower }}/main.yml"
        - "{{ ansible_distribution | lower }}_{{ ansible_architecture | lower }}/main.yml"
        - "{{ ansible_distribution | lower }}_{{ ansible_distribution_major_version }}/main.yml"
        - "{{ ansible_distribution | lower }}/main.yml"
        - "{{ ansible_os_family | lower }}/main.yml"
  loop_control:
    loop_var: _current_detected_env

- name: Flush before leaving
  meta: flush_handlers
