<?php
$title = 'Shows Directory';
$this->assets->collection('custom_css')->addCss('vendor/world-flags-sprite/stylesheets/flags16.css');
?>

<ul class="autoselect nav nav-pills" rel="<?=$sort ?>">
    <li rel="alpha"><a href="<?=$this->viewHelper->routeFromHere(array('sort' => 'alpha')) ?>">Sort A-Z</a></li>
    <li rel="latest"><a href="<?=$this->viewHelper->routeFromHere(array('sort' => 'latest')) ?>">Sort by Latest Episode</a></li>
</ul>
<br>

<?=$this->viewHelper->renderCommon('podcast', array('podcasts' => $podcasts)) ?>