<?php
$this->headTitle('Shows Directory');

$this->headLink()
    ->appendStylesheet(\DF\Url::content('vendor/world-flags-sprite/stylesheets/flags16.css'));

$cols = \DF\Utilities::columns($this->podcasts, 2);
?>

<div class="row-fluid">
<? foreach($cols as $col): ?>
    <div class="span6">
        <?
        $this->podcasts = $col;
        echo $this->renderCommon('podcast');
        ?>
    </div>
<? endforeach; ?>
</div>