<?php
$title = $podcast->name;
$hide_title = true;
?>

<div class="pg_show_detail">
    <div class="breadcrumb">
        <a href="<?=$this->viewHelper->routeFromHere(array('action' => 'index', 'id' => NULL)) ?>">&laquo; Back to Shows Directory</a>
    </div>

    <div class="clearfix">
        <img class="avatar pull-left" src="<?=\DF\Url::content($podcast->image_url) ?>">
        <div class="buttons pull-right">
            <?=$this->viewHelper->button(array(
                'type'      => 'link',
                'icon'      => 'icon-rss',
                'href'      => $this->viewHelper->routeFromHere(array('action' => 'feed', 'type' => 'single')),
                'text'      => 'Episode RSS Feed',
                'target'    => '_blank',
            )) ?>
        </div>

        <h2><?=$podcast->name ?></h2>

        <? if ($podcast_airs_on): ?>
            <p><i class="icon-volume-up"></i> <?=$podcast_airs_on ?></p>
        <? endif; ?>

        <blockquote>
            <p><?=nl2br($podcast->description) ?></p>
        </blockquote>

        <div class="social">
        <? foreach($social_types as $social_type => $social_info): ?>
            <? if (!empty($podcast[$social_type])): ?>
                <a href="<?=$podcast[$social_type] ?>" target="_blank"><img src="<?=\DF\Url::content('social/'.$social_info['icon'].'.png') ?>" alt="<?=$social_info['name'] ?>"></a>
            <? endif; ?>
        <? endforeach; ?>
        </div>
    </div>

    <br>
    <h3>All Episodes (<?=count($episodes) ?>)</h3>

    <table class="episode_list datatable table-striped table-bordered">
        <colgroup>
            <col width="20%">
            <col width="15%">
            <col width="65%">
        </colgroup>
        <thead>
            <tr>
                <th>&nbsp;</th>
                <th>Date/Time</th>
                <th>Episode</th>
            </tr>
        </thead>
        <tbody>
        <? foreach($episodes as $ep): ?>
            <tr class="input">
                <td class="center">
                    <?=$this->viewHelper->button(array(
                        'type'      => 'small',
                        'icon'      => 'icon-cloud-download',
                        'class'     => 'btn-primary',
                        'href'      => $this->viewHelper->routeFromHere(array('action' => 'episode', 'episode' => $ep['id'])),
                        'target'    => '_blank',
                        'text'      => 'View Episode',
                    )) ?>
                </td>
                <td class="center">
                    <?=date('M j, Y', $ep['timestamp']) ?><br><?=date('g:ia', $ep['timestamp']) ?>
                </td>
                <td>
                    <big><b><a href="<?=$this->viewHelper->routeFromHere(array('action' => 'episode', 'episode' => $ep['id'])) ?>" target="_blank"><?=$ep['title'] ?></a></b></big>
                <? if ($ep['body']): ?>
                    <p><?=\DF\Utilities::truncateText(strip_tags($ep['body']), 200) ?></p>
                <? endif; ?>
                </td>
            </tr>
        <? endforeach; ?>
        </tbody>
    </table>
</div>