<?php
$title = $podcast->name;
$hide_title = true;

$this->assets->collection('custom_js')
    ->addJs('js/podcasts.js');
?>

<div class="pg_show_detail">
    <div class="breadcrumb">
        <a href="<?=$this->url->get('') ?>">Ponyville Live!</a> /
        <a href="<?=$this->url->get('shows') ?>">Shows</a> /
    </div>

    <div class="clearfix">
        <img class="avatar pull-left" src="<?=\PVL\Url::upload($podcast->image_url) ?>">
        <div class="buttons pull-right">
            <?=$this->viewHelper->button(array(
                'type'      => 'link',
                'icon'      => 'icon-rss',
                'href'      => $this->viewHelper->routeFromHere(array('action' => 'feed', 'type' => 'single')),
                'text'      => 'Episode RSS Feed',
                'target'    => '_blank',
            )) ?>
        </div>

        <h2><?=$podcast->name ?></h2>

        <? if ($podcast_airs_on): ?>
            <p><i class="icon-volume-up"></i> <?=$podcast_airs_on ?></p>
        <? endif; ?>

        <blockquote>
            <p><?=nl2br($podcast->description) ?></p>
        </blockquote>

        <div class="social">
        <? foreach($social_types as $social_type => $social_info): ?>
            <? if (!empty($podcast[$social_type])): ?>
                <a href="<?=($social_type == 'contact_email' ? 'mailto:' : '').$podcast[$social_type] ?>" target="_blank"><img src="<?=\DF\Url::content('social/'.$social_info['icon'].'.png') ?>" alt="<?=$social_info['name'] ?>"></a>
            <? endif; ?>
        <? endforeach; ?>
        </div>
    </div>
    <br>

    <? if ($podcast->is_adult): ?>
        <div class="alert alert-danger">
            <b>Warning: Contains Adult Content</b> -- Episodes of this podcast may contain adult material, and are suitable only for people aged 18 and above.
        </div>
    <? endif; ?>

    <h3>All Episodes (<?=count($pager) ?>)</h3>

    <?=$this->viewHelper->paginate($pager) ?>

    <table class="episode_list datatable table-striped table-bordered">
        <colgroup>
            <col width="20%">
            <col width="80%">
        </colgroup>
        <tbody>
        <? foreach($pager as $ep): ?>
            <tr class="input">
                <td class="center">
                    <a class="thumbnail podcast-episode" href="<?=$ep->getPlayerUrl() ?>" data-log="<?=$ep->getLocalUrl('pvlive') ?>">
                        <img src="<?=$ep->getThumbnail() ?>" alt="Thumbnail">
                    </a>
                </td>
                <td>
                    <?=date('M j, Y', $ep['timestamp']) ?> at <?=date('g:ia', $ep['timestamp']) ?><br>
                    <big><b><a class="podcast-episode" href="<?=$ep->getPlayerUrl() ?>" data-log="<?=$ep->getLocalUrl('pvlive') ?>"><?=$ep['title'] ?></a></b></big>
                <? if ($ep['summary']): ?>
                    <p><?=$ep['summary'] ?></p>
                <? endif; ?>
                </td>
            </tr>
        <? endforeach; ?>
        </tbody>
    </table>

    <?=$this->viewHelper->paginate($pager) ?>
</div>