<?php
$this->headTitle('Desktop & Mobile Apps');

$this->layout()->hide_title = true;
$this->layout()->manual = true;
?>

<div class="row-fluid">
	<div class="span6">
		<h1 class="title">Desktop Apps</h1>

		<h2>Google Chrome (HoofSounds)</h2>
		<div class="well">
			<div class="buttons">
				<?=$this->button(array(
					'type'		=> 'link',
					'class'		=> 'btn-primary',
					'icon'		=> 'icon-globe',
					'href'		=> 'http://hoofsounds.little.my/',
					'target'	=> '_blank',
					'text'		=> 'HoofSounds Homepage',
				)) ?>
			</div>

			<div>
				<img src="<?=\DF\Url::content('images/app_hoofsounds_1.jpg') ?>" style="width: 50%;" alt="">
			</div>

			<p>Ponyville Live! has partnered with the PonyHoof development team and Celestia Radio to launch a new Chrome plugin that lets you listen to pony music right from your Chrome browser. Visit the link above to learn more and install it!</p>
		</div>

		<h2>Winamp, iTunes, VLC, etc.</h2>
		<div class="well">
			<div class="buttons">
				<?=$this->button(array(
					'type'		=> 'link',
					'class'		=> 'btn-primary',
					'icon'		=> 'icon-download',
					'href'		=> $this->routeFromHere(array('controller' => 'station', 'action' => 'playlist', 'format' => 'pls')),
					'target'	=> '_blank',
					'text'		=> 'Download PLS (VLC, etc)',
				)) ?>
			</div>
			<p>Download playlist files containing all of the Ponyville Live! radio stations.</p>
		</div>
	</div>
	<div class="span6">
		<h1 class="title">Mobile Apps</h1>

		<h2>PVL! Mobile</h2>
		<div class="well">
			<div class="buttons">
				<?=$this->button(array(
					'type'		=> 'link',
					'class'		=> 'primary btn-tune-in',
					'icon'		=> 'icon-globe',
					'href'		=> 'http://m.pvlive.me',
					'text'		=> 'PVL! Mobile',
				)) ?>
			</div>

			<a href="https://play.google.com/store/apps/details?id=com.ponyvillelive.pvlmobile">
			  <img alt="Get it on Google Play"
			       src="https://developer.android.com/images/brand/en_generic_rgb_wo_60.png" />
			</a>

			<div>
				<img src="<?=\DF\Url::content('images/mobile1.png') ?>" style="width: 30%;" alt="">
				<img src="<?=\DF\Url::content('images/mobile2.png') ?>" style="width: 30%;" alt="">
			</div>

			<p>The new PVL! Mobile web application lets you enjoy awesome pony radio, video stations, podcasts and more, anywhere you go. The mobile site is compatible with all modern smartphones, and can be bookmarked or pinned to your home screen for even easier access.</p>
		</div>

		<h2><i class="icon-android"></i> Android</h2>
		<div class="well">
			<div class="buttons">
				<?=$this->button(array(
					'type'		=> 'link',
					'class'		=> 'btn-primary',
					'icon'		=> 'icon-download',
					'href'		=> 'http://ponyvillelive.com/resources/PonyvilleLive.apk',
					'target'	=> '_blank',
					'text'		=> 'Download PVL! Mobile for Android (Beta)',
				)) ?>
			</div>

			<p>Try out the new beta app for PVL! Mobile on your Android smartphone.</p>
		</div>

		<h2><i class="icon-windows"></i> Windows Phone 8 and Windows 8</h2>
		<div class="well">
			<div class="buttons">
				<?=$this->button(array(
					'type'		=> 'link',
					'class'		=> 'btn-primary',
					'icon'		=> 'icon-download',
					'href'		=> 'http://mlp.reignofcomputer.com/Portal8/',
					'target'	=> '_blank',
					'text'		=> 'MLP Portal (Windows 8)',
				)) ?>
				<?=$this->button(array(
					'type'		=> 'link',
					'class'		=> 'btn-primary',
					'icon'		=> 'icon-download',
					'href'		=> 'http://mlp.reignofcomputer.com/mlpp/',
					'target'	=> '_blank',
					'text'		=> 'MLP Portal (Windows Phone 8)',
				)) ?>
			</div>
			<p>All of Ponyville Live's stations are listed on the MLP Portal application for Windows Phone 8 and Windows 8 desktops. From the app, you can listen to our stations live, view what's playing, and visit the web sites and social media outlets for the stations.</p>
		</div>
	</div>
</div>