<?php
/**
 * @var \App\Assets $assets
 * @var \App\Http\RouterInterface $router
 */

$this->layout(
    'main',
    [
        'title' => __('Custom Branding'),
        'manual' => true,
    ]
);

$props = [
    'settingsApiUrl' => (string)$router->named('api:admin:settings'),
    'browserIconApiUrl' => (string)$router->named('api:admin:custom_assets', [
        'type' => App\Assets\AssetFactory::TYPE_BROWSER_ICON,
    ]),
    'backgroundApiUrl' => (string)$router->named('api:admin:custom_assets', [
        'type' => App\Assets\AssetFactory::TYPE_BACKGROUND,
    ]),
    'albumArtApiUrl' => (string)$router->named('api:admin:custom_assets', [
        'type' => App\Assets\AssetFactory::TYPE_ALBUM_ART,
    ]),
];

$assets->addVueRender('Vue_AdminBranding', '#admin-branding', $props);
?>
<div id="admin-branding"></div>
