---
  - name: Make update script executable again
    file: path="{{ www_base }}/update.sh" state=touch mode="a+x"

  - name: Install Composer Dependencies (Development)
    become: true
    shell: composer install
    args:
      chdir: "{{ www_base }}"
    when: app_env == "development"

  - name: Install Composer Dependencies (Production)
    become: true
    shell: composer install --no-dev
    args:
      chdir: "{{ www_base }}"
    when: app_env == "production"

  - name: Update configuration from legacy
    become: true
    become_user: azuracast
    shell: php {{ util_base }}/cli.php azuracast:config:migrate

  - name: Clear AzuraCast Cache
    become: true
    become_user: azuracast
    shell: php {{ util_base }}/cli.php cache:clear

  - name: Update Database
    become: true
    become_user: azuracast
    shell: php {{ util_base }}/cli.php migrations:migrate --no-interaction --allow-no-migration

  - name: Regenerate Doctrine Proxies
    become: true
    become_user: azuracast
    shell: php {{ util_base }}/cli.php orm:generate-proxies

  - name: Restart Radio Stations
    become: true
    become_user: azuracast
    shell: php {{ util_base }}/cli.php azuracast:radio:restart

