<?php $this->layout('main', ['title' => __('Report Not Available'), 'manual' => true]) ?>

<div class="card">
    <div class="card-header ch-alt">
        <h2><?=__('Report Not Available') ?></h2>
    </div>

    <div class="card-body card-padding">
        <p><?=__('This report is not available for this station, because the system administrator has chosen not to collect detailed IP-based listener information.') ?></p>
    </div>
</div>
