<?php
$this->layout('main', [
    'title' => __('Add Web Hook')
]);
?>

<h3 class="mb-4"><?=__('Select the type of web hook to create.') ?></h3>

<dl>
<?php foreach($connectors as $type => $info): ?>
    <dt class="mb-2"><a href="<?=$router->fromHere(null, ['type' => $type]) ?>" class="btn btn-primary"><?=$info['name'] ?></a></dt>
    <dd class="pb-3"><?=$info['description'] ?></dd>
<?php endforeach; ?>
</dl>
