<?php $this->layout('main', ['title' => __('Web Hooks'), 'manual' => true]) ?>

<div class="card">
    <div class="card-header bg-primary-dark">
        <h2 class="card-title"><?=__('Web Hooks')?></h2>
    </div>
    <div class="card-body alert-info d-flex align-items-center" role="alert">
        <div class="flex-shrink-0 mr-2">
            <i class="material-icons" aria-hidden="true">info</i>
        </div>
        <div class="flex-fill">
            <p class="card-text">
                <?=__('')?>
            </p>
        </div>
    </div>
    <div class="card-actions">
        <a class="btn btn-outline-primary" role="button" href="<?=$router->fromHere('stations:webhooks:add')?>">
            <i class="material-icons" aria-hidden="true">add</i>
            <?=__('Add Web Hook')?>
        </a>
    </div>
    <table class="table table-responsive-md table-striped mb-0">
        <colgroup>
            <col width="30%">
            <col width="35%">
            <col width="35%">
        </colgroup>
        <thead>
        <tr>
            <th><?=__('Actions')?></th>
            <th><?=__('Name')?> / <?=__('Type')?></th>
            <th><?=__('Triggers')?></th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($webhooks as $row): ?>
            <?php /** @var \App\Entity\StationWebhook $row */ ?>
            <tr class="align-middle">

            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>
