<?php
$this->placeholder('content_top')->captureStart();
?>
<div id="secondary_header_stripe">
	<a href="<?=$this->route(array('module' => 'mlpma')) ?>" class="ajax"><img src="<?=\DF\Url::content('mlpma/mlpma_logo.png') ?>" alt="The MLP Music Archive, a Ponyville Live! Project"></a>
</div>
<?
$this->placeholder('content_top')->captureEnd();

$this->custom_styles = array(
	\DF\Url::content('mlpma/style.css'),
	\DF\Url::content('fap/css/jquery.fullwidthAudioPlayer.css'),
	\DF\Url::content('fap/css/jquery.fullwidthAudioPlayer-responsive.css'),
);

$this->custom_scripts = array(
	\DF\Url::content('mlpma/jquery.scrollto.min.js'),
	\DF\Url::content('mlpma/jquery.history.min.js'),
	\DF\Url::content('mlpma/jquery.ajaxify.js'),
	\DF\Url::content('fap/js/jquery-ui.js'),
	\DF\Url::content('fap/js/soundmanager2-nodebug-jsmin.js'),
	'//connect.soundcloud.com/sdk.js',
	\DF\Url::content('fap/js/jquery.fullwidthAudioPlayer.js'),
	\DF\Url::content('fap/js/amplify.min.js'),
	\DF\Url::content('mlpma/custom.js'),
);

$this->layout()->manual = true;
$this->layout()->content = '
<div class="row-fluid">
	<div class="span3">'.$this->renderCommon('mlpma').'</div>
	<div class="span9">'.$this->layout()->content.'</div>
</div>
';

include('default.phtml');
?>