<?php $this->layout('main', ['title' => _('Dashboard'), 'manual' => true]); ?>

<?php $this->start('custom_js') ?>
<script type="text/javascript" src="//code.highcharts.com/highcharts.js"></script>
<script type="text/javascript" src="//code.highcharts.com/highcharts-more.js"></script>
<script type="text/javascript" src="//code.highcharts.com/modules/exporting.js"></script>

<?php if ($customization->getTheme() == 'dark'): ?>
<script type="text/javascript" src="<?=$url->content('js/highcharts/dark-blue.js') ?>"></script>
<?php endif; ?>

<script type="text/javascript" src="<?=$url->content('vendors/bower_components/store-js/store.min.js') ?>"></script>
<script type="text/javascript" src="<?=$assets->getPath('js/radio.js') ?>"></script>
<script type="text/javascript" src="<?=$assets->getPath('js/nchan.js') ?>"></script>
<?php $this->stop('custom_js') ?>

<div class="block-header">
    <h2><?=_('Dashboard') ?></h2>
</div>

<div class="row">
    <div class="col-sm-6">
        <div class="card">
            <div class="card-header ch-alt">
                <h2><?=_('Listeners Across All Stations') ?></h2>
            </div>
            <div class="card-body card-padding-sm">
                <div id="network_chart" style="height: 250px;"></div>
            </div>
        </div>
    </div>
    <div class="col-sm-6">
        <div class="card">
            <div class="card-header ch-alt">
                <h2><?=_('Listeners Per Station') ?></h2>
            </div>
            <div class="card-body card-padding-sm">
                <div id="station_chart" style="height: 250px;"></div>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-sm-12">
        <div class="card">
            <div class="card-header ch-alt">
                <h2><?=_('Station Overview') ?></h2>

                <ul class="actions">
                <?php if ($acl->isAllowed('administer stations')): ?>
                    <li><a class="" title="<?=_('Add') ?>" href="<?=$url->route(['module' => 'admin', 'controller' => 'stations', 'action' => 'edit']) ?>"><i class="zmdi zmdi-plus"></i></a></li>
                <?php endif; ?>
                </ul>
            </div>
            <div class="table-responsive">
                <table class="table table-striped">
                    <colgroup>
                        <col width="5%">
                        <col width="30%">
                        <col width="10%">
                        <col width="40%">
                        <col width="15%">
                    </colgroup>
                    <thead>
                        <tr>
                            <th>&nbsp;</th>
                            <th><?=_('Station Name') ?></th>
                            <th class="text-center"><?=_('Listeners') ?></th>
                            <th><?=_('Now Playing') ?></th>
                            <th><?=_('Options') ?></th>
                        </tr>
                    </thead>
                    <tbody>
                    <?php foreach($stations as $row): ?>
                        <tr class="input" id="station_<?=$row['station']->getId() ?>">
                            <td class="text-center">
                                <a class="btn-audio" href="#" data-url="<?=$this->e($row['stream_url']) ?>">
                                    <i class="zmdi zmdi-play"></i>
                                </a>
                            </td>
                            <td>
                                <big><a href="<?=$url->route(['controller' => 'public', 'station' => $row['short_name']]) ?>" target="_blank"><?=$this->e($row['station']->getName()) ?></a></big>
                            </td>
                            <td class="text-center">
                                <span class="nowplaying-listeners">0</span>
                            </td>
                            <td>
                                <strong><span class="nowplaying-title"><?=_('Song Title') ?></span></strong><br>
                                <span class="nowplaying-artist"><?=_('Song Artist') ?></span>
                            </td>
                            <td>
                                <a class="btn btn-primary" href="<?=$url->route(['module' => 'stations', 'station' => $row['station']->getId()]) ?>"><?=_('Manage') ?></a>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
$(function () {
    Highcharts.setOptions({
        global: {
            timezoneOffset: <?=\App\Timezone::getOffsetMinutes() ?>,
            useUTC: false
        }
    });

    var datetime_axis = {
        type: 'datetime',
        labels: {
            formatter: function () {
                return Highcharts.dateFormat('%a %d %b', this.value);
            },
            dateTimeLabelFormats: {
                minute: '%H:%M',
                hour: '%H:%M',
                day: '%e. %b',
                week: '%e. %b',
                month: '%b \'%y',
                year: '%Y'
            }
        }
    };

    $('#network_chart').highcharts({
        chart: { zoomType: 'x' },
        title: {text: ''},
        xAxis: datetime_axis,
        plotOptions: {
            spline: {
                marker: { enabled: false }
            }
        },
        yAxis: {
            title: {
                text: <?=$this->escapeJs(_('Listeners')) ?>
            },
            min: 0
        },
        tooltip: {
            crosshairs: true,
            shared: true,
            xDateFormat: '%Y-%m-%d'
        },
        colors: [
            '#AEE1FF',
            '#0091E5',
            '#FFA6A6',
            '#8C0000'
        ],

        series: <?=$metrics['network'] ?>
    });

    $('#station_chart').highcharts({
        chart: { zoomType: 'x' },
        title: {text: ''},
        xAxis: datetime_axis,
        plotOptions: {
            spline: {
                lineWidth: 1,
                marker: { enabled: false },
                shadow: false,
                states: {
                    hover: {
                        lineWidth: 3
                    }
                },
                threshold: null
            }
        },
        yAxis: {
            title: {
                text: <?=$this->escapeJs(_('Listeners')) ?>
            },
            min: 0
        },
        tooltip: {
            crosshairs: true,
            xDateFormat: '%Y-%m-%d'
        },

        series: <?=$metrics['station'] ?>
    });
});

$(function() {
    var sub = new NchanSubscriber('/api/live/nowplaying', {subscriber: ['eventsource', 'longpoll']});

    sub.on("message", function(message, message_metadata) {
        var data = JSON.parse(message);

        $.each(data, function (i, row) {
            var station_row = $('#station_' + row.station.id);

            if (station_row.length) {

                if (station_row.find('.btn-audio').hasClass('playing') && 'mediaSession' in navigator) {
                    navigator.mediaSession.metadata = new MediaMetadata({
                        title: row.now_playing.song.title,
                        artist: row.now_playing.song.artist
                    });
                }

                station_row.find('.nowplaying-title').text(row.now_playing.song.title);
                station_row.find('.nowplaying-artist').text(row.now_playing.song.artist);
                station_row.find('.nowplaying-listeners').text(row.listeners.total)
            }
        });
    });

    sub.start();
});
</script>