<?php
$title = 'Podcast Profile';

echo $this->viewHelper->renderHere('header', true, array('title' => $title));
?>

<div class="buttons">
    <?=$this->viewHelper->button(array(
        'type'      => 'link',
        'class'     => 'large',
        'href'      => $this->viewHelper->routeFromHere(array('action' => 'edit')),
        'icon'      => 'icon-pencil',
        'text'      => 'Edit Profile',
    )) ?>
</div>

<?=$form->renderView() ?>