<?php $this->layout('main', ['title' => _('Custom Branding')]); ?>

<?php
/** @var \AzuraCast\Assets $assets */
$assets
    ->load('codemirror_css');
?>

<script type="text/javascript">
    $(function() {

        $('textarea.css-editor').each(function() {
            CodeMirror.fromTextArea($(this)[0], {
                lineNumbers: true,
                theme: '<?=(($customization->getTheme() === 'light') ? 'default' : 'material') ?>'
            });
        });

    });
</script>

<?=$this->fetch('partials/form') ?>