<?php
$this->layout('minimal', [
    'page_class' => 'dj station-'.$station->getShortName(),
    'title' => $this->e($station->getName()),
    'hide_footer' => true
]);

/** @var \Azura\Assets $assets */
$assets
    ->load('webcaster')
?>

<div class="container">
    <div class="row">
        <div class="col-2 settings">
            <div class="card">
                <form>
                    <fieldset>
                        <legend>Setup</legend>
                        <div class="control-group">
                            <div class="controls">
                                <button class="btn btn-primary start-stream">Start streaming</button>
                                <button class="btn btn-danger stop-stream" style="display: none;">Stop streaming</button>
                                <button class="btn btn-info passThrough">CUE</button>
                            </div>
                        </div>
                        <ul class="nav nav-tabs">
                            <li class="active">
                                <a href="#settings" data-toggle="tab">Settings</a>
                            </li>
                            <li>
                                <a href="#metadata" data-toggle="tab">Metadata</a>
                            </li>
                        </ul>
                        <div class="tab-content">
                            <div class="tab-pane active" id="settings">
                                <div class="control-group">
                                    <label>Encoder</label>
                                    <div class="controls">
                                        <label class="radio inline">
                                            <input type="radio" name="encoder" value="mp3" class="encoder" checked>MP3
                                        </label>
                                        <label class="radio inline">
                                            <input type="radio" name="encoder" value="raw" class="encoder">Raw
                                        </label>
                                    </div>
                                </div>
                                <div class="control-group">
                                    <label>Samplerate</label>
                                    <div class="controls">
                                        <select class="samplerate"></select>
                                    </div>
                                    <label>Bitrate</label>
                                    <div class="controls">
                                        <select class="bitrate"></select>
                                    </div>
                                    <label>Channels</label>
                                    <div class="controls">
                                        <label class="radio inline">
                                            <input type="radio" name="channels" value="2" class="channels" checked>Stereo
                                        </label>
                                        <label class="radio inline">
                                            <input type="radio" name="channels" value="1" class="channels">Mono
                                        </label>
                                    </div>
                                </div>
                                <div class="control-group">
                                    <label>Stream destination URI</label>
                                    <div class="controls">
                                        <input class="uri" type="text" size="40" value="ws://source:hackme@localhost:8080/mount">
                                        <label class="checkbox">
                                            <input type="checkbox" class="asynchronous" checked> Use asynchronous worker
                                        </label>
                                    </div>
                                </div>
                            </div>
                            <div class="tab-pane" id="metadata">
                                <div class="alert metadata-updated" style="display: none;">
                                    Metadata updated!
                                </div>
                                <div class="control-group">
                                    <div class="controls">
                                        <label>Title:</label>
                                        <input class="manual-metadata title" type="text" disabled/>
                                        <label>Artist:</label>
                                        <input class="manual-metadata artist" type="text" disabled/>
                                    </div>
                                    <div class="controls">
                                        <button class="btn btn-primary update-metadata" disabled>Update Metadata</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </fieldset>
                </form>
            </div>
        </div>
        <div class="span9">
            <div class="hero-unit">
                <h1>Webcaster Client</h1>
            </div>
        </div>
        <div class="span3 playlist-left well">
            <div class="volume-slider"></div>
            <h3 class="playlist-label">Playlist 1</h3>
            <form>
                <fieldset>
                    <div class="control-group" align="center">
                        <div class="controls">
                            <button class="btn btn-success play-audio player-control"><i class="icon-play"></i></button>
                            <button class="btn btn-warning pause-audio player-control" style="display: none;"><i class="icon-pause"></i></button>
                            <button class="btn previous player-control"><i class="icon-fast-backward"></i></button>
                            <button class="btn next player-control"><i class="icon-fast-forward"></i></button>
                            <button class="btn btn-danger stop player-control"><i class="icon-stop"></i></button>
                            <button class="btn btn-info passThrough">CUE</button>
                        </div>
                    </div>
                </fieldset>
            </form>
            <div class="progress progress-success progress-volume">
                <div class="progress-seek"></div>
                <span class="track-position-text"></span>
                <div class="bar track-position"></div>
            </div>
            <div class="progress progress-left">
                <div class="bar volume-left volume-bar" style="width: 0%"></div>
            </div>
            <div class="progress progress-right">
                <div class="bar volume-right" style="width: 0%"></div>
            </div>
            <div class="playlist">
                <div class="playlist-table" style="display: none;">
                    <table class="files-table table table-striped table-bordered table-hover table-condensed">
                        <tr><th></th><th>Title</th><th>Artist</th><th>Duration</th></tr>
                    </table>
                </div>
                <div class="playlist-input">
                    Add files to playlist:
                    <input type="file" class="files" accept="audio/*" multiple="multiple">
                </div>
            </div>
            <form>
                <fieldset>
                    <div class="control-group">
                        <div class="controls">
                            <label class="checkbox">
                                <input type="checkbox" class="playThrough" checked> Play Through
                            </label>
                        </div>
                        <div class="controls">
                            <label class="checkbox">
                                <input type="checkbox" class="loop"> Repeat playlist
                            </label>
                        </div>
                    </div>
                </fieldset>
            </form>
        </div>
        <div class="span3">
            <div class="mixer well">
                <h2 class="mixer-label">Mixer</h2>
                <div class="slider"></div>
            </div>
            <div class="microphone well">
                <div class="microphone-slider"></div>
                <h3 class="microphone-label">Microphone</h3>
                <form>
                    <fieldset>
                        <div class="control-group" align="center">
                            <div class="controls">
                                <button class="btn btn-danger record-audio player-control"><i class="icon-facetime-video"></i></button>
                                <button class="btn btn-info passThrough">CUE</button>
                            </div>
                        </div>
                    </fieldset>
                    <div class="progress progress-left">
                        <div class="bar volume-left" style="width: 0%"></div>
                    </div>
                    <div class="progress progress-right">
                        <div class="bar volume-right" style="width: 0%"></div>
                    </div>
                    <fieldset>
                        <div class="control-group microphone-entry" align="center" style="display: none;">
                            <label>Microphone source</label>
                            <div class="controls">
                                <select></select>
                            </div>
                        </div>
                    </fieldset>
                </form>
            </div>
        </div>
        <div class="span3 playlist-right well">
            <div class="volume-slider"></div>
            <h3 class="playlist-label">Playlist 2</h3>
            <form>
                <fieldset>
                    <div class="control-group" align="center">
                        <div class="controls">
                            <button class="btn btn-success play-audio player-control"><i class="icon-play"></i></button>
                            <button class="btn btn-warning pause-audio player-control" style="display: none;"><i class="icon-pause"></i></button>
                            <button class="btn previous player-control"><i class="icon-fast-backward"></i></button>
                            <button class="btn next player-control"><i class="icon-fast-forward"></i></button>
                            <button class="btn btn-danger stop player-control"><i class="icon-stop"></i></button>
                            <button class="btn btn-info passThrough">CUE</button>
                        </div>
                    </div>
                </fieldset>
            </form>
            <div class="progress progress-success progress-volume">
                <div class="progress-seek"></div>
                <span class="track-position-text"></span>
                <div class="bar track-position"></div>
            </div>
            <div class="progress progress-left">
                <div class="bar volume-left" style="width: 0%"></div>
            </div>
            <div class="progress progress-right">
                <div class="bar volume-right" style="width: 0%"></div>
            </div>
            <div class="playlist">
                <div class="playlist-table" style="display: none;">
                    <table class="files-table table table-striped table-bordered table-hover table-condensed">
                        <tr><th></th><th>Title</th><th>Artist</th><th>Duration</th></tr>
                    </table>
                </div>
                <div class="playlist-input">
                    Add files to playlist:
                    <input type="file" class="files" accept="audio/*" multiple="multiple">
                </div>
            </div>
            <form>
                <fieldset>
                    <div class="control-group">
                        <div class="controls">
                            <label class="checkbox">
                                <input type="checkbox" class="playThrough" checked> Play Through
                            </label>
                        </div>
                        <div class="controls">
                            <label class="checkbox">
                                <input type="checkbox" class="loop"> Repeat playlist
                            </label>
                        </div>
                    </div>
                </fieldset>
            </form>
        </div>
    </div>
</div>
