<?php
$this->layout('minimal', [
    'page_class' => 'dj has-sidebar station-'.$station->getShortName(),
    'title' => $this->e($station->getName()),
    'hide_footer' => true
]);

/** @var \Azura\Assets $assets */
$assets
    ->load('webcaster')
    ->addInlineJs($this->fetch('frontend/public/dj.js', ['station' => $station]));
?>
<section id="content" role="main" style="height: 100vh; display: flex; align-items: center; justify-content: center;">
    <div class="container">
        <div class="row">
            <!-- Settings/Metadata Column -->
            <div class="col-md-4 mb-sm-4">
                <div class="card settings">
                    <div class="card-header">
                        <h5><?=$this->e($station->getName()) ?></h5>
                        <ul class="nav nav-tabs card-header-tabs mt-0">
                            <li class="nav-item ml-1">
                                <a class="nav-link active" href="#settings" data-toggle="tab"><?=__('Settings') ?></a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#metadata" data-toggle="tab"><?=__('Metadata') ?></a>
                            </li>
                        </ul>
                    </div>
                    <div class="card-body">
                        <form class="form">
                            <div class="tab-content">
                                <div class="tab-pane active" id="settings">
                                    <div class="form-group">
                                        <label><?=__('Encoder') ?></label>
                                        <div class="controls">
                                            <div class="custom-control custom-radio custom-control-inline">
                                                <input id="encoder_mp3" type="radio" name="encoder" value="mp3" class="encoder custom-control-input" checked="checked">
                                                <label for="encoder_mp3" class="custom-control-label"><?=__('MP3') ?></label>
                                            </div>
                                            <div class="custom-control custom-radio custom-control-inline">
                                                <input id="encoder_raw" type="radio" name="encoder" value="raw" class="encoder custom-control-input">
                                                <label for="encoder_raw" class="custom-control-label"><?=__('Raw') ?></label>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label for="select_samplerate"><?=__('Sample Rate (kHz)') ?></label>
                                        <div class="controls">
                                            <select id="select_samplerate" class="form-control samplerate"></select>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label for="select_bitrate"><?=__('Bit Rate (kbps)') ?></label>
                                        <div class="controls">
                                            <select id="select_bitrate" class="form-control bitrate"></select>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label><?=__('Channels') ?></label>
                                        <div class="controls">
                                            <div class="custom-control custom-radio custom-control-inline">
                                                <input id="channels_2" type="radio" name="channels" value="2" class="custom-control-input channels" checked="checked">
                                                <label for="channels_2" class="custom-control-label"><?=__('Stereo') ?></label>
                                            </div>
                                            <div class="custom-control custom-radio custom-control-inline">
                                                <input id="channels_1" type="radio" name="channels" value="1" class="custom-control-input channels">
                                                <label for="channels_1" class="custom-control-label"><?=__('Mono') ?></label>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label><?=__('DJ Credentials') ?></label>

                                        <div class="row">
                                            <div class="col-6">
                                                <input type="text" name="dj_username" class="form-control dj_username" placeholder="<?=__('Username') ?>">
                                            </div>
                                            <div class="col-6">
                                                <input type="text" name="dj_password" class="form-control dj_password" placeholder="<?=__('Password') ?>">
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-group mb-0">
                                        <div class="custom-control custom-checkbox">
                                            <input id="use_async_worker" type="checkbox" class="custom-control-input asynchronous" checked="checked">
                                            <label for="use_async_worker" class="custom-control-label"><?=__('Use Asynchronous Worker') ?></label>
                                        </div>
                                    </div>
                                </div>
                                <div class="tab-pane" id="metadata">
                                    <div class="alert metadata-updated" style="display: none;">
                                        <?=__('Metadata updated!') ?>
                                    </div>
                                    <div class="form-group">
                                        <label for="metadata_title"><?=__('Title') ?></label>
                                        <div class="controls">
                                            <input id="metadata_title" class="form-control manual-metadata title" type="text" disabled="disabled">
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label for="metadata_artist"><?=__('Artist') ?></label>
                                        <div class="controls">
                                            <input id="metadata_artist" class="form-control manual-metadata artist" type="text" disabled="disabled">
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <button class="btn btn-primary update-metadata" disabled="disabled"><?=__('Update Metadata') ?></button>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>

                    <div class="card-actions">
                        <button class="btn btn-primary start-stream"><?=__('Start streaming') ?></button>
                        <button class="btn btn-danger stop-stream" style="display: none;"><?=__('Stop streaming') ?></button>
                        <button class="btn btn-info passThrough"><?=__('Cue') ?></button>
                    </div>
                </div>
            </div>
            <!-- End Settings/Metadata Column -->

            <!-- Playlist Row -->
            <div class="col-md-8">
                <div class="row mb-4">
                    <!-- Playlist 1 -->
                    <div class="col-md-6 mb-sm-4">
                        <div class="card playlist-left">
                            <h5 class="card-header">
                                <?=__('Playlist 1') ?>
                                <div class="float-right">
                                    <input type="range" min="0" max="150" value="100" class="custom-range volume-slider">
                                </div>
                            </h5>
                            <div class="card-body">
                                <?=$this->fetch('frontend/public/dj_playlist', ['id' => 'playlist_1']) ?>
                            </div>
                        </div>
                    </div>
                    <!-- End Playlist 1 -->

                    <!-- Playlist 2 -->
                    <div class="col-md-6">
                        <div class="card playlist-right">
                            <h5 class="card-header">
                                <?=__('Playlist 2') ?>
                                <div class="float-right">
                                    <input type="range" min="0" max="150" value="100" class="custom-range volume-slider">
                                </div>
                            </h5>
                            <div class="card-body">
                                <?=$this->fetch('frontend/public/dj_playlist', ['id' => 'playlist_2']) ?>
                            </div>
                        </div>
                    </div>
                    <!-- End Playlist 2 -->
                </div>
                <div class="row">
                    <!-- Mixer -->
                    <div class="col-md-4 mb-sm-4">
                        <div class="mixer card">
                            <h5 class="card-header">
                                <?=__('Mixer') ?>
                            </h5>
                            <div class="card-body">
                                <div class="d-flex flex-row">
                                    <div class="flex-shrink-0 pt-1 pr-2">1</div>
                                    <div class="flex-fill">
                                        <input type="range" min="0" max="100" value="50" class="custom-range slider">
                                    </div>
                                    <div class="flex-shrink-0 pt-1 pl-2">2</div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- End Mixer -->

                    <!-- Microphone -->
                    <div class="col-md-8">
                        <div class="microphone card">
                            <h5 class="card-header">
                                <?=__('Microphone') ?>

                                <div class="float-right">
                                    <input type="range" min="0" max="150" value="100" class="custom-range microphone-slider">
                                </div>
                            </h5>

                            <div class="card-body">


                                <form>
                                    <div class="control-group d-flex justify-content-center mb-3">
                                        <div class="btn-group btn-group-sm">
                                                <button class="btn btn-danger record-audio player-control"><i class="material-icons">mic</i></button>
                                                <button class="btn btn-info passThrough">CUE</button>
                                        </div>
                                    </div>

                                    <div class="progress progress-left">
                                        <div class="bar volume-left" style="width: 0%"></div>
                                    </div>
                                    <div class="progress progress-right">
                                        <div class="bar volume-right" style="width: 0%"></div>
                                    </div>

                                    <div class="form-group microphone-entry">
                                        <label for="select_microphone_source"><?=__('Microphone Source') ?></label>
                                        <div class="controls">
                                            <select id="select_microphone_source" class="form-control"></select>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                    <!-- End Microphone -->
                </div>
            </div>
        </div>
    </div>
</section>
