<?php
/** @var App\Entity\Station $station */

$this->layout('minimal', [
    'page_class' => 'embed station-'.$station->getShortName(),
    'title' => $this->e($station->getName()),
    'hide_footer' => true
]);

/** @var \App\Assets $assets */
$assets
    ->load('vue')
    ->load('radio')
    ->addInlineJs($this->fetch('frontend/public/embed.js', ['station' => $station]));
?>

<div class="stations nowplaying">
    <?=$this->fetch('frontend/public/player_component', [
        'stream_url' => $stream_url,
        'autoplay' => $autoplay
    ]) ?>

    <div id="radio-embedded-controls">
        <div class="progress jp-volume-bar" style="height: 15px;" title="<?=__('Volume') ?>"><div class="jp-volume-bar-value progress-bar" role="progressbar"></div></div>
    </div>
</div>
