<?php
/** @var App\Entity\Station $station */

$this->layout('minimal', [
    'page_class' => 'embed station-'.$station->getShortName(),
    'title' => $this->e($station->getName()),
    'hide_footer' => true
]);

/** @var \App\Assets $assets */
$assets
    ->load('vue')
    ->load('radio')
    ->addInlineJs($this->fetch('frontend/public/embed.js', ['station' => $station]));
?>

<div class="stations nowplaying">
    <?=$this->fetch('frontend/public/player_component', [
        'stream_url' => $stream_url,
        'autoplay' => $autoplay
    ]) ?>

    <div class="flex-row radio-controls-embedded" id="radio-player-controls">
        <div class="flex-shrink-0">
            <a href="javascript:;" class="text-secondary jp-mute" title="<?=__('Mute') ?>">
                <i class="material-icons">volume_mute</i>
            </a>
        </div>
        <div class="flex-fill">
            <input type="range" title="<?=__('Volume') ?>" class="custom-range jp-volume-range" style="height: 10px;" id="jp-volume-range" min="0" max="100" step="1">
        </div>
        <div class="flex-shrink-0">
            <a href="javascript:;" class="text-secondary jp-volume-full" title="<?=__('Full Volume') ?>">
                <i class="material-icons">volume_up</i>
            </a>
        </div>
    </div>
</div>
