<?php
/** @var \App\Entity\Station $station */

$this->layout('minimal', [
    'page_class' => 'station-'.$station->getShortName(),
    'title' => $this->e($station->getName()),
]);

/** @var \App\Assets $assets */
$assets
    ->load('vue')
    ->load('radio')
    ->load('bootgrid')
    ->load('fancybox')
    ->addInlineJs($this->fetch('frontend/public/index.js', ['station' => $station]));
?>

<div class="public-page">
    <div class="card">
        <div class="card-body">
            <div class="radio-controls-standalone" id="radio-player-controls">
                <a href="javascript:;" class="text-secondary jp-mute" title="<?=__('Mute') ?>">
                    <i class="material-icons">volume_mute</i>
                </a>
                <input type="range" title="<?=__('Volume') ?>" class="d-inline-block custom-range jp-volume-range" style="" id="jp-volume-range" min="0" max="100" step="1">
                <a href="javascript:;" class="text-secondary jp-volume-full" title="<?=__('Full Volume') ?>">
                    <i class="material-icons">volume_up</i>
                </a>
            </div>

            <h2 class="card-title"><?=$this->e($station->getName()) ?></h2>

            <div class="stations nowplaying">
                <?=$this->fetch('frontend/public/player_component', ['stream_url' => $stream_url, 'autoplay' => $autoplay]) ?>
            </div>
        </div>

        <div class="card-actions">
            <a class="btn btn-sm btn-outline-primary" href="#modal-history" data-toggle="modal" data-target="#modal-history">
                <i class="material-icons">history</i> <?=__('Song History') ?>
            </a>
            <?php if ($station->getEnableRequests()): ?>
                <a class="btn btn-sm btn-outline-primary" href="#modal-request" data-toggle="modal" data-target="#modal-request">
                    <i class="material-icons">help_outline</i> <?=__('Request Song') ?>
                </a>
            <?php endif; ?>
            <a class="btn btn-sm btn-outline-primary" href="<?=$router->named('public:playlist', ['station' => $station->getShortName(), 'format' => 'pls']) ?>">
                <i class="material-icons">file_download</i> <?=__('Playlist') ?>
            </a>
        </div>
    </div>
</div>

<div class="modal fade" id="modal-history" tabindex="-1" role="dialog" aria-labelledby="modal-history-label">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="modal-history-label"><?=__('Song History') ?></h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            </div>
            <div class="modal-body">
                <ol type="1" id="station-history">
                    <li v-for="row in history">
                        <b>{{ row.song.title }}</b><br>
                        {{ row.song.artist }}
                    </li>
                </ol>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="modal-request" tabindex="-1" role="dialog" aria-labelledby="modal-request-label">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="modal-request-label"><?=__('Request a Song') ?></h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            </div>
            <div class="modal-body">

                <table class="data-table table table-striped" id="requests-table">
                    <thead>
                    <tr>
                        <th data-column-id="song_id" data-identifier="true" data-visible="false" data-visible-in-selection="false">ID</th>
                        <th data-column-id="song_title"><?=__('Title') ?></th>
                        <th data-column-id="song_artist"><?=__('Artist') ?></th>
                        <th data-column-id="song_album" data-visible="false"><?=__('Album') ?></th>
                        <th data-column-id="commands" data-formatter="commands" data-sortable="false"><?=__('Actions') ?></th>
                    </tr>
                    </thead>
                    <tbody></tbody>
                </table>
            </div>
        </div>
    </div>
</div>
