<?php
/** @var \App\Entity\Station $station */

$this->layout('minimal', [
    'page_class' => 'public-page-content station-'.$station->getShortName(),
    'title' => $this->e($station->getName()),
]);

/** @var \App\Assets $assets */
$assets
    ->load('vue')
    ->load('radio')
    ->load('bootgrid')
    ->load('fancybox')
    ->addInlineJs($this->fetch('frontend/public/index.js', ['station' => $station]));
?>

<div class="public-page">
    <div class="public-block">

        <ul class="actions pull-right" id="radio-player-controls">
            <li><a href="javascript:;" class="jp-mute" title="<?=__('Mute') ?>"><i class="zmdi zmdi-volume-up"></i></a></li>
            <li><a href="javascript:;" class="jp-unmute" title="<?=__('Unmute') ?>"><i class="zmdi zmdi-volume-off"></i></a></li>
            <li>
                <div class="progress jp-volume-bar" style="width: 100px; height: 15px;">
                    <div class="jp-volume-bar-value progress-bar" role="progressbar"></div>
                </div>
            </li>
        </ul>
        <h3 class="text-left"><?=$this->e($station->getName()) ?></h3>

        <div class="stations nowplaying">
            <?=$this->fetch('frontend/public/player_component', ['stream_url' => $stream_url, 'autoplay' => $autoplay]) ?>
        </div>

        <div class="buttons">
            <a class="btn btn-default btn-icon-text" data-toggle="modal" data-target="#modal-history">
                <i class="zmdi zmdi-time-restore"></i> <?=__('Song History') ?>
            </a>
        <?php if ($station->getEnableRequests()): ?>
            <a class="btn btn-default btn-icon-text" data-toggle="modal" data-target="#modal-request">
                <i class="zmdi zmdi-help-outline"></i> <?=__('Request Song') ?>
            </a>
        <?php endif; ?>
            <div class="btn-group">
                <button type="button" class="btn btn-default btn-icon-text dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="zmdi zmdi-download"></i> <?=__('Playlist') ?> <span class="caret"></span>
                </button>
                <ul class="dropdown-menu">
                    <?php foreach(['pls', 'm3u'] as $format): ?>
                        <li><a href="<?=$router->named('public:playlist', ['station' => $station->getShortName(), 'format' => $format]) ?>"><?=sprintf(__('Download %s'), strtoupper($format)) ?></a></li>
                    <?php endforeach; ?>
                </ul>
            </div>
        </div>

    </div>
</div>

<div class="modal fade" id="modal-history" tabindex="-1" role="dialog" aria-labelledby="modal-history-label">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="modal-history-label"><?=__('Song History') ?></h4>
            </div>
            <div class="modal-body">
                <ol type="1" id="station-history">
                    <li v-for="row in history">
                        <b>{{ row.song.title }}</b><br>
                        {{ row.song.artist }}
                    </li>
                </ol>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="modal-request" tabindex="-1" role="dialog" aria-labelledby="modal-request-label">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="modal-request-label"><?=__('Request a Song') ?></h4>
            </div>
            <div class="modal-body">

                <table class="data-table table table-striped" id="requests-table">
                    <thead>
                    <tr>
                        <th data-column-id="song_id" data-identifier="true" data-visible="false" data-visible-in-selection="false">ID</th>
                        <th data-column-id="song_title"><?=__('Title') ?></th>
                        <th data-column-id="song_artist"><?=__('Artist') ?></th>
                        <th data-column-id="song_album" data-visible="false"><?=__('Album') ?></th>
                        <th data-column-id="commands" data-formatter="commands" data-sortable="false"><?=__('Actions') ?></th>
                    </tr>
                    </thead>
                    <tbody></tbody>
                </table>
            </div>
        </div>
    </div>
</div>
