<?php
/** @var \App\Assets $assets */
$assets->addInlineJs($this->fetch('frontend/public/player_component.js'), 95);
?>
<div class="media media-left" id="station-nowplaying">
    <div class="pull-left p-r-10 p-t-5">
        <a class="btn-audio" role="button" title="<?=__('Play/Pause') ?>" href="#" data-url="<?=$this->e($stream_url) ?>" <?php if ($autoplay): ?>data-autoplay="true"<?php endif; ?>>
            <i class="zmdi zmdi-play"></i>
        </a>
    </div>
<?php if (!$customization->hideAlbumArt()): ?>
    <div class="pull-left p-r-10" v-if="np.now_playing.song.art">
        <a v-bind:href="np.now_playing.song.art" data-fancybox target="_blank"><img v-bind:src="np.now_playing.song.art" alt="<?=__('Album Cover') ?>" style="width: 50px; height: auto; border-radius: 5px;"></a>
    </div>
<?php endif; ?>
    <div class="media-body">
        <h4 class="media-heading might-overflow nowplaying-title">
            {{ np.now_playing.song.title }}
        </h4>
        <div class="nowplaying-artist might-overflow">
            {{ np.now_playing.song.artist }}
        </div>
        <div class="nowplaying-progress" v-if="time_display">
            {{ time_display }}
        </div>
    </div>
</div>
