<?php $this->layout('main', ['title' => _('Role Members')]); ?>

<?php foreach($roles as $role): ?>
    <h2>
        <?=$this->e($role['name']) ?><br>
        <small>
            <?php
            $actions = array();
            foreach($role['actions'] as $action)
                $actions[] = $action['name'];

            echo implode(', ', $actions);
            ?>
        </small>
    </h2>

    <ul>
    <?php foreach($role['users'] as $user): ?>
        <li><a href="<?=$url->route(array('module' => 'admin', 'controller' => 'users', 'action' => 'edit', 'id' => $user['id'])) ?>" target="_blank"><?=$this->e($user['name']) ?></a></li>
    <?php endforeach; ?>
    </ul>
<?php endforeach; ?>