<?
$this->headTitle('Request a Song');
$this->layout()->manual = true;
?>

<div class="row-fluid">
	<div class="span4">
		<h2><i class="<?=$this->station->getCategoryIcon() ?>"></i> <?=$this->station->name ?></h2>

		<div class="well">
			<h3>Find a Song</h3>
			<form class="form-inline" action="<?=$this->routeFromHere(array('page' => NULL, 'artist' => NULL, 'q' => NULL)) ?>" method="get">
				<input type="text" name="q" title="Search terms" placeholder="Song or Artist Name..." class="half-width" value="<?=$this->q ?>">
				<?=$this->button(array(
				    'type'		=> 'submit',
				    'class'		=> 'primary',
				    'icon'		=> 'icon-search',
				    'text'		=> 'Search',
				)) ?>
			</form>

			<br>
			<h3>Most Requested Songs</h3>

		<? if ($this->top_songs): ?>
			<ul class="nav nav-list">
			<? foreach($this->top_songs as $record): ?>
				<li><a href="<?=$this->routeFromHere(array('track' => $record['id'])) ?>" title="Click to request this song.">
					<b><?=$record['title'] ?></b> by <?=$record['artist'] ?>
				</a></li>
			<? endforeach; ?>
			</ul>
		<? else: ?>
			<p>No songs have been requested yet. Request one now!</p>
		<? endif; ?>

			<br>
			<h3>Browse by Artist</h3>

			<div style="height: 350px; overflow-y: scroll;">
				<ul class="nav nav-list">
				<? foreach($this->artist_names as $artist): ?>
					<li><a href="<?=$this->routeFromHere(array('artist' => $artist)) ?>" title="View all songs by this artist.">
						<?=$artist ?>
					</a></li>
				<? endforeach; ?>
				</ul>
			</div>

		</div>
	</div>
	<div class="span8">
		<h2><?=$this->page_title ?></h2>

	<? if ($this->reset_button): ?>
		<div class="buttons">
			<?=$this->button(array(
				'type'		=> 'link',
				'icon'		=> 'icon-chevron-sign-left',
				'text'		=> 'Reset Search',
				'href'		=> $this->routeFromHere(array('q' => NULL, 'artist' => NULL, 'page' => 1)),
			)) ?>
		</div>
	<? endif; ?>

		<?=$this->paginate($this->pager) ?>

		<table class="table table-bordered table-striped" width="100%">
			<colgroup>
				<col width="15%">
				<col width="25%">
				<col width="25%">
				<col width="25%">
				<col width="10%">
			</colgroup>
			<thead>
				<tr>
					<th>&nbsp;</th>
					<th>Track Name</th>
					<th>Artist</th>
					<th>Album</th>
					<th>Length</th>
				</tr>
			</thead>
			<tbody>
			<? foreach($this->pager as $record): ?>
				<tr class="input">
					<td class="center">
						<?=$this->button(array(
							'type'		=> 'small',
							'class'		=> 'primary',
							'href'		=> $this->routeFromHere(array('track' => $record['id'])),
							'icon'		=> 'icon-play-sign',
							'text'		=> 'Request',
						)) ?>
					</td>
					<td><big><?=$record['title'] ?></big></td>
					<td><?=$record['artist'] ?></td>
					<td><?=$record['album'] ?></td>
					<td><?=$record['length_text'] ?></td>
				</tr>
			<? endforeach; ?>
			</tbody>
		</table>

		<?=$this->paginate($this->pager) ?>
	</div>
</div>