<?php $this->layout('main', ['title' => 'Users', 'manual' => true]); ?>

<div class="block-header">
    <h2><?=_('Administration') ?></h2>
</div>

<div class="card">
    <div class="card-header ch-alt">
        <?php if ($q): ?>
            <h2><?=sprintf(_('Search Results for "%s"'), $this->e($q)) ?></h2>
        <?php else: ?>
            <h2><?=_('All Users') ?></h2>
        <?php endif; ?>

        <a class="btn bgm-blue btn-float" href="<?=$url->routeFromHere(array('action' => 'edit')) ?>"><i class="zmdi zmdi-plus"></i></a>
    </div>
    <div id="data-table-basic-header" class="bootgrid-header container-fluid">
        <?=$this->paginate($pager) ?>
    </div>
    <div class="table-responsive">
        <table class="table table-striped">
            <colgroup>
                <col width="30%">
                <col width="40%">
                <col width="30%">
            </colgroup>
            <thead>
            <tr>
                <th><?=_('Actions') ?></th>
                <th><?=_('E-mail Address') ?></th>
                <th><?=_('Roles') ?></th>
            </tr>
            </thead>
            <tbody>
            <?php foreach($pager as $user_row): ?>
                <tr class="input">
                    <td>
                    <?php if ($user_row->getId() !== $user->getId()): ?>
                        <a class="btn btn-sm btn-primary" href="<?=$url->routeFromHere(array('action' => 'impersonate', 'id' => $user_row->getId())) ?>"><?=_('Log In') ?></a>
                    <?php endif; ?>
                        <a class="btn btn-sm btn-default" href="<?=$url->routeFromHere(array('action' => 'edit', 'id' => $user_row->getId())) ?>"><?=_('Edit') ?></a>
                        <a class="btn btn-sm btn-danger" href="<?=$url->routeFromHere(array('action' => 'delete', 'id' => $user_row->getId())) ?>"><?=_('Delete') ?></a>
                    </td>
                    <td><?=$this->mailto($user_row->getEmail()) ?> <?php if ($user_row->getId() === $user->getId()): ?>(You)<?php endif; ?></td>
                    <td>
                        <small>
                            <?php
                            if (count($user_row->getRoles()) > 0)
                            {
                                foreach($user_row->getRoles() as $role)
                                    echo '<div>'.$this->e($role->getName()).'</div>';
                            }
                            ?>
                        </small>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>