<?php $this->layout('main', ['title' => 'Playlists', 'manual' => true]) ?>

<div class="block-header">
    <h2><?=$station->name ?></h2>
</div>

<div class="card">
    <div class="card-header ch-alt">
        <h2>Station Playlists</h2>

        <a class="btn bgm-blue btn-float" href="<?=$url->routeFromHere(array('action' => 'edit')) ?>"><i class="zmdi zmdi-plus"></i></a>
    </div>
    <div class="table-responsive">
        <table class="table table-striped">
            <colgroup>
                <col width="25%">
                <col width="30%">
                <col width="15%">
                <col width="15%">
                <col width="15%">
            </colgroup>
            <thead>
            <tr>
                <th>Actions</th>
                <th>Playlist</th>
                <th>Weight</th>
                <th><abbr title="The likelihood that this playlist will be the source of the next song.">Probability</abbr></th>
                <th># Songs</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach($playlists as $row): ?>
                <tr class="vertical-align-middle">
                    <td>
                        <a class="btn btn-sm btn-primary" href="<?=$url->routeFromHere(array('action' => 'edit', 'id' => $row['id'])) ?>">Edit</a>
                        <a class="btn btn-sm btn-danger" href="<?=$url->routeFromHere(array('action' => 'delete', 'id' => $row['id'])) ?>">Delete</a>
                    </td>
                    <td>
                        <big><?=$row['name'] ?></big>
                        <?php if ($row['include_in_automation']): ?>
                            <br><span class="label label-success">Auto-Assigned</span>
                        <?php endif; ?>
                    </td>
                    <td><?=$row['weight'] ?></td>
                    <td><?=$row['probability'] ?></td>
                    <td><?=$row['num_songs'] ?></td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>