<?
$this->headTitle('Sign In to Ponyville Live!');
$this->layout()->manual = true;

$this->headLink()->appendStylesheet(\DF\Url::content('zocial/zocial.css'), 'all')
?>

<div class="row-fluid">
	<div class="span6">
		<div class="floating">
			<h2>Log In with PVL Account</h2>
			<p>If you have an account inside the Ponyville Live! system, enter your username and password below.</p>

			<p><a href="<?=$this->routeFromHere(array('action' => 'register')) ?>">Create New PVL Account</a></p>

			<?=$this->form->render() ?>

			<p><small>You have requested access to a site that requires authentication.</b> This computer system and data herein are available only for authorized purposes by authorized users. Use for any other purpose may result in administrative/disciplinary actions or criminal prosecution against the user. Usage may be subject to security testing and monitoring. Applicable privacy laws establish the expectations of privacy.</small></p>
		</div>
	</div>
	<div class="span6">
		<div class="floating">
			<h2>Log In with a Social Network</h2>

			<div class="buttons"><a href="<?=$this->routeFromHere(array('provider' => 'facebook')) ?>" class="zocial facebook">Sign in with Facebook</a></div>
			<div class="buttons"><a href="<?=$this->routeFromHere(array('provider' => 'google')) ?>" class="zocial googleplus">Sign in with Google+</a></div>
			<div class="buttons"><a href="<?=$this->routeFromHere(array('provider' => 'twitter')) ?>" class="zocial twitter">Sign in with Twitter</a></div>
			<div class="buttons"><a href="<?=$this->routeFromHere(array('provider' => 'tumblr')) ?>" class="zocial tumblr">Sign in with Tumblr</a></div>
		</div>
	</div>
</div>