<?
$title = 'Podcast Center';
$manual = true;

$this->assets->collection('custom_js')
    ->addJs('//code.highcharts.com/highcharts.js', false)
    ->addJs('//code.highcharts.com/highcharts-more.js', false)
    ->addJs('//code.highcharts.com/modules/exporting.js', false);

$skin = \PVL\Customization::get('theme');
if ($skin == "dark")
    $this->assets->collection('custom_js')->addJs('js/highcharts/dark-blue.js');

echo $this->viewHelper->renderHere('header', true, array('title' => $title));
?>

<script type="text/javascript">
Highcharts.setOptions({
    global: {
        useUTC: false
    }
});
</script>

<div class="row-fluid">
    <div class="span12">
        <?=$this->viewHelper->renderHere('index-dailystats') ?>
    </div>
</div>

<div class="row-fluid">
    <div class="span3">

        <div class="well">
            <h4>Network Tools</h4>
            <ul class="nav nav-list">
                <li><a href="<?=$this->viewHelper->route(array('module' => 'frontend', 'controller' => 'show', 'action' => 'view', 'id' => $podcast->id)) ?>" target="_blank"><i class="icon-globe"></i> View Public Page</a></li>
                <li><a href="<?=$this->viewHelper->routeFromHere(array('controller' => 'profile', 'action' => 'index')) ?>"><i class="icon-picture"></i> Podcast Profile</a></li>

                <li><a href="<?=$this->viewHelper->routeFromHere(array('controller' => 'sources', 'action' => 'index')) ?>"><i class="icon-rss"></i> Syndication Sources</a></li>
            </ul>

            <h4>Shortcuts</h4>
            <ul class="nav nav-list">
                <li><a href="<?=$this->viewHelper->route(array('module' => 'default', 'controller' => 'convention', 'action' => 'signup')) ?>" title="Send this form to your station staff if they are interested in attending conventions as PVL press members."><i class="icon-building"></i> Convention Sign-up Form</a></li>
                <li><a href="//www.ponyvillelive.com/resources/brand_package.zip"><i class="icon-download-alt"></i> PVL Network Logos &amp; Branding Kit</a></li>
            </ul>
        </div>

        <h2>Podcast Managers</h2>
        <div class="well">
            <? foreach($podcast->managers as $manager): ?>
            <div style="padding: 5px 0;">
                <?=$manager->name ?> (<?=$this->viewHelper->mailto($manager->email) ?>)<br>
                <small><a href="<?=$this->viewHelper->routeFromHere(array('action' => 'removeadmin', 'id' => $manager->id)) ?>"><i class="icon-minus-sign"></i> Remove</a></small>
            </div>
            <? endforeach; ?>

            <form action="<?=$this->viewHelper->routeFromHere(array('action' => 'addadmin')) ?>" method="post">
                <input type="email" name="email" placeholder="E-mail Address" class="full-width" style="margin: 0;">
                <?=$this->viewHelper->button(array(
                    'type'      => 'submit',
                    'icon'      => 'icon-plus-sign',
                    'text'      => 'Add Admin',
                    'class'     => 'btn-small btn-success',
                )) ?>
            </form>
        </div>
        
    </div>

    <div class="span9">
        <h3>All Episodes (<?=count($pager) ?>)</h3>

        <?=$this->viewHelper->paginate($pager) ?>

        <table class="episode_list datatable table-striped table-bordered">
            <colgroup>
                <col width="20%">
                <col width="10%">
                <col width="70%">
            </colgroup>
            <thead>
            <tr>
                <th>&nbsp;</th>
                <th>Source</th>
                <th>Episode</th>
            </tr>
            </thead>
            <tbody>
            <? foreach($pager as $ep): ?>
                <tr class="input">
                    <td class="center">
                        <div class="btn-group">
                        <?=$this->viewHelper->button(array(
                            'type'      => 'small',
                            'class'     => 'btn-primary',
                            'href'      => \Entity\PodcastEpisode::getEpisodeLocalUrl($ep, 'pvlive'),
                            'target'    => '_blank',
                            'text'      => 'View',
                        )) ?>
                        <?=$this->viewHelper->button(array(
                            'type'      => 'small',
                            'class'     => ($ep->is_active) ? 'btn-danger' : 'btn-success',
                            'href'      => $this->viewHelper->routeFromHere(array('action' => 'toggle', 'id' => $ep->id)),
                            'text'      => ($ep->is_active) ? 'Hide' : 'Show',
                        )) ?>
                        </div>
                    </td>
                    <td class="center">
                        <?
                        $source = $social_types[$ep->source->type];
                        ?>
                        <a href="<?=$ep->source->url ?>" target="_blank"><img src="<?=\DF\Url::content('social/'.$source['icon'].'.png') ?>" alt="<?=$source['name'] ?>"></a>
                    </td>
                    <td><big><b><a href="<?=\Entity\PodcastEpisode::getEpisodeLocalUrl($ep, 'pvlive') ?>" target="_blank"><?=$ep['title'] ?></a></b></big> <span class="badge"><?=$ep['play_count'] ?> Plays</span>
                        <div><?=date('M j, Y', $ep['timestamp']) ?> <?=date('g:ia', $ep['timestamp']) ?></div>
                    </td>
                </tr>
            <? endforeach; ?>
            </tbody>
        </table>

        <?=$this->viewHelper->paginate($pager) ?>
    </div>
</div>