<?php
$options = $form->getOptions();
$inner_form = $form->getForm();
?>

<?=$inner_form->openForm() ?>
<?=$inner_form->renderHidden() ?>

<?php foreach($options['groups'] as $fieldset_id => $fieldset): ?>

    <?php if (!empty($fieldset['legend'])): ?>
    <fieldset id="<?=$fieldset_id ?>" <?php if (!empty($fieldset['class'])): ?>class="<?=$fieldset['class'] ?>"<?php endif; ?>>
        <legend><?=$fieldset['legend'] ?></legend>

        <?php if (!empty($fieldset['description'])): ?>
        <p><?=$fieldset['description'] ?></p>
        <?php endif; ?>

    <?php endif; ?>

    <?php foreach($fieldset['elements'] as $element_id => $element_info): ?>
        <?php
        if (!empty($element_info[1]['belongsTo']))
            $element_id = $element_info[1]['belongsTo'].'_'.$element_id;
        ?>
        <?php if ($element_info[0] == 'submit'): ?>
            <input type="submit" value="<?=$element_info[1]['label'] ?>" class="btn btn-lg btn-primary" />
        <?php else: ?>
            <div class="form-group" id="field_<?=$element_id ?>">
                <?=$inner_form->renderLabel($element_id) ?>
            <?php if (!empty($element_info[1]['description'])): ?>
                <small class="help-block"><?=$element_info[1]['description'] ?></small>
            <?php endif; ?>
            <?php if ($inner_form->hasError($element_id)): ?>
                <small class="help-block form-error"><?=$inner_form->renderError($element_id) ?></small>
            <?php endif; ?>
                <div class="form-field">
                    <?=$inner_form->renderField($element_id) ?>
                </div>
            </div>
        <?php endif; ?>
    <?php endforeach; ?>

    <?php if (!empty($fieldset['legend'])): ?>
    </fieldset>
    <?php endif; ?>

<?php endforeach; ?>

<?=$inner_form->closeForm() ?>