<li class="dropdown" id="radio-player-controls">
    <a data-toggle="dropdown" href=""><i class="him-icon zmdi zmdi-radio"></i></a>
    <ul class="dropdown-menu dm-icon pull-right">
        <li>
            <a href="javascript:;" class="jp-pause"><i class="zmdi zmdi-pause"></i> <?=__('Pause') ?></a>
        </li>
        <li>
            <a href="javascript:;" class="jp-mute"><i class="zmdi zmdi-portable-wifi-off"></i> <?=__('Mute') ?></a>
        </li>
        <li>
            <a href="javascript:;" class="jp-unmute"><i class="zmdi zmdi-portable-wifi"></i> <?=__('Unmute') ?></a>
        </li>
        <li>
            <div class="progress jp-volume-bar">
                <div class="jp-volume-bar-value progress-bar" role="progressbar"></div>
            </div>
        </li>
    </ul>
</li>