<?php $this->layout('main', ['title' => 'Permissions', 'manual' => true]); ?>

<div class="block-header">
    <h2><?=_('Manage Permissions') ?></h2>
</div>

<div class="card">
    <div class="card-header ch-alt">
        <h2><?=_('Roles') ?></h2>
        <a class="btn bgm-blue btn-float" role="button" title="<?=_('Add new item') ?>" href="<?=$url->named('admin:permissions:edit') ?>"><i class="zmdi zmdi-plus"></i></a>
    </div>
    <div class="table-responsive">
        <table class="table table-striped">
            <colgroup>
                <col width="20%">
                <col width="20%">
                <col width="30%">
                <col width="30%">
            </colgroup>
            <thead>
            <tr>
                <th><?=_('Actions') ?></th>
                <th><?=_('Role Name') ?></th>
                <th><?=_('System-Wide Permissions') ?></th>
                <th><?=_('Per-Station Permissions') ?></th>
            </tr>
            </thead>
            <tbody>
            <?php foreach($roles as $role): ?>
                <tr class="input">
                    <td class="center">
                        <a class="btn btn-sm btn-primary" href="<?=$url->named('admin:permissions:edit', ['id' => $role['id']]) ?>"><?=_('Edit') ?></a>

                        <?php if( $role['id'] != 1 ): ?>
                            <a class="btn btn-sm btn-danger" href="<?=$url->named('admin:permissions:delete', ['id' => $role['id'], 'csrf' => $csrf]) ?>"><?=_('Delete') ?></a>
                        <?php else: ?>
                            <a class="btn btn-sm btn-danger disabled" href="#" onclick="alert('<?=_('This role cannot be deleted.') ?>'); return false;"><?=_('Delete') ?></a>
                        <?php endif; ?>
                    </td>
                    <td>
                        <big><?=$this->e($role['name']) ?></big>
                    </td>
                    <td>
                        <?=implode($role['permissions_global'], ', ') ?>
                    </td>
                    <td>
                    <?php foreach($role['permissions_station'] as $station_name => $station_perms): ?>
                        <div><b><?=$this->e($station_name) ?></b>: <?=implode($station_perms, ', ') ?></div>
                    <?php endforeach; ?>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>