<?php
$title = ('URL Shortener Management');

echo $this->viewHelper->renderHere('stationname', true);
echo $this->viewHelper->renderHere('homelink', true);
?>

<h2>My Station's Links</h2>

<div class="buttons">
    <?=$this->viewHelper->button(array(
        'type'      => 'link',
        'class'     => 'btn-large success',
        'href'      => $this->viewHelper->routeFromHere(array('action' => 'edit')),
        'icon'      => 'icon-plus-sign',
        'text'      => 'Add New URL',
    )) ?>
</div>

<table class="table table-striped table-bordered table-condensed">
    <colgroup>
        <col width="20%" />
        <col width="40%" />
        <col width="40%" />
    </colgroup>
    <thead>
    <tr>
        <th>Actions</th>
        <th>Short URL</th>
        <th>Long URL</th>
    </tr>
    </thead>
    <tbody>
    <? foreach($urls as $record): ?>
        <tr class="input">
            <td class="center">
                <div class="btn-group">
                    <?=$this->viewHelper->button(array(
                        'type'      => 'link',
                        'href'      => $this->viewHelper->routeFromHere(array('action' => 'edit', 'id' => $record['id'])),
                        'icon'      => 'icon-pencil',
                        'text'      => 'Edit',
                    )) ?>
                    <?=$this->viewHelper->button(array(
                        'type'      => 'link',
                        'class'     => 'btn-danger confirm-action',
                        'href'      => $this->viewHelper->routeFromHere(array('action' => 'delete', 'id' => $record['id'])),
                        'icon'      => 'icon-trash',
                        'text'      => 'Delete',
                    )) ?>
                </div>
            </td>
            <td><a href="<?=$record->getUrl() ?>" target="_blank"><?=$record->getUrl() ?></a></td>
            <td><a href="<?=$record->long_url ?>" target="_blank"><?=$record->long_url ?></a></td>
        </tr>
    <? endforeach; ?>
    </tbody>
</table>

<div class="row-fluid">
    <div class="span6">
        <h2>Stations</h2>
        <p>These URLs link to the Ponyville Live! homepage and auto-play the specified station.</p>

        <table class="table table-striped table-bordered table-condensed">
            <colgroup>
                <col width="40%" />
                <col width="60%" />
            </colgroup>
            <thead>
            <tr>
                <th>Station Name</th>
                <th>Station URL</th>
            </tr>
            </thead>
            <tbody>
            <? foreach($station_urls as $record): ?>
                <tr class="input">
                    <td><i class="<?=$record['icon'] ?>"></i> <?=$record['name'] ?></td>
                    <td><a href="<?=$record['url'] ?>" target="_blank"><?=$record['url'] ?></a></td>
                </tr>
            <? endforeach; ?>
            </tbody>
        </table>
    </div>
    <div class="span6">
        <h2>Convention Archives</h2>
        <p>These URLs lead to the auto-generated convention archive pages for the specified convention.</p>

        <table class="table table-striped table-bordered table-condensed">
            <colgroup>
                <col width="40%" />
                <col width="60%" />
            </colgroup>
            <thead>
            <tr>
                <th>Convention Name</th>
                <th>Convention URL</th>
            </tr>
            </thead>
            <tbody>
            <? foreach($convention_urls as $record): ?>
                <tr class="input">
                    <td><?=$record['name'] ?></td>
                    <td><a href="<?=$record['url'] ?>" target="_blank"><?=$record['url'] ?></a></td>
                </tr>
            <? endforeach; ?>
            </tbody>
        </table>
    </div>
</div>