<?php
$this->headTitle('URL Shortener Management');
$this->layout()->manual = true;

echo $this->renderHere('stationname', true);
echo $this->renderHere('homelink', true);
?>

<div class="row-fluid">
	<div class="span7">
		<h2>My Station's Links</h2>

		<div class="buttons">
			<?=$this->button(array(
				'type'		=> 'link',
				'class'		=> 'btn-large success',
				'href'		=> $this->routeFromHere(array('action' => 'edit')),
				'icon'		=> 'icon-plus-sign',
				'text'		=> 'Add New URL',
			)) ?>
		</div>

		<table class="table table-striped table-bordered table-condensed">
			<colgroup>
				<col width="20%" />
				<col width="40%" />
				<col width="40%" />
			</colgroup>
			<thead>
				<tr>
					<th>Actions</th>
					<th>Short URL</th>
					<th>Long URL</th>
				</tr>
			</thead>
			<tbody>
			<? foreach($this->urls as $record): ?>
				<tr class="input">
					<td class="center">
						<div class="btn-group">
							<?=$this->button(array(
								'type'		=> 'link',
								'href'		=> $this->routeFromHere(array('action' => 'edit', 'id' => $record['id'])),
								'icon'		=> 'icon-pencil',
								'text'		=> 'Edit',
							)) ?>
							<?=$this->button(array(
								'type'		=> 'link',
								'class'		=> 'btn-danger confirm-action',
								'href'		=> $this->routeFromHere(array('action' => 'delete', 'id' => $record['id'])),
								'icon'		=> 'icon-trash',
								'text'		=> 'Delete',
							)) ?>
						</div>
					</td>
					<td><a href="<?=$record->getUrl() ?>" target="_blank"><?=$record->getUrl() ?></a></td>
					<td><a href="<?=$record->long_url ?>" target="_blank"><?=$record->long_url ?></a></td>
				</tr>
			<? endforeach; ?>
			</tbody>
		</table>
	</div>
	<div class="span5">
		<h2>System-Wide Short URLs</h2>

		<table class="table table-striped table-bordered table-condensed">
			<colgroup>
				<col width="40%" />
				<col width="60%" />
			</colgroup>
			<thead>
				<tr>
					<th>Station Name</th>
					<th>Station URL</th>
				</tr>
			</thead>
			<tbody>
			<? foreach($this->station_urls as $record): ?>
				<tr class="input">
					<td><i class="<?=$record['icon'] ?>"></i> <?=$record['name'] ?></td>
					<td><a href="<?=$record['url'] ?>" target="_blank"><?=$record['url'] ?></a></td>
				</tr>
			<? endforeach; ?>
			</tbody>
		</table>
	</div>
</div>