<?
$title = 'Contact Us';
$manual = true;
?>

<h2>The Ponyville Live! Network</h2>

<div class="row-fluid">
    <div class="span4">
        <div class="media-list">
            <div class="media">
                <img src="<?=\DF\Url::content('images/staff_silvereagle.png') ?>" alt="Silver Eagle" class="pull-left">
                <div class="media-body">
                    <h4 class="media-heading">Silver Eagle<br><small>Network Director</small></h4>
                    <div class="social" style="padding-bottom: 10px;">
                        <a href="mailto:silvereagle@ponyvillelive.com"><img src="<?=\DF\Url::content('social/email.png') ?>" alt="E-mail"></a>
                        <a href="https://twitter.com/SilverEaglePVL" target="_blank"><img src="<?=\DF\Url::content('social/twitter.png') ?>" alt="Twitter"></a>
                        <a href="skype:slvreagle23" target="_blank"><img src="<?=\DF\Url::content('social/skype.png') ?>" alt="Skype"></a>
                        <a href="https://www.youtube.com/user/loobalightdark" target="_blank"><img src="<?=\DF\Url::content('social/youtube.png') ?>" alt="YouTube"></a>
                        <a href="http://steamcommunity.com/id/slvreagle23" target="_blank"><img src="<?=\DF\Url::content('social/steam.png') ?>" alt="Steam"></a>
                    </div>

                    <p>Howdy! My name is Silver Eagle, and I'm the network director for the Ponyville Live! media network. When I'm not doing pony stuff, I'm a web developer both professionally and as a hobby (including this site), a PC gamer, board gamer, music lover and all around geeky guy. I'm happy to help answer questions and solve problems, so feel free to message me or the awesome team listed here!</p>
                </div>
            </div>
        </div>
    </div>
    <div class="span4">
        <div class="media-list">
            <div class="media">
                <img src="<?=\DF\Url::content('images/staff_borg.png') ?>" alt="WeAreBorg" class="pull-left">
                <div class="media-body">
                    <h4 class="media-heading">WeAreBorg<br><small>Associate Director</small></h4>

                    <div class="social" style="padding-bottom: 10px;">
                        <a href="mailto:borg@ponyvillelive.com"><img src="<?=\DF\Url::content('social/email.png') ?>" alt="E-mail"></a>
                        <a href="https://twitter.com/weareborgpony" target="_blank"><img src="<?=\DF\Url::content('social/twitter.png') ?>" alt="Twitter"></a>
                        <a href="skype:weyrling" target="_blank"><img src="<?=\DF\Url::content('social/skype.png') ?>" alt="Skype"></a>
                    </div>

                    <p>Hello! I'm WeAreBorg, and I'm the associate director for the Ponyville Live! media network.  I'm the biggest "brony" you'll ever meet and love helping with conventions and community projects like PVL!  I'm a tech geek that's a server admin by day and a music loving gamer/bike mechanic by night. Let me know if there’s anything I can do to make your PVL! experience better!</p>
                </div>
            </div>
        </div>
    </div>
    <div class="span4">
        <div class="media-list">
            <div class="media">
                <img src="<?=\DF\Url::content('images/staff_azura.png') ?>" alt="PVL Mascot Azura Peavielle" class="pull-left">
                <div class="media-body">
                    <h4 class="media-heading">PVL! Administrators</h4>

                    <dl>
                        <dt>General Information:</dt>
                        <dd><?=$this->viewHelper->mailto('info@ponyvillelive.com') ?></dd>

                        <dt>Public Relations &amp; Promotions:</dt>
                        <dd><?=$this->viewHelper->mailto('pr@ponyvillelive.com') ?></dd>

                        <dt>European Conventions:</dt>
                        <dd><?=$this->viewHelper->mailto('sleepypony@ponyvillelive.com') ?></dd>
                    </dl>
                </div>
            </div>
        </div>
    </div>
</div>

<br>

<div class="row-fluid">
<? foreach($station_columns as $col): ?>
    <div class="span4">
        <h2><?=$col[0] ?></h2>
        <div class="media-list">
        <? foreach($col[1] as $station): ?>
            <div class="media">
                <img src="<?=\DF\Url::content($station['image_url']) ?>" alt="Station" class="pull-left" style="width: 50px;">
                <div class="media-body">
                    <h4 class="media-heading">
                        <?=$station['name'] ?><br><small><?=$station['genre'] ?></small>
                    </h4>

                    <div class="social">
                    <? if ($station['web_url']): ?>
                        <a href="<?=$station['web_url'] ?>" target="_blank"><img src="<?=\DF\Url::content('social/link.png') ?>" alt="Homepage"></a>
                    <? endif; ?>
                    <? if ($station['twitter_url']): ?>
                        <a href="<?=$station['twitter_url'] ?>" target="_blank"><img src="<?=\DF\Url::content('social/twitter.png') ?>" alt="Twitter"></a>
                    <? endif; ?>
                    </div>
                </div>
            </div>
        <? endforeach; ?>
        </div>
    </div>
<? endforeach; ?>
</div>

<br><br>

<h2><i class="icon-rss"></i> Shows &amp; Podcasts</h2>
<div class="row-fluid">
<? foreach($podcasts as $col): ?>
    <div class="span4">
        <div class="media-list">
        <? foreach($col as $podcast): ?>
            <div class="media">
                <img src="<?=\DF\Url::content($podcast['image_url']) ?>" alt="Station" class="pull-left" style="width: 50px;">
                <div class="media-body">
                    <h4 class="media-heading">
                        <?=$podcast['name'] ?>
                    </h4>

                    <div class="social">
                    <? foreach($podcast_social_types as $social_type => $social_info): ?>
                        <? if ($podcast[$social_type]): ?>
                            <a href="<?=$podcast[$social_type] ?>" target="_blank"><img src="<?=\DF\Url::content('social/'.$social_info['icon'].'.png') ?>" alt="<?=$social_info['name'] ?>"></a>
                        <? endif; ?>
                    <? endforeach; ?>
                    </div>
                </div>
            </div>
        <? endforeach; ?>
        </div>
    </div>
<? endforeach; ?>
</div>