<?
$title = 'Contact Us';
$manual = true;
?>

<h2>Bravely Blue</h2>

<div class="row-fluid">
    <div class="span6">
        <div class="media-list">
            <div class="media">
                <img src="<?=\DF\Url::content('images/staff_silvereagle.png') ?>" alt="Silver Eagle" class="pull-left">
                <div class="media-body">
                    <h4 class="media-heading">Silver Eagle<br><small>Network Director</small></h4>
                    <div class="social" style="padding-bottom: 10px;">
                        <a href="mailto:silvereagle@bravelyblue.com"><img src="<?=\DF\Url::content('social/email.png') ?>" alt="E-mail"></a>
                        <a href="https://twitter.com/SilverEaglePVL" target="_blank"><img src="<?=\DF\Url::content('social/twitter.png') ?>" alt="Twitter"></a>
                        <a href="skype:slvreagle23" target="_blank"><img src="<?=\DF\Url::content('social/skype.png') ?>" alt="Skype"></a>
                        <a href="https://www.youtube.com/user/loobalightdark" target="_blank"><img src="<?=\DF\Url::content('social/youtube.png') ?>" alt="YouTube"></a>
                        <a href="http://steamcommunity.com/id/slvreagle23" target="_blank"><img src="<?=\DF\Url::content('social/steam.png') ?>" alt="Steam"></a>
                    </div>

                    <p>Howdy! My name is Silver Eagle, and I'm the network director for the <?=$this->config->application->name ?> media network. When I'm not doing pony stuff, I'm a web developer both professionally and as a hobby (including this site), a PC gamer, board gamer, music lover and all around geeky guy. I'm happy to help answer questions and solve problems, so feel free to message me or the awesome team listed here!</p>
                </div>
            </div>
        </div>
    </div>
    <div class="span6">
        <div class="media-list">
            <div class="media">
                <img src="<?=\DF\Url::content('images/staff_azura.png') ?>" alt="PVL Mascot Azura Peavielle" class="pull-left">
                <div class="media-body">
                    <h4 class="media-heading">Other Questions<br><small>Public Relations</small></h4>

                    <div class="social" style="padding-bottom: 10px;">
                        <a href="mailto:<?=$this->config->application->mail->from_addr ?>"><img src="<?=\DF\Url::content('social/email.png') ?>" alt="E-mail"></a>
                    </div>

                    <p><?=$this->config->application->name ?> and our pony mascot, Azura, are ready to answer your questions! Contact us at <?=$this->viewHelper->mailto($this->config->application->mail->from_addr) ?> with any questions, comments or suggestions and we will be happy to answer!</p>
                </div>
            </div>
        </div>
    </div>
</div>

<br>

<div class="row-fluid">
<? foreach($station_columns as $col): ?>
    <div class="span4">
        <h2><?=$col[0] ?></h2>
        <div class="media-list">
        <? foreach($col[1] as $station): ?>
            <div class="media">
                <img src="<?=\PVL\Url::upload($station['image_url']) ?>" alt="Station" class="pull-left" style="width: 50px;">
                <div class="media-body">
                    <h4 class="media-heading">
                        <?=$station['name'] ?><br><small><?=$station['genre'] ?></small>
                    </h4>

                    <div class="social">
                    <? foreach($podcast_social_types as $social_type => $social_info): ?>
                        <? if (!empty($station[$social_type])): ?>
                            <? if(filter_var($station[$social_type], FILTER_VALIDATE_EMAIL)) { ?>
                            <a href="<?= 'mailto:'.$station[$social_type] ?>" target="_blank">
                            <? } else { ?>
                            <a href="<?=$station[$social_type] ?>" target="_blank">
                            <? } ?>
                                <img src="<?=\DF\Url::content('social/'.$social_info['icon'].'.png') ?>" alt="<?=$social_info['name'] ?>">
                            </a>
                        <? endif; ?>
                    <? endforeach; ?>
                    </div>
                </div>
            </div>
        <? endforeach; ?>
        </div>
    </div>
<? endforeach; ?>
</div>

<br><br>

<h2><i class="icon-rss"></i> Shows &amp; Podcasts</h2>
<div class="row-fluid">
<? foreach($podcasts as $col): ?>
    <div class="span4">
        <div class="media-list">
        <? foreach($col as $podcast): ?>
            <div class="media">
                <img src="<?=\PVL\Url::upload($podcast['image_url']) ?>" alt="Station" class="pull-left" style="width: 50px;">
                <div class="media-body">
                    <h4 class="media-heading">
                        <?=$podcast['name'] ?>
                    </h4>

                    <div class="social">
                    <? foreach($podcast_social_types as $social_type => $social_info): ?>
                        <? if (!empty($podcast[$social_type])): ?>
                            <a href="<?=($social_type == 'contact_email' ? 'mailto:' : '').$podcast[$social_type] ?>" target="_blank"><img src="<?=\DF\Url::content('social/'.$social_info['icon'].'.png') ?>" alt="<?=$social_info['name'] ?>"></a>
                        <? endif; ?>
                    <? endforeach; ?>
                    </div>
                </div>
            </div>
        <? endforeach; ?>
        </div>
    </div>
<? endforeach; ?>
</div>