<?
$title = 'Contact Us';
$manual = true;
?>

<h2>The Ponyville Live! Network</h2>

<div class="media-list">
    <div class="media">
        <img src="<?=\DF\Url::content('images/staff_azura.png') ?>" alt="PVL Mascot Azura Peavielle" class="pull-left">
        <div class="media-body">
            <h4 class="media-heading">PVL! Administrators</h4>

            <dl>
                <dt>General Information:</dt>
                <dd><?=$this->viewHelper->mailto('info@ponyvillelive.com') ?></dd>

                <dt>Public Relations &amp; Promotions:</dt>
                <dd><?=$this->viewHelper->mailto('pr@ponyvillelive.com') ?></dd>
            </dl>
        </div>
    </div>
</div>

<br>

<div class="row-fluid">
<? foreach($station_columns as $col): ?>
    <div class="span4">
        <h2><?=$col[0] ?></h2>
        <div class="media-list">
        <? foreach($col[1] as $station): ?>
            <div class="media">
                <img src="<?=\PVL\Url::upload($station['image_url']) ?>" alt="Station" class="pull-left" style="width: 50px;">
                <div class="media-body">
                    <h4 class="media-heading">
                        <?=$station['name'] ?><br><small><?=$station['genre'] ?></small>
                    </h4>

                    <div class="social">
                    <? foreach($podcast_social_types as $social_type => $social_info): ?>
                        <? if (!empty($station[$social_type])): ?>
                            <? if(filter_var($station[$social_type], FILTER_VALIDATE_EMAIL)) { ?>
                            <a href="<?= 'mailto:'.$station[$social_type] ?>" target="_blank">
                            <? } else { ?>
                            <a href="<?=$station[$social_type] ?>" target="_blank">
                            <? } ?>
                                <img src="<?=\DF\Url::content('social/'.$social_info['icon'].'.png') ?>" alt="<?=$social_info['name'] ?>">
                            </a>
                        <? endif; ?>
                    <? endforeach; ?>
                    </div>
                </div>
            </div>
        <? endforeach; ?>
        </div>
    </div>
<? endforeach; ?>
</div>

<br><br>

<h2><i class="icon-rss"></i> Shows &amp; Podcasts</h2>
<div class="row-fluid">
<? foreach($podcasts as $col): ?>
    <div class="span4">
        <div class="media-list">
        <? foreach($col as $podcast): ?>
            <div class="media">
                <img src="<?=\PVL\Url::upload($podcast['image_url']) ?>" alt="Station" class="pull-left" style="width: 50px;">
                <div class="media-body">
                    <h4 class="media-heading">
                        <?=$podcast['name'] ?>
                    </h4>

                    <div class="social">
                    <? foreach($podcast_social_types as $social_type => $social_info): ?>
                        <? if (!empty($podcast[$social_type])): ?>
                            <a href="<?=($social_type == 'contact_email' ? 'mailto:' : '').$podcast[$social_type] ?>" target="_blank"><img src="<?=\DF\Url::content('social/'.$social_info['icon'].'.png') ?>" alt="<?=$social_info['name'] ?>"></a>
                        <? endif; ?>
                    <? endforeach; ?>
                    </div>
                </div>
            </div>
        <? endforeach; ?>
        </div>
    </div>
<? endforeach; ?>
</div>