<?php
$manual = TRUE;
$hide_title = true;
$this->render_mode = 'homepage';
?>

<?
ob_start();
?>
<div id="home_header" class="rich_header">
    <div class="container">
    <? if ($special_event): ?>
        <div class="well">
            <div class="special_event">
                <div class="row-fluid">
                    <? if (empty($special_chat_embed)): ?>
                        <div class="span12"><?=$special_event_embed ?></div>
                    <? else: ?>
                        <div class="span7"><?=$special_event_embed ?></div>
                        <div class="span5"><?=$this->viewHelper->renderHere('chat', TRUE) ?></div>
                    <? endif; ?>
                </div>
            </div>
        </div>
    <? elseif (count($network_news) > 0): ?>
        <div class="well carousel slide" id="rotator" data-interval="5000">     
            <ol class="carousel-indicators">
            <? for($i = 0; $i < count($network_news); $i++): ?>
                <li data-target="#rotator" data-slide-to="<?=$i ?>" <? if ($i == 0): ?>class="active"<? endif; ?>></li>
            <? endfor; ?>
            </ol>
            <div class="carousel-inner">
            <? foreach($network_news as $i => $article): ?>
                <div class="item layout-<?=$article['layout'] ?> <? if ($i == 0): ?>active<? endif; ?>">
                    <a href="<?=$article['web_url'] ?>" target="_blank"><img src="<?=$article['image_url'] ?>" alt="Article Image"></a>
                    <div class="carousel-caption">
                        <a href="<?=$article['web_url'] ?>" target="_blank">
                            <div class="post-date"><?=date('l, F jS \a\t g:ia', $article['timestamp']) ?></div>
                            <h4><?=$article['title'] ?></h4>
                            <p><?=$article['body'] ?> <span class="readmore">Read more &raquo;</span></p>
                            <div class="tags">
                            <? foreach((array)$article['tags'] as $tag): ?>
                                <span class="tag"><?=$tag ?></span>
                            <? endforeach; ?>
                            </div>
                        </a>
                    </div>
                </div>
            <? endforeach; ?>
            </div>

            <a class="carousel-control left" href="#rotator" data-slide="prev">&lsaquo;</a>
            <a class="carousel-control right" href="#rotator" data-slide="next">&rsaquo;</a>
        </div>
    <? endif; ?>
    </div>
</div>
<div class="hero">
    <div class="container">
        <div class="row-fluid">
            <div class="span6 hero-text">
                <h4>Your Home for Pony Media</h4>
                <p><a href="<?=$this->url->get('about') ?>">Ponyville Live!</a> is a network of <a href="#section_radio">radio stations</a>, <a href="#section_video">video streams</a>, and <a href="#section_shows">shows</a>.</p>
            </div>
            <div class="span3 hero-apps">
                <h5>Take Ponyville Live! With You</h5>
                <div class="btn-group">
                    <?=$this->viewHelper->button(array(
                        'type'      => 'link',
                        'icon'      => 'icon-cloud-download',
                        'text'      => 'Apps &amp; Players',
                        'href'      => $this->url->get('index/app'),
                    )) ?>
                    <?=$this->viewHelper->button(array(
                        'type'      => 'link',
                        'icon'      => 'icon-mobile-phone',
                        'text'      => 'PVL! Mobile',
                        'href'      => 'http://m.pvlive.me/',
                    )) ?>
                </div>
            </div>
            <div class="span3 hero-social">
                <div style="padding: 10px 0;">
                    <a href="https://www.youtube.com/ponyvilleliveglobal" target="_blank"><img src="<?=\DF\Url::content('social/youtube.png') ?>" alt="YouTube"></a>
                    <a href="https://twitter.com/PonyvilleLive" target="_blank"><img src="<?=\DF\Url::content('social/twitter.png') ?>" alt="Twitter"></a>
                    <a href="http://news.ponyvillelive.com/" target="_blank"><img src="<?=\DF\Url::content('social/tumblr.png') ?>" alt="Tumblr"></a>
                    <a href="https://www.facebook.com/pages/Ponyville-LIVE/517435684948331" target="_blank"><img src="<?=\DF\Url::content('social/facebook.png') ?>" alt="Facebook"></a>
                    <a href="http://steamcommunity.com/groups/ponyvillelive" target="_blank"><img src="<?=\DF\Url::content('social/steam.png') ?>" alt="Steam"></a>
                    <a href="https://plus.google.com/+PonyvilleLiveGlobal" rel="publisher" target="_blank"><img src="<?=\DF\Url::content('social/google_plus.png') ?>" alt="Google Plus"></a>
                    <a href="<?=$this->url->get('show/feed') ?>" target="_blank"><img src="<?=\DF\Url::content('social/feed.png') ?>" alt="RSS Feed"></a>
                </div>
            </div>
        </div>
    </div>
</div>
<?
$content_top = ob_get_contents();
ob_end_clean();
?>

<?
/*
<div class="hide-if-empty">
    <h2 id="section_video"><i class="<?=$categories['video']['icon'] ?>"></i> Live Video Streams <small><span id="nowplaying-listeners-video"></span></small></h2>

    <div class="row-fluid">
        <?
        $cat = $categories['video'];
        $stations = $cat['stations'];
        foreach($stations as $station):
        ?>
        <div class="span4"><?=$this->viewHelper->renderCommon('video', array('stations' => array($station))); ?></div>
        <?
        endforeach;
        ?>
    </div>
</div>
*/
?>

<?
$cat = $categories['audio'];
$station_cols = \DF\Utilities::columns($cat['stations'], 3);
?>

<h2 id="section_radio"><i class="<?=$cat['icon'] ?>"></i> Pony Radio Stations <small><span id="nowplaying-listeners-audio"></span></small></h2>

<div class="row-fluid">
    <div class="span4">
        <?
        $stations = $station_cols[0];
        echo $this->viewHelper->renderCommon('station', array('stations' => $stations));
        ?>
    </div>
    <div class="span4">
        <?
        $stations = $station_cols[1];
        echo $this->viewHelper->renderCommon('station', array('stations' => $stations));
        ?>
    </div>
    <div class="span4">
        <?
        $stations = $station_cols[2];
        echo $this->viewHelper->renderCommon('station', array('stations' => $stations));
        ?>
    </div>
</div>

<!-- Upcoming on the Schedule -->
<?
$tz_info = \PVL\Timezone::getInfo();
?>
<h2><i class="icon-calendar"></i> Upcoming Shows &amp; Events <small><i class="icon-time"></i> Times listed in <a href="<?=$this->url->get('profile/timezone') ?>" class="fancybox fancybox.ajax"><?=$tz_info['abbr'] ?></a>, see <a href="<?=$this->url->get('schedule') ?>">entire schedule</a></small></h2>

<div id="schedule_container">
    <?
    echo $this->viewHelper->renderHere('schedule');
    ?>
</div>

<!-- Shows/Podcasts -->
<h2 id="section_shows"><i class="icon-rss"></i> Podcasts &amp; Show Archives <small>Newer episodes first, <a href="<?=$this->url->get('show') ?>">view all</a></small></h2>

<?
$podcasts = array_slice($podcasts, 0, 15);
$podcast_cols = \DF\Utilities::columns($podcasts, 3, true);
?>
<div class="row-fluid">
<? foreach($podcast_cols as $podcast_col): ?>
    <div class="span4"><?=$this->viewHelper->renderCommon('podcast', array('podcasts' => $podcast_col)) ?></div>
<? endforeach; ?>
</div>



<h2><i class="icon-folder-open-alt"></i> Convention Coverage</h2>
<?
$cons = array_slice($conventions_archived, 0, 12);
$cols = \DF\Utilities::columns($cons, 3);
?>

<div class="row-fluid">
<? foreach($cols as $col): ?>
    <div class="span4">
        <? foreach($col as $record): ?>
            <a class="convention coverage_<?=$record['coverage_level'] ?>" href="<?=$this->viewHelper->route(array('controller' => 'convention', 'action' => 'archive', 'id' => $record['id'])) ?>">
                <img src="<?=\DF\Url::content($record['images']['thumb']) ?>" alt="Convention Image">
                <div class="coverage" title="<?=$record['coverage']['text'] ?>">
                    <i class="large-icon <?=$record['coverage']['icon'] ?>"></i>
                </div>
                <div class="name">
                    <h4><?=$record['name'] ?></h4>
                    <?=$record['location'] ?> &bull; <?=$record['range'] ?>
                </div>
            </a>
        <? endforeach; ?>
    </div>
<? endforeach; ?>
</div>

<!-- Player Interface Skeleton Code -->
<?
echo $this->viewHelper->renderHere('player-skeleton', true);
?>

<!-- Schedule Reloader -->
<script type="text/javascript">
var schedule_timeout;
var schedule_interval = 600000;

$(function() {

    $('.btn-play-station').click(function(e) {
        e.preventDefault();

        var station_id = $(this).data('station');
        playStation(station_id);

        return false;
    });

    schedule_timeout = setTimeout('updateSchedule()', schedule_interval);

});

function updateSchedule()
{
    $('#schedule_container').load('<?=$this->url->get('index/schedule') ?>', function(rt, status)
    {
        if (status == 'success')
        {
            clearTimeout(schedule_timeout);
            schedule_timeout = setTimeout('updateSchedule()', schedule_interval);
        }
    });
}
</script>