<?
$title = 'Dashboard';
$manual = true;

$this->assets->collection('custom_js')
    ->addJs('//code.highcharts.com/highcharts.js', false)
    ->addJs('//code.highcharts.com/highcharts-more.js', false)
    ->addJs('//code.highcharts.com/modules/exporting.js', false);

// ->addJs('vendor/moment/moment.js');

/*
foreach($stations as $station)
{
    $sidebar['Stations'][$station->name] = array(
        'url'       => array('module' => 'stations', 'action' => 'index', 'station' => $station->id),
        'icon'      => $station->getCategoryIcon(),
        'permission' => $station->canManage(),
    );
}
*/
?>

<div class="block-header">
    <h2>Dashboard</h2>
</div>

<div class="row">
    <div class="col-sm-6">
        <div class="card">
            <div class="card-header ch-alt">
                <h2>Listeners Across All Stations</h2>
            </div>
            <div class="card-body card-padding-sm">
                <div id="network_chart" style="height: 250px;"></div>
            </div>
        </div>
    </div>
    <div class="col-sm-6">
        <div class="card">
            <div class="card-header ch-alt">
                <h2>Listeners Per Station</h2>
            </div>
            <div class="card-body card-padding-sm">
                <div id="station_chart" style="height: 250px;"></div>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-sm-12">
        <div class="card">
            <div class="card-header ch-alt">
                <h2>Station Overview</h2>
            </div>
            <div class="table-responsive">
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>&nbsp;</th>
                            <th>Station Name</th>
                            <th>Now Playing</th>
                            <th>Options</th>
                        </tr>
                    </thead>
                    <tbody>
                    <? foreach($stations as $row): ?>
                        <tr id="station_<?=$row->id ?>" style="vertical-align: middle;">
                            <td>&nbsp;</td>
                            <td>
                                <big><?=$row->name ?></big>
                            </td>
                            <td>
                                <strong><span class="nowplaying-title">Song Title</span></strong><br>
                                <span class="nowplaying-artist">Song Artist</span>
                            </td>
                            <td>
                                <a class="btn btn-primary" href="<?=$this->url->route(['module' => 'stations', 'station' => $row->id]) ?>">Manage</a>
                            </td>
                        </tr>
                    <? endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
$(function () {
    Highcharts.setOptions({
        global: {
            useUTC: false
        }
    });

    var datetime_axis = {
        type: 'datetime',
        labels: {
            formatter: function () {
                return Highcharts.dateFormat('%a %d %b', this.value);
            },
            dateTimeLabelFormats: {
                minute: '%H:%M',
                hour: '%H:%M',
                day: '%e. %b',
                week: '%e. %b',
                month: '%b \'%y',
                year: '%Y'
            }
        }
    };

    $('#network_chart').highcharts({
        chart: { zoomType: 'x' },
        title: {text: ''},
        xAxis: datetime_axis,
        plotOptions: {
            spline: {
                marker: { enabled: false }
            }
        },
        yAxis: {
            title: { text: 'Listeners' },
            min: 0,
            max: 500
        },
        tooltip: {
            crosshairs: true,
            shared: true,
            xDateFormat: '%Y-%m-%d'
        },
        colors: [
            '#AEE1FF',
            '#0091E5',
            '#FFA6A6',
            '#8C0000'
        ],

        series: <?=$metrics['network'] ?>
    });

    $('#station_chart').highcharts({
        chart: { zoomType: 'x' },
        title: {text: ''},
        xAxis: datetime_axis,
        plotOptions: {
            spline: {
                lineWidth: 1,
                marker: { enabled: false },
                shadow: false,
                states: {
                    hover: {
                        lineWidth: 3
                    }
                },
                threshold: null
            }
        },
        yAxis: {
            title: { text: 'Listeners' },
            min: 0,
            max: 100
        },
        tooltip: {
            crosshairs: true,
            xDateFormat: '%Y-%m-%d'
        },

        series: <?=$metrics['station'] ?>
    });
});

function nowPlaying() {
    $.getJSON('<?=$this->url->route(['module' => 'api', 'controller' => 'nowplaying']) ?>', {}, function(data) {
        $.each(data.result, function(i, row) {
            var station_row = $('#station_'+row.station.id);

            station_row.find('.nowplaying-title').text(row.current_song.title);
            station_row.find('.nowplaying-artist').text(row.current_song.artist);
        });

        setTimeout('nowPlaying()', 30*1000);
    });
}

$(function() {
    nowPlaying();
});
</script>