<?php

$this->layout(
    'main',
    [
        'title' => __('Storage Locations'),
        'manual' => true,
    ]
);

/** @var App\Http\RouterInterface $router */
$props = [
    'listUrl' => (string)$router->fromHere('api:admin:storage_locations'),
];

/** @var \App\Assets $assets */
$assets->addVueRender('Vue_AdminStorageLocations', '#admin-storage-locations', $props);
?>

<div id="admin-storage-locations"></div>
