<?php $this->layout('main', ['title' => _('Restart Broadcasting')]) ?>

<h3><?=_('Restart Broadcasting') ?></h3>
<p><?=_('Status messages related to this process are listed below.') ?></p>

<?php if ($flash->hasMessages()): ?>
    <?php foreach($flash->getMessages() as $message): ?>
        <div class="alert alert-<?=$message['color'] ?>">
            <?=nl2br($message['text']) ?>
        </div>
    <?php endforeach; ?>
<?php endif; ?>