<?php
/** @var \Entity\Station $station */
?>

<?php $this->layout('main', ['title' => _('Profile'), 'manual' => true]) ?>

<?php
/** @var \AzuraCast\Assets $assets */
$assets
    ->load('vue')
    ->load('radio');
?>

<div class="row">
    <div class="col-sm-6">

        <section class="card" role="region">
            <div class="card-header ch-alt">
                <h2><?=_('On the Air') ?></h2>
            </div>
            <div class="card-body card-padding nowplaying" id="profile-nowplaying">
                <div class="row">

                    <div class="col-sm-4">
                        <div class="m-l-25" style="position: relative;">
                            <div style="position: absolute; top: 0; left: -22px;"><i class="zmdi-hc-lg zmdi zmdi-collection-music"></i></div>

                            <h6><?=_('Now Playing') ?>:</h6>

                            <h4 class="media-heading">
                                {{ np.now_playing.song.title }}
                            </h4>
                            <div>
                                {{ np.now_playing.song.artist }}
                            </div>
                            <div class="nowplaying-progress" v-if="time_display">
                                {{ time_display }}
                            </div>
                        </div>
                    </div>

                    <div class="col-sm-4" v-if="np.playing_next">
                        <div class="m-l-25" style="position: relative;">
                            <div style="position: absolute; top: 0; left: -22px;"><i class="zmdi-hc-lg zmdi zmdi-skip-next"></i></div>

                            <h6><?=_('Playing Next') ?>:</h6>

                            <h4 class="media-heading">
                                {{ np.playing_next.song.title }}
                            </h4>
                            <div>
                                {{ np.playing_next.song.artist }}
                            </div>
                        </div>
                    </div>

                    <div class="col-sm-3">
                        <div class="m-l-25" style="position: relative;">
                            <div style="position: absolute; top: 0; left: -22px;"><i class="zmdi-hc-lg zmdi zmdi-headset"></i></div>

                            <h6><?=_('Listeners') ?>:</h6>

                            <h4><span>{{ np.listeners.total }}</span> <?=_('Total') ?></h4>
                            <div>
                                <span>{{ np.listeners.unique }}</span> <?=_('Unique') ?>
                            </div>
                        </div>
                    </div>

                </div>

            <?php if ($backend_type == 'liquidsoap' && $acl->userAllowed($user, 'manage station broadcasting', $station->getId())): ?>
                <div class="buttons pull-right p-t-15">
                    <a id="btn_skip_song" class="btn btn-sm btn-primary" role="button" href="<?=$url->named('api:stations:backend', ['station' => $station->getId(), 'do' => 'skip']) ?>"><i class="zmdi zmdi-skip-next"></i> <?=_('Skip Song') ?></a>
                </div>
                <div class="clearfix"></div>
            <?php endif; ?>
            </div>
        </section>

        <section class="card" role="region">
            <div class="card-header ch-alt">
                <h2><?=_('Profile') ?></h2>

                <?php if ($acl->userAllowed($user, 'manage station profile', $station->getId())): ?>
                <a class="btn bgm-blue btn-float" role="button" title="<?=_('Edit') ?>" href="<?=$url->named('stations:profile:edit', ['station' => $station->getId()]) ?>"><i class="zmdi zmdi-edit"></i></a>
                <?php endif; ?>
            </div>
            <table class="table table-striped table-responsive">
                <colgroup>
                    <col width="30%">
                    <col width="70%">
                </colgroup>
                <tbody>
                    <tr>
                        <td><?=_('Name') ?></td>
                        <td><?=$this->e($station->getName()) ?></td>
                    </tr>
                    <tr>
                        <td><?=_('Description') ?></td>
                        <td><?=$this->e($station->getDescription()) ?></td>
                    </tr>
                    <?php if ($backend->supportsRequests()): ?>
                    <tr>
                        <td><?=_('Song Requests') ?></td>
                        <td>
                        <?php if ($station->getEnableRequests()): ?>
                            <span class="text-success"><?=_('Enabled') ?></span>

                            <div class="form-field">
                                <textarea class="full-width form-control text-preformatted" style="height: 50px;"><iframe src="<?=$url->named('public:embedrequests', ['station' => $station->getShortName()], true) ?>" frameborder="0" allowtransparency="true" style="width: 100%; min-height: 850px; border: 0;"></iframe></textarea>
                            </div>
                        <?php else: ?>
                            <span class="text-danger"><?=_('Disabled') ?></span><br><small><?=_('Edit station profile to enable.') ?></small>
                        <?php endif; ?>
                        </td>
                    </tr>
                    <? endif; ?>
                    <?php if ($backend->supportsStreamers()): ?>
                    <tr>
                        <td><?=_('Streamers/DJs') ?></td>
                        <td>
                        <?php if ($station->getEnableStreamers()): ?>
                            <span class="text-success"><?=_('Enabled') ?></span><br>
                            <a href="<?=$url->named('stations:streamers:index', ['station' => $station->getId()]) ?>"><?=_('Manage streamer accounts') ?></a>
                        <?php else: ?>
                            <span class="text-danger"><?=_('Disabled') ?></span><br><small><?=_('Edit station profile to enable.') ?></small>
                        <?php endif; ?>
                        </td>
                    </tr>
                    <?php endif; ?>
                    <tr>
                        <td><?=_('Base Directory') ?></td>
                        <td class="text-preformatted"><?=$this->e($station->getRadioBaseDir()) ?></td>
                    </tr>
                    <tr>
                        <td><?=_('Media Directory') ?></td>
                        <td class="text-preformatted"><?=$this->e($station->getRadioMediaDir()) ?></td>
                    </tr>
                    <tr>
                        <td><?=_('Player Embed Code') ?></td>
                        <td class="form-field">
                            <textarea class="full-width form-control text-preformatted" style="height: 50px;"><iframe src="<?=$url->named('public:embed', ['station' => $station->getShortName()], true) ?>" frameborder="0" allowtransparency="true" style="width: 100%; min-height: 150px; border: 0;"></iframe></textarea>
                        </td>
                    </tr>
                </tbody>
            </table>
        </section>
    </div>
    <div class="col-sm-6">
        <?php if ($frontend_type == 'remote'): ?>
        <section class="card" role="region">
            <div class="card-header bgm-blue ch-alt">
                <h2>
                    <?=_('External Radio Server') ?>
                </h2>
            </div>
            <table class="table table-condensed table-striped">
                <colgroup>
                    <col width="10%">
                    <col width="90%">
                </colgroup>
                <thead>
                <tr>
                    <th>&nbsp;</th>
                    <th><?=_('Public URL') ?></th>
                </tr>
                </thead>
                <tbody>
                <?php foreach($stream_urls as $stream_url): ?>
                    <tr class="input">
                        <td>
                            <a class="btn-audio" href="#" data-url="<?=$this->e($stream_url) ?>">
                                <i class="zmdi zmdi-play"></i>
                            </a>
                        </td>
                        <td>
                            <a href="<?=$this->e($stream_url) ?>"><?=$this->e($stream_url) ?></a>
                        </td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        </section>
        <?php else: ?>
        <section class="card" role="region">
            <div class="card-header <?php if ($frontend_is_running): ?>bgm-green<?php else: ?>bgm-red<?php endif; ?> ch-alt">
                <h2>
                    <?php if ($frontend_type === 'icecast'): ?>
                        <?=_('Icecast (Broadcasting Service)') ?>
                    <?php elseif ($frontend_type === 'shoutcast2'): ?>
                        <?=_('SHOUTcast DNAS 2 (Broadcasting Service)') ?>
                    <?php endif; ?>
                    <br><small><?php if ($frontend_is_running): ?><?=_('Running') ?><?php else: ?><?=_('Not Running') ?><?php endif; ?></small>
                </h2>

                <?php if ($acl->userAllowed($user, 'manage station broadcasting', $station->getId())): ?>
                <ul class="actions">
                    <li class="dropdown">
                        <a href="" data-toggle="dropdown" aria-expanded="false">
                            <i class="zmdi zmdi-more-vert"></i>
                        </a>
                        <ul class="dropdown-menu dropdown-menu-right">
                            <li><a class="api-call" href="<?=$url->named('api:stations:frontend', ['station' => $station->getId(), 'do' => 'restart']) ?>"><?=_('Restart Service') ?></a></li>
                            <li><a class="api-call" href="<?=$url->named('api:stations:frontend', ['station' => $station->getId(), 'do' => 'start']) ?>"><?=_('Start Service') ?></a></li>
                            <li><a class="api-call" href="<?=$url->named('api:stations:frontend', ['station' => $station->getId(), 'do' => 'stop']) ?>"><?=_('Stop Service') ?></a></li>
                        </ul>
                    </li>
                </ul>
                <?php endif; ?>
            </div>

            <table class="table table-condensed table-striped">
                <colgroup>
                    <col width="10%">
                    <col width="90%">
                </colgroup>
                <thead>
                    <tr>
                        <th>&nbsp;</th>
                        <th><?=_('Public URL') ?></th>
                    </tr>
                </thead>
                <tbody>
                <?php foreach($stream_urls as $stream_url): ?>
                <tr class="input">
                    <td>
                        <a class="btn-audio" href="#" data-url="<?=$this->e($stream_url) ?>">
                            <i class="zmdi zmdi-play"></i>
                        </a>
                    </td>
                    <td>
                        <a href="<?=$this->e($stream_url) ?>"><?=$this->e($stream_url) ?></a>
                    </td>
                </tr>
                <?php endforeach; ?>
                </tbody>
            </table>

            <div class="card-body card-padding">
                <dl>
                    <dt><?=_('Stream Playlists') ?>:</dt>
                    <dd>
                        <a class="btn btn-xs btn-primary" href="<?=$url->named('public:playlist', ['station' => $station->getShortName(), 'format' => 'pls']) ?>">PLS</a>
                        <a class="btn btn-xs btn-primary" href="<?=$url->named('public:playlist', ['station' => $station->getShortName(), 'format' => 'm3u']) ?>">M3U</a>
                    </dd>
                </dl>

                <dl>
                    <dt><?=_('Administration URL') ?>:</dt>
                    <dd><a href="<?=$this->e($frontend->getAdminUrl()) ?>"><?=$this->e($frontend->getAdminUrl()) ?></a></dd>

                    <dt><?=_('Administrator Password') ?>:</dt>
                    <dd><?=$this->e($frontend_config['admin_pw']) ?></dd>

                    <dt><?=_('Source Password') ?>:</dt>
                    <dd><?=$this->e($frontend_config['source_pw']) ?></dd>
                </dl>
            </div>
        </section>
        <?php endif; ?>

        <?php if ($backend_type == 'none'): ?>
        <section class="card" role="region">
            <div class="card-header bgm-bluegray ch-alt">
                <h2><?=_('AutoDJ Disabled') ?></h2>
            </div>
            <div class="card-body card-padding">
                <p><?=_('AutoDJ has been disabled for this station. No music will automatically be played when a source is not live.') ?></p>
            </div>
        </section>
        <?php else: ?>
        <section class="card" role="region">
            <div class="card-header <?php if ($backend_is_running): ?>bgm-green<?php else: ?>bgm-red<?php endif; ?> ch-alt">
                <h2>
                <?php if ($backend_type == 'liquidsoap'): ?>
                    <?=_('Liquidsoap (AutoDJ Service)') ?><br>
                <?php endif; ?>
                    <small><?php if ($backend_is_running): ?><?=_('Running') ?><?php else: ?><?=_('Not Running') ?><?php endif; ?></small>
                </h2>

                <?php if ($acl->userAllowed($user, 'manage station broadcasting', $station->getId())): ?>
                <ul class="actions">
                    <li class="dropdown">
                        <a href="" data-toggle="dropdown" aria-expanded="false">
                            <i class="zmdi zmdi-more-vert"></i>
                        </a>
                        <ul class="dropdown-menu dropdown-menu-right">
                            <li><a class="api-call" href="<?=$url->named('api:stations:backend', ['station' => $station->getId(), 'do' => 'restart']) ?>"><?=_('Restart Service') ?></a></li>
                            <li><a class="api-call" href="<?=$url->named('api:stations:backend', ['station' => $station->getId(), 'do' => 'start']) ?>"><?=_('Start Service') ?></a></li>
                            <li><a class="api-call" href="<?=$url->named('api:stations:backend', ['station' => $station->getId(), 'do' => 'stop']) ?>"><?=_('Stop Service') ?></a></li>
                        </ul>
                    </li>
                </ul>
                <?php endif; ?>
            </div>
            <div class="card-body card-padding">
                <p><?=sprintf(_('LiquidSoap is currently shuffling from <b>%d uploaded songs</b> in <b>%d playlists</b>.'), $num_songs, $num_playlists) ?></p>

                <?php if ($acl->userAllowed($user, 'manage station media', $station->getId())): ?>
                    <div class="buttons">
                        <a class="btn btn-primary" href="<?=$url->named('stations:files:index', ['station' => $station->getId()]) ?>"><?=_('Music Files') ?></a>
                        <a class="btn btn-primary" href="<?=$url->named('stations:playlists:index', ['station' => $station->getId()]) ?>"><?=_('Playlists') ?></a>
                    </div>
                <?php endif; ?>
            </div>
        </section>
        <?php endif; ?>
    </div>
</div>

<script type="text/javascript" nonce="<?=$assets->getCspNonce() ?>">
var nowPlaying;

function iterateTimer() {
    var np_elapsed = nowPlaying.np.now_playing.elapsed;
    var np_total = nowPlaying.np.now_playing.duration;

    if (np_elapsed < np_total) {
        nowPlaying.np.now_playing.elapsed = np_elapsed + 1;
    }
}

function formatTime(time) {
    var sec_num = parseInt(time, 10);

    var hours = Math.floor(sec_num / 3600);
    var minutes = Math.floor((sec_num - (hours * 3600)) / 60);
    var seconds = sec_num - (hours * 3600) - (minutes * 60);

    if (hours < 10) {
        hours = "0" + hours;
    }
    if (minutes < 10) {
        minutes = "0" + minutes;
    }
    if (seconds < 10) {
        seconds = "0" + seconds;
    }
    return (hours !== "00" ? hours + ':' : "") + minutes + ':' + seconds;
}

$(function() {
    nowPlaying = new Vue({
        el: '#profile-nowplaying',
        data: <?=json_encode(['np' => $nowplaying]) ?>,
        computed: {
            "time_display": function() {
                var time_played = this.np.now_playing.elapsed;
                var time_total = this.np.now_playing.duration;

                if (!time_total) {
                    return null;
                }

                if (time_played > time_total) {
                    time_played = time_total;
                }

                return formatTime(time_played) + ' / ' + formatTime(time_total);
            }
        }
    });

    setInterval(iterateTimer, 1000);

    function loadNowPlaying() {
        $.getJSON('<?=$url->named('api:nowplaying:index', ['station' => $station->getId()]) ?>', function(row) {
            nowPlaying.np = row;

            if ('mediaSession' in navigator) {
                navigator.mediaSession.metadata = new MediaMetadata({
                    title: row.now_playing.song.title,
                    artist: row.now_playing.song.artist
                });
            }

            setTimeout(loadNowPlaying, 15000);
        });
    }

    setTimeout(loadNowPlaying, 15000);

    $('#btn_skip_song').on('click', function(e) {
        e.stopPropagation();
        var btn = $(this);

        btn.addClass('disabled');

        $.ajax({
            type: "POST",
            url: btn.attr('href'),
            success: function(data) {
                var notify_type = (data.success) ? 'success' : 'warning';
                notify(data.message, notify_type);

                btn.removeClass('disabled');
            },
            dataType: "json"
        });

        return false;
    });

});
</script>