<?php $this->layout('main', ['title' => __('Listeners'), 'manual' => true]) ?>

<?php
/** @var \App\Assets $assets */
$assets
    ->load('vue')
    ->load('daterangepicker')
    ->load('highmaps')
    ->load('highcharts_theme_'.$customization->getTheme())
    ->addInlineJs($this->fetch('stations/reports/listeners.js', ['station' => $station]));
?>

<div class="row">
    <div class="col-sm-12">
        <div class="card">
            <div class="card-header ch-alt">
                <div class="row">
                    <div class="col-md-8">
                        <h2><?=__('Listeners') ?></h2>
                        <div><span id="listener-count">0</span> Unique</div>
                    </div>
                    <div class="col-md-4 text-right">
                        <a class="btn btn-default" id="reportrange" href="#">
                            <i class="zmdi zmdi-calendar"></i> <span><?=__('Live Listeners') ?></span> <i class="caret"></i>
                        </a>
                    </div>
                </div>
            </div>
            <div id="map" style="height: 350px;">
            </div>
            <table class="data-table table table-responsive table-striped" id="app-datatable">
                <thead>
                    <tr>
                        <th><?=__('IP') ?></th>
                        <th><?=__('Time (sec)') ?></th>
                        <th><?=__('User Agent') ?></th>
                        <th><?=__('Location') ?></th>
                    </tr>
                </thead>
                <tbody>
                    <tr v-for="listener in listeners">
                        <td>{{ listener.ip }}</td>
                        <td>{{ listener.connected_time }}</td>
                        <td>
                            <span v-if="listener.is_mobile" title="<?=__('Mobile Device') ?>">
                                <i class="zmdi zmdi-smartphone"></i>
                            </span>
                            <span v-else title="<?=__('Desktop Device') ?>">
                                <i class="zmdi zmdi-desktop-windows"></i>
                            </span>
                            {{ listener.user_agent }}
                        </td>
                        <td>
                            <span v-if="listener.location.status == 'success'">
                                {{ listener.location.region }}, {{ listener.location.country }}
                            </span>
                            <span v-else-if="listener.location.message">
                                {{ listener.location.message }}
                            </span>
                            <span v-else>
                                <?=__('Unknown') ?>
                            </span>
                        </td>
                    </tr>
                </tbody>
            </table>
            <div class="card-body card-padding-sm text-muted">
                <?=__('This product includes GeoLite2 data created by MaxMind, available from %s.', '<a href="http://www.maxmind.com">http://www.maxmind.com</a>') ?>
            </div>
        </div>
    </div>
</div>
