<?php $this->layout('main', ['title' => __('Listeners'), 'manual' => true]) ?>

<?php
/** @var \Azura\Assets $assets */
$assets
    ->load('vue')
    ->load('daterangepicker')
    ->load('highmaps')
    ->load('highcharts_theme_'.$customization->getTheme())
    ->addInlineJs($this->fetch('stations/reports/listeners.js', ['station' => $station]));
?>

<div class="row">
    <div class="col-sm-12">
        <div class="card">
            <div class="card-body">
                <a class="btn btn-primary float-right dropdown-toggle" id="reportrange" href="#">
                    <i class="material-icons" aria-hidden="true">date_range</i> <span><?=__('Live Listeners') ?></span> <i class="caret"></i>
                </a>
                <h2 class="card-title"><?=__('Listeners') ?></h2>
                <h3 class="card-subtitle"><span id="listener-count">0</span> Unique</h3>
            </div>
            <div id="map" style="height: 350px;">
            </div>
            <table class="data-table table table-responsive table-striped" id="app-datatable">
                <thead>
                    <tr>
                        <th><?=__('IP') ?></th>
                        <th><?=__('Time (sec)') ?></th>
                        <th><?=__('User Agent') ?></th>
                        <th><?=__('Location') ?></th>
                    </tr>
                </thead>
                <tbody>
                    <tr v-for="listener in listeners">
                        <td>{{ listener.ip }}</td>
                        <td>{{ listener.connected_time }}</td>
                        <td>
                            <span v-if="listener.is_mobile">
                                <i class="material-icons" aria-hidden="true">smartphone</i>
                                <span class="sr-only"><?=__('Mobile Device') ?></span>
                            </span>
                            <span v-else>
                                <i class="material-icons" aria-hidden="true">desktop_windows</i>
                                <span class="sr-only"><?=__('Desktop Device') ?></span>
                            </span>
                            {{ listener.user_agent }}
                        </td>
                        <td>
                            <span v-if="listener.location.status == 'success'">
                                {{ listener.location.region }}, {{ listener.location.country }}
                            </span>
                            <span v-else-if="listener.location.message">
                                {{ listener.location.message }}
                            </span>
                            <span v-else>
                                <?=__('Unknown') ?>
                            </span>
                        </td>
                    </tr>
                </tbody>
            </table>
            <div class="card-body card-padding-sm text-muted">
                <?=__('This product includes GeoLite2 data created by MaxMind, available from %s.', '<a href="http://www.maxmind.com">http://www.maxmind.com</a>') ?>
            </div>
        </div>
    </div>
</div>
