<?php $this->layout('main', ['title' => __('Statistics Overview'), 'manual' => true]) ?>

<?php
/** @var \Azura\Assets $assets */
$assets
    ->load('highcharts')
    ->load('highcharts_theme_'.$customization->getTheme())
    ->addInlineJs($this->fetch('stations/reports/overview.js', [
        'daily_ranges' => $daily_ranges,
        'hourly_averages' => $hourly_averages,
        'daily_averages' => $daily_averages,
        'day_of_week_stats' => $day_of_week_stats,
        'averages_by_hour' => $averages_by_hour,
    ]));
?>

<div class="row">
    <div class="col-sm-12">
        <section class="card mb-3" role="region">
            <div class="card-header">
                <ul class="nav nav-pills card-header-pills">
                    <li class="nav-item">
                        <a class="nav-link active" role="tab" data-toggle="tab" aria-expanded="true" aria-controls="listeners-by-day" href="#listeners-by-day"><?=__('Listeners by Day') ?></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" role="tab" data-toggle="tab" aria-controls="listeners-by-hour" href="#listeners-by-hour"><?=__('Listeners by Hour') ?></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" role="tab" data-toggle="tab" aria-controls="listeners-by-day-of-week" href="#listeners-by-day-of-week"><?=__('Listeners by Day of Week') ?></a>
                    </li>
                </ul>
            </div>
            <div class="tab-content">
                <div class="tab-pane card-body active" id="listeners-by-day" role="tabpanel">
                    <div id="listeners_by_day" style="height: 250px;"></div>
                </div>
                <div class="tab-pane card-body" id="listeners-by-hour" role="tabpanel">
                    <div id="listeners_by_hour" style="height: 250px;"></div>
                </div>
                <div class="tab-pane card-body" id="listeners-by-day-of-week" role="tabpanel">
                    <div id="listeners_by_day_of_week" style="height: 250px;"></div>
                </div>
            </div>
        </section>
    </div>
</div>

<div class="row">
    <div class="col-sm-6">
        <section class="card mb-3" role="region">
            <div class="card-body">
                <h2 class="card-title">
                    <?=__('Best Performing Songs') ?>
                    <small><?=__('in the last 48 hours') ?></small>
                </h2>
            </div>
            <div class="table-responsive">
                <table class="table table-striped table-condensed table-nopadding">
                    <colgroup>
                        <col width="20%">
                        <col width="80%">
                    </colgroup>
                    <thead>
                        <tr>
                            <th><?=__('Change') ?></th>
                            <th><?=__('Song') ?></th>
                        </tr>
                    </thead>
                    <tbody>
                    <?php foreach($best_performing_songs as $song_row): ?>
                        <tr>
                            <td class="text-center text-success">
                                <i class="material-icons" aria-hidden="true">keyboard_arrow_up</i> <?=abs($song_row['stat_delta']) ?><br>
                                <small><?=$song_row['stat_start'] ?> to <?=$song_row['stat_end'] ?>
                            </td>
                            <td>
                                <?php if ($song_row['song']['title']): ?>
                                    <b><?=$song_row['song']['title'] ?></b><br>
                                    <?=$song_row['song']['artist'] ?>
                                <?php else: ?>
                                    <?=$song_row['song']['text'] ?>
                                <?php endif; ?>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </section>
    </div>
    <div class="col-sm-6">
        <section class="card mb-3" role="region">
            <div class="card-body">
                <h2 class="card-title">
                    <?=__('Worst Performing Songs') ?>
                    <small><?=__('in the last 48 hours') ?></small>
                </h2>
            </div>
            <div class="table-responsive">
                <table class="table table-striped table-condensed table-nopadding">
                    <colgroup>
                        <col width="20%">
                        <col width="80%">
                    </colgroup>
                    <thead>
                        <tr>
                            <th><?=__('Change') ?></th>
                            <th><?=__('Song') ?></th>
                        </tr>
                    </thead>
                    <tbody>
                    <?php foreach($worst_performing_songs as $song_row): ?>
                        <tr>
                            <td class="text-center text-danger">
                                <i class="material-icons" aria-hidden="true">keyboard_arrow_down</i> <?=abs($song_row['stat_delta']) ?><br>
                                <small><?=$song_row['stat_start'] ?> to <?=$song_row['stat_end'] ?>
                            </td>
                            <td>
                                <?php if ($song_row['song']['title']): ?>
                                    <b><?=$song_row['song']['title'] ?></b><br>
                                    <?=$song_row['song']['artist'] ?>
                                <?php else: ?>
                                    <?=$song_row['song']['text'] ?>
                                <?php endif; ?>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </section>
    </div>
</div>

<div class="row">
    <div class="col-sm-12">
        <section class="card" role="region">
            <div class="card-body">
                <h2 class="card-title">
                    <?=__('Most Played Songs') ?>
                    <small><?=__('in the last month') ?></small>
                </h2>
            </div>
            <div class="table-responsive">
                <table class="table table-striped table-condensed table-nopadding">
                    <colgroup>
                        <col width="10%">
                        <col width="90%">
                    </colgroup>
                    <thead>
                        <tr>
                            <th><?=__('Plays') ?></th>
                            <th><?=__('Song') ?></th>
                        </tr>
                    </thead>
                    <tbody>
                    <?php foreach($song_totals['played'] as $song_row): ?>
                        <tr>
                            <td class="text-center"><?=$song_row['records'] ?></td>
                            <td>
                            <?php if ($song_row['song']['title']): ?>
                                <b><?=$song_row['song']['title'] ?></b><br>
                                <?=$song_row['song']['artist'] ?>
                            <?php else: ?>
                                <?=$song_row['song']['text'] ?>
                            <?php endif; ?>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </section>
    </div>
</div>
