<?php $this->layout('main', ['title' => __('Song Playback Timeline'), 'manual' => true]) ?>

<?php
/** @var \App\Assets $assets */
$assets
    ->load('daterangepicker')
    ->load('bootgrid')
    ->addInlineJs($this->fetch('stations/reports/timeline.js'));
?>

<div class="card">
    <div class="card-body">
        <a class="btn btn-primary float-right dropdown-toggle" id="reportrange" href="#">
            <i class="material-icons">date_range</i> <span><?=__('Last 14 Days') ?></span>
        </a>
        <a class="btn btn-primary float-right mr-2" id="btn-export" href="<?=$router->fromHere('api:stations:history', [], ['format' => 'csv']) ?>" target="_blank" title="<?=__('Download CSV') ?>">
            <i class="zmdi zmdi-download"></i> <?=__('Download CSV') ?>
        </a>
        <h2 class="card-title"><?=__('Song Playback Timeline') ?></h2>
    </div>
    <div class="table-responsive">
        <table class="data-table table table-striped">
            <colgroup>
                <col width="15%">
                <col width="10%">
                <col width="10%">
                <col width="40%">
                <col width="25%">
            </colgroup>
            <thead>
                <tr>
                    <th data-column-id="date_time" data-formatter="datetime"><?=__('Date/Time') ?></th>
                    <th data-column-id="listeners_start"><?=__('Listeners') ?></th>
                    <th data-column-id="delta" data-formatter="delta"><?=__('Change') ?></th>
                    <th data-column-id="song" data-formatter="song_title"><?=__('Song Title') ?></th>
                    <th data-column-id="playlists" data-formatter="playlists"><?=__('Source') ?></th>
                </tr>
            </thead>
            <tbody>
            </tbody>
        </table>
    </div>
</div>
