<?php $this->layout('main', ['title' => __('Song Playback Timeline'), 'manual' => true]) ?>

<?php
/** @var \App\Assets $assets */
$assets
    ->load('bootgrid');
?>

<div class="card">
    <div class="card-header ch-alt">
        <h2><?=__('Song Playback Timeline') ?></h2>

        <ul class="actions">
            <li>
                <a href="<?=$router->fromHere(null, ['format' => 'csv']) ?>" title="<?=__('Download CSV') ?>">
                    <span class="sr-only"><?=__('Download CSV') ?></span>
                    <i class="zmdi zmdi-download"></i>
                </a>
            </li>
        </ul>
    </div>
    <div class="table-responsive">
        <table class="data-table table table-striped">
            <colgroup>
                <col width="15%">
                <col width="10%">
                <col width="10%">
                <col width="40%">
                <col width="25%">
            </colgroup>
            <thead>
                <tr>
                    <th data-column-id="date_time"><?=__('Date/Time') ?></th>
                    <th data-column-id="listeners"><?=__('Listeners') ?></th>
                    <th data-column-id="delta"><?=__('Change') ?></th>
                    <th data-column-id="song"><?=__('Song Title') ?></th>
                    <th data-column-id="playlists"><?=__('Source') ?></th>
                </tr>
            </thead>
            <tbody>
            <?php foreach($songs as $song_row): ?>
                <tr class="input" id="song_<?=$song_row['timestamp'] ?>">
                    <td class="text-center"><?=$customization->formatTime($song_row['timestamp_start']) ?></td>
                    <td class="text-center"><big><?=$song_row['stat_start'] ?></big></td>
                    <td class="text-center">
                        <big>
                    <?php if ($song_row['stat_delta'] > 0): ?>
                        <span class="text-success"><i class="icon-caret-up"></i> <?=$song_row['stat_delta'] ?></span>
                    <?php elseif ($song_row['stat_delta'] < 0): ?>
                        <span class="text-danger"><i class="icon-caret-down"></i> <?=abs($song_row['stat_delta']) ?></span>
                    <?php else: ?>
                        0
                    <?php endif; ?>
                        </big>
                    </td>
                    <td>
                    <?php if ($song_row['song']['title']): ?>
                        <b><?=$song_row['song']['title'] ?></b><br>
                        <?=$song_row['song']['artist'] ?>
                    <?php else: ?>
                        <?=$song_row['song']['text'] ?>
                    <?php endif; ?>
                    </td>
                    <td>
                    <?php if (isset($song_row['request'])): ?>
                        <?=sprintf(__('Request: %s'), date('D g:ia', $song_row['request']['timestamp'])) ?>
                    <?php elseif (isset($song_row['playlist'])): ?>
                        <?=sprintf(__('Playlist: %s'), $song_row['playlist']['name']) ?>
                    <?php else: ?>
                        <?=__('Live Broadcast') ?>
                    <?php endif; ?>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>

<script type="text/javascript" nonce="<?=$assets->getCspNonce() ?>">
    $(function() {
        $(".data-table").bootgrid({
            caseSensitive: false,
            sorting: false,
            css: {
                icon: 'zmdi icon',
                iconColumns: 'zmdi-view-module',
                iconDown: 'zmdi-sort-amount-desc',
                iconRefresh: 'zmdi-refresh',
                iconUp: 'zmdi-sort-amount-asc'
            }
        });
    });
</script>
