<?php $this->layout('main', ['title' => __('Dashboard'), 'manual' => true]); ?>

<?php
/** @var \App\Customization $customization */
/** @var \App\Assets $assets */
$assets
    ->load('vue')
    ->load('radio')
    ->addInlineJs($this->fetch('frontend/index/index.js', ['stations' => $stations]));

if ($metrics) {
    $assets
        ->load('highcharts')
        ->load('highcharts_theme_'.$customization->getTheme())
        ->addInlineJs($this->fetch('frontend/index/index_metrics.js', ['metrics' => $metrics]));
}
?>

<div class="block-header">
    <h2><?=__('Dashboard') ?></h2>
</div>

<?php if ($metrics): ?>
<div class="row">
    <div class="col-sm-6">
        <section class="card" role="region">
            <div class="card-header ch-alt">
                <h2><?=__('Listeners Across All Stations') ?></h2>
            </div>
            <div class="card-body card-padding-sm">
                <div id="network_chart" style="height: 250px;"></div>
            </div>
        </section>
    </div>
    <div class="col-sm-6">
        <section class="card" role="region">
            <div class="card-header ch-alt">
                <h2><?=__('Listeners Per Station') ?></h2>
            </div>
            <div class="card-body card-padding-sm">
                <div id="station_chart" style="height: 250px;"></div>
            </div>
        </section>
    </div>
</div>
<?php endif; ?>

<div class="row">
    <div class="col-sm-12">
        <section class="card" role="region">
            <div class="card-header ch-alt">
                <h2><?=__('Station Overview') ?></h2>

                <ul class="actions">
                <?php if ($acl->userAllowed($user, 'administer stations')): ?>
                    <li><a class="" title="<?=sprintf(__('Add %s'), __('Station')) ?>" href="<?=$router->named('admin:stations:add') ?>"><i class="zmdi zmdi-plus"></i></a></li>
                <?php endif; ?>
                </ul>
            </div>
            <div class="table-responsive">
                <table class="table table-striped" id="station_dashboard">
                    <colgroup>
                        <col width="5%">
                        <col width="30%">
                        <col width="10%">
                        <col width="40%">
                        <col width="15%">
                    </colgroup>
                    <thead>
                        <tr>
                            <th>&nbsp;</th>
                            <th><?=__('Station Name') ?></th>
                            <th class="text-center"><?=__('Listeners') ?></th>
                            <th><?=__('Now Playing') ?></th>
                            <th><?=__('Options') ?></th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr class="align-middle" v-bind:id="'station_' + row.station.id" v-for="row in stations" >
                            <td class="text-center">
                                <a class="btn-audio" role="button" title="<?=__('Play/Pause') ?>" href="#" v-bind:data-url="row.stream_url">
                                    <i class="zmdi zmdi-play"></i>
                                </a>
                            </td>
                            <td>
                                <big><a v-bind:href="row.public_url" target="_blank">{{ row.station.name }}</a></big>
                            </td>
                            <td class="text-center">
                                <span class="nowplaying-listeners">{{ row.np.listeners.current }}</span>
                            </td>
                            <td>
                                <strong><span class="nowplaying-title">{{ row.np.now_playing.song.title }}</span></strong><br>
                                <span class="nowplaying-artist">{{ row.np.now_playing.song.artist }}</span>
                            </td>
                            <td>
                                <a class="btn btn-primary" role="button" v-bind:href="row.manage_url"><?=__('Manage') ?></a>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </section>
    </div>
</div>
