<?php
/** @var \App\Assets $assets */
$assets
    ->addInlineJs($this->fetch('partials/station_form.js'), 99);

$this->start('stepper');
?>
<div class="stepper-horiz">
    <div class="stepper done">
        <div class="stepper-icon">
            <i class="material-icons" aria-hidden="true">check</i>
        </div>
        <span class="stepper-text"><?=__('Create Account') ?></span>
    </div>
    <div class="stepper active">
        <div class="stepper-icon">
            <span>2</span>
        </div>
        <span class="stepper-text"><?=__('Create Station') ?></span>
    </div>
    <div class="stepper">
        <div class="stepper-icon">
            <span>3</span>
        </div>
        <span class="stepper-text"><?=__('System Settings') ?></span>
    </div>
</div>
<?php
$this->stop();
$this->start('prefix');
?>
<div class="card-body">
    <p>
        <?=__('Continue the setup process by creating your first radio station below. You can edit any of these details later.') ?>
    </p>
</div>
<?php
$this->stop();

echo $this->fetch('system/form_page', [
    'title'     => __('Create a New Radio Station'),
    'form'      => $form,
    'prefix'    => $this->section('prefix'),
    'stepper'   => $this->section('stepper'),
]);
?>
