<section class="card" role="region">
    <div class="card-header ch-alt">
        <h2><?=__('Profile') ?></h2>

        <?php if ($acl->userAllowed($user, 'manage station profile', $station->getId())): ?>
            <a class="btn bgm-blue btn-float" role="button" title="<?=__('Edit') ?>" href="<?=$router->fromHere('stations:profile:edit') ?>">
                <span class="sr-only"><?=__('Edit') ?></span>
                <i class="zmdi zmdi-edit"></i>
            </a>
        <?php endif; ?>
    </div>
    <table class="table table-striped table-responsive">
        <colgroup>
            <col width="30%">
            <col width="70%">
        </colgroup>
        <tbody>
        <tr>
            <td><?=__('Name') ?></td>
            <td><?=$this->e($station->getName()) ?></td>
        </tr>
        <tr>
            <td><?=__('Description') ?></td>
            <td><?=$this->e($station->getDescription()) ?></td>
        </tr>
        <?php if ($backend->supportsRequests()): ?>
            <tr>
                <td><?=__('Song Requests') ?></td>
                <td>
                    <?php if ($station->getEnableRequests()): ?>
                        <span class="text-success"><?=__('Enabled') ?></span>

                        <div class="form-field">
                            <textarea class="full-width form-control text-preformatted" style="height: 50px;"><iframe src="<?=$router->named('public:embedrequests', ['station' => $station->getShortName()], [], true) ?>" frameborder="0" allowtransparency="true" style="width: 100%; min-height: 850px; border: 0;"></iframe></textarea>
                        </div>
                    <?php else: ?>
                        <span class="text-danger"><?=__('Disabled') ?></span><br><small><?=__('Edit station profile to enable.') ?></small>
                    <?php endif; ?>
                </td>
            </tr>
        <? endif; ?>
        <?php if ($backend->supportsStreamers()): ?>
            <tr>
                <td><?=__('Streamers/DJs') ?></td>
                <td>
                    <?php if ($station->getEnableStreamers()): ?>
                        <span class="text-success"><?=__('Enabled') ?></span><br>
                        <a href="<?=$router->fromHere('stations:streamers:index') ?>"><?=__('Manage streamer accounts') ?></a>
                    <?php else: ?>
                        <span class="text-danger"><?=__('Disabled') ?></span><br><small><?=__('Edit station profile to enable.') ?></small>
                    <?php endif; ?>
                </td>
            </tr>
        <?php endif; ?>
        <tr>
            <td><?=__('Base Directory') ?></td>
            <td class="text-preformatted"><?=$this->e($station->getRadioBaseDir()) ?></td>
        </tr>
        <tr>
            <td><?=__('Media Directory') ?></td>
            <td class="text-preformatted"><?=$this->e($station->getRadioMediaDir()) ?></td>
        </tr>
        <tr>
            <td><?=__('Player Embed Code') ?></td>
            <td class="form-field">
                <textarea class="full-width form-control text-preformatted" style="height: 50px;"><iframe src="<?=$router->named('public:embed', ['station' => $station->getShortName()], [], true) ?>" frameborder="0" allowtransparency="true" style="width: 100%; min-height: 150px; border: 0;"></iframe></textarea>
            </td>
        </tr>
        </tbody>
    </table>
</section>
