<?php
/**
 * @var App\Http\RouterInterface $router
 * @var App\Environment $environment
 * @var string $token
 */

?><?= __('Account Recovery') ?>

<?= sprintf(__('An account recovery link has been requested for your account on "%s".'), $environment->getAppName()) ?>

<?= __('Click the link below to log in to your account.') ?>

<?= $router->named(
    routeName: 'account:recover',
    routeParams: ['token' => $token],
    absolute: true
)?>
