<?
$title = 'Manage Stations';
$manual = true;
?>

<div class="block-header">
    <h2>Manage Stations</h2>
</div>

<div class="card">
    <div class="card-header ch-alt">
        <h2>All Stations</h2>

        <a class="btn bgm-blue btn-float" href="<?=$this->url->routeFromHere(['action' => 'edit']) ?>"><i class="zmdi zmdi-plus"></i></a>
    </div>
    <div class="table-responsive">
        <table class="table table-striped">
            <colgroup>
                <col width="25%">
                <col width="75%">
            </colgroup>
            <thead>
            <tr>
                <th>Actions</th>
                <th>Station</th>
            </tr>
            </thead>
            <tbody>
            <? foreach((array)$stations as $record): ?>
                <tr class="input">
                    <td class="center">
                        <div class="btn-group">
                            <?=$this->viewHelper->button(array(
                                'type'      => 'small',
                                'class'     => 'btn-primary',
                                'target'    => '_blank',
                                'href'      => $this->viewHelper->route(array('module' => 'stations', 'station' => $record['id'])),
                                'text'      => 'Manage',
                            )) ?>
                            <?=$this->viewHelper->button(array(
                                'type'      => 'small',
                                'class'     => 'btn-default',
                                'href'      => $this->viewHelper->routeFromHere(array('action' => 'edit', 'id' => $record['id'])),
                                'text'      => 'Edit',
                            )) ?>
                            <?=$this->viewHelper->button(array(
                                'type'      => 'small',
                                'class'     => 'btn-danger confirm-delete',
                                'href'      => $this->viewHelper->routeFromHere(array('action' => 'delete', 'id' => $record['id'])),
                                'text'      => 'Delete',
                            )) ?>
                        </div>
                    </td>
                    <td>
                        <big><?=$record['name'] ?></big>
                    </td>
                </tr>
            <? endforeach; ?>
            </tbody>
        </table>
    </div>
</div>