<?
$this->headTitle('Manage Stations');
?>

<div class="buttons">
    <?=$this->button(array(
        'type'      => 'link',
        'class'     => 'large success',
        'href'      => $this->routeFromHere(array('action' => 'edit')),
        'icon'      => 'icon-plus-sign',
        'text'      => 'Add New Station',
    )) ?>
</div>

<h2>Current Active Stations</h2>

<div class="row-fluid">
<? foreach($this->categories as $cat_name => $stations): ?>
    <div class="span6">
        <h3><?=ucfirst($cat_name) ?></h3>
        <table class="table table-striped table-bordered table-condensed">
            <colgroup>
                <col width="30%" />
                <col width="10%" />
                <col width="60%" />
            </colgroup>
            <thead>
                <tr>
                    <th>Actions</th>
                    <th>Image</th>
                    <th>Station</th>
                </tr>
            </thead>
            <tbody>
            <? foreach($stations as $record): ?>
                <tr class="input">
                    <td class="center">
                        <div class="btn-group">
                            <?=$this->button(array(
                                'type'      => 'small',
                                'href'      => $this->routeFromHere(array('action' => 'edit', 'id' => $record['id'])),
                                'text'      => 'Edit',
                            )) ?>
                            <?=$this->button(array(
                                'type'      => 'small',
                                'class'     => 'danger confirm-delete',
                                'href'      => $this->routeFromHere(array('action' => 'delete', 'id' => $record['id'])),
                                'text'      => 'Delete',
                            )) ?>
                        </div>
                    </td>
                    <td class="center"><img src="<?=\DF\Url::content($record['image_url']) ?>" style="max-width: 70px;"></td>
                    <td>
                        <div><big><?=$record['name'] ?></big></div>
                        <div>Stream type: <?=$record['type'] ?></div>
                    <? if ($record['twitter_url']): ?>
                        <div class="text-success"><i class="icon-check-sign"></i> Has Twitter</div>
                    <? else: ?>
                        <div class="text-error"><i class="icon-exclamation-sign"></i> Needs Twitter</div>
                    <? endif; ?>
                    <? if ($record['gcal_url']): ?>
                        <div class="text-success"><i class="icon-check-sign"></i> Has Calendar</div>
                    <? else: ?>
                        <div class="text-error"><i class="icon-exclamation-sign"></i> Needs Calendar</div>
                    <? endif; ?>
                    </td>
                </tr>
            <? endforeach; ?>
            </tbody>
        </table>
    </div>
<? endforeach; ?>
</div>

<h2>Stations Pending Review</h2>

<table class="table table-striped table-bordered table-condensed">
    <colgroup>
        <col width="14%" />
        <col width="7%" />
        <col width="44%" />
        <col width="35%" />
    </colgroup>
    <thead>
        <tr>
            <th>Actions</th>
            <th>Image</th>
            <th>Station</th>
            <th>Votes</th>
        </tr>
    </thead>
    <tbody>
    <? foreach($this->pending_stations as $record): ?>
        <tr class="input">
            <td class="center">
                <div class="btn-group">
                    <?=$this->button(array(
                        'type'      => 'small',
                        'href'      => $this->routeFromHere(array('action' => 'edit', 'id' => $record['id'])),
                        'text'      => 'Edit',
                    )) ?>
                    <?=$this->button(array(
                        'type'      => 'small',
                        'class'     => 'danger confirm-delete',
                        'href'      => $this->routeFromHere(array('action' => 'delete', 'id' => $record['id'])),
                        'text'      => 'Delete',
                    )) ?>
                </div>
            </td>
            <td class="center"><img src="<?=\DF\Url::content($record['image_url']) ?>" style="max-width: 70px;"></td>
            <td>
                <div><big><?=$record['name'] ?></big></div>
                <div><?=$record['description'] ?></div>
                <div><?=$record['station_notes'] ?></div>
            </td>
            <td>
            <? foreach((array)$record['intake_votes'] as $station_id => $vote): ?>
                <div class="<? if ($vote['decision'] == 'Accept'): ?>text-success<? else: ?>text-danger<? endif; ?>"><b><?=$vote['name'] ?></b>: <?=$vote['decision'] ?> - <?=$vote['comments'] ?></div>
            <? endforeach; ?>
            </td>
        </tr>
    <? endforeach; ?>
    </tbody>
</table>