<table class="table table-striped table-bordered table-condensed">
    <colgroup>
        <col width="17%">
        <col width="8%">
        <col width="55%">
        <col width="10%">
        <col width="10%">
    </colgroup>
    <thead>
        <tr>
            <th>Actions</th>
            <th>Image</th>
            <th>Station</th>
            <th>Twitter</th>
            <th>Calendar</th>
        </tr>
    </thead>
    <tbody>
    <? foreach((array)$stations as $record): ?>
        <tr class="input">
            <td class="center">
                <div class="btn-group">
                    <?=$this->viewHelper->button(array(
                        'type'      => 'small',
                        'class'     => 'btn-primary',
                        'target'    => '_blank',
                        'href'      => $this->viewHelper->route(array('module' => 'stations', 'station' => $record['id'])),
                        'text'      => 'Manage',
                    )) ?>
                    <?=$this->viewHelper->button(array(
                        'type'      => 'small',
                        'href'      => $this->viewHelper->routeFromHere(array('action' => 'edit', 'id' => $record['id'])),
                        'text'      => 'Edit',
                    )) ?>
                    <?=$this->viewHelper->button(array(
                        'type'      => 'small',
                        'class'     => 'danger confirm-delete',
                        'href'      => $this->viewHelper->routeFromHere(array('action' => 'delete', 'id' => $record['id'])),
                        'text'      => 'Delete',
                    )) ?>
                </div>
            </td>
            <td class="center"><img src="<?=\DF\Url::content($record['image_url']) ?>" style="display: inline; max-width: 70px;"></td>
            <td>
                <div><big><?=$record['name'] ?></big></div>
                <div><a href="<?=$this->viewHelper->route(array('module' => 'stations', 'controller' => 'streams', 'action' => 'index','station' => $record['id'])) ?>" target="_blank"><?=count($record['streams']) ?> Streams</a></div>
            </td>
            <td class="center">
                <? if ($record['twitter_url']): ?>
                    <div class="large-icon text-success"><i class="icon-check-sign"></i></div>
                <? else: ?>
                    <div class="large-icon text-error"><i class="icon-exclamation-sign"></i></div>
                <? endif; ?>
            </td>
            <td class="center">
                <? if ($record['gcal_url']): ?>
                    <div class="large-icon text-success"><i class="icon-check-sign"></i></div>
                <? else: ?>
                    <div class="large-icon text-error"><i class="icon-exclamation-sign"></i></div>
                <? endif; ?>
            </td>
        </tr>
    <? endforeach; ?>
    </tbody>
</table>