<?php
$title = 'Error';
$page_class = 'four-zero-content';
?>

<div class="four-zero">
    <h2>500</h2>
    <small>
        <?=$exception->getMessage() ?><br>
        <?=$exception->getFile() ?> : <?=$exception->getLine() ?>
    </small>

    <footer>
        <a href="javascript:history.back()"><i class="zmdi zmdi-arrow-back"></i></a>
        <a href="<?=$url->route([]) ?>"><i class="zmdi zmdi-home"></i></a>
    </footer>
</div>