<?php $this->layout('minimal', ['title' => 'Error', 'page_class' => 'four-zero-content']) ?>
<div class="four-zero">
    <div class="fz-block">
        <h2>500</h2>
        <small>
            <?=$exception->getMessage() ?><br>
            <?=$exception->getFile() ?> : <?=$exception->getLine() ?>
        </small>

        <div class="fzb-links">
            <a href="javascript:history.back()"><i class="zmdi zmdi-arrow-back"></i></a>
            <a href="<?=$url->named('home') ?>"><i class="zmdi zmdi-home"></i></a>
        </div>
    </div>
</div>