<?php $this->layout('main', ['title' => $title, 'header' => $header]); ?>

<?php if ($render_mode == 'edit'): ?>
    <?=$this->fetch('partials/form', ['form' => $form]) ?>
<?php else: ?>
    <?=$this->fetch('partials/form_view', ['form' => $form]) ?>
<?php endif; ?>

<?php
/** @var \AzuraCast\Assets $assets */
$assets
    ->load('chosen')
    ->load('zxcvbn');
?>

<script type="text/javascript" nonce="<?=$assets->getCspNonce() ?>">
$(function() {
    $('select').chosen({
        placeholder_text_single: '<?=_('Select...') ?>',
        placeholder_text_multiple: '<?=_('Select...') ?>',
        no_results_text: '<?=_('No results found!') ?>'
    });
});
</script>