<?php $this->layout('main'); ?>

<?php if ($render_mode == 'edit'): ?>
    <?=$this->fetch('partials/form') ?>
<?php else: ?>
    <?=$this->fetch('partials/form_view') ?>
<?php endif; ?>

<?php $this->start('custom_js') ?>
<script type="text/javascript" src="<?=$url->content('vendors/bower_components/chosen/chosen.jquery.min.js') ?>"></script>
<?php $this->stop('custom_js') ?>
<?php $this->start('custom_css') ?>
<link rel="stylesheet" type="text/css" href="<?=$url->content('vendors/bower_components/chosen/chosen.min.css') ?>">
<?php $this->stop('custom_css') ?>

<script type="text/javascript">
$(function() {
    $('select').chosen({
        placeholder_text_single: '<?=_('Select...') ?>',
        placeholder_text_multiple: '<?=_('Select...') ?>',
        no_results_text: '<?=_('No results found!') ?>'
    });
});
</script>