---
- name: Add Redis PPA repository
  apt_repository:
    repo: "ppa:chris-lea/redis-server"
    update_cache: true

- name: Install Redis
  apt:
    name: redis-server

- name: Enable and start all core services
  service:
    name: "{{ _current_service }}"
    enabled: true
    state: started
  loop:
    - "redis-server"
    - "redis"
  loop_control:
    loop_var: _current_service
