<?
$title = 'Manage Users';
$manual = true;
?>

<div class="block-header">
    <h2>Manage Users</h2>
</div>

<div class="card">
    <div class="card-header ch-alt">
        <? if ($q): ?>
            <h2>Search Results for "<?=$q ?>"</h2>
        <? else: ?>
            <h2>All Users</h2>
        <? endif; ?>

        <a class="btn bgm-blue btn-float" href="<?=$this->url->routeFromHere(array('action' => 'edit')) ?>"><i class="zmdi zmdi-plus"></i></a>
    </div>
    <div id="data-table-basic-header" class="bootgrid-header container-fluid">
        <?=$this->viewHelper->paginate($pager) ?>
    </div>
    <div class="table-responsive">
        <table class="table table-striped">
            <colgroup>
                <col width="30%">
                <col width="40%">
                <col width="30%">
            </colgroup>
            <thead>
            <tr>
                <th>Actions</th>
                <th>E-mail Address</th>
                <th>Roles</th>
            </tr>
            </thead>
            <tbody>
            <? foreach($pager as $user): ?>
                <tr class="input">
                    <td>
                        <?=$this->viewHelper->button(array(
                            'type'      => 'small',
                            'class'     => 'btn-primary',
                            'href'      => $this->url->routeFromHere(array('action' => 'impersonate', 'id' => $user->id)),
                            'icon'      => 'key_go',
                            'text'      => 'Log In',
                        )) ?>
                        <?=$this->viewHelper->button(array(
                            'type'      => 'small',
                            'class'     => 'btn-primary',
                            'href'      => $this->url->routeFromHere(array('action' => 'edit', 'id' => $user->id)),
                            'icon'      => 'pencil',
                            'text'      => 'Edit',
                        )) ?>
                        <?=$this->viewHelper->button(array(
                            'type'      => 'small',
                            'href'      => $this->url->routeFromHere(array('action' => 'delete', 'id' => $user->id)),
                            'class'     => 'btn-danger confirm-delete',
                            'icon'      => 'delete',
                            'text'      => 'Delete',
                        )) ?>
                    </td>
                    <td><?=$this->viewHelper->mailto($user->email) ?></td>
                    <td>
                        <small>
                            <?
                            if (count($user->roles) > 0)
                            {
                                foreach($user->roles as $role)
                                    echo '<div>'.$role->name.'</div>';
                            }
                            ?>
                        </small>
                    </td>
                </tr>
            <? endforeach; ?>
            </tbody>
        </table>
    </div>
</div>

<!--
<form class="form-search" action="<?=$this->url->routeFromHere(array('page' => NULL)) ?>" method="get">
    <input type="text" name="q" title="Search terms" placeholder="Search..." class="input-medium span3 search-query" value="<?=$q ?>">
    <?=$this->viewHelper->button(array(
        'type'      => 'submit',
        'class'     => 'primary btn-small',
        'text'      => 'Search Users',
    )) ?>
</form>
<?=$this->viewHelper->paginate($pager) ?>
-->
