<?php
$this->layout('main', [
    'title' => __('System Debugger'),
    'manual' => true,
]);
?>

<h2 class="outside-card-header mb-1"><?=__('System Debugger')?></h2>

<div class="card mb-3">
    <div class="card-header bg-primary-dark">
        <h2 class="card-title"><?=__('Synchronization Tasks')?></h2>
    </div>
    <div class="card-body">
        <div class="row">
            <?php foreach ($sync_times as $sync_key => $sync_info): ?>
                <div class="col">
                    <h5 class="mb-0"><?=$sync_info['name']?></h5>
                    <p><?=implode(', ', $sync_info['contents'])?></p>

                    <div class="buttons">
                        <a class="btn btn-sm btn-primary" role="button" href="<?=$router->named('admin:debug:sync',
                            ['type' => $sync_key])?>">
                            <?=__('Run Task')?>
                        </a>
                    </div>
                </div>
            <?php endforeach; ?>
        </div>
    </div>
</div>

<div class="card">
    <div class="card-header bg-primary-dark">
        <h2 class="card-title"><?=__('Station-Specific Debugging')?></h2>
    </div>
    <div class="card-body pb-0">
        <ul class="nav nav-pills nav-pills-scrollable card-header-pills">
            <?php foreach ($stations as $station_id => $station_name): ?>
                <li class="nav-item">
                    <a class="nav-link" role="tab" data-toggle="tab" aria-expanded="true" aria-controls="debug_station_<?=$station_id?>" href="#debug_station_<?=$station_id?>"><?=$this->e($station_name)?></a>
                </li>
            <?php endforeach; ?>
        </ul>
    </div>
    <div class="tab-content">
        <?php foreach ($stations as $station_id => $station_name): ?>
            <div class="card-body card-padding-sm tab-pane" id="debug_station_<?=$station_id?>">
                <h3><?=$station_name?></h3>

                <div class="row">
                    <div class="col">
                        <h5><?=__('Test AutoDJ Next Song')?></h5>
                        <form class="form" method="get" action="<?=$router->named('admin:debug:nextsong',
                            ['station_id' => $station_id])?>">
                            <div class="form-group">
                                <label for="<?=$station_id?>_now"><?=__('Test time (Leave blank for current time)')?>:</label>
                                <input id="<?=$station_id?>_now" name="now" class="form-control" type="datetime-local">
                            </div>

                            <button type="submit" class="btn btn-primary"><?=__('Run Test')?></button>
                        </form>
                    </div>
                </div>
            </div>
        <?php endforeach; ?>
    </div>
</div>
