<?php
/**
 * @var \App\Assets $assets
 */

$this->layout('main', [
    'title' => __('Run Synchronization Task'),
    'manual' => true,
]);
?>

<div class="card mb-3">
    <div class="card-header bg-primary-dark">
        <h3 class="card-title"><?=__('Run Synchronization Task')?></h3>
    </div>
    <div class="card-actions">
        <a class="btn btn-outline-primary" href="<?=$router->fromHere('admin:debug:index')?>">
            <i class="material-icons" aria-hidden="true">arrow_back</i>
            <?=__('Debug Home')?>
        </a>
    </div>
    <div class="card-body">
        <p class="card-text">
            <?=__('The synchronization task is running in the background. The log below will update automatically.')?>
        </p>

        <?=$this->fetch('partials/log_inline', [
            'url' => (string)$router->fromHere('admin:debug:log', ['path' => $outputLog]),
        ])?>
    </div>
</div>
