<!DOCTYPE html>
<?php
/**
 * @var \League\Plates\Template\Template $this
 * @var \App\Auth $auth
 * @var \AzuraCast\Acl\StationAcl $acl
 * @var \App\Url $url
 * @var \App\Flash $flash
 * @var \AzuraCast\Customization $customization
 * @var array $app_settings
 * @var object $assets
 */
?>
<html>
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">

<?php
if ($title)
    $page_title = $title.' - '.$app_settings['name'];
else
    $page_title = $app_settings['name'];

if (!APP_IN_PRODUCTION)
    $page_title = '('.ucfirst(APP_APPLICATION_ENV).') '.$page_title;
?>
<title><?=$page_title ?></title>

<?=$this->fetch('partials/icons') ?>

<link rel="stylesheet" type="text/css" href="<?=$url->content('vendors/bower_components/animate.css/animate.min.css') ?>">
<link rel="stylesheet" type="text/css" href="<?=$url->content('vendors/bower_components/material-design-iconic-font/dist/css/material-design-iconic-font.min.css') ?>">
<link rel="stylesheet" type="text/css" href="<?=$url->content('css/light.css') ?>">

<?=$this->section('custom_css') ?>

<script type="text/javascript" src="<?=$url->content('vendors/bower_components/jquery/dist/jquery.min.js') ?>"></script>
<script type="text/javascript" src="<?=$url->content('vendors/bower_components/bootstrap/dist/js/bootstrap.min.js') ?>"></script>
<script type="text/javascript" src="<?= $url->content('vendors/bower_components/vue/dist/' . (APP_IN_PRODUCTION ? 'vue.min.js' : 'vue.js')) ?>"></script>

<script type="text/javascript">
    var APP_AppEnv = '<?=APP_APPLICATION_ENV ?>';
    var APP_BaseUrl = '<?=$url->named('home') ?>';
    var APP_ContentPath = '<?=$url->content('') ?>';
</script>
</head>

<body class="embed <?=$page_class ?>">
<?=$this->section('content') ?>

<?=$this->section('custom_js') ?>

<script type="text/javascript" src="<?=$url->content('vendors/bower_components/Waves/dist/waves.min.js') ?>"></script>
<script type="text/javascript" src="<?=$url->content('vendors/bootstrap-growl/bootstrap-growl.min.js') ?>"></script>
<script type="text/javascript" src="<?=$url->content('js/app.min.js') ?>"></script>
</body>
</html>