<?php
header("Content-type: text/html; charset=utf-8");
?>
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <?php
    if ($title)
        $page_title = $title.' - '.$this->config->application->name;
    else
        $page_title = $this->config->application->name;

    $this->tag->setTitle($page_title);
    if (APP_APPLICATION_ENV != "production")
        $this->tag->prependTitle('('.ucfirst(APP_APPLICATION_ENV).') ');

    echo $this->tag->getTitle();

    // Set up CSS includes.
    $this->assets->collection('header_css')
        ->addCss('vendors/bower_components/animate.css/animate.min.css')
        ->addCss('vendors/bower_components/material-design-iconic-font/dist/css/material-design-iconic-font.min.css')
        ->addCss('vendors/bower_components/bootstrap-sweetalert/lib/sweet-alert.css')
        ->addCss('vendors/bower_components/components-font-awesome/css/font-awesome.min.css')
        ->addCss('vendors/bower_components/malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar.min.css')
        ->addCss('css/app.css');

    // Establish custom CSS/JS collections in case they don't exist.
    $this->assets->collection('custom_css');
    $this->assets->collection('custom_js');

    // Output header CSS.
    $this->assets->outputCss('header_css');
    $this->assets->outputCss('custom_css');

    // Set up JS includes.
    $this->assets->collection('header_js')
        ->addJs('vendors/bower_components/jquery/dist/jquery.min.js')
        ->addJs('vendors/bower_components/bootstrap/dist/js/bootstrap.min.js');

    $this->assets->outputJs('header_js');

    $this->assets->collection('footer_js')
        ->addJs('vendors/bower_components/malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar.concat.min.js')
        ->addJs('vendors/bootstrap-growl/bootstrap-growl.min.js')
        ->addJs('vendors/bower_components/bootstrap-sweetalert/lib/sweet-alert.min.js')
        ->addJs('vendors/bower_components/autosize/dist/autosize.js')
        ->addJs('js/functions.js')
        ->addJs('js/app.js');
    ?>
    <script>
        var APP_AppEnv = '<?=(defined('APP_APPLICATION_ENV') ? APP_APPLICATION_ENV : '') ?>';
        var APP_BaseUrl = '<?php echo rtrim($this->url->get(''), '/'); ?>';
        var APP_ContentPath = '<?php echo $this->url->getStatic(''); ?>';
    </script>
</head>
<body class="<?=$page_class ?> <? if (!empty($station)): ?>toggled sw-toggled<? endif; ?>">
<header id="header" class="clearfix" data-current-skin="blue">
    <ul class="header-inner">
        <!--
        <? if (!empty($station)): ?>
        <li id="menu-trigger" data-trigger="#sidebar">
            <div class="line-wrap">
                <div class="line top"></div>
                <div class="line center"></div>
                <div class="line bottom"></div>
            </div>
        </li>
        <? endif; ?>
        -->

        <li class="logo hidden-xs">
            <a href="<?=$this->url->get('') ?>"><strong><?=$this->config->application->name ?></strong> alpha</a>
        </li>

        <li class="pull-right">
            <ul class="top-menu">
                <!--
                <li id="toggle-width">
                    <div class="toggle-switch">
                        <input id="tw-switch" type="checkbox" hidden="hidden">
                        <label for="tw-switch" class="ts-helper"></label>
                    </div>
                </li>
                -->

                <li id="top-search">
                    <a href=""><i class="tm-icon zmdi zmdi-search"></i></a>
                </li>

                <li class="dropdown">
                    <a data-toggle="dropdown" href=""><i class="tm-icon zmdi zmdi-more-vert"></i></a>
                    <ul class="dropdown-menu dm-icon pull-right">
                        <li class="hidden-xs">
                            <a data-action="fullscreen" href=""><i class="zmdi zmdi-fullscreen"></i> Toggle Fullscreen</a>
                        </li>
                        <li class="divider">&nbsp;</li>
                        <? if ($this->acl->isAllowed('administer all')): ?>
                            <li><a href="<?=$this->url->get('admin') ?>"><i class="fa fa-cog"></i> System Administration</a></li>
                        <? endif; ?>
                        <li><a href="<?=$this->url->get('profile') ?>"><i class="fa fa-user"></i> Profile</a></li>
                        <li class="divider">&nbsp;</li>
                        <li><a href="<?=$this->url->get('account/logout') ?>"><i class="fa fa-sign-out"></i> Sign Out</a></li>
                    </ul>
                </li>
            </ul>
        </li>
    </ul>

    <!-- Top Search Content -->
    <div id="top-search-wrap">
        <div class="tsw-inner">
            <i id="top-search-close" class="zmdi zmdi-arrow-left"></i>
            <input type="text">
        </div>
    </div>
</header>

<section id="main">
    <? if (!empty($station)): ?>
    <aside id="sidebar" class="sidebar c-overflow">
        <div class="profile-menu">
            <a href="">
                <div class="profile-pic">
                    <img src="<?=\App\Service\Gravatar::get($this->user->email) ?>" alt="">
                </div>

                <div class="profile-info">
                    Malinda Hollaway

                    <i class="zmdi zmdi-caret-down"></i>
                </div>
            </a>

            <ul class="main-menu">
                <li>
                    <a href="profile-about.html"><i class="zmdi zmdi-account"></i> View Profile</a>
                </li>
                <li>
                    <a href=""><i class="zmdi zmdi-input-antenna"></i> Privacy Settings</a>
                </li>
                <li>
                    <a href=""><i class="zmdi zmdi-settings"></i> Settings</a>
                </li>
                <li>
                    <a href=""><i class="zmdi zmdi-time-restore"></i> Logout</a>
                </li>
            </ul>
        </div>

        <ul class="main-menu">
            <li><a href="index.html"><i class="zmdi zmdi-home"></i> Home</a></li>
            <li class="sub-menu">
                <a href=""><i class="zmdi zmdi-view-compact"></i> Headers</a>

                <ul>
                    <li><a href="textual-menu.html">Textual menu</a></li>
                    <li><a href="image-logo.html">Image logo</a></li>
                    <li><a href="top-mainmenu.html">Mainmenu on top</a></li>
                </ul>
            </li>
            <li><a href="typography.html"><i class="zmdi zmdi-format-underlined"></i> Typography</a></li>
            <li class="sub-menu active toggled">
                <a href=""><i class="zmdi zmdi-widgets"></i> Widgets</a>

                <ul>
                    <li><a class="active" href="widget-templates.html">Templates</a></li>
                    <li><a href="widgets.html">Widgets</a></li>
                </ul>
            </li>
            <li class="sub-menu">
                <a href=""><i class="zmdi zmdi-view-list"></i> Tables</a>

                <ul>
                    <li><a href="tables.html">Normal Tables</a></li>
                    <li><a href="data-tables.html">Data Tables</a></li>
                </ul>
            </li>
            <li class="sub-menu">
                <a href=""><i class="zmdi zmdi-collection-text"></i> Forms</a>

                <ul>
                    <li><a href="form-elements.html">Basic Form Elements</a></li>
                    <li><a href="form-components.html">Form Components</a></li>
                    <li><a href="form-examples.html">Form Examples</a></li>
                    <li><a href="form-validations.html">Form Validation</a></li>
                </ul>
            </li>
            <li class="sub-menu">
                <a href=""><i class="zmdi zmdi-swap-alt"></i>User Interface</a>
                <ul>
                    <li><a href="colors.html">Colors</a></li>
                    <li><a href="animations.html">Animations</a></li>
                    <li><a href="box-shadow.html">Box Shadow</a></li>
                    <li><a href="buttons.html">Buttons</a></li>
                    <li><a href="icons.html">Icons</a></li>
                    <li><a href="alerts.html">Alerts</a></li>
                    <li><a href="preloaders.html">Preloaders</a></li>
                    <li><a href="notification-dialog.html">Notifications & Dialogs</a></li>
                    <li><a href="media.html">Media</a></li>
                    <li><a href="components.html">Components</a></li>
                    <li><a href="other-components.html">Others</a></li>
                </ul>
            </li>
            <li class="sub-menu">
                <a href=""><i class="zmdi zmdi-trending-up"></i>Charts</a>
                <ul>
                    <li><a href="flot-charts.html">Flot Charts</a></li>
                    <li><a href="other-charts.html">Other Charts</a></li>
                </ul>
            </li>
            <li><a href="calendar.html"><i class="zmdi zmdi-calendar"></i> Calendar</a></li>
            <li class="sub-menu">
                <a href=""><i class="zmdi zmdi-image"></i>Photo Gallery</a>
                <ul>
                    <li><a href="photos.html">Default</a></li>
                    <li><a href="photo-timeline.html">Timeline</a></li>
                </ul>
            </li>

            <li><a href="generic-classes.html"><i class="zmdi zmdi-layers"></i> Generic Classes</a></li>
            <li class="sub-menu">
                <a href=""><i class="zmdi zmdi-collection-item"></i> Sample Pages</a>
                <ul>

                    <li><a href="profile-about.html">Profile</a></li>
                    <li><a href="list-view.html">List View</a></li>
                    <li><a href="messages.html">Messages</a></li>
                    <li><a href="pricing-table.html">Pricing Table</a></li>
                    <li><a href="contacts.html">Contacts</a></li>
                    <li><a href="wall.html">Wall</a></li>
                    <li><a href="invoice.html">Invoice</a></li>
                    <li><a href="login.html">Login and Sign Up</a></li>
                    <li><a href="lockscreen.html">Lockscreen</a></li>
                    <li><a href="404.html">Error 404</a></li>

                </ul>
            </li>
            <li class="sub-menu">
                <a href="form-examples.html"><i class="zmdi zmdi-menu"></i> 3 Level Menu</a>

                <ul>
                    <li><a href="form-elements.html">Level 2 link</a></li>
                    <li><a href="form-components.html">Another level 2 Link</a></li>
                    <li class="sub-menu">
                        <a href="form-examples.html">I have children too</a>

                        <ul>
                            <li><a href="">Level 3 link</a></li>
                            <li><a href="">Another Level 3 link</a></li>
                            <li><a href="">Third one</a></li>
                        </ul>
                    </li>
                    <li><a href="form-validations.html">One more 2</a></li>
                </ul>
            </li>
        </ul>
    </aside>
    <? endif; ?>

    <section id="content">
        <div class="container">
        <? if ($manual): ?>
            <?php echo $this->getContent(); ?>
        <? else: ?>
            <div class="block-header">
                <h2><?=$title ?></h2>
            </div>

            <div class="card">
                <div class="card-body card-padding">
                    <?php echo $this->getContent(); ?>
                </div>
            </div>
        <? endif; ?>
        </div>
    </section>
</section>

<footer id="footer">
    Copyright &copy; <?=date('Y') ?> <?=$this->config->application->name ?>.
</footer>

<!-- Page Loader -->
<div class="page-loader">
    <div class="preloader pls-blue">
        <svg class="pl-circular" viewBox="25 25 50 50">
            <circle class="plc-path" cx="50" cy="50" r="20"></circle>
        </svg>

        <p>Please wait...</p>
    </div>
</div>

<?
$this->assets->outputJs('custom_js');
$this->assets->outputJs('footer_js');
?>

<? if ($this->flash->hasMessages()): ?>
    <script type="text/javascript">
        $(function() {
            <? foreach($this->flash->getMessages() as $message): ?>
            notify('<?=$this->escaper->escapeJs($message['text']) ?>', '<?=$message['color'] ?>');
            <? endforeach; ?>
        });
    </script>
<? endif; ?>
</body>
</html>