<?php
$skin = ($skin) ? $skin : 'dark';
$embed = ($embed_mode) ? 'embedded' : 'non-embedded';

$tz_info = \PVL\Timezone::getInfo();
?>
<!DOCTYPE html>
<html class="compact_layout theme_<?=$skin ?> <?=$embed ?>">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,requiresActiveX=true">

    <?php
    if ($title)
        $page_title = $title.' - '.$this->config->application->name;
    else
        $page_title = $this->config->application->name.' - Live Pony Radio, Video, Podcasts, Convention Coverage & More';

    $this->tag->setTitle($page_title);
    if (DF_APPLICATION_ENV != "production")
        $this->tag->prependTitle('('.ucfirst(DF_APPLICATION_ENV).') ');

    echo $this->tag->getTitle();

    $this->assets->collection('header_css')
        ->addCss('//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/css/bootstrap-combined.no-icons.min.css', false)
        ->addCss('//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css', false)
        ->addCss('//fonts.googleapis.com/css?family=Source+Sans+Pro:400,700', false)
        ->addCss('//cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.css', false)
        ->addCss('compiled/style.css');

    // Establish custom CSS/JS collections in case they don't exist.
    $this->assets->collection('custom_css');
    $this->assets->collection('custom_js');

    // Output header CSS.
    $this->assets->outputCss('header_css');
    $this->assets->outputCss('custom_css');

    // Set up JS includes.
    $this->assets->collection('header_js')
        ->addJs('//cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js', false)
        ->addJs('//cdnjs.cloudflare.com/ajax/libs/lodash.js/2.4.1/lodash.compat.min.js', false);

    $this->assets->collection('footer_js')
        ->addJs('//cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.js', false)
        ->addJs('//cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/helpers/jquery.fancybox-media.js', false)
        ->addJs('//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/2.3.2/js/bootstrap.min.js', false)
        ->addJs('//cdnjs.cloudflare.com/ajax/libs/swfobject/2.2/swfobject.min.js', false)
        ->addJs('//cdnjs.cloudflare.com/ajax/libs/hammer.js/2.0.4/hammer.min.js', false)
        ->addJs('//cdnjs.cloudflare.com/ajax/libs/moment.js/2.9.0/moment.min.js', false)
        ->addJs('//cdnjs.cloudflare.com/ajax/libs/store.js/1.3.14/store.min.js', false)
        ->addJs('js/layout.js')
        ->addJs('js/notify.js')
        ->addJs('js/global.js');

    $this->assets->outputJs('header_js');
    ?>
    <script>
        var DF_AppEnv = '<?=DF_APPLICATION_ENV ?>';
        var DF_BaseUrl = '<?php echo rtrim($this->url->get(''), '/'); ?>';
        var DF_ContentPath = '<?php echo $this->url->getStatic(''); ?>';

        var PVL_TimeZone = '<?=$e->escapeJs($tz_info['code']) ?>';
        var PVL_UtcOffset = <?=$tz_info['gmt_offset_hours'] ?>;
    </script>
</head>
<body>
<div id="body-wrapper">
    <div id="body" class="container">
        <? if ($manual): ?>
            <?php echo $this->getContent(); ?>
        <? else: ?>
            <div class="row-fluid">
                <div class="span12">
                    <div class="floating">
                        <div class="content_inner">
                            <?php echo $this->getContent(); ?>
                        </div>
                    </div>
                </div>
            </div>
        <? endif; ?>
    </div>
</div>

<?
echo $this->assets->outputJs('footer_js');
echo $this->assets->outputJs('custom_js');
?>

<!-- Google Universal Analytics -->
<script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', '<?=$this->config->application->analytics_code ?>', 'ponyvillelive.com');
    ga('send', 'pageview');
</script>
<!-- End Google Universal Analytics -->
</body>
</html>