<?php
header("Content-type: text/html; charset=utf-8");
?>
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <?php
    if ($title)
        $page_title = $title.' - '.$this->config->application->name;
    else
        $page_title = $this->config->application->name;

    $this->tag->setTitle($page_title);
    if (APP_APPLICATION_ENV != "production")
        $this->tag->prependTitle('('.ucfirst(APP_APPLICATION_ENV).') ');

    echo $this->tag->getTitle();

    // Set up CSS includes.
    $this->assets->collection('header_css')
        ->addCss('vendors/bower_components/animate.css/animate.min.css')
        ->addCss('vendors/bower_components/material-design-iconic-font/dist/css/material-design-iconic-font.min.css')
        ->addCss('css/app.min.1.css')
        ->addCss('css/app.min.2.css');

    // Output header CSS.
    $this->assets->outputCss('header_css');

    // Set up JS includes.
    $this->assets->collection('footer_js')
        ->addJs('vendors/bower_components/jquery/dist/jquery.min.js')
        ->addJs('vendors/bower_components/bootstrap/dist/js/bootstrap.min.js')
        ->addJs('vendors/bower_components/Waves/dist/waves.min.js')
        ->addJs('js/functions.js');
    ?>
    <script>
    var APP_AppEnv = '<?=(defined('APP_APPLICATION_ENV') ? APP_APPLICATION_ENV : '') ?>';
    var APP_BaseUrl = '<?php echo rtrim($this->url->get(''), '/'); ?>';
    var APP_ContentPath = '<?php echo $this->url->getStatic(''); ?>';
    </script>
</head>

<body class="<?=$page_class ?>">

<?php echo $this->getContent(); ?>

<?
echo $this->assets->outputJs('footer_js');
?>
</body>
</html>