<?php
/**
 * @var array $backups
 * @var \App\Assets $assets
 */

$this->layout('main', [
    'title' => __('Run Manual Backup'),
    'manual' => true,
]);
?>

<div class="card mb-3">
    <div class="card-header bg-primary-dark">
        <h3 class="card-title"><?=__('Run Manual Backup')?></h3>
    </div>
    <div class="card-actions">
        <a class="btn btn-outline-primary" href="<?=$router->fromHere('admin:backups:index')?>">
            <i class="material-icons" aria-hidden="true">arrow_back</i>
            <?=__('Backups Home')?>
        </a>
    </div>
    <div class="card-body">
        <p class="card-text">
            <?=__('The backup process is running in the background. The log below will update automatically.')?>
        </p>

        <?=$this->fetch('partials/log_inline', [
            'url' => (string)$router->fromHere('admin:backups:log', ['path' => $outputLog]),
        ])?>
    </div>
</div>
